### ISSUE TITLE
Cant find ROS code format in Qtcreator options

### ISSUE THREAD

**Issue by raultron** [ros-industrial/ros_qtc_plugin#1]
Hi,

I followed the wiki install instructions but when I try to set the code format to ROS:

> 2.4 Set ROS Code Format
> 
> Open Qt Creator
> Goto: Tools > Options > C++ > Code Style
> Select ROS from the Current Settings drop down list.
> Goto: Tools > Options > Qt Quick > Code Style and repeat step 3.
> Also need to change indent size to 2 space: Tools > Options > Text Editor > Behavior

This options are not available. I am sure that I am using the new Qtcreator compiled version.

Details of my computer:

Ubuntu 14.04
Qt Creator 4.0.2
Based on Qt 5.6.0 (GCC 4.8.4, 64 bit)

**Comment by Levi-Armstrong** [comment]
@raultron, I have created the PR #6 to address the issue. Once it has been merged I will update the Wiki. The user will no longer have to make these changes. They will be handled when the project is created.

**Comment by Levi-Armstrong** [comment]
This has been addressed by PR #6

**Comment by Levi-Armstrong** [comment]
@raultron, To get the latest changes run the command below within the ros_qtc_plugin directory.

`bash setup.sh -u`

or

`bash setup.sh -d`
