### ISSUE TITLE
C++ autocomplete does not work!

### ISSUE THREAD

**Issue by alireza-hosseini** [ros-industrial/ros_qtc_plugin#100]
Recently, I started to use this IDE, but the very very big disadvantage of this version is that is doesn't have auto complete which is very bad!
my OS is ubuntu 16.04, ROS version is kinetic and I'm using catkin tools.

**Comment by Levi-Armstrong** [comment]
The auto completion should be work, but you must build the project first from within the IDE at least once so the necessary cmake project files get generated for the IDE to parse. Did you build from within the IDE?

**Comment by alireza-hosseini** [comment]
Yes I did build the whole workspace using qtcreator.

**Comment by Levi-Armstrong** [comment]
You are using catkin tools instead of catkin make?

**Comment by alireza-hosseini** [comment]
Yes, I do and also my colleagues.

**Comment by Levi-Armstrong** [comment]
Can you launch qt creator from a terminal and build your project and then post the output from terminal?

**Comment by alireza-hosseini** [comment]
It keeps writing following text:
"Unable to locate build directory for package: package-name" 
for many of my packages

**Comment by Levi-Armstrong** [comment]
Does it print out a directory and does the directory exist?

**Comment by Levi-Armstrong** [comment]
I just pushed another release to solve issue #98 which may be related. Try updating and upgrading your system to get the latest in about 30 minutes.

**Comment by Levi-Armstrong** [comment]
@alireza-hosseini: Have you been able to test the latest?

**Comment by Levi-Armstrong** [comment]
@alireza-hosseini, Has this issue been resolved with the latest fix?

**Comment by liamstask** [comment]
I'm seeing this issue on what I believe is the latest version - I can't find any version info in the Qt Creator UI (looked mainly in the plugins dialog, and the detail dialog for the ROS plugin).

In my case, the console msgs are looking for files that do not exist - i.e. `myproj/ros/build/pkgname/pkgname.cbp`

There do not appear to be any .cbp files in my workspace, even after a complete build.

**Comment by liamstask** [comment]
I also notice that the Clang Code Model section of the C++ options is disabled, saying "The Clang Code Model is disabled because the corresponding plugin is not loaded" even though the plugin shows as loaded in the plugins dialog.

**Comment by Levi-Armstrong** [comment]
@liamstask, What build system are you using (catkin_make or catkin tools)?

**Comment by liamstask** [comment]
@Levi-Armstrong catkin tools

**Comment by Levi-Armstrong** [comment]
Did the base directory `myproj/ros/build/pkgname/` at least exist? Also did the build successful from within the IDE?

**Comment by liamstask** [comment]
yes, the directory exists and the build completes successfully in the IDE

**Comment by Levi-Armstrong** [comment]
Can you build it from the terminal using the command below in your workspace and see if the .cbp file shows up?
```
catkin build --cmake-args -G "CodeBlocks - Unix Makefiles"
```

**Comment by liamstask** [comment]
yes - they're generated in that case.

Sorry, I should have mentioned that I had configured the project to run `catkin build` as the build command (as our project has some specific build config specified elsewhere).

**Comment by Levi-Armstrong** [comment]
>Sorry, I should have mentioned that I had configured the project to run catkin build as the build command (as our project has some specific build config specified elsewhere).

Could you provide more details about the statement above. If the cbp file was created providing the command using terminal, it should then get created using the IDE. But there could be issues with my implementation, it may not do what I expect when passing additional argument so catkin.

**Comment by liamstask** [comment]
Sure - I had previously configured my qtcreator build step to be specifically `catkin build`, as opposed to `--cmake-args -G "CodeBlocks - Unix Makefiles"` or the default generated build step (which includes a debug/release setting)

Perhaps the `-G "CodeBlocks - Unix Makefiles"` directive is responsible for generating the .cbp files?

**Comment by Levi-Armstrong** [comment]
Ah that explains why you have no auto complete. The `-G "CodeBlocks - Unix Makefiles"` is what creates the .cbp files which is required at least once and after every clean build. What steps did you use to create your own build step to where it was not passing the `--cmake-args -G "CodeBlocks - Unix Makefiles"` because this is a bug?

Also is there a particular reason you were not wanting to pass the `--cmake-args -G "CodeBlocks - Unix Makefiles"'?

**Comment by liamstask** [comment]
The reason that I needed to modify the build command was the presence of the `-DCMAKE_BUILD_TYPE` args in the default build commands, as my project has specific requirements for managing the build type. Keeping `--cmake-args -G "CodeBlocks - Unix Makefiles"` is no problem, however.

Maybe it would be worth considering a way to remove the `-DCMAKE_BUILD_TYPE` from the default build steps, or somehow otherwise communicate that `--cmake-args -G "CodeBlocks - Unix Makefiles"` is required for code navigation/auto-complete?

**Comment by Levi-Armstrong** [comment]
>Maybe it would be worth considering a way to remove the -DCMAKE_BUILD_TYPE from the default build steps, or somehow otherwise communicate that --cmake-args -G "CodeBlocks - Unix Makefiles" is required for code navigation/auto-complete?

I will take a look and provide some option to get your opinion before implementing, but I think I get something that works.

**Comment by Levi-Armstrong** [comment]
@liamstask What do you think about the proposed changes below?

Add a `User Defined` option under the `Edit build configuration:` dropdown and in the `Build Type:` dropdown where the `-DCMAKE_BUILD_TYPE` is left up to the user to pass it they choose. The only flag that would be passed is the `--cmake-args -G "CodeBlocks - Unix Makefiles"`.

**Comment by liamstask** [comment]
That sounds good to me. Are you planning on allowing for a 'None' option, for Build Type, which would result in the command `catkin build --cmake-args -G "CodeBlocks - Unix Makefiles"`? That's what I would need for my current project, at least :)

**Comment by Levi-Armstrong** [comment]
Yea, that would be the user defined option.

**Comment by Levi-Armstrong** [comment]
@liamstask, Just submitted PR #108 that adds to the user defined feature.

**Comment by liamstask** [comment]
🎉 thanks for the quick response!

**Comment by Levi-Armstrong** [comment]
Addressed by #108 and #101
