### ISSUE TITLE
Qt 5.8 build issue

### ISSUE THREAD

**Issue by oxoocoffee** [ros-industrial/ros_qtc_plugin#102]
Hello and thank you for your work :)

I am not sure if you officially support Qt5.8 but I spoted build issue with it.
Here is my setup
Linux Mate 18.1 x64 
4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Qt 5.8 installed from https://download.qt.io/archive/qt/5.8/5.8.0/
Qt 5.8 installed to /opt/Qt/

Qt Creator 4.2.1
Based on Qt 5.8.0 (GCC 5.3.1 20160406 (Red Hat 5.3.1-6), 64 bit)

Now after cloning your project I did try two things

1. First I did try to open project file with above installed Qt/Creator but build failed at

/src/project_manager/ros_project_manager.cpp
In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project.h:26:0,
                 from ../../../ros_qtc_plugin/src/project_manager/ros_package_wizard.cpp:25:
../../../ros_qtc_plugin/src/project_manager/ros_project_manager.h:26:38: fatal error: qtermwidget5/qtermwidget.h: No such file or directory
In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project_manager.cpp:21:0:
../../../ros_qtc_plugin/src/project_manager/ros_project_manager.h:26:38: fatal error: qtermwidget5/qtermwidget.h: No such file or directory

2. I did try to modify your setup.sh and run it ./setup.sh -u

Here are changes I did in setup file

-QMAKE_PATH=/opt/qt57/bin/qmake
+QMAKE_PATH=/opt/Qt/5.8/gcc_64/bin/qmake

-cd $BASE_PATH && git clone -b 4.1 https://github.com/qtproject/qt-creator.git
+cd $BASE_PATH && git clone --depth 1 --single-branch --branch v4.2.1 https://github.com/qtproject/qt-creator.git

4.2.1 is Qt creator version installed with Qt5.8

Also noticed that on failed build it still try "Add Qt Creator ROS command line launcher: /usr/local/bin/qtcreato" by asking for password.

Do you have PPA for 16.04 and qt5.8?

Also I have idea but did not tried it. Since I have to use 5.8 for other things and your plug in will not support 5.8 some time, is it safe to install default Qt 5.7 and your PPA next to 5.8? Any knows issues?

Rob

**Comment by Levi-Armstrong** [comment]
Let me know if I understand correctly; You want to build a project using 5.8. If this is the case I don't believe that the IDE its self is required to built in 5.8 for you to use it to build a project using 5.8. You will need to install 5.8 somewhere and then setup a kit in Qt Creator which point to the installed 5.8 version. You may also need to clear out some system environment variables inside the IDE because they will point to the 5.7 version because by default it starts with the IDE Environment which will point to /opt/qt57.

**Comment by oxoocoffee** [comment]
Yes You go it. I do not need to build Qt Creator itself since it is already installed.
But I was able to build your plug-in using your script but I had to add libqtermwidget57-0-dev to list of prerequisite

echo "Install build dependencies: build-essential libgl1-mesa-dev"
sudo apt-get install build-essential libgl1-mesa-dev libqtermwidget57-0-dev

This of course did build qt creator. I will try to build plug-in not with out building qt creator. Will let you know.

**Comment by oxoocoffee** [comment]
Levi,

I am working on your setup script adding few things. I will be soon getting option to to skip qt creator build if you have one installed. Do you have any your recommendations  do and don't?

**Comment by Levi-Armstrong** [comment]
>I am working on your setup script adding few things. I will be soon getting option to to skip qt creator build if you have one installed. Do you have any your recommendations do and don't?

I would recommend still building qt creator from source to prevent corrupting the installed version, this is what Qt Creator community recommends. If you were to develop using the installed version and you induce a run-time error you would have to fix it using a text editor and to test it you would have to bring everything down and back up.
