### ISSUE TITLE
catkin tools: build errors not shown in 'Issues' output tab

### ISSUE THREAD

**Issue by liamstask** [ros-industrial/ros_qtc_plugin#104]
When I have some compilation errors, I see them in the 'Compile Output' tab, but they do not appear to be handled by the 'Issues' tab (which also means they are not shown in the editor ui, etc).

**Comment by Levi-Armstrong** [comment]
Only some errors are support right now mainly gcc compiler errors. CMake and Catkin errors are currently not supported at the moment. Qt does provide a CMake Output parser but it was private and they have since change it to exported but it will not be available to till the next release. 

The catkin errors will be an enhancement, it would just take someone to write a output parser for it.

**Comment by liamstask** [comment]
ah, ok - good news that the parser will be made available 👍 

do you happen to know if the cmake output parser also handles compiler/gcc output, as invoked by cmake, or does it just handle cmake specific output? just wondering, as there is no output at all in the 'Issues' tab at the moment, and not sure whether that's expected to be addressed by the cmake parser.

**Comment by Levi-Armstrong** [comment]
It just handles CMake errors but the gcc errors should be showing in the issues tab. Could you provide a test case so I may recreate the issue?

**Comment by liamstask** [comment]
i went through the process of creating a new workspace & package via the qtcreator wizards (a few edge cases are not handled well, such as creating a new package when there is no existing workspace etc).

If I uncomment the `error` line in `src/tester/tester_node.cpp` I see the build fail in the Compile Output tab, but no output (including compiler errors) in the Issues tab, where I would expect to see it.

[ros-plugin-test.tar.gz](https://github.com/ros-industrial/ros_qtc_plugin/files/890984/ros-plugin-test.tar.gz)

**Comment by Levi-Armstrong** [comment]
>i went through the process of creating a new workspace & package via the qtcreator wizards (a few edge cases are not handled well, such as creating a new package when there is no existing workspace etc).

I agree with your findings. Qt Creator provides two ways to implement these feature, one is a simple way using the json files and the other is through C++. Most of these feature are implemented using json which does not provide complex features for checking if the directory provided is correct, but I will add them as enhancements to upgrade them to C++. The package plugin is C++ and I will see what I can do before upgrading the others.

**Comment by Levi-Armstrong** [comment]
I built the provided workspace with catkin_make and catkin tools and the errors showed in the issues list. Are you using one of the CatkinMake or CatkinTools build step and not the CustomProcess?

**Comment by Levi-Armstrong** [comment]
Well I also tested it with the CustomProcess Step and they also showed using it.

**Comment by liamstask** [comment]
which version of cmake and qtcreator are you running? I am running cmake 3.6.2 and qtcreator 4.2.1

I verified that a basic cmake project works as expected, but cmake in that case is being invoked via `cmake --build` which sounds like it handles stderr differently (according to a couple brief searches).

I think stderr may be relevant, because the error output in the Compile Output panel in my cmake test project was colored red, while the error output in the Compile Output panel for the catkin build is black, suggesting it's not recognized as coming from stderr.

I'll keep investigating.

**Comment by Levi-Armstrong** [comment]
There was a recent change to catkin tools because it was printing everything out on stdout instead of printing errors out on stderr. Do you have the latest version of catkin tools?

**Comment by Levi-Armstrong** [comment]
Also can you try catkin_make and see if they shown up?

**Comment by liamstask** [comment]
ah ok - i'm on catkin tools 0.4.2 and it looks like the fix went into 0.4.4 so that is likely the issue. i will look into the process of upgrading our project :)

i tried a build w/catkin_make but there were some errors in our project, so I'm not sure yet whether that would work. I did see the cmake errors colored red in the compile output pane, though.

**Comment by Levi-Armstrong** [comment]
OK, let me know if upgrading catkin tools does not solve your issue.

**Comment by liamstask** [comment]
confirmed that upgrading to catkin tools 0.4.4 from 0.4.2 resolves this issue. thanks for helping track it down.
