### ISSUE TITLE
catkin tools: clang code model disabled

### ISSUE THREAD

**Issue by liamstask** [ros-industrial/ros_qtc_plugin#105]
when i start up my qtcreator installation normally, i can enable the clang code model plugin and it shows up in `Tools > Options > C++ > Code Model` as expected.

even when the plugin is selected in the plugins dialog, it is disabled in `Tools > Options > C++ > Code Model` when running via qtcreator-wrapper.

**Comment by Levi-Armstrong** [comment]
I will test it on my machine and see if I see the same thing.

**Comment by oxoocoffee** [comment]
liamstask

Can you start your Qt Creator and got to Help -> About Plugins -> C++ and see if you see ClangCodeModel is listed there? If it is, is it enabled? This requires restart.

**Comment by liamstask** [comment]
@oxoocoffee yes, it is listed there and it is enabled. As I mentioned above, it appears to run successfully when I am not running via `qtcreator-wrapper`.

**Comment by liamstask** [comment]
Actually, I just double checked and ClangCodeModel does *not* show up in the list of plugins at all when running via `qtcreator-wrapper`. It shows up and runs as expected when running directly from my qtcreator installation.

Seems like it's likely an environment/packaging issue - I don't understand how plugins are packaged with the version of qtcreator that ships in `/opt/qt57` but I can't find the clang code model plugin in there anywhere. Maybe the standard qtcreator plugins that ship in `/opt/qt57` need to be updated?

Or provide a way to include plugins from my existing qtcreator installation?

**Comment by Levi-Armstrong** [comment]
Take a look [here](http://doc.qt.io/qtcreator/creator-clang-codemodel.html) and see if you need to add additional environment variable to the wrapper. The README link also has useful information.

**Comment by liamstask** [comment]
It looks like the ClangCodeModel is not packaged w/the qtcreator that runs from `/opt/qt57`.

I checked each of the other plugins, and they're running from `/opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins` but there's no `libClangCodeModel.so` there.

To compare, `~/qtcreator-4.2.1/lib/qtcreator/plugins/libClangCodeModel.so` does exist and is loaded when running from `~/qtcreator-4.2.1`.

Is there a script that is responsible for packaging the release that might have some clues about why that plugin isn't included?

**Comment by Levi-Armstrong** [comment]
[Here](https://launchpad.net/~levi-armstrong/+archive/ubuntu/qt-libraries-trusty/+files/qt57creator_4.2.1-1basyskom1.debian.tar.xz) is the deb packaging information. Based on the README in the previouse link provided they may not have set up the environment to build it.

**Comment by oxoocoffee** [comment]
I am away for couple of days from my working machine. But I have problem building clang plugin in first place. When I get back I will look into this more. Default Qt online installer does have this plugin.
But when building from source version 4.2 or v4.2.1 I get errors stating that clang 3.9 or higher is needed.
Did you guys had to install any extra dev packages. Can you list then so I will install them when I get back to my desk?

**Comment by liamstask** [comment]
@oxoocoffee https://github.com/qtproject/qt-creator#get-llvmclang-for-the-clang-code-model has suggestions for using prebuilt packages, perhaps those can be integrated to the build/packaging step.

**Comment by Levi-Armstrong** [comment]
I plan to try and do a updated release of the Qt Creator application and I will try adding these to it and see it will work.

**Comment by Levi-Armstrong** [comment]
I was able to get an arm64 release and now I plan to work on the clang model. @oxoocoffee, @liamstask 
 Did either of you get it to work building from source?

**Comment by liamstask** [comment]
i haven't attempted to build from source, have my fingers crossed that you or @oxoocoffee have time and it works ok 😄

**Comment by oxoocoffee** [comment]
Just so you know. I am swapped with project for another week or so. I will try to look at issues when I catch up

**Comment by Levi-Armstrong** [comment]
I will take a look this week and give an update on the progress.

**Comment by Levi-Armstrong** [comment]
@liamstask can you take a look at the latest release and let me know if it available?

**Comment by liamstask** [comment]
just updated and it is not included. however, `libClangStaticAnalyzer.so` is in /opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins so it seems some part of the clang build may have worked? please let me know if there's any other info that would be helpful.

**Comment by Levi-Armstrong** [comment]
It looks like it require clang 3.9. I have a ppa that has it so I will see what I can do about getting to build.

**Comment by liamstask** [comment]
it looks like there are 3.9 binaries available at https://download.qt.io/development_releases/prebuilt/libclang as well

**Comment by liamstask** [comment]
still no luck for libClangCodeModel:
```
$ ll /opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/
total 39340
drwxr-xr-x 3 root root   12288 May 22 10:00 ./
drwxr-xr-x 3 root root   12288 May 22 10:00 ../
-rw-r--r-- 1 root root  923528 May 18 08:12 libAndroid.so
-rw-r--r-- 1 root root  810520 May 18 08:12 libAutoTest.so
-rw-r--r-- 1 root root  234192 May 18 08:12 libAutotoolsProjectManager.so
-rw-r--r-- 1 root root  332768 May 18 08:12 libBareMetal.so
-rw-r--r-- 1 root root  217664 May 18 08:12 libBazaar.so
-rw-r--r-- 1 root root  374536 May 18 08:12 libBeautifier.so
-rw-r--r-- 1 root root  155976 May 18 08:12 libBinEditor.so
-rw-r--r-- 1 root root  131136 May 18 08:12 libBookmarks.so
-rw-r--r-- 1 root root  325016 May 18 08:12 libClangStaticAnalyzer.so
-rw-r--r-- 1 root root  143176 May 18 08:12 libClassView.so
-rw-r--r-- 1 root root  305112 May 18 08:12 libClearCase.so
-rw-r--r-- 1 root root  750536 May 18 08:12 libCMakeProjectManager.so
-rw-r--r-- 1 root root  226368 May 18 08:12 libCodePaster.so
-rw-r--r-- 1 root root 2736520 May 18 08:12 libCore.so
-rw-r--r-- 1 root root 1174744 May 18 08:12 libCppEditor.so
-rw-r--r-- 1 root root 1579824 May 18 08:12 libCppTools.so
-rw-r--r-- 1 root root  193080 May 18 08:12 libCVS.so
-rw-r--r-- 1 root root 3268736 May 18 08:12 libDebugger.so
-rw-r--r-- 1 root root  338688 May 18 08:12 libDesigner.so
-rw-r--r-- 1 root root  443608 May 18 08:12 libDiffEditor.so
-rw-r--r-- 1 root root   39592 May 18 08:12 libEmacsKeys.so
-rw-r--r-- 1 root root  494384 May 18 08:12 libFakeVim.so
-rw-r--r-- 1 root root  201640 May 18 08:12 libGenericProjectManager.so
-rw-r--r-- 1 root root 1042304 May 18 08:12 libGit.so
-rw-r--r-- 1 root root  122976 May 18 08:12 libGLSLEditor.so
-rw-r--r-- 1 root root  656672 May 18 08:12 libHelp.so
-rw-r--r-- 1 root root  114592 May 18 08:12 libImageViewer.so
-rw-r--r-- 1 root root  621816 May 18 08:12 libIos.so
-rw-r--r-- 1 root root  176080 May 18 08:12 libMacros.so
-rw-r--r-- 1 root root  222088 May 18 08:12 libMercurial.so
-rw-r--r-- 1 root root  383152 May 18 08:12 libModelEditor.so
-rw-r--r-- 1 root root  308704 May 18 08:12 libNim.so
-rw-r--r-- 1 root root  255344 May 18 08:12 libPerforce.so
-rw-r--r-- 1 root root 3903824 May 18 08:12 libProjectExplorer.so
-rw-r--r-- 1 root root  143552 May 18 08:12 libPythonEditor.so
-rw-r--r-- 1 root root  615216 May 18 08:12 libQbsProjectManager.so
-rw-r--r-- 1 root root  197352 May 18 08:12 libQmakeAndroidSupport.so
-rw-r--r-- 1 root root 1293440 May 18 08:12 libQmakeProjectManager.so
-rw-r--r-- 1 root root 3774864 May 18 08:12 libQmlDesigner.so
-rw-r--r-- 1 root root  833240 May 18 08:12 libQmlJSEditor.so
-rw-r--r-- 1 root root  246616 May 18 08:12 libQmlJSTools.so
-rw-r--r-- 1 root root  851584 May 18 08:12 libQmlProfiler.so
-rw-r--r-- 1 root root  221672 May 18 08:12 libQmlProjectManager.so
-rw-r--r-- 1 root root  486272 May 18 08:12 libQnx.so
-rw-r--r-- 1 root root  889192 May 18 08:12 libQtSupport.so
-rw-r--r-- 1 root root  670184 May 18 08:12 libRemoteLinux.so
-rw-r--r-- 1 root root  287776 May 18 08:12 libResourceEditor.so
-rw-r--r-- 1 root root  798952 May 18 11:00 libROSProjectManager.so
-rw-r--r-- 1 root root 1418464 May 18 08:12 libScxmlEditor.so
-rw-r--r-- 1 root root  205808 May 18 08:12 libSubversion.so
-rw-r--r-- 1 root root   35616 May 18 08:12 libTaskList.so
-rw-r--r-- 1 root root 1938840 May 18 08:12 libTextEditor.so
-rw-r--r-- 1 root root  250704 May 18 08:12 libTodo.so
-rw-r--r-- 1 root root   60632 May 18 08:12 libUpdateInfo.so
-rw-r--r-- 1 root root  741200 May 18 08:12 libValgrind.so
-rw-r--r-- 1 root root  668064 May 18 08:12 libVcsBase.so
-rw-r--r-- 1 root root   81120 May 18 08:12 libWelcome.so
-rw-r--r-- 1 root root  197272 May 18 08:12 libWinRt.so
drwxr-xr-x 2 root root    4096 May 22 10:00 qmldesigner/
```

and

```
$ find /opt/qt57 -name libClang*
/opt/qt57/lib/x86_64-linux-gnu/qtcreator/libClangbackendipc.so.4
/opt/qt57/lib/x86_64-linux-gnu/qtcreator/libClangbackendipc.so.4.2
/opt/qt57/lib/x86_64-linux-gnu/qtcreator/libClangbackendipc.so
/opt/qt57/lib/x86_64-linux-gnu/qtcreator/libClangbackendipc.so.4.2.1
/opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libClangStaticAnalyzer.so
```

**Comment by Levi-Armstrong** [comment]
Did it install libclang1-3.9 by chance?

**Comment by liamstask** [comment]
looks like it did not:
```
$ dpkg -l | grep libclang
ii  libclang-common-3.8-dev                               1:3.8-2ubuntu3~trusty4                              amd64        clang library - Common development package
ii  libclang1-3.8:amd64                                   1:3.8-2ubuntu3~trusty4                              amd64        C interface to the clang library
```

**Comment by Levi-Armstrong** [comment]
Ok maybe i did not add the dependency correctly, I will check and push a new version.

**Comment by Levi-Armstrong** [comment]
@liamstask Are you on trusty or xenial?

**Comment by Levi-Armstrong** [comment]
Just noticed in the previous comment is show the library as trusty. Sorry I only updated the Xenial because I thought you were on Xenial. I will let you know when the trusty version has been updated.

**Comment by liamstask** [comment]
Yes, I'm stuck on trusty for now :) that would be great, thank you!

**Comment by Levi-Armstrong** [comment]
OK, I think it should be available. Check the latest and let me know if it is available.

**Comment by Levi-Armstrong** [comment]
I just tested it and it is available, but you may have to manually install libclang-3.9 and libllvm3.9.

**Comment by liamstask** [comment]
confirmed - i upgraded without installing libclang and libllvm and it was not included. once I installed libclang and libllvm manually, it installed and clang code model plugin is available 👍 

Looks like this may be just internal to that plugin, but I see lots of the following line: `SOFT ASSERT: "!resourceDir.isEmpty()" in file /build/qt57creator-BxSDzP/qt57creator-4.2.1.2/src/plugins/clangcodemodel/clangutils.cpp, line 151`

**Comment by Levi-Armstrong** [comment]
Is that an output to the terminal when qt creator is launched from the terminal?

**Comment by liamstask** [comment]
yes - just to the terminal, not in the UI

**Comment by Levi-Armstrong** [comment]
OK, I have not used the plug-in so I am not sure if this is normal behavior or not. You may try opening another project that is not a ROS Project and see if you get similar outputs. If not, I could be doing something incorrectly when creating the code model.

**Comment by liamstask** [comment]
No problem - doesn't seem to impact functionality in any way, so probably OK to ignore. I would say, if you are able to either:
* fix the installation to properly depend on libclang and llvm 3.9 packages
* or update the wiki to indicate those must be installed manually as prerequisites

then we should close out this issue 👍

**Comment by luator** [comment]
Hey, I just saw, that this is working now. That's great, thanks a lot for the effort!

**Comment by liamstask** [comment]
sounds good - let me know if there's anything that would be helpful to test

**Comment by Levi-Armstrong** [comment]
I did a fresh install and everything worked without having to manually add the clang libraries.
