### ISSUE TITLE
Can't Link ROS with QTcreator.

### ISSUE THREAD

**Issue by aliben7** [ros-industrial/ros_qtc_plugin#107]
Hi,

A few months ago I had ROS linked with Qtcreator tool. After this months of inactivity, today I tried to install Qtcreator and linked with ROS in a new Ubuntu 16 desktop but ROS doesn' t appear.
I linked as say's in ROS wiki:
http://wiki.ros.org/IDEs#Qt_Creator_Plugin_for_ROS

Last time I was able to create ROS packages, but unffortonatly not today.

I download Qt 5.7.0 from here:

https://download.qt.io/archive/qt/5.7/

Anyone have the same issue?

Thanks.

Ben.

**Comment by Levi-Armstrong** [comment]
The wiki you referenced is out dated, it was written before this plug-in existed. Please follow this wiki [here](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)) and I recommend removing the qt version you downloaded.

**Comment by aliben7** [comment]
Hi,

Thanks for the answer. Everything works fine.
