### ISSUE TITLE
QbsProjectManager plugin cannot be loaded

### ISSUE THREAD

**Issue by psotiropoulos** [ros-industrial/ros_qtc_plugin#109]
I have just updated the qt-creator-plugin and when I start qtcreator I get the following msg: 

/opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libQbsProjectManager.so: Cannot load library /opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libQbsProjectManager.so: (libqbscore.so.1.7: cannot open shared object file: No such file or directory)

With the previous version I did not have such an issue.

**Comment by Levi-Armstrong** [comment]
Do you know which ppa you are using for the qt57?

`ppa:levi-armstrong/qt-libraries-trusty`

or

`ppa:beineri/opt-qt57-trusty`

**Comment by psotiropoulos** [comment]
I'm using:
ppa:levi-armstrong/qt-libraries-trusty

I have removed ppa:beineri/opt-qt57-trusty

**Comment by Levi-Armstrong** [comment]
I would try a purge removal of qt57creator and reinstall.

**Comment by Levi-Armstrong** [comment]
@psotiropoulos Did you have any luck with getting it installed?

**Comment by psotiropoulos** [comment]
@Levi-Armstrong it actually worked, thanks. Removing everything and re-installing was enough.

**Comment by msinvent** [comment]
Coming across the similar problem, tried re-installing the qt twice, by purging the old install. Could not get any success.

**Comment by Levi-Armstrong** [comment]
@msinvent I think your issues is related to issue #142
