### ISSUE TITLE
[QAction] Problem compiling

### ISSUE THREAD

**Issue by henriqueribeiro** [ros-industrial/ros_qtc_plugin#11]
Hey

I'm having this problem compiling:

`./ui_ros_package_wizard_details_page.h:13:25: fatal error: QtGui/QAction: No such file or directory
 #include <QtGui/QAction>`

As far as I could see, QAction change from QtGui to QtWidgets. Can you help me with that? Thanks

**Comment by Levi-Armstrong** [comment]
I will take a look

**Comment by Levi-Armstrong** [comment]
Is this the first time you ran the setup script or did you run the script to get the latest updates?

**Comment by Levi-Armstrong** [comment]
I expect you need to update Qt. Did you perform this [step](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-Setup-ROS-Qt-Creator-Plug-in#11-download-the-latest-version-of-qt)? If so navigate to this folder and run the MaintenanceTool and perform an update. You may need to perform this operation multiple time until it tells you there are no more updates.

**Comment by henriqueribeiro** [comment]
Yes, it was the first time.
Qt is working and correctly installed.
I think one of the problems in the qtchooser file. Instead of `~/Qt/5.6/gcc_64/lib` it should be only `~/Qt/5.6/gcc_64/`, but I'm not really sure

**Comment by Levi-Armstrong** [comment]
Can you run the command `qmake -v` and post the output?

**Comment by Levi-Armstrong** [comment]
@henriqueribeiro, I updated the setup script can you run the command below in the ros_qtc_plugin directory twice. The first time will pull the latest then the second time will run the new setup script.

**Comment by Levi-Armstrong** [comment]
@henriqueribeiro, were you able to resolve the issue?

**Comment by henriqueribeiro** [comment]
@Levi-Armstrong. I'm currently at sea trials and I cannot test that now. Next week I will try...

**Comment by henriqueribeiro** [comment]
Hey @Levi-Armstrong 

I just tested everything on a new installation and everything is working now! Thanks for the help

**Comment by Levi-Armstrong** [comment]
@henriqueribeiro Great!, glad I could help!
