### ISSUE TITLE
Build errors on latest fork

### ISSUE THREAD

**Issue by oxoocoffee** [ros-industrial/ros_qtc_plugin#110]
I just forked latest and after following User setup then Developer setup I got following errors
This is on clean Ubutnu 16.04.2 with latest updates, ROS Kinetic Desktop, cmake 3.7 build from source

g++ -c -pipe -O2 -g -std=gnu++11 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_CAST_TO_ASCII -DQT_RESTRICTED_CAST_FROM_ASCII -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_FAST_CONCATENATION -DQMAKE_AS_LIBRARY -DPROPARSER_THREAD_SAFE -DPROEVALUATOR_THREAD_SAFE -DPROEVALUATOR_CUMULATIVE -DPROEVALUATOR_SETENV -DQT_QML_DEBUG -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../qt-creator-build/src -I../../../qt-creator/src -I../../../qt-creator/src/libs -I/home/oxoocoffee/projects/github/qt-creator/tools -I../../../qt-creator/src/plugins -I../../../qt-creator/src/shared -I../../../qt-creator/src/libs/3rdparty -I. -I../../../ros_qtc_plugin/src/project_manager -I/opt/qt57/include -I/opt/qt57/include/QtWidgets -I/opt/qt57/include/QtGui -I/opt/qt57/include/QtConcurrent -I/opt/qt57/include/QtNetwork -I/opt/qt57/include/QtCore -I.moc/release-shared -I.uic -I/opt/qt57/mkspecs/linux-g++ -o .obj/release-shared/ros_project_plugin.o ../../../ros_qtc_plugin/src/project_manager/ros_project_plugin.cpp
../../../ros_qtc_plugin/src/project_manager/ros_catkin_make_step.cpp: In member function ‘virtual bool ROSProjectManager::Internal::ROSCatkinMakeStep::init(QList<const ProjectExplorer::BuildStep*>&)’:
../../../ros_qtc_plugin/src/project_manager/ros_catkin_make_step.cpp:114:84: error: ‘ProjectExplorer::ToolChain::Language’ has not been declared
     ToolChain *tc = ToolChainKitInformation::toolChain(target()->kit(), ToolChain::Language::Cxx);
                                                                                    ^
g++ -c -pipe -O2 -g -std=gnu++11 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DIDE_LIBRARY_BASENAME=\"lib\" -DQT_CREATOR -DQT_NO_CAST_TO_ASCII -DQT_RESTRICTED_CAST_FROM_ASCII -DQT_USE_FAST_OPERATOR_PLUS -DQT_USE_FAST_CONCATENATION -DQMAKE_AS_LIBRARY -DPROPARSER_THREAD_SAFE -DPROEVALUATOR_THREAD_SAFE -DPROEVALUATOR_CUMULATIVE -DPROEVALUATOR_SETENV -DQT_QML_DEBUG -DQT_NO_DEBUG -DQT_PLUGIN -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../../qt-creator-build/src -I../../../qt-creator/src -I../../../qt-creator/src/libs -I/home/oxoocoffee/projects/github/qt-creator/tools -I../../../qt-creator/src/plugins -I../../../qt-creator/src/shared -I../../../qt-creator/src/libs/3rdparty -I. -I../../../ros_qtc_plugin/src/project_manager -I/opt/qt57/include -I/opt/qt57/include/QtWidgets -I/opt/qt57/include/QtGui -I/opt/qt57/include/QtConcurrent -I/opt/qt57/include/QtNetwork -I/opt/qt57/include/QtCore -I.moc/release-shared -I.uic -I/opt/qt57/mkspecs/linux-g++ -o .obj/release-shared/ros_project_wizard.o ../../../ros_qtc_plugin/src/project_manager/ros_project_wizard.cpp
../../../ros_qtc_plugin/src/project_manager/ros_project.cpp: In member function ‘void ROSProjectManager::Internal::ROSProject::refreshCppCodeModel()’:
../../../ros_qtc_plugin/src/project_manager/ros_project.cpp:234:97: error: ‘ProjectExplorer::ToolChain::Language’ has not been declared
     ToolChain *toolChain = ToolChainKitInformation::toolChain(activeTarget()->kit(), ToolChain::Language::Cxx);
                                                                                                 ^
Makefile:4507: recipe for target '.obj/release-shared/ros_catkin_make_step.o' failed
make[2]: *** [.obj/release-shared/ros_catkin_make_step.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:5408: recipe for target '.obj/release-shared/ros_project.o' failed
make[2]: *** [.obj/release-shared/ros_project.o] Error 1
../../../ros_qtc_plugin/src/project_manager/ros_catkin_tools_step.cpp: In member function ‘virtual bool ROSProjectManager::Internal::ROSCatkinToolsStep::init(QList<const ProjectExplorer::BuildStep*>&)’:
../../../ros_qtc_plugin/src/project_manager/ros_catkin_tools_step.cpp:123:84: error: ‘ProjectExplorer::ToolChain::Language’ has not been declared
     ToolChain *tc = ToolChainKitInformation::toolChain(target()->kit(), ToolChain::Language::Cxx);
                                                                                    ^
Makefile:4760: recipe for target '.obj/release-shared/ros_catkin_tools_step.o' failed
make[2]: *** [.obj/release-shared/ros_catkin_tools_step.o] Error 1
make[2]: Leaving directory '/home/oxoocoffee/projects/github/ros_qtc_plugin-build/src/project_manager'
Makefile:42: recipe for target 'sub-project_manager-make_first-ordered' failed
make[1]: *** [sub-project_manager-make_first-ordered] Error 2
make[1]: Leaving directory '/home/oxoocoffee/projects/github/ros_qtc_plugin-build/src'
Makefile:43: recipe for target 'sub-src-make_first-ordered' failed
make: *** [sub-src-make_first-ordered] Error 2
Add Qt Creator ROS command line launcher: /usr/local/bin/qtcreator

**Comment by oxoocoffee** [comment]
Looks like static ToolChain *toolChain(const Kit *k) takes only one parameter?

**Comment by Levi-Armstrong** [comment]
Before you ran the setup script did you update this [line](https://github.com/ros-industrial/ros_qtc_plugin/blob/master/setup.sh#L35) to 4.2?

**Comment by Levi-Armstrong** [comment]
I had mentioned on issue #103, but you may have not seen it yet.

**Comment by oxoocoffee** [comment]
For now I did try to build clean clone from your repo.
I just double checked local and it is 4.1

**Comment by Levi-Armstrong** [comment]
I would change it to 4.2 and re run the script or you can just navigate to the qtcreator directory and perform a `git checkout 4.2` and rebuild qtcreator then everything should work build.

**Comment by oxoocoffee** [comment]
Yes, Just did build and updating to 4.2 builds find. I did it couple of days ago with 4.2.1 but this was coincidently with my change. This time around I wared to start clean with how you had it in repo then add my changes. I am good now.

**Comment by Levi-Armstrong** [comment]
Great!
