### ISSUE TITLE
E: Unable to locate package qt57creator-plugin-ros

### ISSUE THREAD

**Issue by harryman1** [ros-industrial/ros_qtc_plugin#111]
Hi

I'm trying to install the plug-in and I have this error message
E: Unable to locate package qt57creator-plugin-ros

I did  the sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial  and sudo add-apt-repository ppa:levi-armstrong/ppa  

I checked and ensure all was correct and no errors were present 

when I run the installation I got the error message 

E: Unable to locate package qt57creator-plugin-ros

I have install qtCreator from ubuntu 16.04 repositories, not sure why is not installing, I did followed the wiki 

please help

**Comment by Levi-Armstrong** [comment]
I would recommend removing the qtcreator installed from 16.04 repositories. When install the plug-in it will install a different version of qtcreator. 

Also did you perform and `sudo apt update` prior to trying to install?

**Comment by harryman1** [comment]
Thanks, I did remove the package from 16.04 and ran it again 

Get:25 http://ppa.launchpad.net/levi-armstrong/qt-libraries-xenial/ubuntu xenial/main arm64 Packages [912 B]
Get:26 http://ppa.launchpad.net/levi-armstrong/qt-libraries-xenial/ubuntu xenial/main Translation-en [3,340 B]
Fetched 22.3 kB in 2s (8,978 B/s)                           
Reading package lists... Done

ubuntu@robotsp1:/etc/apt/sources.list.d$ sudo apt-get install qt57creator-plugin-ros
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qt57creator-plugin-ros


Same issue

Thanks for the help

**Comment by Levi-Armstrong** [comment]
I am not sure why it is not locating it. Is the `sudo apt update` successful?

Did you see a Get for http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu xenial/main?

**Comment by harryman1** [comment]
the sudo apt update shows that all sources have been found and no errors 

Hit:15 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease                                                   
Hit:16 http://ppa.launchpad.net/levi-armstrong/qt-libraries-xenial/ubuntu xenial InRelease                              
Hit:17 http://ports.ubuntu.com/ubuntu-ports xenial-updates InRelease                                                    
Hit:18 http://packages.ros.org/ros/ubuntu xenial InRelease  

I did had the GET and I'm seen a HIT for the http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu xenial/main

Thanks

**Comment by harryman1** [comment]
Hi Levi-Armstrong, so definitely the issue is architecture, sorry for the fuss, could you please let me know how do I compile from source, I did git clone the source code and ran the setup.sh

but as the architecture is arm I have this output

please help me and I can put the package available for anyone to use

ubuntu@robotsp1:~/QT code/ros_qtc_plugin$ ./setup.sh -ui
Install build dependencies: build-essential libgl1-mesa-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
libgl1-mesa-dev is already the newest version (12.0.6-0ubuntu0.16.04.1).
The following packages were automatically installed and are no longer required:
  gir1.2-rb-3.0 gir1.2-secret-1 gnome-video-effects libdmapsharing-3.0-2 libgpod-common libgpod4 librhythmbox-core9 libsgutils2-2 media-player-info
  python-urlgrabber python3-mako rhythmbox-data
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
./setup.sh: line 35: cd: /home/ubuntu/QT: No such file or directory
make: *** No rule to make target 'clean'.  Stop.
./setup.sh: line 44: /opt/qt57/bin/qmake: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
make: *** No rule to make target 'clean'.  Stop.
./setup.sh: line 64: /opt/qt57/bin/qmake: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
Add Qt Creator ROS command line launcher: /usr/local/bin/qtcreator
ln: target '/usr/local/bin/qtcreator' is not a directory

**Comment by Levi-Armstrong** [comment]
Are you on 16.04 or 14.04?

**Comment by Levi-Armstrong** [comment]
I am going to attempt to do an arm release.

**Comment by harryman1** [comment]
I'm on a 16.04

:)
Thanks, I own you a beer :)

**Comment by Levi-Armstrong** [comment]
I am releasing everything for **ARM ARMv8 (arm64)** do you think that should be work?

**Comment by harryman1** [comment]
Yes, I hope so

**Comment by Levi-Armstrong** [comment]
So I was able to release all of the Qt Libraries except Qt Creator on the arm64. Would you be willing to help with creating a patch for Qt Creator; I can help walk you through the process?

**Comment by harryman1** [comment]
yes, I'm willing to help, please guide me with this, I will get that done 

Thanks

**Comment by Levi-Armstrong** [comment]
So what you will want to do first is try and install my qt libraries. Try qt57base? Then you will want to download the qt creator source [here](https://launchpad.net/~levi-armstrong/+archive/ubuntu/qt-libraries-xenial/+files/qt57creator_4.2.1.orig.tar.xz) and try and build it. The readme.md in the download explains how to build it and it will fail. I recommend making the folder tracked by git before you make changes so you may create a patch once you get it to build. Once you get it to build you can use Meld to create the patch and post it here.

**Comment by harryman1** [comment]
the QT57 has uses version 5.5.1, I'm struggling to get it working,  however I found this two links, please check (the first link might work) as the main issue is with cpuid.h

https://patchwork.openembedded.org/patch/57035/ 
https://github.com/erlio/vernemq/issues/175

**Comment by Levi-Armstrong** [comment]
>the QT57 has uses version 5.5.1

Do you mind elaborating on this; It should be 5.7.1? Also, make sure you execute the command below so it sets up your environment to point to the qt libraries in the /opt/qt57 directory when opening a terminal to build qt creator.

```
source /opt/qt57/bin/qt57-env.sh
```

**Comment by harryman1** [comment]
sorry for the delay, I had to rebuilt my Jetson TX1

yes, I noticed that I was missing to source the QT environmental definitions, I got to the point where it shows me this 


Info: creating stash file /home/ubuntu/qt-creator-opensource-src-4.2.1/.qmake.stash
Info: creating cache file /home/ubuntu/qt-creator-opensource-src-4.2.1/.qmake.cache
Reading /home/ubuntu/qt-creator-opensource-src-4.2.1/src/src.pro
 Reading /home/ubuntu/qt-creator-opensource-src-4.2.1/src/shared/qbs/src/lib/corelib/corelib.pro
Project ERROR: Unknown module(s) in QT: script

**Comment by harryman1** [comment]
OK, god news

I managed to compile and run QT creator :)

I was trying to get in to why Botan.cpp and Botan.h did not compile and was asking to the CPUID.h library, as I you had pointed out, it is due the ARM architecture and to ignore the x86 macros.

so after the full weekend working on this and fails and many errors I decided to test already existing patch located here.

https://codereview.qt-project.org/#/c/79728/1

it complied :)


please add the patch and feel free to create the package for other to use.

**Comment by Levi-Armstrong** [comment]
Did you apply the patch as is?

**Comment by harryman1** [comment]
yes, this is correct, I did applied the patch without any modification, as my modification were not necessary

**Comment by harryman1** [comment]
Hi, I would like to know if you will be releasing the the arm64 package soon?
Thanks

**Comment by Levi-Armstrong** [comment]
Thank you for the help and I do plan too. I am currently moving into a new house so I plan to try and get a release of Qt Creator sometime this week.

**Comment by harryman1** [comment]
As I promised, if you can send

**Comment by harryman1** [comment]
FYI: Apparently botan v 2.0 does compile in arm64 without any patch, but I can't find the libraries that are used for the Qcreator :(

**Comment by Levi-Armstrong** [comment]
I am waiting on a space increase on launchpad.net to be able to push the changes for arm64, so hopefully I will get the increase soon.

The libraries you are looking for are in `src/libs/3rdparty/botan/` directory.

**Comment by Levi-Armstrong** [comment]
I just got he space increase so I will work on a release for arm64.

**Comment by Levi-Armstrong** [comment]
There is now an arm64 of Qt Creator for xenial. Please let me know if you have any issues.

**Comment by Levi-Armstrong** [comment]
@harryman1 Have you had a chance to try and install qtcreator?

**Comment by harryman1** [comment]
Hi, Sorry I was away on a business trip, I had been able to install the package qt57creator and test a simle C++ program, but I can't install the qt57creator-plugin-ros, 

Thanks

**Comment by Levi-Armstrong** [comment]
Great! Also, thanks for the reminder about the plugin. I just started the qt57creator-plugin-ros arm64 build. I will let you know if there are any issue.

**Comment by Levi-Armstrong** [comment]
@harryman1, I am unable to build the plug-in on an arm64 via launchpad.net. I get a connection refused when executing the command below. Are you able to test the command and see if you get the same issue on your arm64?

```
wget https://launchpad.net/~levi-armstrong/+archive/ubuntu/qt-libraries-xenial/+files/qt57creator_4.2.1.2.orig.tar.xz
```

**Comment by harryman1** [comment]
I got this warning about the digital certificate but I can connect and download

wget https://launchpad.net/~levi-armstrong/+archive/ubuntu/qt-libraries-xenial/+files/qt57creator_4.2.1.2.orig.tar.xz --no-check-certificate
--2017-05-04 21:35:38--  https://launchpad.net/~levi-armstrong/+archive/ubuntu/qt-libraries-xenial/+files/qt57creator_4.2.1.2.orig.tar.xz
Resolving launchpad.net (launchpad.net)... 91.189.89.222
Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
WARNING: cannot verify launchpad.net's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://launchpadlibrarian.net/317480878/qt57creator_4.2.1.2.orig.tar.xz [following]
--2017-05-04 21:35:39--  https://launchpadlibrarian.net/317480878/qt57creator_4.2.1.2.orig.tar.xz
Resolving launchpadlibrarian.net (launchpadlibrarian.net)... 91.189.89.228
Connecting to launchpadlibrarian.net (launchpadlibrarian.net)|91.189.89.228|:443... connected.
WARNING: cannot verify launchpadlibrarian.net's certificate, issued by ‘CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 16204520 (15M) [application/octet-stream]
Saving to: ‘qt57creator_4.2.1.2.orig.tar.xz’

qt57creator_4.2.1.2.orig.tar.xz    100%[===============================================================>]  15.45M  2.11MB/s    in 8.7s    

2017-05-04 21:35:49 (1.78 MB/s) - ‘qt57creator_4.2.1.2.orig.tar.xz’ saved [16204520/16204520]

ubuntu@robotsp1:~/Downloads$

**Comment by Levi-Armstrong** [comment]
I noticed that you passed `--no-check-certificate` flag does it fail without this option?

**Comment by harryman1** [comment]
yes, this is correct it will fail, please see below

ubuntu@robotsp1:~/Downloads$ wget https://launchpad.net/~levi-armstrong/+archive/ubuntu/qt-libraries-xenial/+files/qt57creator_4.2.1.2.orig.tar.xz
--2017-05-05 15:58:36--  https://launchpad.net/~levi-armstrong/+archive/ubuntu/qt-libraries-xenial/+files/qt57creator_4.2.1.2.orig.tar.xz
Resolving launchpad.net (launchpad.net)... 91.189.89.222, 91.189.89.223
Connecting to launchpad.net (launchpad.net)|91.189.89.222|:443... connected.
ERROR: cannot verify launchpad.net's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to launchpad.net insecurely, use `--no-check-certificate'.

**Comment by Levi-Armstrong** [comment]
OK, I will try adding the option and see if it solves the issue on launchpad.net.

**Comment by harryman1** [comment]
Hi

I was looking at the logs created by launchpad and it seems that you might have also a permission issue, as there is a refused connection, when I did my test the issue was on the digital certificate as it was not possible to verify the certificate.

in your case might be some kind of authentication issue

All the best 

Henry

(see below for the logs taken form your compilation process) [https://launchpadlibrarian.net/318149481/buildlog_ubuntu-xenial-arm64.qt57creator-plugin-ros_0.1.5-0xenial10_BUILDING.txt.gz](url)


--2017-05-03 14:06:21--  https://launchpadlibrarian.net/317480878/qt57creator_4.2.1.2.orig.tar.xz
Resolving launchpadlibrarian.net (launchpadlibrarian.net)... 10.189.0.25
Connecting to launchpadlibrarian.net (launchpadlibrarian.net)|10.189.0.25|:443... failed: Connection refused.
debian/rules:29: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 4
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
debian/rules:26: recipe for target 'build-arch' failed
make: *** [build-arch] Error 2
dpkg-buildpackage: error: debian/rules build-arch gave error exit status 2

**Comment by Levi-Armstrong** [comment]
@harryman1  Do you have any suggestions I may try. It is weird that it work on the other platforms but fails on the arm64.

**Comment by harryman1** [comment]
The only thing I can suggest is to ensure the user has access to port 443 as this might be a privileged access, or to check file permissions security settings too, And use the no-check-certificate

**Comment by harryman1** [comment]
I had found this https://irclogs.ubuntu.com/2015/02/02/%23launchpad.html

It mentions some permissions that you might need to request to allow you complete the build

**Comment by Levi-Armstrong** [comment]
I think I may have a something to resolve the as I have not received a response from launchpad.net. I will provide an update later today.

**Comment by Levi-Armstrong** [comment]
@harryman1 I finally was able to figure out how to get everything to work. Please try installing everything and let me know if it works and sorry it took so long to figure out how to get a release for the arm64.

**Comment by harryman1** [comment]
it works, thank you :)

i wil  following now the setup steps for QT creator, any issue I will let you know on a new topic
