### ISSUE TITLE
deb package script

### ISSUE THREAD

**Issue by oxoocoffee** [ros-industrial/ros_qtc_plugin#114]
Lavi

Is there a easy way to make deb package? Is this part of this repo? or you have some standalone script that you use and could share?

I might integrate to setup.sh as I am adding some other options.

Beside libROSProjectManager.so what other files are part of output if I need to move to other machine?

**Comment by Levi-Armstrong** [comment]
I do, it is in my personal fork. Are you wanting a release using Qt 5.8?

**Comment by oxoocoffee** [comment]
No not publicly. Just so I can build it locally and put it on my machines. Not sure how quickly after you accept my changes (and if you do :) you will update ppa

**Comment by Levi-Armstrong** [comment]
I do like the changes and appreciate the help. For the most part it has only been myself doing the development. I am planning to pull it down over the weekend and test it. In the mean time you could create a new branch in your repo called debian/xenial and rebase it on my debian/xenial and follow the instruction on my wiki for creating the debian.

**Comment by oxoocoffee** [comment]
Ok great. I will try to help. I have to catch up with work now but will do it soon

**Comment by oxoocoffee** [comment]
I just check wiki here and do not see any documents referring to deb package creation. Do you have a link?

**Comment by Levi-Armstrong** [comment]
Yea it is on my personal fork [here](https://github.com/Levi-Armstrong/ros_qtc_plugin/wiki/Debian-Release-Process). Let me know if you have any issues.
