### ISSUE TITLE
Failed to add CMakeLists.txt to source control Dialog Box

### ISSUE THREAD

**Issue by oxoocoffee** [ros-industrial/ros_qtc_plugin#116]
I noticed that when adding new package I get dialog box stating that CMakeLists.txt failed to add to source control. How to recreate it

1. mkdir ~/testCatkinTools
2. Create CatkinTool project in QT Creator and point it to ~/testCatkinTools and finish wizard
3. While Qt creator is open go to ~/testCatkinTools and do git init
4. Switch to Qt Crator and add first package Pkg1 in src/.  When completing I got error dialog box stating that CMakeLists.txt was failed when adding to source control

There should be a way to add watcher for source control initialization.

**Comment by oxoocoffee** [comment]
Actually I noticed that above it part of problem. Here is another case

1. mkdir ~/testCatkinTools
2. Create CatkinTool project in QT Creator and point it to ~/testCatkinTools and finish wizard
3. Add first package to src/
4. Close QtCreator and in Terminal go to ~/testCatkinTools
5. git init and add all files and folders
6. commit to master
7. git branch -b test
8. Start Qt Crator and add second package Pkg2 in src/.  When completing I got error dialog box stating that CMakeLists.txt was failed when adding to source control even git was initialized

Doing git status I see this
src/Pkg2/package.xml is already staged and 
src/Pkg2/CMakeLists.txt is untracked

I am assuming that Qt creator is adding package wizard is adding all files to source control do you know top of your head where problem might be located? I never worked with Qt plugins so I learn as I go ...

**Comment by Levi-Armstrong** [comment]
This is using the existing version?

**Comment by Levi-Armstrong** [comment]
Oops! It is do to a spelling error [here](https://github.com/ros-industrial/ros_qtc_plugin/blob/master/src/project_manager/ros_package_wizard.cpp#L251). It should be **CMakeLists.txt** instead of **CMakeList.txt**.

**Comment by oxoocoffee** [comment]
Thank you. This was it and was fixed.
