### ISSUE TITLE
ROS wizard title

### ISSUE THREAD

**Issue by oxoocoffee** [ros-industrial/ros_qtc_plugin#118]
I think ROS Wizard should be moved from Import Project to Other Project. Looks like Wizard is responsible to creation and not import project. Is there some historical reason for naming it import?
If it is ok by you I can change it relay quick to be consistent.

**Comment by Levi-Armstrong** [comment]
Not really. The previous way Qt Creator was used to manage ROS project was the Generic Project which was under Import, but we have moved away from this, so I am ok with switching it. When you do can you update the wiki to reflect the changes?

**Comment by oxoocoffee** [comment]
Ok will do. Can you look into my new pull request #120

**Comment by Levi-Armstrong** [comment]
Moved in the latest release.
