### ISSUE TITLE
QtCreator with ROS plugin not working

### ISSUE THREAD

**Issue by jmlago91** [ros-industrial/ros_qtc_plugin#12]
Hi!

After building QtCreator and the ROS plugin with the script, I open QtCreator in a terminal, import an existing ros workspace, and when I try to open it, QtCreator force close and gives a segmentation fault.

Any idea?

Thanks.

**Comment by Levi-Armstrong** [comment]
After the import process did the project not open automatically?

**Comment by jmlago91** [comment]
No, it closes the import windows, but creates the .workspace file. Then I try to open the project, and force close the QtCreator, giving a segmentation fault in the terminal.


Thanks for the help.

**Comment by Levi-Armstrong** [comment]
Can you post the content of the .workspace file?

**Comment by jmlago91** [comment]
This is a .workspace generated from a fully working catkin_ws:

`<?xml version="1.0"?>
<Workspace>
    <WatchDirectories>
        <Directory>src</Directory>
    </WatchDirectories>
    <IncludePaths>
        <Directory>/usr/src/gtest</Directory>
        <Directory>/usr/src/gtest/include</Directory>
        <Directory>/home/****/catkin_ws/src/velodyne_height_map-master/include</Directory>
        <Directory>/opt/ros/indigo/include</Directory>
        <Directory>/usr/include/eigen3</Directory>
        <Directory>/usr/include/ni</Directory>
        <Directory>/usr/include/pcl-1.7</Directory>
        <Directory>/usr/include/vtk-5.8</Directory>
    </IncludePaths>
</Workspace>`

Also I've noticed that if I open the original QtCreator (installed in ~/Qt/tools/QtCreator/bin/qtcreator with original Qt installer) in Options ->Build & Run it detects qmake and the Qt kit installed, but if I open the binary "qtcreator" build with ros_qtc_plugin script, It doesn't detect anything.


Thanks again for the help.

**Comment by fulinx** [comment]
Hi, 

I also got the same segmentation fault. I'm running Ubuntu 16.04, ROS kinetic, Qt5.7.

`Thread 1 "qtcreator" received signal SIGSEGV, Segmentation fault.
0x00007fffe3c9e5c6 in ProjectExplorer::Internal::LocalApplicationRunControlFactory::canRun(ProjectExplorer::RunConfiguration*, Core::Id) const ()
   from /home/delaval/ws_ams/ros_qtcreator/qt-creator-build/lib/qtcreator/plugins/libProjectExplorer.so
`

**Comment by jmlago91** [comment]
Sorry, I'm running Ubuntu 14.04,  ROS Indigo and Qt 5.7.

**Comment by jmlago91** [comment]
After rebuilding all again, and manually configuring QtCreator to detect my Qt 5.7 installation, I obtain the same error, a segmentation fault.

**Comment by Levi-Armstrong** [comment]
Can you you run the setup script again, I change it to do a clean build each time. Then launch qtcreator from a terminal and let me know if it prints out any information prior to the segmentation fault.

**Comment by GarethZhang** [comment]
Hi,
I got the same problem here... Im running qt creator 5.6 on Ubuntu 14.04 ros jade

**Comment by Levi-Armstrong** [comment]
@GarethZhang can you run `qmake -v` and post the output?

**Comment by GarethZhang** [comment]
Hi, I am new to qt creator, the output is as follows

QMake version 3.0
Using Qt version 5.6.0 in /home/haowei/Qt/5.6/gcc_64/lib

Not sure if this is what you need...

**Comment by Levi-Armstrong** [comment]
@GarethZhang I have update the setup script to help debug this issue. Can you rerun the command below in the ros_qtc_plugin directory?
`bash setup.sh -u`

Then run the command below and follow step 4 of the [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-Setup-ROS-Qt-Creator-Plug-in#section1.4).
`bash setup.sh -ui`

**Comment by GarethZhang** [comment]
Hi, below is the command line output. Qt creator froze (didnt quit) as I tried to create a ros package. Hope these information can be helpful

`haowei@Haowei-PC:~/Documents/src/ros_qtc_plugin$ gdb /home/haowei/Documents/src/qt-creator-build/bin/qtcreator
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/haowei/Documents/src/qt-creator-build/bin/qtcreator...Reading symbols from /home/haowei/Documents/src/qt-creator-build/bin/qtcreator.debug...done.
done.
(gdb) run
Starting program: /home/haowei/Documents/src/qt-creator-build/bin/qtcreator 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffebfd6700 (LWP 23050)]
[New Thread 0x7fffe1eea700 (LWP 23051)]
[New Thread 0x7fffe16e9700 (LWP 23052)]
[New Thread 0x7fffe0cce700 (LWP 23053)]
[New Thread 0x7fffd1373700 (LWP 23055)]
[New Thread 0x7fffd0b72700 (LWP 23056)]
[New Thread 0x7fffcbfff700 (LWP 23057)]
[Thread 0x7fffd0b72700 (LWP 23056) exited]
QML debugging is enabled. Only use this in a safe environment.
[Thread 0x7fffcbfff700 (LWP 23057) exited]
[New Thread 0x7fffcbfff700 (LWP 23059)]
[New Thread 0x7fffd0b72700 (LWP 23060)]
[New Thread 0x7fffabd61700 (LWP 23061)]
[New Thread 0x7fffaa797700 (LWP 23062)]
[New Thread 0x7fffa8a4a700 (LWP 23065)]
[Thread 0x7fffa8a4a700 (LWP 23065) exited]

Program received signal SIGSEGV, Segmentation fault.
ProjectExplorer::Project::activeTarget (this=0x0)
    at ../../../../qt-creator/src/plugins/projectexplorer/project.cpp:233
233	    return d->m_activeTarget;
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y

`

**Comment by Levi-Armstrong** [comment]
After you receive this segfault can you type `bt` to print the back trace?

**Comment by GarethZhang** [comment]
Uhhh, the command took too long to run and I can try it another time

**Comment by Levi-Armstrong** [comment]
OK, I updated everything on my system and I am also no receiving the segfault. It looks like one of the base classes recently changed, so I am looking into what needs to be added.

**Comment by Levi-Armstrong** [comment]
@jmlago91, @GarethZhang, @fulinx, I just submitted PR #16 which will solve this issue. Once it is merged please run the setup script again and let me know if it solves the issue on your end.

**Comment by Levi-Armstrong** [comment]
@jmlago91, @GarethZhang, @fulinx it has been merged so you should be able to test the changes.

**Comment by jmlago91** [comment]
Thanks! All is working now!
