### ISSUE TITLE
QtCreator Menu bar disapear after passing in ui edit mode

### ISSUE THREAD

**Issue by PrMoustache** [ros-industrial/ros_qtc_plugin#121]
Hello everybody,

It's seems that when I edit a ui file with ros_qtc I can have acces anymore  to  qtCreator menu bar (can't access to File, Edit, Debug etc).
It's realy realted to the ui edit mode (Qtdesigner) and note the ui file's because I can edit them in text mode.

here below some information about my system and the ui file that i'm working with (mainwindow.txt didn't try with other ui's)

Does anyone has a clue ?

By the way thank to developers, it's a great tool.  

[qtCreator_information.txt](https://github.com/ros-industrial/ros_qtc_plugin/files/990104/qtCreator_information.txt)
[mainwindow.txt](https://github.com/ros-industrial/ros_qtc_plugin/files/990127/mainwindow.txt)

**Comment by Levi-Armstrong** [comment]
Hello, I am sorry you are have issues. Can you provide your system information?

**Comment by PrMoustache** [comment]
Can you tell me what could help you more than that I have put into qtCreator_information.txt because I don't know what more could be use full (lsb_release ouput is on the third line).

**Comment by Levi-Armstrong** [comment]
@PrMoustache, Sorry missed those files. Does the menu come back when closing and reopening the application?

**Comment by Levi-Armstrong** [comment]
@marip8 Didn't you have a similar issue where the Qt Creator Menu disappeared?

**Comment by PrMoustache** [comment]
@Levi-Armstrong Yes, it comes back. It's really as soon as I edit a ui file. I don't have this issues with any other editing mode (ressouces files)

**Comment by Levi-Armstrong** [comment]
I will take a look and see if I have the same experience.

**Comment by marip8** [comment]
@Levi-Armstrong `ctrl-shift-f11` is a hot-key for making the menu bar in the QT editor appear and disappear. Maybe that might solve this issue?

**Comment by PrMoustache** [comment]
Juste tried, didn't made it. it just put QtCreator in fullscreen.
By the way changing the ubuntu menu window's location (in system parameter) don't change the problem.

**Comment by Levi-Armstrong** [comment]
I just tested it on my machine and the menu bar does not disappear. Have you tried performing a purge removal and reinstalling qt57 libraries?

**Comment by PrMoustache** [comment]
Sorry I thought I had answered.
Nop I didn't try this solution and I won't for the moment, maybe within 2 weeks.

**Comment by AgnosticPope** [comment]
I'm having the same issue.  Ubuntuj 14.04.  Completely reproducible.

**Comment by Levi-Armstrong** [comment]
Have you tried a purge removal and then reinstall of the qt57 libraries?

**Comment by PrMoustache** [comment]
I've just tried, still the same problem.

**Comment by AgnosticPope** [comment]
It's not a problem with the plugin persay, it also happens in Vanilla creator.  Shall we perhaps move the bug there?

**Comment by Levi-Armstrong** [comment]
I agree it is most likely and issues in Qt Creator and not the plugin.
