### ISSUE TITLE
Some index files failed to download

### ISSUE THREAD

**Issue by ahuo002** [ros-industrial/ros_qtc_plugin#122]
Err http://ppa.launchpad.net trusty/main amd64 Packages                        
  404  Not Found
Hit http://cn.archive.ubuntu.com trusty/restricted i386 Packages               
Err http://ppa.launchpad.net trusty/main i386 Packages                         
  404  Not Found
Hit http://cn.archive.ubuntu.com trusty/universe i386 Packages                 
Ign http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://cn.archive.ubuntu.com trusty/multiverse i386 Packages               
Hit http://cn.archive.ubuntu.com trusty/main Translation-en                    
Hit http://cn.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://cn.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://cn.archive.ubuntu.com trusty/universe Translation-en                
W: Failed to fetch http://ppa.launchpad.net/yani/iatsl/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/yani/iatsl/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by Levi-Armstrong** [comment]
It should be fixed now, I was working on trying to fix some open issues.
