### ISSUE TITLE
Cannot change from 2 spaces

### ISSUE THREAD

**Issue by AgnosticPope** [ros-industrial/ros_qtc_plugin#123]
When you hit tab, it is always 2 spaces. This is the default (as it should be!) but there's no way to change it.  If you go into Tools->Options->C++ and select "Qt [builtin]" or any other value can be selected, but the formatting will still be two spaces (I think it's getting this from "ROS [builtin]"?) when you hit tab, or use Ctrl+I to format a section of code.

**Comment by Levi-Armstrong** [comment]
Is this in a ros project? If so , it is set at the project level. Got to the project tab on the left and then there should be a code style section where you can change it for the project. You can also set it to use global settings.

**Comment by Levi-Armstrong** [comment]
@AgnosticPope Did this resolve your issue?

**Comment by AgnosticPope** [comment]
Yes it did. I'm old enough to remember when creator didn't have per project settings for style, and I think I forgot:)  Thank you!

**Comment by nathangeorge1** [comment]
If possible in one of the setup tutorials, maybe add the steps for changing the editor and code style settings within the Projects tab, saying that going to the Tools > Options thing doesn't work for QT ROS project; I didn't know that and had to come here to resolve it. Thanks.

**Comment by Levi-Armstrong** [comment]
Sounds great! Do you mind updating the wiki?

**Comment by nathangeorge1** [comment]
Not at all; I didn't know I was allowed to do that. I will do that sometime soon.

**Comment by Levi-Armstrong** [comment]
If you cannot let me know.

**Comment by nathangeorge1** [comment]
Another problem I am having is that when I set the tab policy to tabs only, it actually is outputting 4 spaces, which is making it difficult to develop in Python; my settings:

![image](https://user-images.githubusercontent.com/2744891/31093500-e878c032-a77f-11e7-8a11-c3c4ae5d272b.png)

any ideas?

**Comment by Levi-Armstrong** [comment]
Are you changing it in the project setting or at the global level?

**Comment by Levi-Armstrong** [comment]
In the project tab > project settings for the ROS[built-in] copy it and then select edit and update it there and it should work.

**Comment by nathangeorge1** [comment]
O, I was changing it in the global setting on accident. I changed it in Projects >Editor. I'll update the wiki now. Also, I noticed that changing in Projects > Code Style does not working, even if I make a copy of ROS[built-in].

**Comment by nathangeorge1** [comment]
Also, I don't believe I have write access to the wiki.

**Comment by Levi-Armstrong** [comment]
Sorry, It is now open to the public to make edits.

**Comment by nathangeorge1** [comment]
ok it's updated in section 3

**Comment by Levi-Armstrong** [comment]
Great! Thank you.
