### ISSUE TITLE
Add node class to Import Wizard

### ISSUE THREAD

**Issue by karanchawla** [ros-industrial/ros_qtc_plugin#124]
Hi,

I'd like to add default node class to the file import wizard. Any clue how I'd go about editing the code base? I'd like to create a new publisher/subscriber class and would like to have the boilerplate code for the same. 

IMO I'll have to edit the `ros_project_wizard.cpp` but I'm not sure. Can I get a clue as to how to go about achieving this. 

Thanks.

**Comment by Levi-Armstrong** [comment]
Thank you for your interest @karanchawla. I believe they may already be in this repository but have not been release in the latest binary. Please take a look and see if they need any improvements. If they are simple templates they can be implemented using JSON files and [here](https://github.com/ros-industrial/ros_qtc_plugin/tree/master/share/templates/wizards/files) are the ones currently implement in this plug-in. Also if you are interested in creating more advanced templates you can follow this [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/2.-Improve-ROS-Qt-Creator-Plugin-(Developers-ONLY)) to get setup for building the plugin locally.

**Comment by Levi-Armstrong** [comment]
This is now available in the latest release.
