### ISSUE TITLE
Update to Qt Creator v4.3.0

### ISSUE THREAD

**Issue by CodeFinder2** [ros-industrial/ros_qtc_plugin#126]
Hi,

first of all great work!

Qt Creator 4.3.0 / Qt 5.9.0 has been released. Would be great if you could update the repo with that version(s).

Thanks once again!

**Comment by Levi-Armstrong** [comment]
Thanks for letting me know; I will take a look.

**Comment by stefanchoo** [comment]
I got a  _fatal error: projectexplorer/iprojectmanager.h not found_ in building Qt Creator 4.3.0; The file 
 _iprojectmanager.h_ has been deleted in Qt Creator 4.3.0, please pay attention when you have time to do the job.

**Comment by Levi-Armstrong** [comment]
Thank you for the heads up. Is there a particular reason you want to use 4.3.0; did they add new capability?

**Comment by CodeFinder2** [comment]
On my side, I would like to use the new capabilities related to CMake's (>= v3.7) "server-mode". Also refactoring with "ClangRefactoring" plugin seems to be very interesting.

For information can be found here: http://blog.qt.io/blog/2017/05/24/qt-creator-4-3-0-released/

**Comment by Levi-Armstrong** [comment]
This is very interesting, I think it should be relatively easy to upgrade. Though it will most likely not use the server mode feature for the ROS plug-in for the short term, because it most likely will require significant changes.

**Comment by stefanchoo** [comment]
I wanna to use 4.3.0, just because I downloaded the Qt 5.9 which released with Qt Creator 4.3.0. And I agree with  @CodeFinder2, the CMake's (>= v3.7) "server-mode" is an interesting change.

**Comment by oxoocoffee** [comment]
I will try this tonight or tomorrow

**Comment by oxoocoffee** [comment]
Little update. I got it build against Qt5.9 couple of days ago. Needs more testing but it is coming.
Also added support to build against multiple Qt Creators versions so help with testing and allow multiple versions to run.

**Comment by facontidavide** [comment]
I am looking forward for this

**Comment by Levi-Armstrong** [comment]
Everything has been upgraded to 4.3.1, let me know if you have any issues.

**Comment by andrei-herdt** [comment]
The upgrade seems to be incomplete, since in setup.sh the default version is still set to 4.2 / 5.7.
Also, QtCreator 4.4 has been released this week. Could the plugin be used with this version too?

**Comment by Levi-Armstrong** [comment]
The plugin is currently released for 4.3.X and will not work with QtCreator 4.4. 

If you are using the setup.sh to build your own version instead of using the one provided by the ppa, you can build it for 4.3. Output the help for the setup.sh file and there is a way to change the branch for QtCreator.

**Comment by oxoocoffee** [comment]
If build fails for some reason please zip/tar setup.log file and attach to bug.
