### ISSUE TITLE
Problem with Installation procedure

### ISSUE THREAD

**Issue by DanielLandMineBoys** [ros-industrial/ros_qtc_plugin#127]
Hello, I'm a new user with ROS, and I am having trouble with trying to get the plugin to install.

I followed the instructions on the wiki and ran:
sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial  
sudo add-apt-repository ppa:levi-armstrong/ppa  
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros

When I ran the last command, It did manage to download some files, but it ended with an error:

```
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros
Hit:1 http://packages.ros.org/ros/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]     
Hit:3 http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu xenial InRelease      
Hit:4 http://ca.archive.ubuntu.com/ubuntu xenial InRelease              
Get:5 http://ca.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Ign:6 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial InRelease
Hit:7 http://ppa.launchpad.net/levi-armstrong/qt-libraries-xenial/ubuntu xenial InRelease
Ign:8 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial Release
Ign:9 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 Packages
Get:10 http://ca.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Ign:11 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en_CA
Ign:14 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en
Ign:15 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 Packages
Ign:11 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en_CA
Ign:14 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en
Ign:15 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 Packages
Ign:11 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en_CA
Ign:14 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en
Ign:15 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 Packages
Ign:11 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en_CA
Ign:14 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en
Ign:15 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Ign:9 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 Packages
Ign:11 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en_CA
Ign:14 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en
Ign:15 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Err:9 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 Packages
  404  Not Found
Ign:11 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main i386 Packages
Ign:12 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main all Packages
Ign:13 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en_CA
Ign:14 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main Translation-en
Ign:15 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main amd64 DEP-11 Metadata
Ign:16 http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial/main DEP-11 64x64 Icons
Fetched 306 kB in 4s (64.4 kB/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/levi-armstrong/qt-libraries-trusty/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

```
I attempted to run the commands
```
sudo add-apt-repository --remove ppa:beineri/opt-qt57-xenial
sudo add-apt-repository --remove ppa:beineri/opt-qt571-xenial
```
and
```
sudo rm /etc/apt/sources.list.d/beineri-opt-qt57-xenial-xenial.list
sudo rm /etc/apt/sources.list.d/beineri-opt-qt571-xenial-xenial.list
```

but when I tried to repeat the installation procedure and ran 
```
sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial  
sudo add-apt-repository ppa:levi-armstrong/ppa  
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros
```

afterwards, I obtained the same result. When I launch Qtcreator, I do not see an option to create a ROS Workspace under File>New File>Import Project as seen in https://www.youtube.com/watch?v=MPovFrZloaY 

Any insight would be appreciated. I apologize if this was the wrong place to post this.

**Comment by Levi-Armstrong** [comment]
Sorry, I thought I had already replied. It looks like the wrong ppa was add for the version of ubuntu. At the start of the statement you specify adding `sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial`, but the error out put show `ppa.launchpad.net/levi-armstrong/qt-libraries-trusty`. I think if you fix this everything should install correctly.

**Comment by Levi-Armstrong** [comment]
@DanielLandMineBoys were you able to solve the issue?

**Comment by FreelanceJavaDev** [comment]
I have a similar problem where I can't even locate the package.  I'm on Ubuntu Mate 16.04 running on a Raspberry Pi 3 (armv7)

**Comment by Levi-Armstrong** [comment]
Sorry it is currently only released for armv8. I will try one for armv7 but not sure how it will go.

**Comment by Levi-Armstrong** [comment]
They are currently building so I will keep you up to date.

**Comment by Levi-Armstrong** [comment]
@FreelanceJavaDev Most of the Qt Libraries built but two. It is complaining about a missing dependency libglesv2. Can you check and verify that this library is able to be installed on your machine?  If so it is most likely just a missing dependency in the debian which I can easily fix.

**Comment by FreelanceJavaDev** [comment]
Here's what I get in Terminal:
` Hit:1 http://packages.ros.org/ros/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/flexiondotorg/minecraft/ubuntu xenial InRelease
Hit:3 http://ports.ubuntu.com xenial InRelease                           
Hit:4 http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu xenial InRelease
Hit:5 http://ports.ubuntu.com xenial-updates InRelease
Hit:6 http://ppa.launchpad.net/levi-armstrong/qt-libraries-xenial/ubuntu xenial InRelease
Hit:7 http://ports.ubuntu.com xenial-security InRelease
Hit:8 http://ppa.launchpad.net/ubuntu-mate-dev/welcome/ubuntu xenial InRelease
Hit:9 http://ports.ubuntu.com xenial-backports InRelease                 
Hit:10 http://ppa.launchpad.net/ubuntu-mate-dev/xenial-mate/ubuntu xenial InRelease
Hit:11 http://ports.ubuntu.com/ubuntu-ports xenial InRelease             
Hit:12 http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu xenial InRelease
Hit:13 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease
Reading package lists... Done                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qt57creator-plugin-ros
E: Unable to locate package libqtermwidget57-0-dev
ros@ros-desktop:~$ sudo apt-get update
Hit:1 http://packages.ros.org/ros/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/flexiondotorg/minecraft/ubuntu xenial InRelease 
Hit:3 http://ports.ubuntu.com xenial InRelease                                 
Hit:4 http://ports.ubuntu.com xenial-updates InRelease                   
Hit:5 http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu xenial InRelease
Hit:6 http://ppa.launchpad.net/levi-armstrong/qt-libraries-xenial/ubuntu xenial InRelease
Hit:7 http://ports.ubuntu.com xenial-security InRelease                  
Hit:8 http://ppa.launchpad.net/ubuntu-mate-dev/welcome/ubuntu xenial InRelease
Hit:9 http://ports.ubuntu.com xenial-backports InRelease                 
Hit:10 http://ports.ubuntu.com/ubuntu-ports xenial InRelease             
Hit:11 http://ppa.launchpad.net/ubuntu-mate-dev/xenial-mate/ubuntu xenial InRelease
Hit:12 http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu xenial InRelease
Hit:13 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease    
Reading package lists... Done                      
ros@ros-desktop:~$ sudo apt-get update && sudo apt-get install qt57creator-plugin-ros libqtermwidget57-0-dev
Hit:1 http://packages.ros.org/ros/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/flexiondotorg/minecraft/ubuntu xenial InRelease
Hit:3 http://ports.ubuntu.com xenial InRelease                           
Hit:4 http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu xenial InRelease
Hit:5 http://ports.ubuntu.com xenial-updates InRelease                   
Hit:6 http://ppa.launchpad.net/levi-armstrong/qt-libraries-xenial/ubuntu xenial InRelease
Hit:7 http://ports.ubuntu.com xenial-security InRelease                  
Hit:8 http://ppa.launchpad.net/ubuntu-mate-dev/welcome/ubuntu xenial InRelease
Hit:9 http://ports.ubuntu.com xenial-backports InRelease                 
Hit:10 http://ports.ubuntu.com/ubuntu-ports xenial InRelease             
Hit:11 http://ppa.launchpad.net/ubuntu-mate-dev/xenial-mate/ubuntu xenial InRelease
Hit:12 http://ppa.launchpad.net/ubuntu-pi-flavour-makers/ppa/ubuntu xenial InRelease
Hit:13 http://ports.ubuntu.com/ubuntu-ports xenial-security InRelease    
Reading package lists... Done                      
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package qt57creator-plugin-ros
E: Unable to locate package `libqtermwidget57-0-dev`
For libgles I took this screenshot of the available options:
![libgles](https://user-images.githubusercontent.com/8966065/28739794-0e971896-73cc-11e7-85a1-21e453a257d5.png)

I currently have libgles2-mes and libgles2-mesa-dev.
Hope this helps...

**Comment by Levi-Armstrong** [comment]
Do mind trying the command below and see if the library is able to be installed?

`sudo apt install libglesv2`

**Comment by FreelanceJavaDev** [comment]
@Levi-Armstrong Unable to locate package. I've also tried `sudo apt-get install libglesv2` as well:
`sudo apt install libglesv2`
`[sudo] password for ros:` 
`Reading package lists...  Done`
`Building dependency tree`       
`Reading state information... Done`
`E: Unable to locate package libglesv2`

**Comment by Levi-Armstrong** [comment]
Ok I am going to see if I can find a work around.

**Comment by FreelanceJavaDev** [comment]
Thank you.

**Comment by Levi-Armstrong** [comment]
@FreelanceJavaDev  It looks like it is part of the libgles2-mesa-dev, but when building on the launchpad.net it still cannot find the library when linking. It does install it, but I think something is missing when executing qmake.

 I do not have a armv7 to do extensive testing. Would you be able to download the source [here](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt571-xenial/+files/qt57qbs_1.8.0.orig.tar.xz) and see if you can get it to build?

**Comment by Levi-Armstrong** [comment]
@FreelanceJavaDev Well I finally was able to tinker enough and get it to build on launchpad.net. Currently Qt Creator is building so hopefully everything goes smooth and it should be available for you to install.

**Comment by Levi-Armstrong** [comment]
Well Qt Creator did not build now, but I will keep working on it.

**Comment by Levi-Armstrong** [comment]
@FreelanceJavaDev QtCreator is now release under armv7 and I am now working on the plugin

**Comment by Levi-Armstrong** [comment]
@FreelanceJavaDev Everything is released for armv7 let me know if you have any issues.

**Comment by SalvaCobos** [comment]
Hello Levi,

I have Ubuntu 18.04, my architecture is aarch64 and the ros version I am using is ROS Melodic.
Is there a way to install the ros qtcreator plugin?
I have installed qtcreator in my system but the version of the installer (Bionic) for ubuntu 18.04 is not compatible with my architecture.

Thank you in advance.
Best regards

**Comment by Levi-Armstrong** [comment]
@SalvaCobos This architecture is currently not supported. You may be able to pull down add build from source.

**Comment by SalvaCobos** [comment]
Thank you Levi,

I am trying to install everything from: https://github.com/ros-industrial/ros_qtc_plugin
I have installed all the dependencies except libqtermdiget 57-0-dev. 
Do you know how I can install libqtermdiget 57-0-dev?

Many thanks!

**Comment by Levi-Armstrong** [comment]
[This](https://github.com/Levi-Armstrong/ros_qtc_plugin/tree/master/installer) has a lot of useful information. This contains the scripts I use for building the installer which you may be able to modify to get one for your architecture.
