### ISSUE TITLE
setup procedure without PPA

### ISSUE THREAD

**Issue by NikolausDemmel** [ros-industrial/ros_qtc_plugin#128]
What is the best way to compile this plugin for a recent version of QtCreator without using the debs from the PPA? I.e. how would I go about downloading the official binary releases of Qt / QtCreator and then compiling this plugin against those?

**Comment by gavanderhoorn** [comment]
Not sure whether it's 'the best way', but I've done something in the past, before the plugin was distributed using the PPA.

See #17, in particular https://github.com/ros-industrial/ros_qtc_plugin/issues/17#issuecomment-231378913 and the linked gist.

**Comment by Levi-Armstrong** [comment]
You may also take a look at the debian rules file [here](https://github.com/Levi-Armstrong/ros_qtc_plugin/blob/debian/trusty/debian/rules) used to build the debian. You would most likely need to update the `QTC_SOURCE_DIR` and `QT_BASE_DIR` variable which set the location of the source and install location.

**Comment by NikolausDemmel** [comment]
Thanks @gavanderhoorn and @Levi-Armstrong. In the meantime I have actually managed to get this working with qtcreator from PPA on our setup, but this should serve nicely as a future reference for me and others.
