### ISSUE TITLE
RVIZ errors after sourcing /opt/qt57/bin/qt57-env.sh

### ISSUE THREAD

**Issue by MarqRazz** [ros-industrial/ros_qtc_plugin#130]
This is an issue I am having on a fresh install of Ubuntu 16.04 and Kinetic. I installed QT 5.7.1 with QT Creator 4.2.0. If this bug belongs to RVIZ just let me know and I will close and move this.

I downloaded QT (this is the same version I was using on Indigo)
`wget http://download.qt.io/official_releases/qt/5.7/5.7.1/qt-opensource-linux-x64-5.7.1.run`

After install of QT I can fire up RVIZ without any issues. 
I then followed the directions on the wiki here to add the ros_qtc_plugin.

I get errors if I do either of the following and launch RVIZ:
1. I add a symbolic link to my local bin directory so I can launch qtcreator from the command line:
`sudo ln -s /home/marq/Qt5.7.1/Tools/QtCreator/bin/qtcreator /usr/local/bin/qtcreator`
2. I source the plugin environment
`source /opt/qt57/bin/qt57-env.sh`

I get the following errors when I start RVIZ....
```
[ INFO] [1498239700.746284509]: rviz version 1.12.10
[ INFO] [1498239700.746346144]: compiled against Qt version 5.5.1
[ INFO] [1498239700.746362084]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1498239701.669091732]: Stereo is NOT SUPPORTED
[ INFO] [1498239701.669184405]: OpenGl version: 4.5 (GLSL 4.5).
[ERROR] [1498239701.810493145]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/rotate.svg'
[ERROR] [1498239701.810542339]: Could not load pixmap 'package://rviz/icons/rotate.svg' -- using default cursor instead.
[ERROR] [1498239701.810698255]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/rotate_cam.svg'
[ERROR] [1498239701.810718621]: Could not load pixmap 'package://rviz/icons/rotate_cam.svg' -- using default cursor instead.
[ERROR] [1498239701.810845035]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/move2d.svg'
[ERROR] [1498239701.810865240]: Could not load pixmap 'package://rviz/icons/move2d.svg' -- using default cursor instead.
[ERROR] [1498239701.810981097]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/move_z.svg'
[ERROR] [1498239701.811001328]: Could not load pixmap 'package://rviz/icons/move_z.svg' -- using default cursor instead.
[ERROR] [1498239701.811117737]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/zoom.svg'
[ERROR] [1498239701.811137284]: Could not load pixmap 'package://rviz/icons/zoom.svg' -- using default cursor instead.
[ERROR] [1498239701.811265505]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/crosshair.svg'
[ERROR] [1498239701.811285406]: Could not load pixmap 'package://rviz/icons/crosshair.svg' -- using default cursor instead.
[ERROR] [1498239701.859351918]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/cursor.svg'
[ERROR] [1498239701.914988182]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/classes/Measure.svg'
[ERROR] [1498239701.915418690]: Could not load pixmap 'package://rviz/icons/crosshair.svg' -- using default cursor instead.
[ERROR] [1498239701.915866273]: Could not load pixmap 'package://rviz/icons/rotate.svg' -- using default cursor instead.
[ERROR] [1498239701.915913431]: Could not load pixmap 'package://rviz/icons/rotate_cam.svg' -- using default cursor instead.
[ERROR] [1498239701.915946760]: Could not load pixmap 'package://rviz/icons/move2d.svg' -- using default cursor instead.
[ERROR] [1498239701.915977185]: Could not load pixmap 'package://rviz/icons/move_z.svg' -- using default cursor instead.
[ERROR] [1498239701.916014260]: Could not load pixmap 'package://rviz/icons/zoom.svg' -- using default cursor instead.
[ERROR] [1498239701.916030751]: Could not load pixmap 'package://rviz/icons/crosshair.svg' -- using default cursor instead.
[ERROR] [1498239701.926973073]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/classes/Displays.svg'
[ERROR] [1498239701.932463131]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/classes/Views.svg'
[ERROR] [1498239701.935306068]: Could not load pixmap '/opt/ros/kinetic/share/rviz/icons/classes/Time.svg'
```

**Comment by Levi-Armstrong** [comment]
I have also see this on my machine but I does not appear to have any effect on Rviz. Do you have any issues with Rviz? I think it may have to do with sourcing qt57 when rviz was compiled with 5.5.1. When you don't source qt57 do the errors appear?

**Comment by MarqRazz** [comment]
It doesn't seem to have any effect other than the icons that couldn't load chance to little blue squares.

I ended up making a symbolic link for the .desktop launch for QT from `~/.local/share/applications/` to my desktop and changed the Exec line to ``Exec=/opt/qt57/bin/qtcreator`` so that I can launch from there without all my shells having to sourcing `source /opt/qt57/bin/qt57-env.sh`. I cant launch from terminal but that's pretty easy to live with.

**Comment by gavanderhoorn** [comment]
Doesn't the Qt installer include the `-wrapper.sh` script? That would seem to avoid having to `source` all sorts of files?

Btw: is using the regular Qt installer and the plugin from the PPA actually supported @Levi-Armstrong? Are the Qt Creator version in your PPA and the one from the regular installer binary compatible?

**Comment by Levi-Armstrong** [comment]
>Doesn't the Qt installer include the -wrapper.sh script? That would seem to avoid having to source all sorts of files?

You are correct there is a wrapper, @MarqRazz you may have better luck if you created a symbolic link against the -wrapper.sh instead of directly against `/opt/qt57/bin/qtcreator`.

>Btw: is using the regular Qt installer and the plugin from the PPA actually supported @Levi-Armstrong?

Qt installer? Are you referring to downloading Qt from there website and installing versus using `sudo apt install`? If so, it currently is not. 

>Are the Qt Creator version in your PPA and the one from the regular installer binary compatible?

They should be.

**Comment by gavanderhoorn** [comment]
>>Btw: is using the regular Qt installer and the plugin from the PPA actually supported @Levi-Armstrong?
> 
> Qt installer? Are you referring to downloading Qt from there website and installing versus using `sudo apt install`? If so, it currently is not. 

Isn't that what @MarqRazz is doing? See his OP:

> I downloaded QT (this is the same version I was using on Indigo)
`wget http://download.qt.io/official_releases/qt/5.7/5.7.1/qt-opensource-linux-x64-5.7.1.run`

**Comment by Levi-Armstrong** [comment]
Oh, I missed that part. It should be ok but it will not use them as it will install the Qt Libraries into the opt directory form my ppa.

**Comment by MarqRazz** [comment]
Are you saying that this step is not needed during install? 
> I downloaded QT (this is the same version I was using on Indigo)
wget http://download.qt.io/official_releases/qt/5.7/5.7.1/qt-opensource-linux-x64-5.7.1.run

I thought ros_qtc_plugin was just a plugin and required qtcreator to be installed beforehand.

**Comment by gavanderhoorn** [comment]
@MarqRazz wrote:
> 1 . I add a symbolic link to my local bin directory so I can launch qtcreator from the command line:
`sudo ln -s /home/marq/Qt5.7.1/Tools/QtCreator/bin/qtcreator /usr/local/bin/qtcreator`

@Levi-Armstrong: I'm uncertain what will happen here now, if @MarqRazz starts this instance of Qt Creator with all the environment variables pointing to the other one.

**Comment by gavanderhoorn** [comment]
@MarqRazz: no, you don't need to install Qt Creator yourself. The [install instructions](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)) also don't ask you to.

**Comment by MarqRazz** [comment]
> @Levi-Armstrong: I'm uncertain what will happen here now, if @MarqRazz starts this instance of Qt Creator with all the environment variables pointing to the other one.

I still get the RVIZ errors, but haven't tried to use the environment to see if there are other effects.

My bad.... I installed this partly from memory and the wiki instructions and thought that installing a version of qtcreator was a requirement (thinking this was a plug-in and not a full package). Some of the old instructions have you install it before the plugin.
[https://github.com/Levi-Armstrong/ros_qtc_plugins/wiki/Setup-Qt-Creator-for-ROS](url)

Ill clean up my install and let you know if I still get the errors.

**Comment by Levi-Armstrong** [comment]
@MarqRazz, Were you able to resolve the issue?

**Comment by MarqRazz** [comment]
Sorry It took me so long to get back to this. Everything is working fine now, thanks for your help guys!!

**Comment by msinvent** [comment]
Is the above problem resolved ? I am getting the same problem when I followed the exact installation instructions. Apart from that when I am running 
`rosrun rqt_graph rqt_graph`
I am getting the following error
```
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965

```
I am not able to see any visible changes with the tool

But when i did the same with 
`rosrun rqt_plot rqt_plot`
I am getting the same set of errors along with it is not working the way it should.

Is it have to do anything with the ros_qtc_plugin ? Can anyone reproduce the same results ?

**Comment by Levi-Armstrong** [comment]
If you build and run from a terminal does this error go away?

**Comment by msinvent** [comment]
No, it stays in both the cases.

**Comment by Levi-Armstrong** [comment]
Was it a clean build from the terminal? If so, I don't think it has to do with the ros_qtc_plugin but cannot be certain. One way to make sure is to create a virtual machine and test your running your code then install qtcreator and ros_qtc_plugin then test again and see if it shows up.

**Comment by msinvent** [comment]
Let me try this. Will get back to you once i will perform above test.

**Comment by akashjinandra** [comment]
Was anybody able to get rid of the rviz errors? It doesn't cause any issues as Levi mentioned, but it is kind of annoying as it spams the screen.

**Comment by Levi-Armstrong** [comment]
@akashjinandra If you delete the build and devel directory and build outside of Qt Creator does it go away?

**Comment by machinekoder** [comment]
I get exactly the same error, but I don't use the qtc plugin. I'm not sure if this error is what's causing problems in my visualization.

The error has very likely to do with multiple Qt versions being in use on one machine. I use Qt 5.10.1 for example, but my systems Qt version is 5.7. I recompiled ROS with Qt 5.10, but the problem resides.

**Comment by x-libin** [comment]
@MarqRazz , I have the same question as you, can you tell me how did you solve the problem。

**Comment by Levi-Armstrong** [comment]
If you switch to using the [Qt Installer](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html) this should go away. I would recommend completely removing the Qt version installed from beineri or levi-armstrong/qt-libraries-xenial ppa depending on when you first installed the plugin.
