### ISSUE TITLE
QtCreator installation issue - Ubuntu 14.04

### ISSUE THREAD

**Issue by marketto89** [ros-industrial/ros_qtc_plugin#131]
Hello,

Thank you for providing the best IDE for ROS!

I am trying to install ros_qtc_plugin on a fresh Ubuntu 14.04 machine.

Following the wiki: 
`sudo add-apt-repository ppa:levi-armstrong/qt-libraries-trusty
sudo add-apt-repository ppa:levi-armstrong/ppa  
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros`

I obtained the following (tail of the) error:

```
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en
Hit http://us.archive.ubuntu.com trusty/universe Translation-en
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US
Reading package lists... Done                                                  
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qt57creator-plugin-ros : Depends: qt57creator (>= 4.2.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Then, I tried:
`sudo apt-get install qt57creator`
with this result:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qt57creator : Depends: libllvm3.9 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Am I doing something wrong?
Thank you

**Comment by chupakabra1996** [comment]
Have the same issue.
Looked through issues and try to install ```qt57creator``` manually, no results

**Comment by lanyouzibetty** [comment]
Hello, I have met the same problem, have you solved it?

**Comment by Levi-Armstrong** [comment]
Sorry for the issue, recently the ability to use the clang code model was added which depends on libllvm3.9. I am not sure why it does not add it to the list of libraries to be installed but I am looking into if I set something up incorrectly during the Debian creation.

Try to manually install the libllvm3.9 library then try going through the install steps again.

**Comment by lanyouzibetty** [comment]
Hello, Levi-Armstrong, thanks for your reply. I installed the libllvm3.9 manually, but the problem still exists.

**Comment by lanyouzibetty** [comment]
@Levi-Armstrong Hello, thanks for your reply, I installed the libllvm3.9 manually, but the problem still exists.

**Comment by Levi-Armstrong** [comment]
What error does it print out?

**Comment by Thompson104** [comment]
@Levi-Armstrong Same error message after manually installed libllvm 3.9

**Comment by Levi-Armstrong** [comment]
I found the issue libllvm3.9 was renamed to libllvm3.9v4 on trusty. I will update it and let you know when it has been published.

**Comment by Thompson104** [comment]
@Levi-Armstrong Thank you for your help.

**Comment by Levi-Armstrong** [comment]
There is a new version, let me know if you have any issues.

**Comment by marketto89** [comment]
Thank you @Levi-Armstrong it works!

**Comment by lanyouzibetty** [comment]
@marketto89 hello, how did you solve this problem? I installed the libllvm3.9v4 manually, but the problem still exists, thanks in advance.
