### ISSUE TITLE
Plugin working but QT is not resolving my include files

### ISSUE THREAD

**Issue by reinzor** [ros-industrial/ros_qtc_plugin#132]
![image](https://user-images.githubusercontent.com/4176023/27984775-83e7b996-63de-11e7-9480-ed39e9e9548d.png)

Set-up my workspace using catkin tools, compiling works but my include files are not resolved (picture above). Any ideas? Just followed the user-setup WIKI.

**Comment by Levi-Armstrong** [comment]
Are you compiling using the IDE or from the command line?

**Comment by Levi-Armstrong** [comment]
I should probably add this to the wiki somewhere, but when using the IDE you will need to build once and after every clean from within the IDE which will generate a project file that the IDE parses to build the internal code model. After this you may build from the terminal, but you will occasionally need to update the code model by right on the project node and selecting reload code model. This is only necessary when you make edits to a CMakeLists.txt file but not project files.

**Comment by Levi-Armstrong** [comment]
@reinzor were you able to resolve the issue?

**Comment by reinzor** [comment]
Hi @Levi-Armstrong , I dit not have time yet to look back at this issue. I will give it a shot this weekend. Thanks!

**Comment by reinzor** [comment]
Still not working, I did try the following:

1) catkin build on new ws --> import ws in qtcreator (not working)
2) catkin clean in qtcreator --> catkin build --> repopened ws --> build (not working)

Any ideas?

**Comment by Levi-Armstrong** [comment]
Can you check the build directory and in each packages directory there should be a file package_name.cbp? Let me know if they exist or not.

**Comment by lochappy** [comment]
I aslo have the similar issue, any idea? The .cbp does exist in my case.

**Comment by lochappy** [comment]
I guess it cannot load the include path for some reason. Is there any way to add the include path manually, just like INCLUDEPATH += /opt/ros/indigo/include in normal .pro file, for example?

**Comment by Levi-Armstrong** [comment]
Just want to check. You followed the instructions for importing a ros workspace and have built it using qt creator? If it is missing the .cbp file this is due to not building using qt creator.

**Comment by lochappy** [comment]
I followed the procedure as:
From QtCreator 4.2.1, (QT 5.7.1)
 + File -> New Project -> Import Project -> Import ROS Workspace (Distribution : Indigo, Build system: CatkinMake, the workspace path points to an empty folder) -> Next -> Finish
 + From  sidebar, right-click on src -> add new -> ROS -> Package -> (Name: demo, Dependencies Catkin: roscpp) -> Next -> Finish
 + From  sidebar, right-click on demo -> add new -> ROS -> Basic Node -> (Name: demo) -> Next -> Finish
![screenshot from 2017-07-29 11 26 30](https://user-images.githubusercontent.com/9412700/28741785-cc9341ec-7450-11e7-9fec-24be2acb6515.png)

The #include <ros/ros.h> cannot be resolved.

**Comment by Levi-Armstrong** [comment]
OK have you built from within Qt Creator?

**Comment by lochappy** [comment]
I have built it within the Qt Creator,the attachment is the compile output.
![screenshot from 2017-07-29 11 35 12](https://user-images.githubusercontent.com/9412700/28741817-0d04a30a-7452-11e7-8f50-54c1edade303.png)

**Comment by Levi-Armstrong** [comment]
Have you added the add_executable for demo.cpp to the CMakeLists file?

**Comment by lochappy** [comment]
I did not, I thought I was automatically added in when I created through QtCreator.
I just added it manually, then thing works fine now.
Thank you very much for your quick reply!!!

**Comment by Levi-Armstrong** [comment]
Great! This is something that is in the plan.

**Comment by lochappy** [comment]
Can't wait to see this feature!!! Cheers!!!

**Comment by nathangeorge1** [comment]
I built my `catkin_ws` within QtCreator; here's the output:

![image](https://user-images.githubusercontent.com/2744891/29835260-6ecb703e-8cbf-11e7-94c3-73067855c34a.png)

but my header files are not being resolved:

![image](https://user-images.githubusercontent.com/2744891/29835309-9697c9f0-8cbf-11e7-9bbd-bfdf46d71658.png)

I also right-clicked the `catkin_ws` and ran "Reload Project Build Info..."

What am I missing?

**Comment by nathangeorge1** [comment]
I got it working, I needed to right click the project and `Build`; the problem was that it wasn't building properly; simple enough

**Comment by Levi-Armstrong** [comment]
That is interesting. Let me know if you keep running into the same issue.

**Comment by nathangeorge1** [comment]
o @Levi-Armstrong , I meant that by personal project had build issues; nothing wrong with your repo; although, there wasn't much documentation on solving this problem; so it might be helpful to newcomers to have a doc or video on solving build and indexing issues.

**Comment by ARSblithe212** [comment]
hi i meet the same problem . how do you solve it?

**Comment by Levi-Armstrong** [comment]
@ARSblithe212  Did you build from within the IDE?

**Comment by ARSblithe212** [comment]
Thank you!!!  The reason is not Build.

**Comment by Levi-Armstrong** [comment]
I am working on integrating the CMake Build Manager developed by Qt Creator which uses the CMake Server which should alleviate this issue in the future.
