### ISSUE TITLE
 Could not find a package configuration file provided by "roscpp"

### ISSUE THREAD

**Issue by antoan** [ros-industrial/ros_qtc_plugin#133]
After following the installation instructions in the wiki I get the above error when opening a catkin package

Ubuntu 14.04
Qt Creator 4.2.1
[QtCreatorOutput.txt](https://github.com/ros-industrial/ros_qtc_plugin/files/1152152/QtCreatorOutput.txt)

**Comment by Levi-Armstrong** [comment]
Do you have ROS installed?

**Comment by antoan** [comment]
Yes, ROS Indigo LTS

**Comment by Levi-Armstrong** [comment]
Can you post the qtcreator environment for the project? If you go to the project tab on the left and under build you will find the environment information.

**Comment by antoan** [comment]
I took some screenshots as I wasn't able to select/copy/paste the environment listings directly, I hope thats ok.
![env1](https://user-images.githubusercontent.com/1454427/28830798-bdfdb6d6-76cf-11e7-8044-8f252ab56e3c.png)
![env2](https://user-images.githubusercontent.com/1454427/28830802-bee74f4e-76cf-11e7-9cf8-07c6d7cddfd8.png)
![env3](https://user-images.githubusercontent.com/1454427/28830797-bdf57304-76cf-11e7-9911-c788e8bb0415.png)

**Comment by Levi-Armstrong** [comment]
OK, I see the issue. You are opened it as a CMake Project and not a ROS Project. To open as a ROS project goto File>New File or Project>Projects>Import Project>Import ROS Workspace and follow the instruction. I recommend selecting Catkin Tools as the build system.

**Comment by Levi-Armstrong** [comment]
@antoan Were you able to import it as a ros project?

**Comment by antoan** [comment]
Not quite, I got a  notification for the desktop kit which mentions my version of Cmake 
is unsupported and I need to upgrade to 3.0?

Other than that, I seem to be able to load my catkin workspace which contains multiple ros packages. Is it possible to open packages individually?

**Comment by Levi-Armstrong** [comment]
The plugin still require it be a workspace. But if you have it in a workspace and you only want to see a single package in the project tree, then open up the  <project_name>.workspace and change the input *src* to *src/<package_name>* and only this package will show ups.

```
<WatchDirectories>
  <Directory>src/package_name</Directory>
</WatchDirectories>
```

If you want see more than one package then do this.
```
<WatchDirectories>
  <Directory>src/package_name1</Directory>
  <Directory>src/package_name2</Directory>
</WatchDirectories>
```

**Comment by antoan** [comment]
I see, thank you. 

I'm still unable to build, I'm guessing because of the Cmake version issue I mentioned earlier? What would be the best way to resolve this?

```
14:11:40: Could not start process "catkin" build --cmake-args -G 'CodeBlocks - Unix Makefiles' -DCMAKE_BUILD_TYPE=Debug
Error while building/deploying project test (kit: Desktop)
The kit Desktop has configuration issues which might be the root cause for this problem.
When executing step "CatkinTools Step"
```

**Comment by Levi-Armstrong** [comment]
Do you mind providing another screen shot of your build configuration screen?

**Comment by Levi-Armstrong** [comment]
@antoan Did you add the CatkinTools Step under the deploy section?

**Comment by Levi-Armstrong** [comment]
No Response
