### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by AustinDeric** [ros-industrial/ros_qtc_plugin#134]
/opt/qt57/bin/qtcreator: symbol lookup error: /opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libROSProjectManager.so: undefined symbol: _ZN4YAML6detail9node_data14convert_to_mapEN5boost10shared_ptrINS0_13memory_holderEEE

when running opening a project or specifying catkin tools.  everything works fine when using catkin_make.

**Comment by AustinDeric** [comment]
running```sudo apt-get install libboost1.58-all-dev``` fixes the issue.  If there are no code mods on the QT side to give a clearer error message or install boost 1.58 with QT, then we should close the issue.

**Comment by Levi-Armstrong** [comment]
Is this on kinetic?

**Comment by Levi-Armstrong** [comment]
It sounds like I may not be linking against yamlcpp correctly discussed [here](https://stackoverflow.com/questions/36403287/compiler-error-with-yaml-cpp-undefined-reference-to-yamldetailnode-data).

**Comment by Levi-Armstrong** [comment]
Also I just noticed that yaml-cpp is not a run depend for the binary. Can you verify that yaml-cpp is installed?

**Comment by Levi-Armstrong** [comment]
@AustinDeric were you able to resolve the issue?

**Comment by Levi-Armstrong** [comment]
@AustinDeric Were you able to resolve the issue?
