### ISSUE TITLE
Indexing ("building C++ Code Model") fails for packages that are symlinked into the catkin source space

### ISSUE THREAD

**Issue by koenlek** [ros-industrial/ros_qtc_plugin#137]
I have a workspace in which I add a stack of packages using a symlink. I.e. on my system I have:

- `~/my-project-git-clone/ros/` which contains several packages.
- `~/catkin_ws`, which is my catkin tools based catkin ws.
- and a symlink `~/catkin_ws/src/ros -> ~/my-project-git-clone/ros/`. 

This works fine with catkin tools, but unfortunately, the ROS Qt Creator plugin seems unable to deal with it. My includes don't resolve, code completion doesn't work, etc. In other words: indexing (or in Qt terms: building the C++ Code Model) fails. Even after a clean rebuild.

As soon as I remove the symlink and put a copy of the folder and rebuild, all works fine. When I revert again and rebuild, indexing is broken again. Using a bind mount also works fine.

I also tried to point the catkin source space directly to the folder, rather than symlinking below `catkin_ws/src`. E.g. `catkin config -s ~/my-project-git-clone/ros/`. This works fine with catkin tools, but I couldn't get QtCreator to deal with it. It wouldn't show any source files at all (in the Edit view, "projects" section). I tried deleting the qtcreator project files and recreating it, but I couldn't get it to work. I even tried hardcoding the absolute src path `/home/<me>/my-project-git-clone/ros/` as a "watch direcotry" in the `<project_name>.workspace` file. No luck...

So far I have no nice solution, except for the bind mount (which I need to do after every reboot).

I'm not sure if this bug is with the Plugin, or with QtCreator itself. It would be great if it could be fixed!

**Comment by Levi-Armstrong** [comment]
I will create a test case and see how to resolve the issue.

**Comment by Levi-Armstrong** [comment]
This should be resolved by #152

**Comment by Levi-Armstrong** [comment]
@koenlek I just released everything for 4.4.1 which should fix the issue let me know if it does not.

**Comment by koenlek** [comment]
Works like a charm!
