### ISSUE TITLE
Add `--no-status` as `catkin build` arg by default

### ISSUE THREAD

**Issue by koenlek** [ros-industrial/ros_qtc_plugin#138]
The Compile Output console of QtCreator is polluted by many lines because the console isn't capable of dealing with 'carriage returns'. The catkin tools 'status bar' at the bottom of the compile output is normally updated by using carriage returns, but in QtCreator it results in a new line for every update of the status line. To avoid this pollution, the switch `--no-status` can be used (from the catkin build help, it says *Suppresses status line, useful in situations where carriage return is not properly supported.*).

I would recommend adding this setting by default to the ROS QtCreator Plugin.

**Comment by Levi-Armstrong** [comment]
Thank you, I will add set it as the default.

**Comment by Levi-Armstrong** [comment]
@koenlek I tested this on a fresh install on a VM and it works fine without `--no-status`. I think it might be something with your configuration.

**Comment by koenlek** [comment]
For me, compiling works fine, but the output in the "Compile Output" window (which you can select in the bottom bar of qt-creator) shows tons of extra lines (every 'refresh' of the status msg creates a new line). Are you sure that doesn't happen in your VM? If it indeed works fine for you I'll fire up a VM too to check it myself too.

**Comment by Levi-Armstrong** [comment]
I don't see this on any of my VM's including the training VM. I have seen this on one other machine but they were have a lot issues other than this which lead me to believe something was different in there configuration.

**Comment by oxoocoffee** [comment]
I am also running on desktop and in couple VM and do not see this problem.

**Comment by koenlek** [comment]
Then I guess it's just me... I'll see this week if I can clear all QtCreator settings in some way to get it fixed... But for me we can consider this issue closed.
