### ISSUE TITLE
Need to restart the qt to reflect the update made in the launch files.

### ISSUE THREAD

**Issue by msinvent** [ros-industrial/ros_qtc_plugin#140]
I am running a simple program in which I am simply launching gazebo with and without the robot. The change is only appearing after I am restarting the qt.

I tried to remove and add the run step but to no avail. I am trying to build it again, but I believe that build is not happening again because there are no changes in the src files.

Is there any step that I can add so that I need not restart Qt again for the changes in the launch file to reflect?

Thanks

**Comment by Levi-Armstrong** [comment]
What files are you editing?

**Comment by Levi-Armstrong** [comment]
@msinvent are you still having issues.
