### ISSUE TITLE
I got error message about QbsProjectManager when run QTcreator

### ISSUE THREAD

**Issue by Neoplanetz** [ros-industrial/ros_qtc_plugin#142]
Hello. I install Ros Kinetic desktop-full. and I install QT creator plugin-ROS.

As follow this install instruction,  I install qt57creator-plugin-ros. 

sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial  
sudo add-apt-repository ppa:levi-armstrong/ppa  
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros

Installation is completely installed. and then, I execute qtcreator in terminal and I got this message always.
![error](https://user-images.githubusercontent.com/9695835/29998507-84c1b33e-9067-11e7-95f1-c13d210dae2e.JPG)

So, I remove qt57creator-plugin-ros  using this command 

 $  sudo apt-get --purge remove qt57creator-plugin-ros

and doing command as your instruction 

sudo add-apt-repository --remove ppa:beineri/opt-qt57-xenial
sudo add-apt-repository --remove ppa:beineri/opt-qt571-xenial

After that, I re-install qt57creator-plugin-ros, but all thing is same like before.

$  sudo apt-get update && sudo apt-get install qt57creator-plugin-ros

How could I solve this problem?

**Comment by lq1216766050** [comment]
I also encountered the same problem last night, but I installed this plugin on another machine 2 days ago did not appear on this issue, the problem you solved?

**Comment by Neoplanetz** [comment]
Not yet. What are your another machines you installed completely? 
In my case, I installed this plug-in in the VMware virtual machine. Is it a problem?

**Comment by lq1216766050** [comment]
I installed it on Ubuntu16.04 ，not on the virtual machine，and this time is also on Ubuntu16.04，I found that the problem don't affect the development. But every time I open the qt creator the Pop-ups is annoying. 
`/opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libQbsProjectManager.so: Cannot load library /opt/qt57/lib/x86_64-linux-gnu/qtcreator/plugins/libQbsProjectManager.so: (libqbscore.so.1.7: 无法打开共享对象文件: 没有那个文件或目录)`
I  only found libqbscore.so.1.8 in /opt/qt57/lib, not libqbscore.so.1.7, and I found it in /home/liuqiang/Qt5.7.1/Tools/QtCreator/lib/qtcreator/plugins.I don't know what to do.

**Comment by Levi-Armstrong** [comment]
I am in the process of upgrading to Qt Creator 4.3 which is the reason for the error. I have a PR wait review sorry for the inconvenience.

**Comment by hljchenxi** [comment]
How long will it work ?

**Comment by Neoplanetz** [comment]
Levi Thank you for your work! We are waiting for fixing this problem ASAP ^^

**Comment by Levi-Armstrong** [comment]
If you are developing only ros projects it should work without issues.

**Comment by nathangeorge1** [comment]
thank you @Levi-Armstrong ; also experiencing the same problem

**Comment by nathangeorge1** [comment]
thanks @Levi-Armstrong ; now, I get the following error after getting the latest PR merge

![image](https://user-images.githubusercontent.com/2744891/30175586-0b7c9bce-93cd-11e7-90ba-e37480d2d357.png)

**Comment by js708fw** [comment]
I got same issue as @nathangeorge1 , cannot even open workspace

**Comment by Levi-Armstrong** [comment]
I am working the release of the plug-in for Qt 4.3.1 and should be available soon.

**Comment by Levi-Armstrong** [comment]
I don't recommend doing an update upgrade on your system until it is published.

**Comment by nathangeorge1** [comment]
Ok; is that until your release for the Qt 4.3.1 is published? 

Is there a way to revert back also, because I already did `sudo apt upgrade`?

**Comment by Levi-Armstrong** [comment]
It is available perform an update and upgrade and you should be good to go.

**Comment by nathangeorge1** [comment]
Cool; the errors went away; thanks; and great plugin btw!

**Comment by Levi-Armstrong** [comment]
Great! Let me know if you have any issues.
