### ISSUE TITLE
Command Panel Section disappeared

### ISSUE THREAD

**Issue by XuxinDoubleWang** [ros-industrial/ros_qtc_plugin#145]
Hi everyone, 
I am using QT to design my own GUI.
At beginning, I run my node, the window shows as following:
![1001667-20161221032040839-1490518329](https://user-images.githubusercontent.com/20387673/30192642-a63782ac-9416-11e7-8675-52755c70573d.png)

Once I closed Command Panel Section, I cannot open it due to I cannot find where to open it.
Now, my windows shows as following : 
![screenshot from 2017-09-07 18 25 40](https://user-images.githubusercontent.com/20387673/30192669-d9d9c61a-9416-11e7-9646-fbcd252d4ba6.png)
Does anyone know where I can reload the Command Panel Section?

Thanks in advance!!!

**Comment by Levi-Armstrong** [comment]
You will most likely need to add a button either in a menu or some where on the gui to show the panel again. If this is not the behavior you want you could change it to another widget where it minimizes to the left like some of the panels in rviz.

**Comment by alexchua0108** [comment]
{ui.[name of your dock widget]->show();
}
eg.  ui.dock_status->show();

add this in to the menu to show the panel again
