### ISSUE TITLE
Item "Import ROS Workspace" not available

### ISSUE THREAD

**Issue by JonathanSchmalhoferBMW** [ros-industrial/ros_qtc_plugin#146]
I do  have **qt57creator** installed on **Ubuntu 16.04 LTS** and installed the plugin as described in the Wiki. Yet, I cannot find the menu item "**Import ROS Workspace**" under **File>New File or Project>Projects>Import Project**.
The Plugin seems to be installed correctly though. Any ideas?

Screenshot: 
![image](https://user-images.githubusercontent.com/26005950/30210969-383023c0-949f-11e7-9142-36fbba1179ba.png)
![image](https://user-images.githubusercontent.com/26005950/30211007-66fd4692-949f-11e7-8e38-fa5f4ba5a726.png)

**Comment by Levi-Armstrong** [comment]
Sorry, The version I released yesterday moved it under `Other Project`. I will update the wiki.

**Comment by Levi-Armstrong** [comment]
The wiki has been updated.

**Comment by JonathanSchmalhoferBMW** [comment]
Thanks for the hint, but still there is no Menu-Item "**Import ROS Workspace**". I do have an Iteam "**ROS Workspace**" there, which seems to be used to create a new ROS Workspace from blank:
![image](https://user-images.githubusercontent.com/26005950/30212546-bb538fc0-94a5-11e7-8887-b04ffeecd879.png)

A colleague of mine had no problems following the tutorials a few weeks ago. He uses QT Creator 4.2.1 based on QT 5.7.1. I have QT Creator 4.3.1 based on QT 5.7.1 installed. Might this have an impact?

**Comment by Levi-Armstrong** [comment]
I did not relize the name was changed from Import ROS Workspace. Use the ROS Workspace option, it is used for both creating and opening existing workspaces.

**Comment by JonathanSchmalhoferBMW** [comment]
OK got it. The Menu-Title-Bar under "**ROS Workspace**" still states "Create New ROS Project" which mislead me to thinking, that this is a different workflow than importing an existing project. I guess this should be adapted to avoid future confusion.

Nevertheless, it works like a charm now. Thank you very much, @Levi-Armstrong!

**Comment by Levi-Armstrong** [comment]
Thank you for your feedback. I will update the title.
