### ISSUE TITLE
Update to Qt 5.9

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#147]

**Comment by justwillim** [comment]
expected for this very much.

**Comment by Levi-Armstrong** [comment]
I was able to build all dependencies on qt 5.9.1 for arm, so this weekend I will upgrade everything .

**Comment by x3Randomise** [comment]
HI Levi,

I got the following problem after update to Qt5.9

conghui@conghui-Pc:~$ sudo apt-get install qt59creator
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 **qt59creator : Depends: libclang1-4.0 (>= 3.6) but it is not installable**
               Recommends: qt59creator-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
conghui@conghui-Pc:~$

**Comment by x3Randomise** [comment]
The problem has been solved by ticking "Installed updates from" as the picture below.
![screenshot from 2017-10-19 14-26-22](https://user-images.githubusercontent.com/31727725/31757052-c84462dc-b4d9-11e7-9205-0a827738c8c4.png)

**Comment by Levi-Armstrong** [comment]
@x3Randomise I apologize I missed this post. Let me know if you have may more issues.

**Comment by intgogo** [comment]
I  installed qt57creator-plugin-ros for qt5.9.2,but no ros found in qtcreator.How to fix this?

**Comment by intgogo** [comment]
Finally,I use this qtcreator and it works...
![screenshot from 2017-10-26 11-18-54](https://user-images.githubusercontent.com/31696329/32037584-8ccfa0de-ba58-11e7-90fa-0b3282b3ab98.png)

**Comment by Levi-Armstrong** [comment]
@intgogo I just released a new version of qtcreator which create a symbolic link in the usr/bin director called `qtcreator-ros` to make it easier to launch from a terminal.

**Comment by duonglacbk** [comment]
I install Qt59 with ros plugin but when I create a "new ros package" in tab ROS, the Qt is not responding and close. I think Qt59 may have some errors. Please help me!

**Comment by Levi-Armstrong** [comment]
Please provide step by step procedure to I may try and recreate the issue on my end?

**Comment by duonglacbk** [comment]
Sorry for late reply, I have been reinstall Ubuntu and Qt ros
1. I completed installing Ros plug in for Qt59 as this instruction:

sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial
sudo add-apt-repository ppa:levi-armstrong/ppa
sudo apt update && sudo apt install qt59creator
sudo apt install qt57creator-plugin-ros

2. I create a new ROS package:
![1](https://user-images.githubusercontent.com/15654372/33241227-f3a0ccaa-d305-11e7-9481-5f7d1dfd508a.png)

I only write ros as the name of my package

![2](https://user-images.githubusercontent.com/15654372/33241236-1380a3ec-d306-11e7-9807-b44426ac539d.png)

Then Next

![3](https://user-images.githubusercontent.com/15654372/33241242-1e13df40-d306-11e7-81f1-9045f6bc85ed.png)

After that I push Finish, the Qt59 auto close. And the errors as following:

![5](https://user-images.githubusercontent.com/15654372/33241318-02f26d02-d307-11e7-8b40-c5adc14e27bc.png)

![6](https://user-images.githubusercontent.com/15654372/33241323-14a68bbe-d307-11e7-97f4-95c7bb23e2d9.png)

Please help me!
If you need further information please let me know!

**Comment by Levi-Armstrong** [comment]
Ok have you created/imported your ros workspace prior to creating the package? The reason I ask is the path specified when creating the paclate looks like your home directory.

**Comment by duonglacbk** [comment]
Dear Levi-Armstrong,

That exactly as you predict. I didn't make a ROS workspace so that Qt can't create the Package in that 
workspace.

Thank @Levi-Armstrong  so much,
Best wish for you!

**Comment by Levi-Armstrong** [comment]
Great! I will create an issue to add a check and give an error message.
