### ISSUE TITLE
Import projects

### ISSUE THREAD

**Issue by BrunoXL** [ros-industrial/ros_qtc_plugin#148]
Is not possible to import ROS projects anymore unlike previous version?

![ros plugin](https://user-images.githubusercontent.com/11648780/30250941-497381c4-962d-11e7-9f0a-cf6093968f26.png)

**Comment by Levi-Armstrong** [comment]
It was moved to other projects in the latest version.

**Comment by BrunoXL** [comment]
On "other projects"  I'm just able to create new projects as i go through the menu.
It creates on the chosen path  the default ros folders (src, devel and build) again

**Comment by Levi-Armstrong** [comment]
It does the same as it did before. It should import is the workspace has already been initialized and if not it sets it up and initializes it.

**Comment by BrunoXL** [comment]
Ok. Know I saw
