### ISSUE TITLE
How to run launch file using PushButton

### ISSUE THREAD

**Issue by XuxinDoubleWang** [ros-industrial/ros_qtc_plugin#149]
Hi everyone,
I try to add many buttons that if I click one, one ros command line run automatically. 
For example, if I click a push button, one launch file from other packages can run.
I already added a push button in .ui.
However, I tried some methods by myself to finish the following function (created by QT) but it is not successfully.

void qt::MainWindow::on_run_clicked()
{
    
}

Does anyone have some tutorials or ideas about it? 
Many thanks in advance!!!!!!!

**Comment by Levi-Armstrong** [comment]
Where would you like to see the output? If you don't care to see the output you can create a qprocess object, start a bash terminal an send it the same commands you would in a terminal. Take a look at this [file](https://github.com/ros-industrial/ros_qtc_plugin/blob/master/src/project_manager/ros_utils.cpp) I do this several places to get ros related information. If you are interested in see the output within your GUI I would recommend integrating qtermwidget and send it the commands.

**Comment by Levi-Armstrong** [comment]
@XuxinDoubleWang Were you able to get it to work?

**Comment by XuxinDoubleWang** [comment]
No, I have not. I am working on it. If I finish it , I will post it here.

**Comment by Maunil2k** [comment]
Hey @Levi-Armstrong ,
Could you pls share some reference material related to this again, the link that you had sent earlier is not working.

**Comment by christian-rauch** [comment]
I think this question was generically about how to launch _something_ via a button press in Qt. It's not related to the plugin. I am going to close this. If this is related to the plugin, reopen the issue and provide details.
