### ISSUE TITLE
"Follow symbol under cursor, F2 shortcut" not working

### ISSUE THREAD

**Issue by raultron** [ros-industrial/ros_qtc_plugin#15]
Hi,

Whenever I opened a package into Qt Creator using the CMakeLists.txt file (previous method that I had before using your plugin) I was able to navigate through my code using Qt Creator shortcuts (e.g select the name of a function and press F2 to go into the function definition).

Now using your plugin, even though I am able to build everything I can't do that anymore. Does it work for you? maybe I have something wrong in my config.

thanks.

**Comment by Levi-Armstrong** [comment]
Try right clicking on the project node, then select **Reload Project Include Directories...**

**Comment by Levi-Armstrong** [comment]
@raultron, were you able to resolve the issue?

**Comment by raultron** [comment]
I did a Reload Project Include Directories, took some time, still doesn't work.
Qt Creator gives me a warning in each of my packages includes, for example in a cpp file if I have:

    #include " my_package_name/my_node_include.hpp"

Qt creator gives me the following message when I hover with the mouse in that line:

    my_package_name/my_node_include.hpp: No such file or directory

**Comment by raultron** [comment]
I got it to work. I deleted the .workspace files in my catkin_ws, cleaned everything using catkin and then imported the project again. I wonder if I will have to do that everytime I add a new package to my workspace.

Thanks for the help.

**Comment by Levi-Armstrong** [comment]
You should not, but anytime a new library is added to the cmakelists.txt or a new package is added you will need to **Reload Project Include Directories...**. The Reload should of solved the issue if you run into this issue again please let me know. 

I am currently working on an improvement to manage this internally so the user does not have to manually update the code model, but it is not ready yet.

**Comment by raultron** [comment]
Ok everything clear. Thank you very much for your help. I have been programming the whole week with your plugin and it is very comfortable. All my colleagues are starting to use it as well.

**Comment by Yiping-Steven** [comment]
I had the same problem and cannot solve by reloading the project or catkin clean & build

**Comment by Levi-Armstrong** [comment]
Has the project successfully built? The reason I ask is because the Code model will not get built until you have at least one successful build. Then if following builds fail it will continue to use the last successful one.

**Comment by Levi-Armstrong** [comment]
Also look at the general message tab and see if you see any [ROS WARNING|ERROR|DEBUG].
