### ISSUE TITLE
ERROR Operation canceled when run setup script.

### ISSUE THREAD

**Issue by surachairobotic** [ros-industrial/ros_qtc_plugin#150]
I try install ROS Qt Creator Plugin follow by this tutorial --> [https://github.com/ros-industrial/ros_qtc_plugin/wiki/2.-Improve-ROS-Qt-Creator-Plugin-(Developers-ONLY)](url)
In step 
1.3 Run ROS Qt Creator setup script.
git clone -b master https://github.com/ros-industrial/ros_qtc_plugins.git
but when run this command [ **bash setup.sh -d** ] got a **_ERROR_** message below.

> dell@dell-Inspiron-3543:~/catkin_ws/src/ros_qtc_plugin$ bash setup.sh -d
> == Output redirected to setup.log
> == ROS Qt Plugin Git(d3662b6)
> ==
> == Checking build dependencies
> ==  Installed      : build-essential
> ==  Installed      : libgl1-mesa-dev
> ==  Installed      : libqtermwidget57-0-dev
> ==  Installed      : python-catkin-tools
> ==  Installed      : libyaml-cpp-dev
> ==
> == Entering /home/dell/catkin_ws/src/qt-creator-4.2 source path
> ==  Updating Qt Creator from github.com
> ==  Fetching into qt-creator-4.2
> ==  0 hr, 0 min, 4 sec elapsed
> ==  Pulling into qt-creator-4.2
> ==  0 hr, 0 min, 7 sec elapsed
> ==  Entering /home/dell/catkin_ws/src/qt-creator-4.2-build build path
> ==  Cleaning project QtCreator
> ==  0 hr, 0 min, 11 sec elapsed
> ==  Building project QtCreator
> ==  0 hr, 41 min, 39 sec elapsed
> ==
> == Entering /home/dell/catkin_ws/src/ros_qtc_plugin
> ==  Updating modules
> ==  Creating /home/dell/catkin_ws/src/ros_qtc_plugin-4.2-build build path
> ==  Building project ros_qtc_plugin
> ==  0 hr, 41 min, 47 sec elapsed
> ==  ERROR Operation canceled. Check setup.log
> dell@dell-Inspiron-3543:~/catkin_ws/src/ros_qtc_plugin$ 
> 

When see in setup.log found message more than 7900 lines
็pls. help me to fix it.

ps.
QT Creator 4.3.1 base on QT 5.7.1
ROS Kinetic & Ubuntu 16.04 LTS

**Comment by Levi-Armstrong** [comment]
Try `setup.sh -d -qtr master -qtc 4.3`

**Comment by surachairobotic** [comment]
OK . . . Happy ROSing
Thank you very much.
