### ISSUE TITLE
Does ros_qtc_plugin support Qt creator 4..4?

### ISSUE THREAD

**Issue by vincent-hui** [ros-industrial/ros_qtc_plugin#153]
Can I use ros_qtc_plugin in Qt creator 4..4? I do not see Qt creator 4.4 branch.

**Comment by Levi-Armstrong** [comment]
I have PR to upgrade to 4.4 so should be released in about a week.

**Comment by oxoocoffee** [comment]
Approved. Also tested just released Qt Creator 4.4.1 and it works too.

**Comment by Levi-Armstrong** [comment]
Ok I will do a release for 4.4.1 with Qt 5.7. I am still working on releasing Qt 5.9.1 on arm and arch.

**Comment by Levi-Armstrong** [comment]
Everything has been released for 4.4.1 enjoy.
