### ISSUE TITLE
the type of "data" of "generators" in some wizard.json files is wrong and ../../global/genericfilewizard.png is missing

### ISSUE THREAD

**Issue by vincent-hui** [ros-industrial/ros_qtc_plugin#159]
The type of "data" of "generators" in some wizard.json files is wrong. It should be an array not an object. For example, ros_basic_node/wizard.json is wrong. Another issue is that ../../global/genericfilewizard.png is missing, "global" does not contains genericfilewizard.png.

    "generators" :
    [
        {
            "typeId": "File",
            "data":
            {
                "source": "file.cpp",
                "target": "%{FileName}",
                "openInEditor": true
            }
        }
]

**Comment by Levi-Armstrong** [comment]
Sorry, I don't follow.

**Comment by Levi-Armstrong** [comment]
The does not appear to be in qt creator any longer. Though they added another parameter iconText so I will work on updating them to this instead of using the png.

**Comment by Levi-Armstrong** [comment]
This PR #160 should resolve the issue.
