### ISSUE TITLE
Feasibility of binary distribution of the plugin?

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_qtc_plugin#17]
It'd be great if the exact (minimal) version numbers for dependencies such as Qt and Qt Creator could be listed somewhere, probably the repository readme.

From `setup.sh` I gather that it clones the `4.0` branch of Qt Creator, so if that means that the dependencies are basically those listed in the [qt-creator/readme.md](https://github.com/qtproject/qt-creator/blob/342e87edb84bd92bee42b40459512606433d949d/README.md), something along the lines of "refer to the Qt Creator readme for further dependencies" could be enough.

**Comment by Levi-Armstrong** [comment]
I can add the minimum version for Qt, but since Qt Creator currently must be built from source it may confuse people.

**Comment by gavanderhoorn** [comment]
Well, it would already help if you just say something like "all build dependencies are satisfied by following the Qt Creator instructions".

> but since Qt Creator currently must be built from source

Is that just because a binary distribution of Qt Creator 4 is missing, or is there some other reason?

**Comment by Levi-Armstrong** [comment]
>Well, it would already help if you just say something like "all build dependencies are satisfied by following the Qt Creator instructions".

That works.

> Is that just because a binary distribution of Qt Creator 4 is missing, or is there some other reason?

For 14.04 both Qt 5.4 and Qt Creator 4 are missing, but a binary should be possible in the newer versions of Ubuntu.

**Comment by gavanderhoorn** [comment]
> > Is that just because a binary distribution of Qt Creator 4 is missing, or is there some other reason?

> For 14.04 both Qt 5.4 and Qt Creator 4 are missing, but a binary should be possible in the newer versions of Ubuntu.

Would [ppa:beineri/opt-qt57-trusty](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt57-trusty) work?

**Comment by gavanderhoorn** [comment]
I'm looking at `setup.sh` to see what would be involved trying to get `ros_qtc_plugin` to build against the Qt 5.7 installed from that PPA. @Levi-Armstrong are you already doing that? If so, I'll wait :).

**Comment by Levi-Armstrong** [comment]
I am not, but if there was one it should allow me to make a binary for the plugin to work on 14.04

**Comment by gavanderhoorn** [comment]
I got it to work, using the Qt and Qt Creator from `ppa:beineri/opt-qt57-trusty`. Source build of neither is needed. Plugin build time is about 5 minutes. The process is quite similar to how you do Linux kernel out-of-tree builds.

I'll post instructions later.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: could you perhaps test [ros-qtc-plugin-qt57_0.1.0_amd64.deb.zip](https://github.com/ros-industrial/ros_qtc_plugin/files/342066/ros-qtc-plugin-qt57_0.1.0_amd64.deb.zip) for me?

In a terminal:

```shell
wget -O /tmp/ros-qtc-plugin-qt57_0.1.0_amd64.deb https://github.com/ros-industrial/ros_qtc_plugin/files/342066/ros-qtc-plugin-qt57_0.1.0_amd64.deb.zip
sudo add-apt-repository ppa:beineri/opt-qt57-trusty
sudo apt-get update
sudo apt-get install qt57creator qt57-meta-minimal
sudo dpkg -i /tmp/ros-qtc-plugin-qt57_0.1.0_amd64.deb
/opt/qt57/bin/qtcreator-wrapper
```

That should give you a Qt Creator 4.0.2 instance with your ROS plugin.

I'm not sure whether you have to undo some of the changes to your environment that `setup.sh` makes.

**Comment by gavanderhoorn** [comment]
If you download manually, don't forget to rename to `.deb` again (`.zip` was necessary to be able to attach it to this issue).

**Comment by gavanderhoorn** [comment]
Improved package: [qt57creator-ros-plugin_0.1.0-git-aa485eac_amd64.deb.zip](https://github.com/ros-industrial/ros_qtc_plugin/files/343120/qt57creator-ros-plugin_0.1.0-git-aa485eac_amd64.deb.zip). Installation procedure is identical (apart from the filename of course).

**Comment by Levi-Armstrong** [comment]
Thanks, I will take a look at this over the weekend and try out the docker.

**Comment by gavanderhoorn** [comment]
Well, the `Dockerfile` isn't there yet, it was just an idea. If you already have `qt57creator` and its dependencies on your system it wouldn't make much difference (it'd probably be slower).

If you could test the `.deb` and tell me whether it works for you with the Qt Creator from `ppa:beineri/opt-qt57-trusty` (and I expect it will), that'd be great.

**Comment by Levi-Armstrong** [comment]
I was going to use one of the docker images Dave Coleman setup [here](https://groups.google.com/forum/m/#!msg/moveit-users/6mSZ0ulDRAk/CrLsxFDxBAAJ)

**Comment by gavanderhoorn** [comment]
Well, that probably works, but for just compiling the plugin it'd probably be a bit overkill. A full Indigo image fi is about 2.5GB. A bare Ubuntu Trusty image is under 200MB.

**Comment by Levi-Armstrong** [comment]
Is this a Debian of just our plug-in or of Qt Creator with the plug-in?

**Comment by gavanderhoorn** [comment]
`qt57creator-ros-plugin_0.1.0-git-aa485eac_amd64.deb` contains just the plugin. The PPA provides QtCreator (and Qt itself).

**Comment by gavanderhoorn** [comment]
btw, I guessed the version to be `0.1.0`, but that is easily changeable.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: have you had a chance to test the deb?

**Comment by Levi-Armstrong** [comment]
I am currently installing it on a VM right now should have an update shortly.

**Comment by gavanderhoorn** [comment]
Btw I noticed that the last step in https://github.com/ros-industrial/ros_qtc_plugin/issues/17#issuecomment-229742368 (`/opt/qt57/bin/qtcreator-wrapper`) is not really necessary: `qt57creator` also installs a menu item, so the Dash should show the correct icon that starts the 4.0.2 version of Qt Creator with the plugin.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Everything worked! I did have to source /opt/qt57/qt57-env.sh to get the correct version of qtcreator to load. This is probably due to me having multiple versions.

**Comment by gavanderhoorn** [comment]
> Everything worked!

Good to hear.

> I did have to source /opt/qt57/qt57-env.sh to get the correct version of qtcreator to load. This is probably due to me having multiple versions.

Yeah, that's why I wrote earlier that I expected that you'd have to undo some of the changes your `setup.sh` script makes to the environment. But I'm surprised that would be necessary in a VM? Or is the VM not a 'clean' one?

I have multiple version of Qt Creator as well (default Trusty one (a 3.x I believe), and the Qt 5.7 one, and both the Dash icon as well as the `qtcreator-wrapper` start the correct version.

**Comment by Levi-Armstrong** [comment]
Yea the VM was not clean. Also it did not install a Dash icon on my VM. I had to open a terminal and run the commands below to get it to load the correct qtcreator.

```
source qt57-env.sh
qtcreator
```

**Comment by gavanderhoorn** [comment]
Did you try `/opt/qt57/bin/qtcreator-wrapper`?

**Comment by Levi-Armstrong** [comment]
That allowed me to open the correct version without having to source the terminal.

**Comment by gavanderhoorn** [comment]
Great. I'll make the build scripts available to you.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, friendly reminder about posting the build script.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong see [this gist](https://gist.github.com/gavanderhoorn/9694c13193bdf1f25f2893dfff5067a2).

Steps explained in `gistfile1.txt`.

It's a bit rough, but should work. The patch to `ros_qtc_plugin.pri` is necessary because you hard-code the location of the Qt Creator sources in it. Somehow I could not get the command-line override (passed as argument to `qmake`) to work.

**Comment by gavanderhoorn** [comment]
O and the docker image is only a bit of convenience: you can also run everything without docker, just make sure to install `qt57-creator` and `qt57-meta-base` from the PPA, and `fpm` first.

**Comment by gavanderhoorn** [comment]
Build of latest `HEAD`: [qt57creator-ros-plugin_0.1.0-git-1d247be1_amd64.deb.zip](https://github.com/ros-industrial/ros_qtc_plugin/files/354486/qt57creator-ros-plugin_0.1.0-git-1d247be1_amd64.deb.zip)

**Comment by gavanderhoorn** [comment]
Build of 1d247be1 for Xenial (and on top of `ppa:beineri/opt-qt57-xenial`): [qt57creator-ros-plugin_0.1.0-git-1d247be1_amd64_xenial.deb.zip](https://github.com/ros-industrial/ros_qtc_plugin/files/366418/qt57creator-ros-plugin_0.1.0-git-1d247be1_amd64_xenial.deb.zip)

**Comment by doisyg** [comment]
Tried on a fresh ubuntu 16.04 install with kinetic, i get this error when started from the CLI with /opt/qt57/bin/qtcreator-wrapper

**Comment by gavanderhoorn** [comment]
@doisyg: I'm a bit confused now: does it now work, or doesn't it?

Or can you run the Qt Creator 4 from the ppa, but when you install the plugin, things start to fail?

> Edit2: I had to uninstall/reinstall Qt to start Qt creator (without ros plugin), using `sudo dpkg -r qt57creator-ros-plugin` alone was no enough

that is strange, as removing the plugin should remove all files. If there are configuration files created afterwards, those could be left behind though.

**Comment by doisyg** [comment]
Working! 
I had the Qt + Qtcreator previous installation from the *.run (http://www.qt.io/download/)  conflicting I guess. I removed it through the Maintenance Tool, reinstalled from ppa:beineri/opt-qt57-xenial + your deb packet and now everything's working.
Thanks a lot for your help!

**Comment by gavanderhoorn** [comment]
Hm, good to know you got it working, but the clash with other Qt / Qt Creator instances should not happen. It might be that there are some assumptions in the PPA packages that don't hold when the binary distribution from `qt.io` is installed. I've also not experienced this on my machine (multiple Qt versions installed: from source, binary dist from `qt.io` and the platform default. But I run Trusty).

Does it now also work when you start it from the Dash? @Levi-Armstrong reported he didn't see an icon for the 5.7 version of the creator.

**Comment by doisyg** [comment]
yes, working from the dash!

**Comment by gavanderhoorn** [comment]
Build of latest `HEAD` (e15737ef):

 - Trusty: [qt57creator-ros-plugin_0.1.0-git-e15737ef_amd64.deb](https://github.com/ros-industrial/ros_qtc_plugin/files/416967/qt57creator-ros-plugin_0.1.0-git-e15737ef_amd64.deb.zip)
 - Xenial: [qt57creator-ros-plugin_0.1.0-git-e15737ef_amd64_xenial.deb](https://github.com/ros-industrial/ros_qtc_plugin/files/416968/qt57creator-ros-plugin_0.1.0-git-e15737ef_amd64_xenial.deb.zip)

**Comment by Levi-Armstrong** [comment]
Hello Everyone, 

I would like to announce that a binary has been released on launchpad.net, no need to use the setup script anymore. Please see the updated [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-Setup-ROS-Qt-Creator-Plug-in) for instruction how to get the latest Debian. For those that have installed the Debian previously provided on this issue you will need to remove it and install the new one.  You will also now be able to get the lastest by performing the `sudo apt-get update && sudo apt-get upgrade` after following the wiki instructions.

**Comment by Levi-Armstrong** [comment]
FYI: A Debian has been released so the plugin can be installed via apt-get see the previous comment and wiki for details.

@doisyg, @shaun-edwards, @gavanderhoorn, @rhaschke, @bharat-robotics, @RickBlacker, @	GarethZhang, @HeYijia, @raultron, @jmlago91, @henriqueribeiro, @VictorLamoine

**Comment by RickBlacker** [comment]
Hi Levi...

As I've mentioned, I'm still very new to the world of Linux.  So, I've got several questions.  

I'm still unsure what the difference is between 
A) Setup for users
B) Setup for developers.

For me, I'm just wanting to use QT.  We have some hardware/software that uses ROS.  I'd like to be able to use QT for project creating, compiling, debugging, syntax highlighting of new software/hardware applications.  BUT, I don't plan on digging into the guts of ROS itself.  

I've tried to follow along with your instructions, but I'm clearly not knowledgeable enough to fully grasp all these concepts... yet...

**Step 1.2.2**
When I look at my folder structure, there is no file called /usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf 

I don't have a directory called QT in my home directory.  In fact, I don't have a /home<username> folder at all.  So it's not entirely clear what I'm supposed to do here. So, I skipped step 1.2.2 all together.

**Step 1.2.3**
Rather than using the git command, I used the website and downloaded it as a zip. I extracted it. This left "-master" at the end of the folder name. I tried running bash setup.sh -d.  The setup didn't like the fact that -master was still on the folder and part of the script failed to find some of the files.  I guess there is a hard coded path in the script somewhere?

So, I removed all the folders that it attempted to create, renamed the folder and removed the -master.  Reran the script.  I got other errors in the script. Here is where the script started failing.... 

> In file included from ../../../qt-creator/src/libs/extensionsystem/iplugin.h:29:0,
>                  from ../../../ros_qtc_plugin/src/project_manager/ros_project_plugin.h:23,
>                  from ../../../ros_qtc_plugin/src/project_manager/ros_project_plugin.cpp:21:
> ../../../qt-creator/src/libs/extensionsystem/extensionsystem_global.h:29:28: **fatal error**: QLoggingCategory: No such file or directory
> compilation terminated.
> Makefile:4837: recipe for target '.obj/release-shared/ros_project_plugin.o' **failed**
> make[2]: *** [.obj/release-shared/ros_project_plugin.o] **Error 1**
> make[2]: *** Waiting for unfinished jobs....
> In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project_manager.cpp:21:0:
> ../../../ros_qtc_plugin/src/project_manager/ros_project_manager.h:26:41: **fatal error**: qtermwidget/lib/qtermwidget.h: No such file or directory
> compilation terminated.
> Makefile:4306: recipe for target '.obj/release-shared/ros_project_manager.o' **failed**
> make[2]: *** [.obj/release-shared/ros_project_manager.o] **Error 1**
> In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project.h:26:0,
>                  from ../../../ros_qtc_plugin/src/project_manager/ros_package_wizard.cpp:25:
> ../../../ros_qtc_plugin/src/project_manager/ros_project_manager.h:26:41: **fatal error**: qtermwidget/lib/qtermwidget.h: No such file or directory
> compilation terminated.
> Makefile:3794: recipe for target '.obj/release-shared/ros_package_wizard.o' **failed**
> make[2]: *** [.obj/release-shared/ros_package_wizard.o] Error 1
> In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project.h:26:0,
>                  from ../../../ros_qtc_plugin/src/project_manager/ros_project.cpp:21:
> ../../../ros_qtc_plugin/src/project_manager/ros_project_manager.h:26:41: **fatal error**: qtermwidget/lib/qtermwidget.h: No such file or directory
> compilation terminated.
> In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project.h:26:0,
>                  from ../../../ros_qtc_plugin/src/project_manager/ros_build_configuration.cpp:24:
> ../../../ros_qtc_plugin/src/project_manager/ros_project_manager.h:26:41: **fatal error**: qtermwidget/lib/qtermwidget.h: No such file or directory
> compilation terminated.
> Makefile:4094: recipe for target '.obj/release-shared/ros_project.o' **failed**
> make[2]: *** [.obj/release-shared/ros_project.o] Error 1
> Makefile:3293: recipe for target '.obj/release-shared/ros_build_configuration.o' **failed**
> make[2]: *** [.obj/release-shared/ros_build_configuration.o] Error 1
> In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project.h:26:0,
>                  from ../../../ros_qtc_plugin/src/project_manager/ros_project_nodes.cpp:22:
> ../../../ros_qtc_plugin/src/project_manager/ros_project_manager.h:26:41: **fatal error:** qtermwidget/lib/qtermwidget.h: No such file or directory
> compilation terminated.
> Makefile:4511: recipe for target '.obj/release-shared/ros_project_nodes.o' **failed**
> make[2]: *** [.obj/release-shared/ros_project_nodes.o] Error 1
> In file included from ../../../ros_qtc_plugin/src/project_manager/ros_project.h:26:0,
>                  from ../../../ros_qtc_plugin/src/project_manager/ros_make_step.cpp:23:
> ../../../ros_qtc_plugin/src/project_manager/ros_project_manager.h:26:41: **fatal error**: qtermwidget/lib/qtermwidget.h: No such file or directory
> compilation terminated.
> Makefile:3536: recipe for target '.obj/release-shared/ros_make_step.o' **failed**
> make[2]: *** [.obj/release-shared/ros_make_step.o] Error 1
> make[2]: Leaving directory '/home/rick/DEVELOPMENT/ros_qtc_plugin-build/src/project_manager'
> Makefile:39: recipe for target 'sub-project_manager-make_default-ordered' **failed**
> make[1]: *** [sub-project_manager-make_default-ordered] Error 2
> make[1]: Leaving directory '/home/rick/DEVELOPMENT/ros_qtc_plugin-build/src'
> Makefile:40: recipe for target 'sub-src-make_default-ordered' **failed**
> make: *** [sub-src-make_default-ordered] Error 2
> Add Qt Creator ROS command line launcher: /usr/local/bin/qtcreator
> rick@rick:~/DEVELOPMENT/ros_qtc_plugin$ 

**Step 1.3**
When I try to click on the QT-Creator icon on the desktop, I get a popup error saying "There was an error launching the application"

Also, I'm still not sure why it is that this installs a new version of QT when I already have QT5.7 installed. 

At this stage I'm pretty lost. Any help will be HUGELY appreciated.  
Thanks
Rick

**Comment by Levi-Armstrong** [comment]
Sorry @RickBlacker, You should only need to perform the 1.1 Setup for users which is for individual that only want to use the software for ROS development. The 1.2 Setup for developers is for individuals who want to enhance the ROS Qt Creator Plug-in by adding functionality to it.

I would remove anything you did for steps 1.2 and 1.3 (delete the folders) and remove the new version of QT (In the qt folder it provides a maintenance tool for removal) but don't remove QT5.7. You will also need to remove the ros-qtcreator-plugin previously installed, this can be done using `sudo apt-get remove  qt57creator-ros-plugin*` then only follow the steps in the wiki for section 1.1 Setup for users.

**Comment by RickBlacker** [comment]
From there do I move onto the other sections?
2. Setup QT Creator for ROS
3. Debugging Catkin Workspace
4. Where to find Qt Creator Plug in Support 

???

**Comment by Levi-Armstrong** [comment]
>From there do I move onto the other sections?
2. Setup QT Creator for ROS
3. Debugging Catkin Workspace
4. Where to find Qt Creator Plug in Support

Yes I would then move on to the other section. After you verify that the 

>You mention I need to remove the ros-qtcreator-plugin previously installed. Not sure why this is because in your instructions in 1.1 Setup for users, step 3 in that section you mention installing the plugin. Why do I need to uninstall it?

The one you installed previously is more or less a standalone Debian meaning you can not get update by performing the `sudo apt-get update && sudo apt-get upgrade`.  By remove this one and adding my ppa and installing the plugin from my ppa, you can always get the latest and greatest by performing the  `sudo apt-get update && sudo apt-get upgrade`.

**Comment by RickBlacker** [comment]
Ok.
I manually deleted the folders that were created.
For some reason I am not able to find the maintenance tool.  In the past I know it's been available in the "Search your computer" app.  

Ok, I ran the uninstall of the plugin.  I'm now going back and performing all the steps in 1.1.
Wish me luck.  :)

**Comment by RickBlacker** [comment]
`sudo apt-get install qtcreator-plugin-ros`
Getting an error.  
_Unable to locate package qtcreator-plugin-ros_

**Comment by Levi-Armstrong** [comment]
Where you able to install libqtermwidget5-0?

**Comment by RickBlacker** [comment]
Yeah… I didn’t get any problems on any of these

sudo add-apt-repository ppa:beineri/opt-qt57-trusty  

sudo add-apt-repository ppa:levi-armstrong/ppa  

sudo apt-get update

sudo apt-get install libqtermwidget5-0

sudo apt-get install qt57creator

 

Only thing that had any issues was installing qt57creator, but that was just a message saying it couldn't install it because it was already installed.  Which I knew that, but thought it might just install over itself and not be a problem.

**Comment by RickBlacker** [comment]
At this point in time I'd be very happy to completely clean out my system of all Qt and start fresh, only problem is, I'm not able to find any traces of an uninstall for Qt.   Sure I could just manually delete the folder but I'm not sure if that leaves traces of Qt in any other locations and or any Qt file entries anywhere.

**Comment by Levi-Armstrong** [comment]
It is interesting that you were able to install  libqtermwidget5-0 from my ppa but it did not find qtcreator-plugin-ros. I will see if it has anything to do with my ppa.

**Comment by RickBlacker** [comment]
Is it possible that I have some legacy junk laying around in the file system somehow?  Like I mentioned, I was not able to figure out how to properly uninstall anything, I just deleted some folders.

**Comment by RickBlacker** [comment]
Just for grins... I'm completely blowing away my Ubuntu install and loading up a fresh clean Ubuntu 16.04 install.  If you want to work out any kinks let me know.

**Comment by Levi-Armstrong** [comment]
@RickBlacker, it was only published for trusty, I am currently publishing it for Xenial, but it may take about an hour until you can install it. Sorry for the inconvenience, I am new to the Debian creation.

**Comment by Levi-Armstrong** [comment]
@RickBlacker I figured out why you were able to install libqtermwidget5-0. The developers of this library are now publishing there binaries so you will need to uninstall it. Once I have everything published I will provide instruction on how to finish the install.

**Comment by RickBlacker** [comment]
Ok.. Just a FYI, I've got a brand new fresh Ubuntu 16.04 install now.  I have a few work related things to get setup on it such as ROS, but will hold off on anything related to QT until you let me know it's good to go.

**Comment by Levi-Armstrong** [comment]
@RickBlacker, It is ready. I would follow the procedure on the wiki. I change the library name slightly to reflect the use of qt57 to guarantee there was no conflicts. Let me know how it goes.

**Comment by henriqueribeiro** [comment]
@Levi-Armstrong 
I just made a clean installation of ubuntu 14.04 and ROS and after following step 1.1 qtcreator was unable to find the plugin. There is no "Import ROS Workspace" option available.

**Comment by RickBlacker** [comment]
Hi Levi
I started following the "For User" instructions.

sudo add-apt-repository ppa:beineri/opt-qt57-trusty  
sudo add-apt-repository ppa:levi-armstrong/ppa  
sudo apt-get update
sudo apt-get install libqtermwidget57-0

Those all seemed to work just fine, however, when I ran 
**sudo apt-get install qt57creator** 
I get the following message 

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package qt57creator is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'qt57creator' has no installation candidate
```

**Comment by gavanderhoorn** [comment]
@RickBlacker wrote:
> I've got a brand new fresh Ubuntu 16.04 install now.

and:

@RickBlacker wrote:
> I started following the "For User" instructions.

> [..]

> sudo add-apt-repository ppa:beineri/opt-qt57-trusty

16.04 is Ubuntu Xenial, the PPA you added is for Ubuntu Trusty (== 14.04). So that won't work.

There is a version of that PPA for Xenial ([ppa:beineri/opt-qt57-xenial](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt57-xenial)), but I don't know if you should use it. It depends on whether @Levi-Armstrong uses the distribution Qt for the Xenial deb in his PPA or not.

**Comment by Levi-Armstrong** [comment]
I will update the wiki you should use ppa:beineri/opt-qt57-xenial instead.

**Comment by gavanderhoorn** [comment]
@RickBlacker wrote:
> Just as a clarification, I have not installed QT yet. Am I supposed to install QT BEFORE running this step? 

No.

> The apt-get command would lead me to think it's not necessary to install QT beforehand. 

Indeed.

In general: when using package managers on Linux, the idea is that those will determine and resolve all dependencies for you. If installation sources are downloaded from an online repository (as is the default), then everything should be taken care of for you, provided you have the correct repositories configured.

If you downloaded a `.deb` manually (through your browser fi) and use `dpkg` or `gdebi`, there might be some additional manual steps required.

**Comment by Levi-Armstrong** [comment]
@RickBlacker, I update the wiki to show the correct ppa for both Ubuntu 14.04 and 16.04.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: I suggest we close this issue. Your PPA works, and future problems with your packages or setup instructions should be reported in new issues.

**Comment by Levi-Armstrong** [comment]
Agree, I will close it now and open a new issue

**Comment by Levi-Armstrong** [comment]
@RickBlacker; A new issue #41 has been created for future questions related to installation using the PPA.
