### ISSUE TITLE
Failed opening project...No plugin can open project type

### ISSUE THREAD

**Issue by nathangeorge1** [ros-industrial/ros_qtc_plugin#175]
When trying to open `~/catkin_ws/catkin_ws.workspace` I get the following error:

![image](https://user-images.githubusercontent.com/2744891/31722925-6c90bff6-b3eb-11e7-8217-f646a455d843.png)

Does this have something to do with an update; for example, I can't import a ROS workspace anymore, as per the tutorial:
![image](https://user-images.githubusercontent.com/2744891/31723006-a5dbe218-b3eb-11e7-970d-01f24d18cdf8.png)

Thanks,
Nathan

**Comment by x3Randomise** [comment]
Similar problem i got after update to Qt59creator, see the following:

conghui@conghui-Pc:~$ sudo apt-get install qt59creator
The following packages have unmet dependencies:
 **qt59creator : Depends: libclang1-4.0 (>= 3.6) but it is not installable**
               Recommends: qt59creator-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by luator** [comment]
I have the same problem after doing an update yesterday.

**Comment by luator** [comment]
I noticed that in the installation instructions it now says
```
sudo apt update && sudo apt install qt59creator
sudo apt install qt57creator-plugin-ros
```
On my system I had `qt57creator` installed instead of `qt59creator`. However installing `qt59creator` did not help. It also seems weird to me that different versions are used (`qt59creator` vs `qt57creator-plugin-ros`), is this intended? There is no `qt59creator-plugin-ros`, though.

**Comment by Levi-Armstrong** [comment]
With the latest release a lot has changed to work with Qt Creator 4.4. The Import ROS workspace has moved under "Other Projects". Also to not break things during the update I left the debian name the same "qt57creator-plugin-ros" though it has been upgraded to Qt 5.9. When going to the next LTS I will remove the any reference to the version of qt in the name of the debian.

**Comment by Levi-Armstrong** [comment]
Oh, Also when I did an upgrade it would not upgrade directly. Because the dependencies changed from Qt 5.7 to Qt 5.9 you must perform `sudo apt install qt57creator-plugin-ros`. During a `sudo apt upgrade` you should see something about it being held back due to dependency changing saying to perform a install to correct. I apologize there was no way around this.

**Comment by luator** [comment]
@Levi-Armstrong Thanks for the information. I did the reinstall and now it is working again.

**Comment by nathangeorge1** [comment]
thanks @Levi-Armstrong that worked for me too. I believe the 2 installation videos are outdated. I can create updated installation instructions if you'd like.

**Comment by Levi-Armstrong** [comment]
@nathangeorge1  That would be great! I have moved away from using the GitHub wiki to using Sphinx documentation so the pages have been moved to the directory gh_pages. After making changes you can test it by running the command `make html` from within the gh_pages directory. Then open this file `gh_pages/_build/html/index.html`.  After you are happy with the changes you can create a PR.

**Comment by nathangeorge1** [comment]
sounds good; it might take some time to learn front end stuff; but I'll get to it soon

**Comment by nathangeorge1** [comment]
Sorry it took so long but I just started working on creating an intro install/usage video today; hopefully should finish by end of week

**Comment by Levi-Armstrong** [comment]
Just a heads up, I changes the method for installing to use a Qt Installer which is reflect in the documentation I just merged.

**Comment by nathangeorge1** [comment]
yes I saw the latest install method and will have the video using this

![image](https://user-images.githubusercontent.com/2744891/37615456-c3b4bebc-2b83-11e8-959e-8347adca12b0.png)

Currently the video will have the following components:
•	Explain ROS needs to be installed
•	Installing the plugin
•	Create catkin_ws
•	Importing ROS workspace
•	Run and Build Settings
•	Hello World example
•	Indexing
•	Explain further information is in wiki

Is there anything that I should add/modify?

**Comment by Levi-Armstrong** [comment]
There is only a few other items you might mention.

- ROS Terminal
- Changing the code style at the project level
