### ISSUE TITLE
trusty upgrades?

### ISSUE THREAD

**Issue by liamstask** [ros-industrial/ros_qtc_plugin#176]
Hi Levi - do you plan to release any of the qtc 4.4/qt 5.9 updates to the `debian/trusty` branch (and ppa's)? I'm still on that distribution, it would be great to get access to those updates if possible 👍 Thanks!

**Comment by Levi-Armstrong** [comment]
Well have ran into an issue releasing on trusty. I can do a release if I exclude the clang code model because there appears to be a binary incompatibility because Qt Creator requires g++ 4.9 which is not the current version on trusty. When compiling I receive the error below and I have tried multiple attempts to resolve the issue, but I believe to resolve the issue I would need to build llvm/clang from source and release my own version. I am open to suggestion or help in resolving.


@gavanderhoorn Have you every ran into this type of error?
```
/usr/bin/ld: /usr/lib/llvm-3.9/lib/libclangTooling.a(CompilationDatabase.cpp.o): unrecognized relocation (0x2a) in section `.text._ZN5clang7tooling19CompilationDatabaseD2Ev'
/usr/bin/ld: final link failed: Bad value
```

**Comment by Levi-Armstrong** [comment]
Good news after a week of research I was able to stumble onto a solution. I have all of the Qt 5.9 Libraries  and Qt Creator 4.4.1 published on trusty last night. I will work on a releasing the plug-in tonight.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong wrote:
> @gavanderhoorn Have you every ran into this type of error?

sorry my late reply, but I don't think I would've been able to help you anyway.

> I have all of the Qt 5.9 Libraries and Qt Creator 4.4.1 published on trusty [..]

Are you now distribution qt 5.9 on trusty? How does that work with the 'default' Qt versions on that OS?

And I haven't been following too closely, but what about [ppa:beineri/opt-qt591-trusty](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt591-trusty)?

**Comment by Levi-Armstrong** [comment]
> Are you now distribution qt 5.9 on trusty? How does that work with the 'default' Qt versions on that OS?

This does not have much of an affect Qt provides a way to easily switch between different versions.

>And I haven't been following too closely, but what about ppa:beineri/opt-qt591-trusty?

Yea, I start with his version and then I modify them to accommodate building on arm processor. I also maintain my own copy to prevent things from breaking because occasionally he upgrades and things break along with a few other things.

**Comment by liamstask** [comment]
Great news! Looking forward to testing it. Thanks for your work on this 👍

**Comment by Levi-Armstrong** [comment]
@liamstask  It is released let me know if you have any issues. Note: since there is a dependence change you will most likely to reinstall.

**Comment by liamstask** [comment]
Ah, unfortunately we have a dependency pinned that prevents me from upgrading libstdc++ to the version required by `qt59creator` :/

However, because `qt57creator-plugin-ros` now appears to depend on `qt59creator` (this is unintuitive) it's not simple to reinstall the version that was previously working.

Seems like it might be clearer to create a `qt59creator-plugin-ros` that depends on `qt59creator` instead?

**Comment by liamstask** [comment]
@Levi-Armstrong can you recommend a way to reinstall the version that was working previously? Looking at https://launchpad.net/~levi-armstrong/+archive/ubuntu/ppa/+packages I see references to a `0.1.5-0trusty8` version but it appears to no longer be published?

Right now, I am not able to use the plugin due to these dependency issues :(

**Comment by Levi-Armstrong** [comment]
What is your dependency issue?

**Comment by Levi-Armstrong** [comment]
This is most likely your issues, see issue #187.

**Comment by liamstask** [comment]
Hi @Levi-Armstrong yes, that is related - the problem is that due to some other unrelated projects, I can't upgrade my gcc toolchain to 4.9 and must stay on 4.8 for now.

One solution that occurred to me was that, if the previous version of the `qt57creator-plugin-ros` package (i.e. before the change was made to depend on `qt59creator`) was still available, I could explicitly install that version of the plugin and continue using it on QtCreator 4.2.

However, because I uninstalled the plugin in order to upgrade to the current release, I no longer have it installed and have no way to reinstall the previous version, since it appears to no longer be published, as I mentioned above.

**Comment by Levi-Armstrong** [comment]
You should be able to have multiple version of gcc toolchain installed and then set the active one to gcc 4.8. See if the link below help with setting up multiple versions.

https://askubuntu.com/questions/26498/choose-gcc-and-g-version

**Comment by liamstask** [comment]
Thanks @Levi-Armstrong. I took a look but was unsuccessful.

Our project unfortunately has a pretty specific set of packages pinned, and I'm not able to install the required version of gcc-4.9.

I was mostly just hoping there was a way to revert to the previous version of the plugin that I was using, as that worked well :D

**Comment by Levi-Armstrong** [comment]
I would recommend cloning this repository and use the setup script to build everything local for the version you need. It works well and you can specify the Qt Creator Branch and the ROS plugin branch and it will build and create a desktop icon with the version label.
