### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by BrunoXL** [ros-industrial/ros_qtc_plugin#177]
On installing from [user's tutorial ](http://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html)it gives error of **not found repository** :

` Err:21 http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial Release    
  404  Not Found
Reading package lists... Done                                                                 
E: The repository 'http://ppa.launchpad.net/bzindovic/suitesparse-bugfix-1319687/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default`

**Comment by Levi-Armstrong** [comment]
This ppa `http://ppa.launchpad.net/bzindovic` is not related to the Qt Creator ROS Plugin.  I checked out the ppa and it contains several libraries for spars matrix math; did you add this for some other reason? If you are not using this ppa I would recommend removing it and then perform an `apt` update/upgrade.
