### ISSUE TITLE
Unmet dependency

### ISSUE THREAD

**Issue by BrunoXL** [ros-industrial/ros_qtc_plugin#186]
On installing version `0.1.8` I came across the following issue:

` You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libqtermwidget59-0 : Depends: qtermwidget59-data (= 0.6.1-0xenial1) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution). `
 
Running  `apt-get -f install ` results on the following : 

`dpkg: error processing archive /var/cache/apt/archives/qtermwidget59-data_0.6.1-0xenial1_all.deb (--unpack):
 trying to overwrite '/usr/share/qtermwidget5/color-schemes/Linux.colorscheme', which is also in package qtermwidget57-data 0.6.0-0xenial1
Errors were encountered while processing:
 /var/cache/apt/archives/qtermwidget59-data_0.6.1-0xenial1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

**Comment by Levi-Armstrong** [comment]
It looks like I need to add a conflict to the qtermwidget59-data debian to fix this. In the interim just `sudo apt remove --purge qtermwidget57-data`, then reinstall.

**Comment by BrunoXL** [comment]
I'm unable to remove `qtermwidget57-data`

`    You might want to run 'apt-get -f install' to correct these:
     The following packages have unmet dependencies:
 libqtermwidget59-0 : Depends: qtermwidget59-data (= 0.6.1-0xenial1) but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).`

**Comment by BrunoXL** [comment]
I've done this through `aptitude` .
