### ISSUE TITLE
Can't install qt59creator on Ubuntu 14.04.

### ISSUE THREAD

**Issue by bpinaya** [ros-industrial/ros_qtc_plugin#187]
Hi there I followed the instructions provided [here](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html), but can't seem to get qt59creator on Ubuntu.
This is my output, while it seems to be an issue from qt, I tried installing it from the .run file and then tried to install qt57creator-plugin-ros but can't still.
The following information may help to resolve the situation:

```
The following packages have unmet dependencies:
 qt59creator : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
               Depends: qt59qbs but it is not going to be installed
               Recommends: qt59creator-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```
My `lsb-release -a` output is:

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**Comment by Levi-Armstrong** [comment]
I appoligize, I did not think this would be required for users. You will need to add this dependency to get g++-4.9.

https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

**Comment by bpinaya** [comment]
Thank you, that indeed solves my issue.

**Comment by 130s** [comment]
>  You will need to add this ppa to get g++-4.9 dependency.
>
> https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test

Can it be documented? In particular, I don't know how the command for this looks like. I tried the following:
```
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/+archive/ubuntu/test                                                                      
Cannot add PPA: 'ppa:ubuntu-toolchain-r/+archive/ubuntu/test'.
Please check that the PPA name or format is correct.
```

**Comment by 130s** [comment]
> I don't know how the command for this looks like. I tried the following:

Found that in the referenced link.
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
```

Opened https://github.com/ros-industrial/ros_qtc_plugin/pull/192 to document this.

**Comment by MauleshSTrivedi** [comment]
The command worked for me fine.. weird!

**Comment by MauleshSTrivedi** [comment]
@130s 

'''
Toolchain test builds; see https://wiki.ubuntu.com/ToolChain

 More info: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpuz1jbvit/secring.gpg' created
gpg: keyring `/tmp/tmpuz1jbvit/pubring.gpg' created
gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpuz1jbvit/trustdb.gpg: trustdb created
gpg: key BA9EF27F: public key "Launchpad Toolchain builds" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

'''
