### ISSUE TITLE
Create installer to be used in conjunction with Qt installer method.

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#188]
@oxoocoffee Have you looked into this at all? It was quite painful with the last upgrade to get everything in Qt built and released just to release the plug-in. I think going forwards it may be better to go with an installer like how Qt releases its newer version.

**Comment by oxoocoffee** [comment]
I did not have time yet.

**Comment by Levi-Armstrong** [comment]
Complete
