### ISSUE TITLE
cannot be installed on ubuntu 14.04

### ISSUE THREAD

**Issue by jontromanab** [ros-industrial/ros_qtc_plugin#189]
I am trying to install ros_qtc_plugin on ubuntu 14.04 from here:
http://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html

This line fails: "sudo apt-get install qt59creator"
with the error:
The following packages have unmet dependencies:
 qt59creator : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
               Depends: qt59qbs but it is not going to be installed
               Recommends: qt59creator-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Please help me.

**Comment by jontromanab** [comment]
Sorry My bad. It needed gcc 4.9. It can be installed in ubuntu 14.04 like this:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9

Problem solved.

**Comment by Levi-Armstrong** [comment]
Addressed by #192 and #195
