### ISSUE TITLE
No include and src folder for created package (qt59creator & qt57creator-plugin-ros)

### ISSUE THREAD

**Issue by HubertWelp** [ros-industrial/ros_qtc_plugin#190]
I have installed qt59creator and qt57creator-plugin-ros on Ubuntu 16.04 LTS. After creating a ROS workspace I wanted to add a package by selecting the "src"-folder and then "add new ...", "Package". QtCreator creates a subentry for  this package under "src". But this subentry does not contain an "include" nor a "src" folder, although these folders were created on disk. Subsequently I am not able to add a source code file to my project. The warning "This file is not part of any project" is displayed.  
I am not very experienced with Linux and its administration, but I don't know what I did wrong and would like to know whether this could be a bug or I missed something.
![qt](https://user-images.githubusercontent.com/24245037/32316781-e473ab06-bfb1-11e7-8b95-d9845ed494b1.png)

**Comment by Levi-Armstrong** [comment]
I am assuming the folder is empty is why it is not showing up. To add the file have you tried to just right clicking on any folder > Add New  then select file to add and select Chose then it will bring to another window where you can change the directory location on where to place the file and browse to the src directory. Then it should automatically show up. 

Though empty folder use to show up but Qt Creator must have changed how it handles empty folder so I will create an issue to get it fixed.

**Comment by HubertWelp** [comment]
Thank you for that workaround. The folders now appear in the project tree. But the added files are still not recognized as being part of the project. After adding a new file the warning "This file is not part of any project." still appears and there are no appropriate build-entries for this file in the CMakeLists.txt. I suppose the plugin is intended to maintain the CMake files?!

**Comment by Levi-Armstrong** [comment]
Currently it is still up to the user to add the file to the CMakeLists file. Though this is a planned feature. 

I have not seen the message you are referring to. Do you mind providing how I may recreate the message and where does it appear?

**Comment by HubertWelp** [comment]
For getting the warning proceed as follows: after creating a workspace and a package right-click on the src-folder of the package > add new ... > select i.e. Basic Node >  Choose > select Name and Path of the src-folder of the package > Next > Finish.
The complete warning says: "This file is not part of any project. The code model might have issues to parse this file properly." The warning appears above the editor window as shown in the screenshot above. Interestingly, this warning doesn't appear again if I completely remove the file and add a new file with the same filename.

**Comment by Levi-Armstrong** [comment]
Oh, I believe this warning is normal. It will go a way once the file is added to the CMakeLists file and you build the project. The code model gets built after every build and it parses particular file from the build directory to generate the code model.

**Comment by HubertWelp** [comment]
Yes, but the last sentence in my comment above holds also for files that I did not add to the CMakelistss file.

**Comment by Levi-Armstrong** [comment]
I will look into further and see what I can find out.

**Comment by Levi-Armstrong** [comment]
Ok, I have tested the process you provided and the warning showed up but removing and adding the file again did not make the warning go away for me. The only thing that caused it to go away was adding the file to the CMakeList file. I expected this because the project code model is built from a project file generated by CMake when the workspace is built and if you open a file with an extension associated to the project code model but is not part of the code model you will receive this error.

**Comment by Levi-Armstrong** [comment]
@HubertWelp How is everything working?

**Comment by HubertWelp** [comment]
I haven't done a lot of further testing. But in accordance with your testing I couldn't reproduce the behavior which I described as "this warning doesn't appear again if I completely remove the file and add a new file with the same filename".
