### ISSUE TITLE
How to import a package to the QtCreator(have install ros_qtc_plugin) which create by "catkin_create_qt_pkg" command in terminal? 

### ISSUE THREAD

**Issue by lhzlhz** [ros-industrial/ros_qtc_plugin#196]
- Hello, I create a package through the command "catkin_create_qt_pkg" in the terminal, but I don't know how to import the pacakge to the QtCreator.

- I search on the net, some way to solve the question by "New File or Project>>Import Project>>ROS WorkPlace" to import the package. But I know the latest version of ros_qtc_plugin doesn't have the menu of "New File or Project>>Import Project>>ROS WorkPlace", only have the menu "New File or Project>>Other Project>>ROS WorkPlace". I try to use the "Other Project>>ROS WorkPlace" to import the package, but it's can't work. 

- Can you tell me how to import the package create by the command "catkin_create_qt_pkg" in terminal?

- my setup:
Ubuntu:16.04.3
ROS: kinetic

**Comment by Levi-Armstrong** [comment]
You only need to import the workspace. After the workspace is imported it monitors the src directory for any new files/directories and when items are added either using the terminal or Qt Creator is see that a new object was added and adds it to the project tree,

**Comment by lhzlhz** [comment]
Thanks for your reply.
    I try to use the "New Project->>Ohter Project->>ROS Workspace" to import the workspace to the Qt Creator, and then to build it. It has some errors, like the picture down.
![image](https://user-images.githubusercontent.com/32038764/32428129-300b01a4-c2ff-11e7-8364-805d37de0bf0.png)
    I try to create the qt package in the terminal again(use the command of "catkin_create_qt_pkg qtros"), and use the command "catkin_make" to make the package, it has errors like this:
![image](https://user-images.githubusercontent.com/32038764/32428330-23eb4522-c300-11e7-894f-56e964bfa1cc.png)
    My setup:
    Ubuntu:16.04.3
    ROS:kinetic
  I use the same operation in the ubuntu 14.04.5 and ROS indigo, the gui pannel can appear.

**Comment by Levi-Armstrong** [comment]
You will need to add `sudo add-apt-repository ppa:ubuntu-toolchain-r/test` this ppa to get the 4.9. I just merged a PR that updates the documentation that adds this line and should have it published soon.

As for the build errors, does it build from the terminal after you clean it?

**Comment by lhzlhz** [comment]
Yes, in Ubuntu-16.04.3 ROS Kinetic, I create a new qt package in the terminal, then build it. It has errors in the picture 2.

**Comment by Levi-Armstrong** [comment]
OK, there error is related to BOOST_JOINT are you using boost within your GUI? If so I would start there.

**Comment by lhzlhz** [comment]
I check the package just now,  I don't find something about boost. The package is created by the command "catkin_create_qt_pkg", and I don't modify a little.

**Comment by lhzlhz** [comment]
I have test on three computers(Ubuntu-16.04.3+ROS-Kinetic), and the result are same. 
My setup:
Win10 + VMware14.0.0(Ubuntu-16.04.3 + ROS-Kinetic)
The test steps:
![image](https://user-images.githubusercontent.com/32038764/32447771-f3a59028-c347-11e7-96a1-d9c45b904947.png)
![image](https://user-images.githubusercontent.com/32038764/32447824-1ca9df38-c348-11e7-957d-c62145fdec33.png)
The same operate is ok in the Ubuntu-14.04.5 and ROS-indigo.
The result is:
![image](https://user-images.githubusercontent.com/32038764/32448617-5d55105a-c34a-11e7-9b3e-04bdbfec7280.png)
![image](https://user-images.githubusercontent.com/32038764/32448702-94798318-c34a-11e7-9870-3258853bfe04.png)

**Comment by lhzlhz** [comment]
I search the errors on the net, and find a way to solve the problem.
http://blog.csdn.net/h321654/article/details/54582341
The steps:
1. sudo gedit /usr/include/boost/type_traits/detail/has_binary_operator.hpp
2. Modify "namespace BOOST_JOIN(BOOST_TT_TRAIT_NAME,_impl) {...}" to 
"
#ifndef Q_MOC_RUN
namespace BOOST_JOIN(BOOST_TT_TRAIT_NAME,_impl) {
#endif
....
#ifndef Q_MOC_RUN
}
#endif
"
And then build the ros-qt package is ok.
Thanks for your help.

**Comment by Levi-Armstrong** [comment]
Glad to here you found the issue.
