### ISSUE TITLE
Can't use qt3D libraries inside qt Ros

### ISSUE THREAD

**Issue by praveenputhettu** [ros-industrial/ros_qtc_plugin#197]
I am trying to visualize the data using qml3D. But unable to link the required libraries.
I don't know whether this is possible..

**Comment by Levi-Armstrong** [comment]
Is this a standalone application or are you writing a plugin for an existing ros utility like Rviz?

**Comment by praveenputhettu** [comment]
This is a standalone application which I am building by using ros packages in qt. Currently I am able to visualize data in 2D.
I installed the ros_qtc_plugin from here :  http://ros-industrial.github.io/ros_qtc_plugin/_source/-Install-Users.html
Currently I am trying to use qt 3D capabilities for visualizing data's generated by the ros packages. When i include the files 'import Qt3D.core 2.0 ' in the qml file i encountered errors. So is it possible to use the qt 3D libraries from this plugin.

**Comment by Levi-Armstrong** [comment]
What version of Ubuntu are you on?

**Comment by praveenputhettu** [comment]
Ubuntu 16.04

**Comment by Levi-Armstrong** [comment]
I have a few ideas,  first lets launch Qt Creator using this command `/opt/qt59/bin/qtcreator-wrapper` this will setup the necessary Qt environment variables. Then try cleaning the project and rebuilding the project.

**Comment by praveenputhettu** [comment]
I tried above procedure, but still has the errors.

The error details is as follows:
'by not providing "FindQt53DRender" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Qt53DRender", but CMake did not find one. Could not find a package configuration file provided by "Qt53DRender" with any of the following names: Qt53DRenderConfig.cmake, qt53drender-config.cmake. Add the installation prefix of "Qt53DRender" to CMAKE_PREFIX_PATH or set "Qt53DRender_DIR" to a directory containing one of the above files. If "Qt53DRender" provides a separate development package or SDK,  be sure it has been installed.
I don't know how to do this.

**Comment by praveenputhettu** [comment]
A screenshot of the error is

![cmake_error](https://user-images.githubusercontent.com/33420537/32560006-82dd7dd2-c4ce-11e7-9197-752b508158e5.png)

**Comment by Levi-Armstrong** [comment]
Can you look at your environment variable in the project tab on the left in Qt Creator. I would make sure that the /opt/qt59 related paths were added to the appropriate variables. To get the appropriate environment variables I recommend opening up this file `/opt/qt59/bin/qtcreator-wrapper` to see what it should of setup. I assume this issue is related to getting the environment setup correctly.

**Comment by oxoocoffee** [comment]
Levi
I am in process updating setup script to add desktop icon with option reading shell variables. As we all know Qt creator build with setup and Qt official installer does not read your .bashrc. I will have PR shortly.
I would be interested if building your project from Terminal builds fine? That would be indication of such issue.
