### ISSUE TITLE
Software Updater failed (ROS plugin for Qt Creator IDE, Terminal emulator widget for Qt 5.9)

### ISSUE THREAD

**Issue by MaxWattage** [ros-industrial/ros_qtc_plugin#200]
Hi,
I'm running Ubuntu 16.04.3 LTS (xenial) and today my software update process failed.
Details of updates:
    ROS plugin for Qt Creator IDE
            Changes for qt57creator-plugin-ros versions:
            Installed version: 0.1.6-0xenial1
            Available version: 0.1.8-0xenial3
    Terminal emulator widget for Qt 5.9 (data files)
           Changes for qtermwidget59-data versions:
           Installed version: None
           Available version: 0.6.1-0xenial1

The updates sources include:
http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu
http://ppa.launchpad.net/levi-armstrong/qt-libraries-xenial/ubuntu

I'm not a Linux expert, so I'm not sure what to do about this.

**Comment by Levi-Armstrong** [comment]
I forgot to add a conflict in the debian with the older version of qt57termwidget. Uninstall qt57termwidget and the try installing the plugin again.

**Comment by MaxWattage** [comment]
You will see from my posting that  "Installed version: None",
i.e. I don't currently have any version of qt57termwidget installed for me to uninstall.

I checked in "Synaptic Package Manager", and it can find no reference to a qt57termwidget package.

**Comment by Levi-Armstrong** [comment]
Sorry qt57termwidget-data need to be uninstalled.

**Comment by Levi-Armstrong** [comment]
If that does not work perform a force install.

**Comment by MaxWattage** [comment]
Can you give specific instructions on how to do this?

I tried:
- sudo apt-get update
- sudo apt-get install qt57termwidget-data
Which resulted in...
- Reading package lists... Done
- Building dependency tree       
- Reading state information... Done
- E: Unable to locate package qt57termwidget-data

NB: I did a search, and there is no package called "qt57termwidget-data" (or anything similarly named) showing in "Synaptic Package Manager".

Can you also please confirm the correct repository names for use with my Ubuntu 16.04.3 LTS (xenial) system?
Thank you

**Comment by Levi-Armstrong** [comment]
try `sudo apt install -f`

**Comment by MaxWattage** [comment]
sudo apt-get install -f qt57termwidget-data
- Unable to locate package qt57termwidget-data

If the package can't be found, then "force" isn't going to help.

**Comment by Levi-Armstrong** [comment]
try it without the library name `sudo apt-get install -f` if that does not work try `sudo apt-get install -f qt57creator-plugin-ros`

**Comment by MaxWattage** [comment]
Well, that borked things.
Software update now says everything is up to date, however...
Qt 5.7.1 Creator now just gives "There was an error launching the application" when you try and open it.

Attempting to re-install Qt 5.7.1 Creator gives the following:
sudo apt-get update && sudo apt-get install qt57creator
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 qt57creator : Depends: qt57qbs but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by MaxWattage** [comment]
PS:
dpkg --get-selections | grep hold
returns nothing, so I assume this means there are no held packages.

**Comment by Levi-Armstrong** [comment]
OK, try this below.

```
sudo apt-get remove --purge '^qt57.*'
sudo apt-get update && sudo apt install qt59creator
sudo apt-get install qt57creator-plugin-ros
```

**Comment by MaxWattage** [comment]
Worked a treat!
Thanks

**Comment by Levi-Armstrong** [comment]
Great

**Comment by Levi-Armstrong** [comment]
I just fixed the Debian adding a conflict qtermwidget57-data.
