### ISSUE TITLE
include file

### ISSUE THREAD

**Issue by weijiav** [ros-industrial/ros_qtc_plugin#201]
After the installation of apt, you can compile the file package normally, but open the cpp file, all the include files have red line below, can not find the relevant header files. How to solve this problem?

**Comment by weijiav** [comment]
ubuntu 16.04.3

**Comment by Levi-Armstrong** [comment]
Assuming you followed the wiki and opened the workspace as a ros project there is usually two reasons why the headers are not being found. The first is the project has not been built within the Qt Creator. The second is the library or package is not added to the CMakeLists.txt or the package.xml.

**Comment by Levi-Armstrong** [comment]
@weijiav Are you still having issues?

**Comment by weijiav** [comment]
Thank you very much. I reinstall the system, and the problem is solved.

**Comment by Levi-Armstrong** [comment]
Great!
