### ISSUE TITLE
Create ROS QTC installer

### ISSUE THREAD

**Issue by oxoocoffee** [ros-industrial/ros_qtc_plugin#204]
I am in process adding qt installer option. I will post more final information and PG when ready.

**Comment by Levi-Armstrong** [comment]
I think I found Qt's packaging tool. We may follow the structure but there looks way more involved than what this would need.
http://code.qt.io/cgit/qtsdk/qtsdk.git/tree/packaging-tools

**Comment by Levi-Armstrong** [comment]
I have created a [Qt Installer](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/installers/latest/qtcreator-ros-latest-online-installer.run) which I will be updating the wiki soon to show the new install procedure.
