### ISSUE TITLE
current appropriate version for qt creator ROS plugin

### ISSUE THREAD

**Issue by drorerezprivate** [ros-industrial/ros_qtc_plugin#205]
I installed the qt creator and the ROS plugin as explained in - 
https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html
That installed qt creator 4.4.1 based on qt 5.9.1.

Now, it seems that the user interface is not exactly the same as in the video tutorial.
The main difference is that the ROS workspace can be created from "other project", rather than from "import project" as it shows in the video.
So I continued from there, but when creating the new project there is no "generate files" button, and finally there is no "src" folder neither its appropriate CMakeLists file.
There are also some other differences from the video.

I suspect that I installed something wrong.
Any idea?

Thanks

**Comment by Levi-Armstrong** [comment]
Sorry, the videos are a little outdated from the current version but should more or less follow the same sequence of steps. Once you went through the import/create process the src folder does not show in the tree because it is empty but right click on the main folder at the top and add new but then update the path to the src folder. This has been logged as a bug because something in qt creator changed in the latest version where empty folders do not show. I am working on a fix to have them show up.

**Comment by drorerezprivate** [comment]
Thanks.
I create a package and I see the new folder and the CMakeLists  being
created in the files browser, but can not see nothing in the qt.
I didn't understand how to update the path to the src folder.

Additionally, and more important - there is no CMakeLists neither a src
folder in the root.

Any suggestions?
Thanks

**Comment by drorerezprivate** [comment]
OK, got a semi solution.
I created manually an src folder under the project folder.
Then moved manually the new package into it and then performed a Build.
It seems now that the environment was created right but still nothing
appears at the qt.
So I closed the project and reopened, and it is there.
From now on, it seems ok, packages are created, shown and catkin make works.
Only the first CMakeLists at the root is still missing, I hope it doesn't
affect anything?

Please refer to this solution, whether it seems with no future problems.
Thanks.

**Comment by Levi-Armstrong** [comment]
The root CMakeLists file will be missing if you are building with catkin tools instead of catkin_make. Are you building with catkin tools?

**Comment by drorerezprivate** [comment]
No.
It is catkin make which i am using.
I tried adding a cpp file within a package within the project, and the
catkin make do not recognize it...


בתאריך 27 בנוב׳ 2017 7:02 אחה״צ,‏ "Levi Armstrong" <notifications@github.com>
כתב:

**Comment by Levi-Armstrong** [comment]
I just ran into this myself. Make sure you add a src folder to the workspace before proceeding. I will need to add a check for this.

**Comment by drorerezprivate** [comment]
Got it, and it really seems ok.
BUT - the cpp files which I write, are not recognized by the compiler.
I think that the relevant CMakeLists files are not updated for some reason.
Attached is a screen shot which explains everything.
Please refer to -
*1. The warning above: This file is not part of any project..... I added
the file using the plugin menus but that message is always there. It is the
same for all cpp files.*
2. The Build output, where there is no evidence for the cpp files
compilation

In addition, attached below is the CMakeLists file, where all the comments
remain as comments....

Please advise.
Thanks,
Dror

cmake_minimum_required(VERSION 2.8.3)
project(tom21)

## Compile as C++11, supported in ROS Kinetic and newer
# add_compile_options(-std=c++11)

## Find catkin macros and libraries
## if COMPONENTS list like find_package(catkin REQUIRED COMPONENTS xyz)
## is used, also find other catkin packages
find_package(catkin REQUIRED COMPONENTS
  roscpp
)

## System dependencies are found with CMake's conventions
# find_package(Boost REQUIRED COMPONENTS system)


## Uncomment this if the package has a setup.py. This macro ensures
## modules and global scripts declared therein get installed
## See http://ros.org/doc/api/catkin/html/user_guide/setup_dot_py.html
# catkin_python_setup()

################################################
## Declare ROS messages, services and actions ##
################################################

## To declare and build messages, services or actions from within this
## package, follow these steps:
## * Let MSG_DEP_SET be the set of packages whose message types you use in
##   your messages/services/actions (e.g. std_msgs, actionlib_msgs, ...).
## * In the file package.xml:
##   * add a build_depend tag for "message_generation"
##   * add a build_depend and a run_depend tag for each package in
MSG_DEP_SET
##   * If MSG_DEP_SET isn't empty the following dependency has been pulled
in
##     but can be declared for certainty nonetheless:
##     * add a run_depend tag for "message_runtime"
## * In this file (CMakeLists.txt):
##   * add "message_generation" and every package in MSG_DEP_SET to
##     find_package(catkin REQUIRED COMPONENTS ...)
##   * add "message_runtime" and every package in MSG_DEP_SET to
##     catkin_package(CATKIN_DEPENDS ...)
##   * uncomment the add_*_files sections below as needed
##     and list every .msg/.srv/.action file to be processed
##   * uncomment the generate_messages entry below
##   * add every package in MSG_DEP_SET to generate_messages(DEPENDENCIES
...)

## Generate messages in the 'msg' folder
# add_message_files(
#   FILES
#   Message1.msg
#   Message2.msg
# )

## Generate services in the 'srv' folder
# add_service_files(
#   FILES
#   Service1.srv
#   Service2.srv
# )

## Generate actions in the 'action' folder
# add_action_files(
#   FILES
#   Action1.action
#   Action2.action
# )

## Generate added messages and services with any dependencies listed here
# generate_messages(
#   DEPENDENCIES
#   std_msgs  # Or other packages containing msgs
# )

################################################
## Declare ROS dynamic reconfigure parameters ##
################################################

## To declare and build dynamic reconfigure parameters within this
## package, follow these steps:
## * In the file package.xml:
##   * add a build_depend and a run_depend tag for "dynamic_reconfigure"
## * In this file (CMakeLists.txt):
##   * add "dynamic_reconfigure" to
##     find_package(catkin REQUIRED COMPONENTS ...)
##   * uncomment the "generate_dynamic_reconfigure_options" section below
##     and list every .cfg file to be processed

## Generate dynamic reconfigure parameters in the 'cfg' folder
# generate_dynamic_reconfigure_options(
#   cfg/DynReconf1.cfg
#   cfg/DynReconf2.cfg
# )

###################################
## catkin specific configuration ##
###################################
## The catkin_package macro generates cmake config files for your package
## Declare things to be passed to dependent projects
## INCLUDE_DIRS: uncomment this if your package contains header files
## LIBRARIES: libraries you create in this project that dependent projects
also need
## CATKIN_DEPENDS: catkin_packages dependent projects also need
## DEPENDS: system dependencies of this project that dependent projects
also need
catkin_package(
#  INCLUDE_DIRS include
#  LIBRARIES tom21
#  CATKIN_DEPENDS roscpp
#  DEPENDS system_lib
)

###########
## Build ##
###########

## Specify additional locations of header files
## Your package locations should be listed before other locations
include_directories(
# include
  ${catkin_INCLUDE_DIRS}
)

## Declare a C++ library
# add_library(${PROJECT_NAME}
#   src/${PROJECT_NAME}/tom21.cpp
# )

## Add cmake target dependencies of the library
## as an example, code may need to be generated before libraries
## either from message generation or dynamic reconfigure
# add_dependencies(${PROJECT_NAME} ${${PROJECT_NAME}_EXPORTED_TARGETS}
${catkin_EXPORTED_TARGETS})

## Declare a C++ executable
## With catkin_make all packages are built within a single CMake context
## The recommended prefix ensures that target names across packages don't
collide
# add_executable(${PROJECT_NAME}_node src/tom21_node.cpp)

## Rename C++ executable without prefix
## The above recommended prefix causes long target names, the following
renames the
## target back to the shorter version for ease of user use
## e.g. "rosrun someones_pkg node" instead of "rosrun someones_pkg
someones_pkg_node"
# set_target_properties(${PROJECT_NAME}_node PROPERTIES OUTPUT_NAME node
PREFIX "")

## Add cmake target dependencies of the executable
## same as for the library above
# add_dependencies(${PROJECT_NAME}_node ${${PROJECT_NAME}_EXPORTED_TARGETS}
${catkin_EXPORTED_TARGETS})

## Specify libraries to link a library or executable target against
# target_link_libraries(${PROJECT_NAME}_node
#   ${catkin_LIBRARIES}
# )

#############
## Install ##
#############

# all install targets should use catkin DESTINATION variables
# See http://ros.org/doc/api/catkin/html/adv_user_guide/variables.html

## Mark executable scripts (Python etc.) for installation
## in contrast to setup.py, you can choose the destination
# install(PROGRAMS
#   scripts/my_python_script
#   DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
# )

## Mark executables and/or libraries for installation
# install(TARGETS ${PROJECT_NAME} ${PROJECT_NAME}_node
#   ARCHIVE DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
#   LIBRARY DESTINATION ${CATKIN_PACKAGE_LIB_DESTINATION}
#   RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
# )

## Mark cpp header files for installation
# install(DIRECTORY include/${PROJECT_NAME}/
#   DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION}
#   FILES_MATCHING PATTERN "*.h"
#   PATTERN ".svn" EXCLUDE
# )

## Mark other files for installation (e.g. launch and bag files, etc.)
# install(FILES
#   # myfile1
#   # myfile2
#   DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
# )

#############
## Testing ##
#############

## Add gtest based cpp test target and link libraries
# catkin_add_gtest(${PROJECT_NAME}-test test/test_tom21.cpp)
# if(TARGET ${PROJECT_NAME}-test)
#   target_link_libraries(${PROJECT_NAME}-test ${PROJECT_NAME})
# endif()

## Add folders to be run by python nosetests
# catkin_add_nosetests(test)

**Comment by Levi-Armstrong** [comment]
The code model is not updated until you build the project. Once you add the files to the cmakelists and build it should be recognized and the warning will go away.

**Comment by drorerezprivate** [comment]
But i sent the build log....
It doesnt work

בתאריך 28 בנוב׳ 2017 7:42 לפנה״צ,‏ "Levi Armstrong" <
notifications@github.com> כתב:

The code model is not updated until you build the project. Once you add the
files to the cmakelists and build it should be recognized and the warning
will go away.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ros-industrial/ros_qtc_plugin/issues/205#issuecomment-347419909>,
or mute the thread

**Comment by drorerezprivate** [comment]
I read again your answer.
Do i need to manualy add the new files to the relevant CMakelists file?
Doesnt the plugin do it for me?

בתאריך 28 בנוב׳ 2017 8:24 לפנה״צ,‏ "Dror Erez" <dror.erez.private@gmail.com>
כתב:

**Comment by Levi-Armstrong** [comment]
Yes you will need to manually add them to the CMakeLists file. Currently it does not handle this, but in the future it may for some file types.

**Comment by drorerezprivate** [comment]
Ok.
Thanks a lot

בתאריך 28 בנוב׳ 2017 3:42 אחה״צ,‏ "Levi Armstrong" <notifications@github.com>
כתב:

**Comment by Levi-Armstrong** [comment]
Resolved

**Comment by drorerezprivate** [comment]
Thanks 😊

בתאריך 14 בדצמ׳ 2017 5:43 אחה״צ,‏ "Levi Armstrong" <notifications@github.com>
כתב:
