### ISSUE TITLE
Creating a new workspace without src folder fails to create the workspace.

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#206]

**Comment by xlan09** [comment]
Thanks for fixing the bug, Levi. Just want to make sure here 'fail' means only files in `src` folder are shown in the project tree on the left panel. That's what I saw after installing ros_qt_plugin in a new machine.

**Comment by Levi-Armstrong** [comment]
Are you referring to the workspace src directory? That the build, devel, etc do not show in tree?

**Comment by xlan09** [comment]
Sorry, I should specify. My project has a weird project structure(some legacy code). So basically I want the project tree panel to show all the folders and files inside the same folder with the `.wokspace`. That's basically the `src` folder of my project. I could create a `src` folder and put everything inside the `src` folder, then create a workspace in the same folder containing the new `src` folder. But I do not want to do that if there are other ways around. I guess this is not supported yet.

**Comment by Levi-Armstrong** [comment]
Oh open the .workspace and add additional directory tags with the directories you want to show. I hope there is not to many, if dso I can add an additional tag indicating show all directories.

**Comment by xlan09** [comment]
ahh, nice, thanks, Levi. I will use that trick for now. But in the future it would be nice if you could add a tag like that. Not sure how many people will use it. I guess it does not hurt if it is not lots of work.

**Comment by Levi-Armstrong** [comment]
This is addressed by PR #234

**Comment by Levi-Armstrong** [comment]
@xlan09  Also PR #234 adds the ability to watch the workspace directory by removing all <Directory> tags.

**Comment by Levi-Armstrong** [comment]
@xlan09 I have just released the latest version. Please see wiki for new install procedure.
