### ISSUE TITLE
Can't see the "Import ROS Workspace" in Import Project section

### ISSUE THREAD

**Issue by CrazyPopLin** [ros-industrial/ros_qtc_plugin#208]
Hi, I am installed Qt 5.9.2 and Qtcreator firstly from official offline installer. Everything works fine. Then installed **ros_qtc_plugin** follow [wiki](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html).   
Open qt59creator.desktop, I can see **ROS Workspace** in Other project section, but no **Import ROS Workspace** in Import Project section as pics shown below.  

**1th:**
![1](https://user-images.githubusercontent.com/11235093/33366077-2ae8d2b8-d525-11e7-8d5e-1ac19dc40fd7.png)  

**2th:**
![2](https://user-images.githubusercontent.com/11235093/33366121-486eafa6-d525-11e7-9e64-bd1db87b2844.png)
Some basic infos:
- Ubuntu 14.04.5 LTS
- `qmake -v`: QMake version 3.1, Using Qt version 5.9.2 in /opt/Qt5.9.2/5.9.2/gcc_64/lib
-  `which qtcreator`: /opt/qt59/bin/qtcreator
- I also can see **ROSProjectManager** from Installed Plugins

Any suggestions, thanks so much

**Comment by Levi-Armstrong** [comment]
I assume you followed the instruction from the video which is a little outdated. It was recently moved to the "Other Project" section.

**Comment by CrazyPopLin** [comment]
I mean **Import ROS Workspace** not in **Import Project** section, please see my 2th picture poseted above. I can't import existing ROS workspace. thanks

**Comment by CrazyPopLin** [comment]
I see, you've changeed **Import ROS Workspace** to **Create New ROS Project**
