### ISSUE TITLE
Stopping an empty ROS terminal kills Qt creator with Segmentation fault

### ISSUE THREAD

**Issue by raultron** [ros-industrial/ros_qtc_plugin#21]
With Alt-8 it is possible to see the opened ROS terminals when you are running a node or a launch file. If you press the Red button it will stop the current terminal, but if you don't have any terminal then it seg faults Qt creator.

**Comment by Levi-Armstrong** [comment]
@raultron, Thanks for the feedback, I will see if I can get a fix out today.

**Comment by Levi-Armstrong** [comment]
@raultron, this should be fix if you perform an update.
