### ISSUE TITLE
Warning: This file is not part of any project. 

### ISSUE THREAD

**Issue by klapetos** [ros-industrial/ros_qtc_plugin#210]
There is the following warning on the top side of the text editor:
![image](https://user-images.githubusercontent.com/16204660/33768303-27147542-dc2e-11e7-8bc6-864c55994471.png)

- I have installed the ros-qtcreator following the proposed steps from Wiki.
- I have created the catkin workspace with Catkin Tools build system.

I think due to this issue the text parsing is very slow. 
Have seen something like that before?

**Comment by Levi-Armstrong** [comment]
This occurs if the file in question has not been added to the CMakeLists.txt file and built. Have you added the file and built the project?

**Comment by klapetos** [comment]
Yes, of course, this warning comes in every .cpp or.h file that I edit.

**Comment by Levi-Armstrong** [comment]
The warning should go away after adding it to the add_executable(); have tried to closing the file and reopening it?

**Comment by klapetos** [comment]
Yes, this happens for all the code files inside workspace.

**Comment by Levi-Armstrong** [comment]
If you check in the build directory for a given package to see a file called<package_name>.cbp?

**Comment by klapetos** [comment]
Yes

**Comment by Levi-Armstrong** [comment]
Ok are you able to create an example workspace that recreates the issue that I can use?

**Comment by klapetos** [comment]
When I am creating a new clean workspace with a new package, there is no warning.
So maybe something is going wrong with my workspace.

Thank you for your help and your immediate response!

**Comment by Levi-Armstrong** [comment]
No problem. Have you by chance tried deleting the build and devel along along with the .workspace and .workspace.user files, then import the workspace again?

**Comment by beetleskin** [comment]
I'm having the same issue after opening an already existing workspace with QtCreator. It warns me for every single header or source file.

**Comment by klapetos** [comment]
I tried also to delete all the other files except src folder and import new ROS Workspace with CatkinTools. But the problem remains. 

I can follow the headers correctly, the only issue is that is a little bit slow until to resolve new namespace.

**Comment by Levi-Armstrong** [comment]
@beetleskin and @klapetos have you built the workspace from within Qt Creator?

**Comment by klapetos** [comment]
Yes.
I did the following steps:
1. New Project
2. Other Project -> ROS Workspace
3. Build System -> CatkinTools
4. Workspace Path: (one folder with only the src* folder inside) 
5. Build

*Note: the src folder contains many ros pkgs/meta-pkgs which i have checked out from svn so all the src folder is under version

**Comment by Levi-Armstrong** [comment]
Not sure why it is still showing up. Lets check the code model Tools->C++->Inspect C++ Code Model and see if you can find the file showing the warning. After open go to the Project Parts Tab and fine the target the file in question should be associated to. Then select it and in the below tabs select the Project Files tab and see if it is listed there. Example Below.

![image](https://user-images.githubusercontent.com/9803128/34209603-71545702-e558-11e7-8de8-9b5e94d4f037.png)

**Comment by klapetos** [comment]
There are listed all the associated files. Now I just notice that the error changed and is the following: 

![image](https://user-images.githubusercontent.com/16204660/34210065-34c95bda-e59d-11e7-9727-fe087344eeaf.png)

**Comment by Levi-Armstrong** [comment]
If you click on the 720:9 what information does it provide.

**Comment by klapetos** [comment]
It doesn't show anything by clicking it.

**Comment by beetleskin** [comment]
> @beetleskin and @klapetos have you built the workspace from within Qt Creator?
I tried both, it has no impact on the warning.

For me its still the same error. Also, it seems that all the project files are listed correctly \o/

**Comment by Levi-Armstrong** [comment]
@klapetos  Does it by chance refer to line column in the file? Do you use a macro on that line?

**Comment by Levi-Armstrong** [comment]
>I also see the other error sometimes, but can't reproduce a rule. But, it seems that all the project files are listed correctly \o/

So if everything is showing correctly and you can code follow then everything is probably working. Though not sure why the message would persist. I will need to look into Qt Creator may require an event be triggered when code model creation/modification.

**Comment by beetleskin** [comment]
seems legit, the warning seems rather pointless since everything works as expected

**Comment by Levi-Armstrong** [comment]
Yea, I will see what I can find out.

**Comment by Levi-Armstrong** [comment]
This has been added to the FAQ section in the wiki.
