### ISSUE TITLE
ros_qtc_plugin cannot be built with Qt Creator 4.5

### ISSUE THREAD

**Issue by vincent-hui** [ros-industrial/ros_qtc_plugin#211]
ros_qtc_plugin cannot be built with Qt Creator 4.5 because some signals and functions were remove.

**Comment by Levi-Armstrong** [comment]
Thank you for the reminder, I see that Qt Just release 4.5 so we will work on the upgrade to the plugin.

**Comment by Levi-Armstrong** [comment]
Addressed by PR #234.
