### ISSUE TITLE
Ubuntu 16.04.3 ROS Kinetic installed Qt Creator and ROS Plugin do not see option to import ROS projects

### ISSUE THREAD

**Issue by victorwhwu** [ros-industrial/ros_qtc_plugin#212]
I followed the most recent instruction to install the ROS plugin for Qt Creator. It shows ROS project option when trying to create new project but do not have ROS project option when try to import project. I just follow the videos in Youtube but the interface looks different!

**Comment by Levi-Armstrong** [comment]
Sorry it was recently moved to other projects.

**Comment by victorwhwu** [comment]
After I added a new package it does not create the two necessary directory of src and include !

**Comment by Levi-Armstrong** [comment]
It executes the the command line tool catkin_create_pkg so you must add the Carlin depend roscpp for those folders to get created. You may also create the folder when adding a new file in Qt Creator.

**Comment by victorwhwu** [comment]
I certainly did add roscpp as one of the dependencies when adding the new package but it did not create the two folders for me. When I add the .cpp file and choose the path to be under an src folder, when the editor started it gave the warning: This file is not part of any project. The code might have issues to parse this file properly.

**Comment by Levi-Armstrong** [comment]
Ok, so currently empty folder no longer show in the tree which is flagged by another issue. The folders should be in the directory since you added roscpp as a depend. The warning will show up until it is added to the cmakelists file and the workspace is built.

**Comment by victorwhwu** [comment]
So when will the .cpp file be added in the cmakelists.txt or rather how to add it into the cmakelists? Or do I have to add it into cmakelists manually?

**Comment by Levi-Armstrong** [comment]
You will need to add files manually to the cmakelists file.

**Comment by victorwhwu** [comment]
Would it be very difficult to add these file names into the CMakeLists.txt file?

**Comment by Levi-Armstrong** [comment]
Pull requests are always welcome.

**Comment by victorwhwu** [comment]
I have decided to give up on Qt. Thank you for all your effort and help. All the best.

**Comment by Levi-Armstrong** [comment]
Sorry to hear that. There are several IDE's out there like Eclipse and CodeBlocks which which manage it as CMake project where each package is a separate project. You will need to generate project files using the available cmake utilities.
