### ISSUE TITLE
Is there any complete tutorial about how to install this plug-in?

### ISSUE THREAD

**Issue by QiuYilin** [ros-industrial/ros_qtc_plugin#213]
sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial 
sudo add-apt-repository ppa:levi-armstrong/ppa 
sudo apt update && sudo apt install qt57creator 
sudo apt install qt57creator-plugin-ros

I run these command but it doesn't work.

**Comment by Levi-Armstrong** [comment]
What error did you receive?

**Comment by Levi-Armstrong** [comment]
Not sure if this is the issue but the instruction also show installing this libqtermwidget57-0-dev.

**Comment by nathangeorge1** [comment]
I'm going to be working on a complete tutorial within the next month or two @QiuYilin; sorry for the delay @Levi-Armstrong

**Comment by Levi-Armstrong** [comment]
Thats great to here, will you be adding it to the Sphinx documentation?

**Comment by Levi-Armstrong** [comment]
[documentation location](https://github.com/ros-industrial/ros_qtc_plugin/tree/4.4/gh_pages)
[Result](https://ros-industrial.github.io/ros_qtc_plugin/)

**Comment by nathangeorge1** [comment]
I plan to; but learning HTML again will take some time

**Comment by Levi-Armstrong** [comment]
Oh the great thing about Sphinx is you don't need to know HTML. It use Markdown or Restructured Text (I prefer this because you have better features) and then sphinx handles everything converting it to HTML, formating, ect. . I usually use the github wiki to write it then I save the content to a file and place it in this [directory](https://github.com/ros-industrial/ros_qtc_plugin/tree/4.4/gh_pages/_source). Then add the file to this [file](https://github.com/ros-industrial/ros_qtc_plugin/blob/4.4/gh_pages/index.rst) and run Sphinx to see the results. If you run into any issue just let me know.

**Comment by nathangeorge1** [comment]
Ok; I'll do it the same way as you do it then

**Comment by Ghost-CBC** [comment]
@Levi-Armstrong 
Dear sir,
I installed ros_qtc_plugin as recommend:
  sudo add-apt-repository ppa:levi-armstrong/qt-libraries-trusty
  sudo add-apt-repository ppa:levi-armstrong/ppa
  sudo apt-get update 
  sudo apt-get install qt59creator
Then threw:
    ghost@ghost-ThinkCentre-M8600t-N000:~$ sudo apt-get install qt59creator
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    The following packages have unmet dependencies:
    qt59creator : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
               Depends: qt59qbs but it is not going to be installed
               Recommends: qt59creator-doc but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.
Could you give me some advice what's the problem?
Thanks in advance.

**Comment by Levi-Armstrong** [comment]
Sorry, I need to push the latest updates to the wiki. There is a missing ppa required.
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
```

**Comment by KevinGHub** [comment]
I got this when I try to apt qt59creator.
_________________________________________________________________
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qt59creator : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
               Depends: qt59qbs but it is not going to be installed
               Recommends: qt59creator-doc but it is not going to be installed
_________________________________________________________________
Anything I can do? THX.

**Comment by Levi-Armstrong** [comment]
So for some reason on certain individuals machines it does not automatically install dependencies. So I think the message wants you to manually install qt59qbs.
Try:
```
sudo apt-get install qt59qbs
sudo apt-get install qt59creator
```

**Comment by Ghost-CBC** [comment]
@Levi-Armstrong 
Thank you.
I add “sudo add-apt-repository ppa:ubuntu-toolchain-r/test as” as you recommend.
It work.

**Comment by Levi-Armstrong** [comment]
@Ghost-CBC Great! I also just pushed a new version of the documentation.
