### ISSUE TITLE
Support partial build

### ISSUE THREAD

**Issue by beetleskin** [ros-industrial/ros_qtc_plugin#215]
With the current catkin build setup, I don't see a possibility to trigger a partial build of a single package. Often I only want to build the package, I'm currently editing. With a custom build step, I achieved this with:

**comamnd**: `catkin`
**arguments**: `build --this --no-deps --no-status`
**working directory**: `%{CurrentDocument:Path}`

**Comment by Levi-Armstrong** [comment]
Based on the description you provided, I believe you may not be using this plugin. You should see this below and you would put the package name under catkin tools arguments.

![image](https://user-images.githubusercontent.com/9803128/34162175-60543258-e498-11e7-822e-a33e9088d5d7.png)

**Comment by beetleskin** [comment]
Hi Levi, thanks for the fast reply.

I want to automate the "put the package name under catkin tools arguments"-part by setting the **working directory** to `%{CurrentDocument:Path}`. This way, I only build the package belonging to the file that is currently opened. However, selecting the working directory seems not to be supported by your CatkinTools build setup mask. And I don't know another way to do this. 

Or do you have the "current" package name lying around as variable, similar to `%{CurrentDocument:Path}`?

**Comment by Levi-Armstrong** [comment]
Let me know if I understand correctly, you want the build to only build the package related to the open file?

**Comment by Levi-Armstrong** [comment]
I labeled this a bug it should be setting the working directory to what the user specify.

**Comment by beetleskin** [comment]
> Let me know if I understand correctly, you want the build to only build the package related to the open file?

Exactly. The background is, that we're working in a workspace with close to 100 packages (it's a bigger project), and building everything takes some non-trivial amount of time. Even when everything else is already built and not touched, catkin needs a lot of time to figure that out.

**Comment by Levi-Armstrong** [comment]
OK, So I the interim you will have to add the package to catkin tools argument. If you know you are just going to be working on a few package you could also create separate build configurations one for each package and then use the tool in the bottom left to easily switch between the build configurations.

**Comment by Levi-Armstrong** [comment]
I need to make a change [here](https://github.com/ros-industrial/ros_qtc_plugin/blob/4.4/src/project_manager/ros_catkin_tools_step.cpp#L140) to set the appropriate working directory.

**Comment by beetleskin** [comment]
Now that I think of it .. having the "current" package name (i.e. the name of the package the currently opened file belongs to) around as variable could be useful for a bunch of other catkin commands as well, like `catkin lint -W2 --pkg %{CurrentDocument:RosPackage}`

**Comment by Levi-Armstrong** [comment]
This is addressed by PR #234

**Comment by Levi-Armstrong** [comment]
@beetleskin I have just released the latest version. Please see wiki for new install procedure.
