### ISSUE TITLE
I can't find src and include folder in my project tree

### ISSUE THREAD

**Issue by hljchenxi** [ros-industrial/ros_qtc_plugin#217]
After add a rospackage ,there are  src and include folder in my package folder,but I can see it in my project tree on qt. Only CMakeLists.txt and package.xml in there.

**Comment by hljchenxi** [comment]
I'm sorry... I add a cpp file in my src ,then I can see it in projcet tree.

**Comment by Levi-Armstrong** [comment]
@hljchenxi Check out this #193 so your empty folders will show up in the future.
