### ISSUE TITLE
How to build a Qt  Designer file in the package created by the plugin?

### ISSUE THREAD

**Issue by sunyuzhe2017** [ros-industrial/ros_qtc_plugin#218]
I want to set a new ui file in the ros package which is created by ros_qtc_plugin,in order to call in the default interface by a button like in ,do I need to do any special configuration?why there is always wrong ?

**Comment by Levi-Armstrong** [comment]
I not sure I fully understand the questions, but you can create/add ui files to a ros workspace and edit them using the designer. Note that you will have to manually add it to the CMakeLists file.

**Comment by Levi-Armstrong** [comment]
Is this for a plug-in for rviz, rqt, etc?

**Comment by sunyuzhe2017** [comment]
![errormanualdialog](https://user-images.githubusercontent.com/33214493/34352090-6651b612-ea5b-11e7-9095-0de25893d3b6.png)

**Comment by sunyuzhe2017** [comment]
[Yeah,I want to make an interface for a ros project so I can connect and control by the interface .I‘m new to  Qt and ros ,I 'd like to give my steps as follows:
First,I create a package ["test2"](https://github.com/sunyuzhe2017/Qt-ROS.git) with the command catkin_create_qt_pkg,then I can get a interface show some message,after that,I add a Qt Designer Form Class"manualdialog" in test2's src folder,and there are four files,I move them to the respective folders,and put some buttons on the manualdialog.ui interface.
    I add a button "ManualControl" in the main_window.ui ,and want to call the manualDialog interface by this button,when I build the project,there shows "File not find : CMakeFiles/test2.dir/src/manualdialog.cpp.o:-1: In function `ManualDialog::ManualDialog(QWidget*)': "" /home/sun/catkin_new/src/test2/src/manualdialog.cpp:6: error: undefined reference to `vtable for ManualDialog'"
![errormanualdialog](https://user-images.githubusercontent.com/33214493/34355410-03b1d658-ea70-11e7-8109-d2d4323352e5.png),I guess that must be some change in CMakelists,but I don't konw what to add in it,could you give me an example in detail. Thank you very much!

**Comment by sunyuzhe2017** [comment]
I'm not sure if my expression is clear or the method I used for adding  interface is just toally messed and wrong.I do appreciate it if you could give me some useful dirctions (examples is much better)for add an interface in ros project ,Thanks again! @Levi-Armstrong

**Comment by Levi-Armstrong** [comment]
Take a look at this [file](https://github.com/Levi-Armstrong/urdf_builder/blob/master/urdf_editor/CMakeLists.txt). I think you are missing a few things.

I am not sure this [line](https://github.com/sunyuzhe2017/Qt-ROS/blob/master/test2/CMakeLists.txt#L26) is valid.

**Comment by sunyuzhe2017** [comment]
Thank you,I have solved it last night.I can't believe it's just because this line ...
`file(GLOB_RECURSE QT_MOC RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} FOLLOW_SYMLINKS include/test2/*.hpp *.h)` I add " *.h "at the end of it.
The header files create by command "catkin_create_qt_pkg" all with a " .hpp "suffix,and the file I added in Qt Designer Form  Class with " .h " suffix,it can't be find ! I  should miss that！ 
![headerfile](https://user-images.githubusercontent.com/33214493/34367399-1ef343a0-eae5-11e7-889d-3fb046b1c22a.png)

**Comment by Levi-Armstrong** [comment]
That is great to here!
