### ISSUE TITLE
 Header can not be found

### ISSUE THREAD

**Issue by dugujing** [ros-industrial/ros_qtc_plugin#219]
Hello:
I use the environment：
Ubuntu16.04.
installed by default：
Qt5.9.1 Creator
$ git clone xxxros_qtc_pluginxxx
Modify QTC_BRANCH = "4.4", QMAKE_PATH = "/ opt / qt59 / bin / qmake" and libqtermwidget57-0-dev is libqtermwidget59-0-dev in setup.sh. succed；And create workspace and package through ui interface, add a header file problems whether ros or standard library
![image](https://user-images.githubusercontent.com/27988338/34400850-80146f1a-ebd0-11e7-8831-4350942b7793.png)

What do I need to do?Looking forward to your reply.

**Comment by Levi-Armstrong** [comment]
Have you built from within Qt Creator?

**Comment by dugujing** [comment]
Thank you, I know， now it works.
