### ISSUE TITLE
No import ros workspace

### ISSUE THREAD

**Issue by lusu8892** [ros-industrial/ros_qtc_plugin#229]
Hi Levi

I followed the the [instruction here] (https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html) to install Qtcreator ros plugin, I have tried multiple times but that import ros workspace just did not show in qtcreator. Before install Qtcreator, there is no other qtcreator version in my ubuntu 16.04.

**Comment by Levi-Armstrong** [comment]
So under "Other Projects" you don't see ROS Workspace?

**Comment by Levi-Armstrong** [comment]
The reason I ask is the title suggests the old style of importing the workspace.

**Comment by Levi-Armstrong** [comment]
The new process is explained [here](https://ros-industrial.github.io/ros_qtc_plugin/_source/Import-ROS-Workspace.html).

**Comment by lusu8892** [comment]
I could not see import ros worksapce at Import Project tab. But I do see ros workspace at Other Project tag. So I am good to go?

**Comment by Levi-Armstrong** [comment]
Yep, it should work.

**Comment by lusu8892** [comment]
Thanks
