### ISSUE TITLE
Using git status crashes qtcreator-ros

### ISSUE THREAD

**Issue by azhural** [ros-industrial/ros_qtc_plugin#231]
Hello,
I'm currently experiencing this problem on three different machines (all of them Ubuntu 16.04LTS). On two of them I purged qt57 and qt59, as described in [the installation how-to](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html#). The third did not have qtcreator installed before, so I also followed the mentioned how-to.

On calling "git status" qtcreator-ros crashes with "Segmentation fault (core dumped)" if the working directory is clean or has some modified files. Having untracked files circumvents the problem. If the untracked files are deleted, thus having a clean working directory again, qtcreator-ros will not crash again until it's restarted.

Edit: I also experienced segmentation faults when renaming files using the projects explorer. Having untracked files in the repository circumvents this as well.
Edit2: The untracked file has to be created in the current session.

**Comment by Levi-Armstrong** [comment]
Thank you for your feedback, I have recently experience this myself just last week. I am currently trying to track down the issue.

**Comment by Levi-Armstrong** [comment]
This should be addressed by PR #234.

**Comment by Levi-Armstrong** [comment]
@azhural I have just released the latest version. Please see wiki for new install procedure.
