### ISSUE TITLE
Opening multiple projects (workspaces) causes qtcreator to crash

### ISSUE THREAD

**Issue by d-walsh** [ros-industrial/ros_qtc_plugin#232]
I'm not sure if this is a qtcreator problem or an issue with the plugin.

Whenever I have a project (workspace) open, it works fine. However when I add a second project to the same session qtcreator crashes (seg fault). I am using catkin_tools.

Thanks!

**Comment by Levi-Armstrong** [comment]
Are you on 14.04 or 16.04?

**Comment by d-walsh** [comment]
I'm on 16.04

**Comment by Levi-Armstrong** [comment]
If you launch qt creator from the terminal does anything print to the terminal?

**Comment by d-walsh** [comment]
It prints several of these messages:
- >"Unable to locate build directory for package: ......"
- >"Flags file does not exist: /....../CMakeFiles/executable.dir/flags.make"

Then finally:
> [1]    22011 segmentation fault (core dumped)  qtcreator-ros

I also did a backtrace in gdb and it gave me: [qt_creator_crash_gdb.txt](https://github.com/ros-industrial/ros_qtc_plugin/files/1650259/qt_creator_crash_gdb.txt)

**Comment by Levi-Armstrong** [comment]
Ok think it has to do with the same segfault when executing a git status. I should have a pr up soon to address it.

**Comment by d-walsh** [comment]
OK, great thanks!

**Comment by Levi-Armstrong** [comment]
This should be addressed by PR #234.

**Comment by Levi-Armstrong** [comment]
@d-walsh I have just released the latest version. Please see wiki for new install procedure.

**Comment by d-walsh** [comment]
Thanks @Levi-Armstrong !
