### ISSUE TITLE
Building Catkin Workspace Fails

### ISSUE THREAD

**Issue by nathangeorge1** [ros-industrial/ros_qtc_plugin#233]
Hello,

From last night when it was working, now I get the following error this morning:

![image](https://user-images.githubusercontent.com/2744891/35103135-042c2000-fc33-11e7-927f-5ff14c7b85af.png)

I know this custom build step is working because I did in via bash. What is wrong?

Thanks,
Nathan

**Comment by Levi-Armstrong** [comment]
I am not sure. Can you provide an example so I can recreate it on my end?

**Comment by nathangeorge1** [comment]
I actually just figured out the problem. I accidentally clicked on `catkin_ws.creator` in the Welcome > Recent Projects sections, which I think was a file from an older version. I fixed it by clicking on `catkin_ws.workspace`. Thanks for the quick response.
