### ISSUE TITLE
clang code model performance

### ISSUE THREAD

**Issue by beetleskin** [ros-industrial/ros_qtc_plugin#235]
Hi, I'm running into the issue that the _Clang Code Model_ is *really* slow for code completion, and, it seems, for parsing the current file in general (resolving includes and whatever happens under the hood). It is so slow, that it's almost not worth working with it, since for each file I open, I have to wait a couple of seconds. The same applies when editing a c++ file (I guess the code model is reloaded (from scratch?)). 

I know that seems not to be an issue of this plugin (unless the includes you set are over-blown), but is there any tweak I'm missing out?
The built-in QtCreator code model is much faster, but can't handle c++11, 14, .. unless one is working with qmake ([ref](https://stackoverflow.com/a/16950073/1880234)).

**Comment by Levi-Armstrong** [comment]
I have used the Clang Code Model once before, but I have read several places that it is very slow. Not sure if that is just Qt's implementation or the Clang Code Model itself. It could be how I am building the code model but one way to test it out would be initialize your workspace as catkin_make and then open as a pure cmake within Qt Creator and see if the code model is still slow.

**Comment by beetleskin** [comment]
I'll try. 

But if you're not using clang .. do you use the built-in code model for completion and stuff? Is that working with your plugin?

**Comment by Levi-Armstrong** [comment]
I use the built in code model which works. Are you have issues with the built in code model when using the plugin?

**Comment by beetleskin** [comment]
Yes, as stated above:
- does not find ros-header
- does not find workspace includes
- does not find .. anything despite system includes and local ones (e.g. `#include "../local_header.h"`)
- cant cope with c++11/14/..

**Comment by Levi-Armstrong** [comment]
Ok that should not be happening. Have you built the project from withing the IDE?

**Comment by beetleskin** [comment]
Yes I did, but this seems to be a default issue for this QtCreator version:
https://www.google.de/search?client=ubuntu&hs=MB2&channel=fs&dcr=0&q=+site:stackoverflow.com+qtcreator+c%2B%2B11&sa=X&ved=0ahUKEwj-3KKO_OvYAhUPfFAKHYfrDfoQrAMINA&biw=2079&bih=1115

I'm running on Ubuntu 16.04 with QtCreator 4.4.1.

**Comment by Levi-Armstrong** [comment]
If you don't mind setting ups a simple workspace that recreates the issue I can take a look to determine how to resolve it.

**Comment by Levi-Armstrong** [comment]
What do you mean by working? For me code following and code completions is working.

**Comment by beetleskin** [comment]
also for `shared_ptr`?

Here comes the minimal not-working example with c++11:

```c++
#include <memory>
#include <nav_msgs/Path.h>

std::shared_ptr<nav_msgs:Path> patPtr = std::make_shared<nav_msgs:Path>();
patPtr.//[STRG+SPACE]
patPtr->//[STRG+SPACE]
```

`patPtr.//[STRG+SPACE]` should give me the autocomplete options of the `shared_ptr` itself.
`patPtr->//[STRG+SPACE]` should give me the autocomplete options of underlying `nav_msgs:Path`.

None of the above is working for me with the default QtCreator Code Model (but works with Clang Code Model).

In general, how do you tell QtCreator that c++11, 14, .. is used when set via cmake (via catkin)?

**Comment by Levi-Armstrong** [comment]
I add this `add_compile_options("-std=c++11")` below project().

**Comment by beetleskin** [comment]
we're setting this via `CMAKE_CXX_FLAGS` .. which is not supported then?

**Comment by Levi-Armstrong** [comment]
If you don't mind creating a simple package that recreates the issue, I will take a look this week and push a fix assuming one exists.

**Comment by beetleskin** [comment]
Ok, I can't reproduce with a fresh ws and a dummy package. I think my problem was using custom partial builds (#215) instead of building everything with the default built chain of the plugin. 

So I guess you're collecting information for the code model within the catkin build steps? And this information is missing out, partly, when I use my own custom build chain?
