### ISSUE TITLE
Support for zsh

### ISSUE THREAD

**Issue by nils-huegel** [ros-industrial/ros_qtc_plugin#237]
This plugin is very nice, good job!

Unfortunately, the dependency on bash and the "setup.bash" is hardcoded at 
https://github.com/ros-industrial/ros_qtc_plugin/blob/caf3eb65669e67cbb36a7fd9a6ce5349a9ae67b0/src/project_manager/ros_run_steps.cpp#L154

So if your default shell is the zsh, the zsh will interpret the bash setup script - incorrectly - and run into an error:
```
nils@nilsrosbox ~/ros/default_ws :) $ source /home/nils/ros/default_ws/devel/setup.bash                                                                                     
/home/nils/ros/default_ws/devel/setup.bash:.:8: no such file or directory: /home/nils/ros/default_ws/setup.sh
```
If I replace the setup.bash with a link to the setup.zsh, it works.

Thanks,
Nils

**Comment by Levi-Armstrong** [comment]
Any ideas on how to determine what default shell is being used?

**Comment by nilshuegel** [comment]
You can read it from the environment variable SHELL

```
nils@nilsrosbox ~ :) $ echo $SHELL
/usr/bin/zsh
```

**Comment by Levi-Armstrong** [comment]
Since the IDE environment does not affect the host would you be opposed to the IDE always setting it to bash?

**Comment by nilshuegel** [comment]
Well, that would probably be a better workaround than mine (symlink). Although I liked that I can use my default shell in the IDE, to be sure it behaves the same.

**Comment by Levi-Armstrong** [comment]
Addressed by PR #234 
@nils-huegel  I added support for the three shell types bash, sh and zsh.

**Comment by nils-huegel** [comment]
Great, thanks.
I will give feedback once the build gets released.

**Comment by Levi-Armstrong** [comment]
@nils-huegel I have just released the latest version. Please see wiki for new install procedure.

**Comment by nils-huegel** [comment]
Nice job. It works perfectly.

**Comment by Levi-Armstrong** [comment]
Great!
