### ISSUE TITLE
Linux Package Manager Broke Indexing

### ISSUE THREAD

**Issue by nathangeorge1** [ros-industrial/ros_qtc_plugin#238]
Hello,

After installing Ubuntu Software Updates (I noticed one of them was for qt), indexing doesn't work, even though my project is built correctly; any ideas?

Thanks,
Nathan

**Comment by Levi-Armstrong** [comment]
I just had a coworker run into a similar thing. In his case he still had this ppa *(ppa:beineri/opt-qt571-trusty)* on his system. I would check the /etc/apt/source.list.d/ directory and see if you see anything with the name beineri in it. If so I would purge remove anything libraries from this ppa then delete the files from this directory. After that go back through the install process and everything should work. 

The reason this occurred was a while backed I switched to hosting my own version of qt because depending on another ppa they would update and then my stuff would break. This way I could control all dependencies.

**Comment by nathangeorge1** [comment]
I checked the directory but nothing says "beineri"; there are many things that start with "levi-armstrong" though. Should I still try reinstalling?

**Comment by Levi-Armstrong** [comment]
Yea I would try that next.

**Comment by nathangeorge1** [comment]
I reinstalled using the 16.04 instructions found here: https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html

but the same problem; anything else?

**Comment by Levi-Armstrong** [comment]
Do you mind posting an output of what you are seeing for context?

**Comment by nathangeorge1** [comment]
![image](https://user-images.githubusercontent.com/2744891/35574666-6caa6faa-05a8-11e8-9aa4-04896ad7bfb1.png)

No actual error messages; indexing is just not working

**Comment by Levi-Armstrong** [comment]
Sorry I was thinking of something else when you mentioned indexing. I would launch qtcreator-ros from the terminal then proceed with opening your project. I would then post what gets printed out to the terminal.

**Comment by nathangeorge1** [comment]
it outputted this:

```
"Unable to locate package camera build file: /home/bloom/catkin_ws/build/bloomautomation/src/camera/camera.cbp"
"Unable to locate package camera_calibration build file: /home/bloom/catkin_ws/build/image_pipeline/camera_calibration/camera_calibration.cbp"
"Unable to locate package depth_image_proc build file: /home/bloom/catkin_ws/build/image_pipeline/depth_image_proc/depth_image_proc.cbp"
"Unable to locate package image_publisher build file: /home/bloom/catkin_ws/build/image_pipeline/image_publisher/image_publisher.cbp"
"Unable to locate package image_rotate build file: /home/bloom/catkin_ws/build/image_pipeline/image_rotate/image_rotate.cbp"
"Unable to locate package image_view build file: /home/bloom/catkin_ws/build/image_pipeline/image_view/image_view.cbp"
"Unable to locate package io_link build file: /home/bloom/catkin_ws/build/bloomautomation/src/io_link/io_link.cbp"
"Unable to locate package learning build file: /home/bloom/catkin_ws/build/bloomautomation/src/learning/learning.cbp"
"Unable to locate package librealsense build file: /home/bloom/catkin_ws/build/librealsense/librealsense.cbp"
"Unable to locate package localizing build file: /home/bloom/catkin_ws/build/newmind/src/localizing/localizing.cbp"
"Unable to locate package main build file: /home/bloom/catkin_ws/build/newmind/src/main/main.cbp"
"Unable to locate package manipulation build file: /home/bloom/catkin_ws/build/bloomautomation/src/manipulation/manipulation.cbp"
"Unable to locate package o3d3xx build file: /home/bloom/catkin_ws/build/o3d3xx-ros/o3d3xx.cbp"
"Unable to locate package path_planner build file: /home/bloom/catkin_ws/build/newmind/src/path_planner/path_planner.cbp"
"Unable to locate package planner build file: /home/bloom/catkin_ws/build/newmind/src/planner/planner.cbp"
"Unable to locate package plant_trimmer build file: /home/bloom/catkin_ws/build/bloomautomation/src/plant_trimmer/plant_trimmer.cbp"
"Unable to locate package q_learning build file: /home/bloom/catkin_ws/build/newmind/src/q_learning/q_learning.cbp"
"Unable to locate package simulation build file: /home/bloom/catkin_ws/build/newmind/src/simulation/simulation.cbp"
"Unable to locate package util build file: /home/bloom/catkin_ws/build/newmind/src/util/util.cbp"
"Unable to locate package utility build file: /home/bloom/catkin_ws/build/bloomautomation/src/utility/utility.cbp"
"Unable to locate package vision build file: /home/bloom/catkin_ws/build/newmind/src/vision/vision.cbp"
```

In going to those directories, I couldn't find the .cbp files, although build files are good.

**Comment by Levi-Armstrong** [comment]
Try a clean build from within the qt creator

**Comment by nathangeorge1** [comment]
yes everything is working now; essentially from within qt, I right clicked the catkin_ws project, and then did `Clean` then `Rebuild`. Do you know what broke things?

**Comment by Levi-Armstrong** [comment]
Not sure but you must build at least once from within the qt creator which creates the cbp files and set a flag to keep updating every time. Then you can build outside of Qt Creator. Now that being said if you clean it or add new packages you must build(you do not have to clean) from within Qt Creator again.

**Comment by Levi-Armstrong** [comment]
Had you built from within the qt creator yet?

**Comment by nathangeorge1** [comment]
O I didn't know that. I can add that to the installation instructions/video that I'm supposed to be doing soon. Sorry it's taking forever btw, but my 2 startups are eating a lot of my time. Hopefully soon though.

**Comment by Levi-Armstrong** [comment]
Yea it probably be good to have that mentioned somewhere. I think I recently added a FAQ section which it may be in that.
