### ISSUE TITLE
i can't install qt59creator in ubuntu14.04.5 because of depends,anybody can help me ?

### ISSUE THREAD

**Issue by CodeIsWorld** [ros-industrial/ros_qtc_plugin#239]
when i input this :    sudo apt-get install qt57creator-plugin-ros
i got this 
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qt57creator-plugin-ros : Depends: qt59creator (>= 4.4.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

then i input this:    sudo apt-get install qt59creator
then i got this
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qt59creator : Depends: libclang1-3.9 (>= 3.6) but it is not installable
               Recommends: qt59creator-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

so what should i do?

**Comment by Levi-Armstrong** [comment]
It looks like you need to install libclang1-3.9  and then try and install again.

**Comment by Levi-Armstrong** [comment]
Please use the online installer found [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/installers/xenial/) now.
