### ISSUE TITLE
C++ Code Style forced to ROS 

### ISSUE THREAD

**Issue by beetleskin** [ros-industrial/ros_qtc_plugin#242]
I was wondering why Qt is not following my defined C++ Code Style. I figured it uses the ROS style all the time, no matter what you actually select in the corresponding options. Can you confirm this?

**Comment by Levi-Armstrong** [comment]
It is set at the project level. Under the project tab on the left you can set the code style.

**Comment by beetleskin** [comment]
Ahhhh .. my bad, thanks :)
