### ISSUE TITLE
Error on importing C headers

### ISSUE THREAD

**Issue by BrunoXL** [ros-industrial/ros_qtc_plugin#243]
I tried to open a third-person project (hector_quadrotor) on Qt creator 4.4.1. However, qt simple [does not recognize C header files](https://ddgobkiprc33d.cloudfront.net/0705fce5-cb2c-4d06-9b75-91ed967bc8d7.png). What could be wrong?

EDIT: I imported the project via ROS wokspace option

**Comment by Levi-Armstrong** [comment]
Did you build from within the IDE?

**Comment by BrunoXL** [comment]
Thanks, I was building from outside
