### ISSUE TITLE
Ubuntu 16.04 could not be  installed:Depends: libclang1-4.0 (>= 3.6)

### ISSUE THREAD

**Issue by wojiaojiao** [ros-industrial/ros_qtc_plugin#246]
Installation Procedure for Ubuntu 14.04

sudo add-apt-repository ppa:levi-armstrong/qt-libraries-trusty
sudo add-apt-repository ppa:levi-armstrong/ppa
sudo apt-get update && sudo apt-get install qt59creator
sudo apt-get install qt57creator-plugin-ros

with the error:
The following packages have unmet dependencies:
qt59creator : Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
Depends: qt59qbs but it is not going to be installed
Recommends: qt59creator-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

i solve it:
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9

but
 Installation Procedure for Ubuntu 16.04
sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial
sudo add-apt-repository ppa:levi-armstrong/ppa
sudo apt update && sudo apt install qt59creator
sudo apt install qt57creator-plugin-ros

when i $ sudo apt install qt59creator
with the error:
The following packages have unmet dependencies:
 qt59creator : Depends: libclang1-4.0 (>= 3.6) but it is not installable
               Recommends: qt59creator-doc but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

please help me solve it!

**Comment by Levi-Armstrong** [comment]
I believe the install procedure you posted for 14.04 is actually the one for 16.04 see [here](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html#installation-procedure-for-ubuntu-14-04) which was missing  `sudo add-apt-repository ppa:ubuntu-toolchain-r/test` as you found out.

It looks like you need to install libclang1-4.0. I recommend installing it and then trying to install everything again.

`sudo apt install libclang1-4.0`

**Comment by wojiaojiao** [comment]
@Levi-Armstrong 
thank you！I've already solved it！
i refer to：https://packages.ubuntu.com/xenial-updates/devel/libclang1-4.0
download and install libclang1-4.0
and again install qt59creator is ok!

**Comment by Levi-Armstrong** [comment]
Great!
