### ISSUE TITLE
How to run a node or launch file?

### ISSUE THREAD

**Issue by GarethZhang** [ros-industrial/ros_qtc_plugin#25]
Hi,
Could you please give us a brief tutorials on how to do basic rosrun and roslaunch using the plugin? THX!

**Comment by Levi-Armstrong** [comment]
No problem, I will put something together and post it.

**Comment by GarethZhang** [comment]
Thx

**Comment by Levi-Armstrong** [comment]
I made a few tutorial [videos](https://github.com/ros-industrial/ros_qtc_plugin/files/382065/Videos.zip), let me know if you have any questions.

**Comment by GarethZhang** [comment]
Thanks. Been very helpful!

**Comment by vfdev-5** [comment]
Thanks for video tutorials, it's definitely should be somewhere at wiki pages. 
However, starting my workspace in debug mode ("Start Debugging"), I have the following message in Application Output console : `No executable specified. Debugging has finished`.
Starting the same debug mode with "Ctrl + R", ROS Terminal starts my roslaunch configuration without any problem. Could you hint me, what would be the issue, please?

**Comment by Levi-Armstrong** [comment]
@vfdev-5, Did you got through the process below prior to "Ctrl + R"? Depending on what you are debugging you may need to place a sleep at the start to give the debugger time to attach.

`Debug->Start Debugging->Attach to an Unstarted Application and select your Executable then check "Continue on Attach"`

**Comment by vfdev-5** [comment]
Right, I got debugger working with mode `Debug->Start Debugging->Attach to an Unstarted Application and select your Executable then check "Continue on Attach`. Just, I have been confused by the button "Debug" on the left of the IDE.

**Comment by Levi-Armstrong** [comment]
OK, Eventually there will be a run step to attach to process where then that button will work but for now this is the best way.

**Comment by Levi-Armstrong** [comment]
@vfdev-5, Thank you for making me aware that the videos had not been added to the wiki.  I added links to tutorial videos on youtub to the home page of the wiki.

**Comment by amcelroy** [comment]
Sorry to necro a closed topic, but adding the sleep command to allow the debugger to attach would be a huge help if mentioned in the tutorial. The debugger kept skipping my breakpoints and it was driving me nuts and couldn't find an answer until searching through all the closed topics.

**Comment by Levi-Armstrong** [comment]
@amcelroy  Thank you for the reminder. I have updated the Notes section the debug [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/4.-Debugging-Catkin-Workspace).

**Comment by amcelroy** [comment]
@Levi-Armstrong Thanks. Thanks also for making such a great tool, it is an amazing way to write code for ROS and has sped up development dramatically. Very nice tool!
