### ISSUE TITLE
Unable to locate package libqtermwidget5-0

### ISSUE THREAD

**Issue by RohanBampal** [ros-industrial/ros_qtc_plugin#258]
I am reinstalling Qt Creator ROS plugin and saw a new way to install the plugin(old method worked perfectly). I followed all the steps and on the step: `sudo apt install libqtermwidget5-0`, the error `Unable to locate package libqtermwidget5-0` shows. I am using Ubuntu 14.04. Thanks.

**Comment by Levi-Armstrong** [comment]
Have you added the ppa below?

`sudo add-apt-repository ppa:levi-armstrong/ppa`

**Comment by RohanBampal** [comment]
Yes, I have added it, and also run `sudo apt-get update` afterwards.

**Comment by Levi-Armstrong** [comment]
Try `sudo apt-get install libqterm<tab><tab>` and see if it provides a list of options.

**Comment by Levi-Armstrong** [comment]
Sorry, I thought the library was named the same in my ppa. It should be `sudo apt-get install libqtermwidget59-0`

**Comment by Levi-Armstrong** [comment]
Let me know if it works and I will update the documentation.

**Comment by RohanBampal** [comment]
Now it can find the package, but now it shows the error: `The following packages have unmet dependencies:
 libqtermwidget59-0 : Depends: qt59base but it is not installable`

**Comment by RohanBampal** [comment]
It finally worked! Thanks for the Help

**Comment by Levi-Armstrong** [comment]
OK I will update the documentation, sorry for the issues.
