### ISSUE TITLE
Installation compilation issue

### ISSUE THREAD

**Issue by doisyg** [ros-industrial/ros_qtc_plugin#26]
I ran into the following errors while executing` setup.sh ` to install the plugin.
```
/usr/bin/ld: cannot find -lProjectExplorer
/usr/bin/ld: cannot find -lCppTools
/usr/bin/ld: cannot find -lQtSupport
```

I downloaded and installed before Qt 5.7 though the *.run file and edited qtchooser.
I am going to try again on a fresh instal.

**Comment by Levi-Armstrong** [comment]
Have you tried to run the setup.h script more than once? We found an issue yesterday requiring you to run the setup script twice, which I will have a fix for it today.

**Comment by doisyg** [comment]
Yes, actually I have errors about missing folders when i run it the first time, which disappear the second time

**Comment by Levi-Armstrong** [comment]
OK, so after running it twice does everything work?

**Comment by doisyg** [comment]
No, i get these error the second time:

/usr/bin/ld: cannot find -lProjectExplorer
/usr/bin/ld: cannot find -lCppTools
/usr/bin/ld: cannot find -lQtSupport

**Comment by doisyg** [comment]
Just tested on a different machine. Same errors.
Is there any dependencies that I should install first?

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: not trying to frustrate the debug process here, but in case @doisyg is only interested in working *with* the plugin, perhaps we could suggest trying out the pkg and instructions from #17?

**Comment by doisyg** [comment]
@gavanderhoorn  Yes I am only interested in making the plugin work (for now), can you please detail the steps needed to install it from your *.deb file. Thanks!

**Comment by gavanderhoorn** [comment]
I'll wait for @Levi-Armstrong to respond first, as I don't want to rob him from an opportunity to debug and then test a possible solution for the build script problem he mentioned.

**Comment by doisyg** [comment]
Ok, more info about my setup:
Ubuntu 16.04
Ros kinetic
Qt 5.7

**Comment by gavanderhoorn** [comment]
Ah, then using the `deb` is not possible anyway, as it targets Trusty.

**Comment by Levi-Armstrong** [comment]
I have not tested the setup script on 16.04 or have the means right now so lets move forward with the deb.

**Comment by gavanderhoorn** [comment]
@doisyg: see https://github.com/ros-industrial/ros_qtc_plugin/issues/17#issuecomment-232997366 for some instructions.

I also don't run Xenial. Package was built in a Docker container running Xenial, so I expect it to work. Please let us know if it does.

**Comment by Levi-Armstrong** [comment]
@doisyg were you able to get the plugin installed using the debian?

**Comment by doisyg** [comment]
@Levi-Armstrong, Yes, as reported here: https://github.com/ros-industrial/ros_qtc_plugin/issues/17#issuecomment-232997366, working like a charm on ubuntu 16.04 and kinetic
