### ISSUE TITLE
"ROSProjectManager plugin has errors and cannot be loaded" error on opening QtCreator.

### ISSUE THREAD

**Issue by RohanBampal** [ros-industrial/ros_qtc_plugin#263]
I installed QtCreator-ROS plugin with Qt Installer. On opening the QtCreator, this error shows: 
```ROSProjectManager plugin has errors and cannot be loaded.
/home/rohan/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so: 
Cannot load library /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so: 
(/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by 
/home/rohan/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so))
```
I am using Ubuntu 14.04. Thanks.

**Comment by Levi-Armstrong** [comment]
Try the command below and see if it gets resolved.

`sudo apt-get install libstdc++6`

if not then try

```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get upgrade
```

**Comment by RohanBampal** [comment]
Now I'm getting a different error:
``` /home/rohan/QtCreator1/latest/lib/qtcreator/plugins/libROSProjectManager.so: Cannot load library 
/home/rohan/QtCreator1/latest/lib/qtcreator/plugins/libROSProjectManager.so: 
(/home/rohan/QtCreator1/latest/lib/qtcreator/plugins/libROSProjectManager.so: symbol 
_ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined 
in file libstdc++.so.6 with link time reference)
```

**Comment by Levi-Armstrong** [comment]
try

```
sudo apt-get update
sudo apt-get install -f
sudo apt-get upgrade
```

**Comment by Levi-Armstrong** [comment]
Ok, I am going to create a clean VM and see if I have the same issue and try to resolve them. In the interim you could us the ppa version.

**Comment by Levi-Armstrong** [comment]
Did you by chance have the ppa version installed before or was this on a clean machine?

**Comment by RohanBampal** [comment]
No, it was a clean machine.

**Comment by Levi-Armstrong** [comment]
It looks like I am going to have to create one specific to each trusty, so it will take a few days to accomplish this.

**Comment by gavanderhoorn** [comment]
> It looks like I am going to have to create one specific to trusty

do you really mean each Ubuntu Trusty version, or each Ubuntu distribution?

In any case: perhaps Docker can help here?

**Comment by Levi-Armstrong** [comment]
I think just Ubuntu distribution. I think docker would help just not that familiar with it.

**Comment by gavanderhoorn** [comment]
Let me know if I can help you with anything @Levi-Armstrong.

But in short: you'd basically use a Docker image of the target Ubuntu distribution and run your regular build script (I'm assuming it's a script) in there. That has three advantages:

 1. you don't build a redistributable artefact on a system that has potentially many pkgs installed that are not present on the systems onto which the artefact is to be deployed
 1. you don't pollute your system with build infrastructure
 1. you can build for just about any Linux distribution that you'd like to support without having to use VMs

**Comment by iglstone** [comment]
I met the same error in Ubuntu14.04, ros indigo..

**Comment by iglstone** [comment]
/home/gl/QtCreator-ros/latest/lib/qtcreator/plugins/libROSProjectManager.so: Cannot load library /home/gl/QtCreator-ros/latest/lib/qtcreator/plugins/libROSProjectManager.so: (/home/gl/QtCreator-ros/latest/lib/qtcreator/plugins/libROSProjectManager.so: symbol _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference)

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn What docker image should I start with?

**Comment by gavanderhoorn** [comment]
Ubuntu provides a nr of official images. For Trusty, that would be `ubuntu:trusty` (or `ubuntu:14.04`) and for Xenial `ubuntu:xenial` (or `ubuntu:16.04`). See also [hub.docker.com/ubuntu](https://hub.docker.com/_/ubuntu/).

Perhaps we should discuss this off-line, or in a separate issue?

**Comment by Levi-Armstrong** [comment]
@iglstone @RohanBampal I believe have a working installer generated using docker. Do you mind downloading it [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/qtcreator-ros-trusty-latest-offline-installer.run) and testing it?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn I have been able to get everything to run in the docker but it looks like everything in the mapped directory generated by the docker is root. What is the best way to solve this so it is not generated as root?

**Comment by gavanderhoorn** [comment]
Well .. the 'best way' would probably involve a combination of `-u` and `-v` options, but if you want something simply, just do a `sudo chown $USER: -R .` on the host in the dir that you volume mounted into your Docker container.

**Comment by RohanBampal** [comment]
@Levi-Armstrong I have downloaded and installed the qtcreator-ros using your installer and it opens fine. But on opening a Project, the application closes.
Here is the terminal output: 
```
rohan@rohan:~/QtCreator/latest/bin$ ./qtcreator-ros 
No tool chain set up in kit "Imported Kit" for "C++".
No tool chain set up in kit "Imported Kit" for "C++".
Segmentation fault (core dumped)```

**Comment by Levi-Armstrong** [comment]
I will take a look

**Comment by Levi-Armstrong** [comment]
@RohanBampal  Do you mind the command in the terminal and posting the output?
```
ldd ~/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so
```

**Comment by RohanBampal** [comment]
Here is the output:
```rohan@rohan:~$ ldd ~/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so
	linux-vdso.so.1 =>  (0x00007ffdc0ec8000)
	/usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6d59a6f000)
	libCore.so => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libCore.so (0x00007f6d595a6000)
	libProjectExplorer.so => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libProjectExplorer.so (0x00007f6d58fa3000)
	libCppTools.so => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libCppTools.so (0x00007f6d58be4000)
	libTextEditor.so => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libTextEditor.so (0x00007f6d587d0000)
	libDebugger.so => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libDebugger.so (0x00007f6d582da000)
	libCMakeProjectManager.so => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libCMakeProjectManager.so (0x00007f6d57fcb000)
	libQtSupport.so => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libQtSupport.so (0x00007f6d57cca000)
	libExtensionSystem.so.4 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libExtensionSystem.so.4 (0x00007f6d57a85000)
	libUtils.so.4 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libUtils.so.4 (0x00007f6d576a8000)
	libqtermwidget5.so.0 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libqtermwidget5.so.0 (0x00007f6d573c6000)
	libyaml-cpp.so.0.5 => /usr/lib/x86_64-linux-gnu/libyaml-cpp.so.0.5 (0x00007f6d57146000)
	libQt5Widgets.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Widgets.so.5 (0x00007f6d5690c000)
	libQt5Gui.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Gui.so.5 (0x00007f6d56125000)
	libQt5Core.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Core.so.5 (0x00007f6d559d5000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6d556cf000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6d554b8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6d550ef000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6d5a053000)
	libAggregation.so.4 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libAggregation.so.4 (0x00007f6d54ee9000)
	libQt5PrintSupport.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5PrintSupport.so.5 (0x00007f6d54c7b000)
	libQt5Help.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Help.so.5 (0x00007f6d54a08000)
	libQt5Qml.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Qml.so.5 (0x00007f6d543d7000)
	libQt5Network.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Network.so.5 (0x00007f6d54041000)
	libQt5Sql.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Sql.so.5 (0x00007f6d53df9000)
	libQt5Concurrent.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Concurrent.so.5 (0x00007f6d53bf2000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007f6d5398a000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6d5376c000)
	libQtcSsh.so.4 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libQtcSsh.so.4 (0x00007f6d53312000)
	libCPlusPlus.so.4 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libCPlusPlus.so.4 (0x00007f6d52e8d000)
	libQt5Xml.so.5 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libQt5Xml.so.5 (0x00007f6d52c53000)
	libLanguageUtils.so.4 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libLanguageUtils.so.4 (0x00007f6d52a44000)
	libQmlDebug.so.4 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libQmlDebug.so.4 (0x00007f6d52816000)
	libQmlJS.so.4 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../libQmlJS.so.4 (0x00007f6d52487000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6d52283000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6d5206a000)
	libicui18n.so.56 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libicui18n.so.56 (0x00007f6d51bd1000)
	libicuuc.so.56 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libicuuc.so.56 (0x00007f6d51819000)
	libicudata.so.56 => /home/rohan/QtCreator/latest/lib/qtcreator/plugins/../../Qt/lib/libicudata.so.56 (0x00007f6d4fe36000)
	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f6d4fc34000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f6d4f92c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6d4f724000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f6d4f4fa000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f6d4f2f7000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f6d4f0f4000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f6d4eeee000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f6d4ecec000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f6d4eabe000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f6d4e8ac000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f6d4e6a9000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f6d4e4a3000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f6d4e2a1000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f6d4df6c000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f6d4dd55000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f6d4db50000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f6d4d931000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f6d4d72b000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f6d4d51d000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f6d4d2df000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f6d4d0db000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f6d4ced5000)
```

**Comment by Mylittledream** [comment]
I have the same problem. On opening the QtCreator, this error shows:

/home/rohan/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so: 
Cannot load library /home/rohan/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so: 
(/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by 
/home/rohan/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so))
I am using Ubuntu 14.04. 

Thanks.

**Comment by Levi-Armstrong** [comment]
Everyone, I am working a fix that should solve the issue. I am having to change things a bit to ensure it will work on most Linux distributions. I apologizes for the inconvenience.

**Comment by Levi-Armstrong** [comment]
Great news! with the help from the folks at Qt I have an automated way for packaging Qt Creator with the ROS Plugin for different Ubuntu distributions. I currently rebuilding everything and once the repository is update (Which should be later this afternoon) I will provide an update. Also you should not need to add any ppa's know since everything is package internally to simplify things.

**Comment by Mylittledream** [comment]
Thanks a lot!

**Comment by Levi-Armstrong** [comment]
I just finished repackaging everything for xenial and should be finished with trusty soon. I post a link here when finished until I get the documentation updated.

**Comment by Levi-Armstrong** [comment]
The latest version has been released [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/installers/trusty/) for trusty. Recommend downloading the online installer and let me know if you have any issues.

**Comment by NiclasEvestedt** [comment]
Hi, thanks for the great work! 

I tried installing a few days ago and got the initial problem on my 14.04 machine. I now tried the installer in the link you gave above and now I got even more errors when opening QtCreator. Alot of plugins fail with a similar error to this. 

> Cannot load plugin because dependency failed to load: Debugger(4.5.1)
Reason: Cannot load plugin because dependency failed to load: ProjectExplorer(4.5.1)
Reason: Cannot load plugin because dependency failed to load: TextEditor(4.5.1)
Reason: /home/niclas/QtCreator/latest/lib/qtcreator/plugins/libTextEditor.so: Cannot load library /home/niclas/QtCreator/latest/lib/qtcreator/plugins/libTextEditor.so: (/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/niclas/QtCreator/latest/lib/qtcreator/plugins/libTextEditor.so))

 Here are two images showing all the plugins that failed. 

![screenshot from 2018-03-15 15 22 38](https://user-images.githubusercontent.com/6905833/37494183-f11eaa38-2864-11e8-9ed7-cd41852eaecc.png)
![screenshot from 2018-03-15 15 22 31](https://user-images.githubusercontent.com/6905833/37494184-f40e9f6e-2864-11e8-833d-ed76a7f5339b.png)

Thanks!

**Comment by Levi-Armstrong** [comment]
I thought that might be an issue. You will need to add a few things for trusty. I will see if I can package it into the installer but that may be to big of a pain to pull in all of its dependencies.

```
sudo add-apt-repository ppa:levi-armstrong/qt-libraries-trusty
sudo apt-get update
sudo apt-get install libstdc++-4.9-dev
```

**Comment by Levi-Armstrong** [comment]
I briefly looked into it and I think I may be able to package it in if you don't mind testing it for me later.

**Comment by NiclasEvestedt** [comment]
Thanks! I did not install the missing packages yet so I can do a test tomorrow.

**Comment by Levi-Armstrong** [comment]
@NiclasEvestedt I just uploaded an installer [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/qtcreator-ros-trusty-latest-offline-installer.run) if you don't mind testing?

**Comment by NiclasEvestedt** [comment]
@Levi-Armstrong Thanks! I tried it. I still had the same errors. I also tried to install latest QtCreator without ROS plugin just to make sure I haven't screwed something up. That worked without any errors though.

**Comment by Levi-Armstrong** [comment]
Ok, I switching it to statically link against libstdc++ which should solve the issue. It is running now and should be able to upload a new versions in about an hour.

**Comment by Levi-Armstrong** [comment]
@NiclasEvestedt I just uploaded a new version [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/qtcreator-ros-trusty-latest-offline-installer.run)

**Comment by NiclasEvestedt** [comment]
@Levi-Armstrong Most of the errors are gone. Only one left. QbsProjectManager fails with

> /home/niclas/QtCreator/latest/lib/qtcreator/plugins/libQbsProjectManager.so: Cannot load library /home/niclas/QtCreator/latest/lib/qtcreator/plugins/libQbsProjectManager.so: (/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/niclas/QtCreator/latest/lib/qtcreator/plugins/../libqbscore.so.1.10))

**Comment by Levi-Armstrong** [comment]
Thank you I will see how to fix that one.

**Comment by Levi-Armstrong** [comment]
@NiclasEvestedt I just uploaded a new version [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/qtcreator-ros-trusty-latest-offline-installer.run)

**Comment by Levi-Armstrong** [comment]
@NiclasEvestedt if the new installer still results in the qbs error could you disable the qbs plugin and then see if Qt Creator will load without any other errors?

**Comment by Levi-Armstrong** [comment]
@NiclasEvestedt I test the previouse two and they did not work but the latest one where I package the system libraries with Qt Creator worked. I have tested it on a clean VM but do you mind testing it just to confirm? It can be found [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/qtcreator-ros-trusty-latest-offline-installer.run)

**Comment by Levi-Armstrong** [comment]
The latest version has been released [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/installers/trusty/) for trusty. Recommend downloading the online installer and let me know if you have any issues.

**Comment by Levi-Armstrong** [comment]
@liamstask I just finished the installer for trusty packaging in the libstdc++ so you don't have to upgrade your system. See the comment above. I am currently working on updating the documentation to reflect the changes.

**Comment by NiclasEvestedt** [comment]
@Levi-Armstrong The latest installer works and I have no more errors! Thanks for the great work!

**Comment by Levi-Armstrong** [comment]
Great!
