### ISSUE TITLE
Lost ROS Project

### ISSUE THREAD

**Issue by Lejou** [ros-industrial/ros_qtc_plugin#264]
I don't have the "Import ROS Project"  when I intend to create a new ros project in QT 5.10.0.
I have installed QT5.10.0 and then change the shortcut, then I follow the instruction on 

https://ros-industrial.github.io/ros_qtc_plugin/_source/Improve-ROS-Qt-Creator-Plugin-Developers-ONLY.html

and execute the following codes :

sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial
sudo add-apt-repository ppa:levi-armstrong/ppa
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros

then i change username and version in the file path to match your system
that is all for my installation. but, when I open QT, I can cmake my Project and look through my code except to import ros project as a new project.  For this case, anyone has the solutions?
I'm a newbee for QT, please help me.

**Comment by Levi-Armstrong** [comment]
Sorry missed this issue. Are you wanting to make modification to the plugin or are you just wanting to use it for developing in ROS?

**Comment by Lejou** [comment]
Thank you for you reply! I'm so glad to receive it!  I use it for developing in ROS, and now I'v already solved my problem. Thank you, my friend!
