### ISSUE TITLE
qtcreator-ros-trusty-latest-offline-installer.run

### ISSUE THREAD

**Issue by Mylittledream** [ros-industrial/ros_qtc_plugin#265]
I install the QT Creator(4.5.1).After I install the ros_qtc_plugin.But when I open the catkinxx.workspace,this software will exit.
Please help to solve this

**Comment by Levi-Armstrong** [comment]
I have been working on a solution and should have something in a few days. The ppa is still up so you can use that version until this is resolved.

**Comment by Mylittledream** [comment]
Thanks!
