### ISSUE TITLE
"The following plugins have errors and cannot be loaded"

### ISSUE THREAD

**Issue by yukelele** [ros-industrial/ros_qtc_plugin#266]
Try to install the ROS Qt Creator Plug-in, so I followed the instructions mentioned [here](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html).

When I open qtcreator on the command line using: `qtcreator-ros`
It opens qtcreator, but I get the following message:
_"The following plugins have errors and cannot be loaded:
ROSProjectManager

Details:
/home/lidar/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so: Cannot load library /home/lidar/QtCreator/latest/lib/qtcreator/plugins/libROSProjectManager.so: (libyaml-cpp.so.0.5: cannot open shared object file: No such file or directory)"_

I followed through all of the instructions; however one thing that was different from the pictures in the instructions occurred at "Select Components".
In the picture, it shows "Qt Creator (4.5.1)" & **"ROS Plug-In (0.2.1)"**, but when I installed, it only showed "Qt Creator (4.5.1)". 

Any idea what I did wrong?

**Comment by Levi-Armstrong** [comment]
You are missing libyaml-cpp which is usually installed when installing ROS. You just need to install yaml-cpp version 0.5.

**Comment by Levi-Armstrong** [comment]
I am currently working on packaging libyaml-cpp into the installer so this does not occur anymore.

**Comment by Levi-Armstrong** [comment]
I just finished everything for 16.04 xenial, you can get the installer [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/installers/xenial). Use the online installer. I should have everything for trusty done soon then I will go through and update the documentation.

**Comment by Levi-Armstrong** [comment]
The latest version has been released [here](https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/installers/trusty/) for trusty.

**Comment by Levi-Armstrong** [comment]
New installer for trusty has been released please see [documentation](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html).
