### ISSUE TITLE
I can't install libqtermwidget57-0-dev

### ISSUE THREAD

**Issue by ziqi-zhang** [ros-industrial/ros_qtc_plugin#268]
My system is Ubuntu 16.04 and Qt version is 5.10. I have followed the wiki trying to install the plugin. Here is the command I used.
`sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial
sudo add-apt-repository ppa:levi-armstrong/ppa
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros libqtermwidget57-0-dev`

But libqtermwidget57-0-dev can't be installed because of following reason:

dpkg: error processing archive /var/cache/apt/archives/qtermwidget57-data_0.6.0-0xenial1_all.deb (--unpack):
 trying to overwrite '/usr/share/qtermwidget5/kb-layouts/macbook.keytab', which is also in package qtermwidget5-data 0.6.0+20160108-3
Preparing to unpack .../libqtermwidget57-0_0.6.0-0xenial1_amd64.deb ...
Unpacking libqtermwidget57-0 (0.6.0-0xenial1) ...
dpkg: error processing archive /var/cache/apt/archives/libqtermwidget57-0_0.6.0-0xenial1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libqtermwidget5.so.0.6.0', which is also in package libqtermwidget5-0 0.6.0+20160108-3
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package libqtermwidget57-0-dev.
Preparing to unpack .../libqtermwidget57-0-dev_0.6.0-0xenial1_amd64.deb ...
Unpacking libqtermwidget57-0-dev (0.6.0-0xenial1) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Errors were encountered while processing:
 /var/cache/apt/archives/qtermwidget57-data_0.6.0-0xenial1_all.deb
 /var/cache/apt/archives/libqtermwidget57-0_0.6.0-0xenial1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ziqi-zhang** [comment]
I tried to uninstall 5.10 and install 5.7 only to failed to address this problem

**Comment by Levi-Armstrong** [comment]
I have moved to using an Qt Installer please see the documentation [here](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html) on how to install going forwards.

**Comment by ziqi-zhang** [comment]
@Levi-Armstrong 
Thanks! I have done installing it.

**Comment by ziqi-zhang** [comment]
@Levi-Armstrong 
Sorry I still have some questions.
Firstly, can you please tell me what's the difference between Qt4.5 plugin and Qt5.7 plugin? I saw some installation documents of Qt5.7 but your link is about Qt4.5
Secondly, how can I use Qt libraries in ROS? I followed the installation instructions in the link and I think it's a great interface to develop ROS. But I don't know how to introduce Qt libraries such QMutex and QThread into ROS node. Should I add something into CMakeLists?
Thank you very much!

**Comment by Levi-Armstrong** [comment]
>Firstly, can you please tell me what's the difference between Qt4.5 plugin and Qt5.7 plugin?

The Qt5.7 was Qt Creator build using Qt libraries version 5.7. The Qt 4.5 is the version of Qt Creator. The currently version of Qt Creator is 4.5 which I have built using Qt Libraries version 5.10.

>Secondly, how can I use Qt libraries in ROS? I followed the installation instructions in the link and I think it's a great interface to develop ROS. But I don't know how to introduce Qt libraries such QMutex and QThread into ROS node. Should I add something into CMakeLists?

You will need to the libraries to your CMakeLists file. I would take a look at some of the other ros packages using Qt like rviz or any of the other rviz plugins. Here is one of my [packages](https://github.com/Levi-Armstrong/urdf_builder/blob/master/urdf_editor/CMakeLists.txt)  that uses qt libraries.

**Comment by ziqi-zhang** [comment]
Thank you very much!
