### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by nathangeorge1** [ros-industrial/ros_qtc_plugin#273]
Hi @Levi-Armstrong ,

I'll use this issue to track the video making process, as opposed to the other closed issue we were talking in. I created all the videos today. Soon (hopefully tomorrow) I'll edit them and start the PR.

For my additions, I'd like to:
1. On the homepage of the wiki, move video tutorials to Installation and then replace your 2 videos with mine by editing gh_pages/index.rst, running `make html`, and then pushing the code to a branch.
2. Edit the README to include the video.

Let me know if that works,
Nathan

**Comment by Levi-Armstrong** [comment]
So you want to move Videos below the Install, Section order (Install, Videos, FAQ, etc)? If so, that is fine with me.

Also, it may be good to keep the older videos as reference we could just mark them as outdated or add another section at the bottom "Other References"

You will not need to run `make html` and push the results, just push the changes to the rst files because I will run another script on the main branch which builds documentation for all branches and creates a single GitHub Page. I will do this after the PR has been merged.

Do you plan to push the videos to the repository?

**Comment by nathangeorge1** [comment]
I was hoping to put the videos in the "Install" section because it's an installation video. I thought headings should be based on content, not what they are, in the sense that "Install" is what you do with it but "video" is what it actually is; so having a video section might confuse people (it did for me when I was first starting).

My experience from beginners in ROS is that deprecated information confuses them more than it helps (did for me too), but if you think otherwise, than "Other References" makes sense.

Ok; I will only change the files index.rst and README.txt. Yes, I was planning to push the video to the repo.

**Comment by gavanderhoorn** [comment]
@nathangeorge1 wrote:
> Yes, I was planning to push the video to the repo.

may I suggest to try and host them somewhere else?

Videos are large, binary files that are essentially opaque blobs to git. It doesn't make much sense to me to store them in a repository.

**Comment by Levi-Armstrong** [comment]
I agree, if you could email them to me I could host then on the same server that the installers are on.

**Comment by nathangeorge1** [comment]
Oh ok; I forgot about that; sure when it's done, I'll email it to you

**Comment by nathangeorge1** [comment]
how do I find your email @Levi-Armstrong? The installation video is finished

**Comment by nathangeorge1** [comment]
Hey @Levi-Armstrong, I sent the video to your email. Let me know how I should link the video to the PR in my fork.

**Comment by Levi-Armstrong** [comment]
@nathangeorge1 I watched the video and it looks great and thank you for taking the time to create it. I wanted to get your opinion on one thing. Usually we try to keep tutorial videos to less than 3 minutes and maybe @shaun-edwards and @gavanderhoorn could provide more details on why. I believe there is data available that suggest anything longer people loose patients and it becomes difficult to find particular item in the video. It may be better to break the video you have already created into a series of videos using some editing software, what are your thoughts?

**Comment by nathangeorge1** [comment]
Ya that makes sense. I'll try to divide the video into chunks <3 min and resend to your email.

**Comment by Levi-Armstrong** [comment]
I apologize, I have been getting ready for a demo. I will take a look on Thursday.

**Comment by nathangeorge1** [comment]
PR made

**Comment by nathangeorge1** [comment]
I see that the PR is approved; is there another step for me to do so the PR can be merged?
