### ISSUE TITLE
Cannot compile catkin_ws inside QT

### ISSUE THREAD

**Issue by JaFEKl** [ros-industrial/ros_qtc_plugin#274]
Hi everyone,
I'm trying to use the ros_qtc_plugin to simplify my working with ROS.
I followed the steps on how to import an existing catkin workspace from here: https://github.com/Levi-Armstrong/ros_qtc_plugins/wiki/Setup-Qt-Creator-for-ROS and set up the build settings like explained.

I followed each step carefully, but when I want to start building my workspace I get the following error:

`14:23:41: Running steps for project catkin_ws...
14:23:41: Starting: "/opt/ros/kinetic/bin/catkin_make" -DCMAKE_BUILD_TYPE=Debug
Base path: /home/janfelix
The specified source space "/home/janfelix/src" does not exist
14:23:41: The process "/opt/ros/kinetic/bin/catkin_make" exited with code 1.
Error while building/deploying project catkin_ws (kit: Desktop)
When executing step "Custom Process Step"
14:23:41: Elapsed time: 00:00.`
Using catkin_make from my terminal executes fine.

I don't know why, but the base path is set wrong. 
![screenshot from 2018-04-10 14-26-20](https://user-images.githubusercontent.com/38248337/38554427-420adad2-3ccb-11e8-8c59-d1f0aac6d27c.png)

![screenshot from 2018-04-10 14-27-52](https://user-images.githubusercontent.com/38248337/38554458-610e2844-3ccb-11e8-869e-f7e110b66ec5.png)

**Comment by danneboom** [comment]
Two solutions:
1) specify the catkin_ws path in your applications .desktop file 
Path=/home/yourname/catkin_ws
2) open ROS Workspace using
File->New File or Project -> Other Project -> ROS Workspace -> choose -> Choose name, distribution, CatkinMake and Path of your catkin_ws -> next -> ... -> finish

**Comment by iman01** [comment]
> Two solutions:
> 
> 1. specify the catkin_ws path in your applications .desktop file
>    Path=/home/yourname/catkin_ws
> 2. open ROS Workspace using
>    File->New File or Project -> Other Project -> ROS Workspace -> choose -> Choose name, distribution, CatkinMake and Path of your catkin_ws -> next -> ... -> finish
> 
> I strongly recommend the second as it recognizes the workspace as a ROS workspace - the build-Section will be different!

solved my problem, thanks
