### ISSUE TITLE
How to set ros project CMakeLists file to find qt59's modules?

### ISSUE THREAD

**Issue by sunyuzhe2017** [ros-industrial/ros_qtc_plugin#276]
Ubuntu 16.04,ros kinetic
I created  a  project with 'catkin_create_qt_pkg'command ,then the CMakeLists file is build with QT4,like this:
`rosbuild_prepare_qt4(QtCore QtGui) `and so on ,which qt modules were located at "/usr/include/qt4"
I change the CMakeLists file to qt5,like follow sentences:
```
cmake_minimum_required(VERSION 2.8.0)
project(test1)
set(CMAKE_INCLUDE_CURRENT_DIR ON)#added necessary
##############################################################################
# Catkin
##############################################################################

# qt_build provides the qt cmake glue, roscpp the comms for a default talker
find_package(catkin REQUIRED COMPONENTS roscpp)
find_package(Qt5 REQUIRED Core Widgets)#added
set(QT_LIBRARIES Qt5::Widgets)#added
include_directories(${catkin_INCLUDE_DIRS})

# Use this to define what the package will export (e.g. libs, headers).
# Since the default here is to produce only a binary, we don't worry about
# exporting anything. 
catkin_package()
##############################################################################
# Qt Environment
##############################################################################
# this comes from qt_build's qt-ros.cmake which is automatically 
# included via the dependency call in package.xml
#rosbuild_prepare_qt4(QtCore QtGui) # Add the appropriate components to the component list here
##############################################################################
# Sections
##############################################################################
file(GLOB QT_FORMS RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} ui/*.ui)
file(GLOB QT_RESOURCES RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} resources/*.qrc)
file(GLOB_RECURSE QT_MOC RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} FOLLOW_SYMLINKS include/test1/*.hpp)

QT5_ADD_RESOURCES(QT_RESOURCES_CPP ${QT_RESOURCES})
QT5_WRAP_UI(QT_FORMS_HPP ${QT_FORMS})
QT5_WRAP_CPP(QT_MOC_HPP ${QT_MOC}) `
```
then I find that the Qt modules path changed to "/usr/lib/x86_64-linux-gnu/qt5",still it wasn't from qt59 (/opt/qt59),how could I change the CMakeLists file to make cmake find qt modules from /opt/qt59?

I have tried to create a Qt  Widgets Application project ,the file module is from /opt/qt59,however,when I create a ros project with qt GUI,the path was wrong,so I guess this must be something different with the qt version used by ros.
Could you change the ros_qtc_plugin to build the ros project with qt59?or could you give me some advices about  how to change the CMakeLists file to make it find qt59's(/opt/qt59) modules but from /usr/lib/x86_64-linux-gnu/qt5 or /usr/include/qt4?

**Comment by Levi-Armstrong** [comment]
I recommend reinstalling because new versions are distributed using a Qt Installer which should solve this issue. I recommend removing all of the `/opt/qt59` described in the wiki.

[Wiki](https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html)

**Comment by sunyuzhe2017** [comment]
I have tried reinstall as "Xenial Online Installer (Recommended)" this one.It doesn't work.So it's not the plugin's matter,the CMakeLists file was created by "catkin_create_qt_pkg",it must be the command's matter.I'll find other solutions,thanks any way.
By the way,after I reinstalled by Qt Installer,I find 'Help' problem when start QtCreator.There  is no help for qt,this problem never happen when I used the ppa.so I need to change back to the ppa.I don't konw if it is Qt Installer's problem.Thanks.
![help](https://user-images.githubusercontent.com/33214493/40164585-9567e696-59ec-11e8-8272-d8f9c331da19.png)
