### ISSUE TITLE
#include<ros/ros.h> (no such file or directory)

### ISSUE THREAD

**Issue by MrYelameli** [ros-industrial/ros_qtc_plugin#278]
I followed these steps to install qt ros plugin [https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html](url) 

After that these steps to create a workspace https://ros-industrial.github.io/ros_qtc_plugin/_source/Import-ROS-Workspace.html 

I created a node.  You can see first line red underline. It says ros/ros.h No such file or dirctory. 
Could you help me? I cross checked many times I think I followed all the steps. 

![screenshot from 2018-05-18 03-54-12](https://user-images.githubusercontent.com/11991052/40154616-03c72db2-5944-11e8-98b9-89ed4933290a.png)

**Comment by Levi-Armstrong** [comment]
I would take a look at the FAQ section on the wiki.

[Warning this file is not part of any project](https://ros-industrial.github.io/ros_qtc_plugin/_source/FAQ.html#warning-this-file-is-not-part-of-any-project)
