### ISSUE TITLE
New ROS files customization 

### ISSUE THREAD

**Issue by cgkournelos** [ros-industrial/ros_qtc_plugin#279]
Is it possible somehow to customize the templates for the new files  (Basic node, CMakeLists.txt, etc.) ?

**Comment by Levi-Armstrong** [comment]
Yes, are interested in added them to the repository or just to for your use? [Here](https://github.com/ros-industrial/ros_qtc_plugin/tree/4.5/share/templates/wizards) are the currents ones which can be used as a guide. I have added them before to an already installed version but it has been a while. I will test it and then update on how I added them to an already installed version.

**Comment by klapetos** [comment]
I don't know. I just thought that it would be a good feature to be able to customize these template file according to your personal preference.

**Comment by Levi-Armstrong** [comment]
Ok, so depending on where you install your version you should be able to place them in this location. You will see the current ones available that are added using the json method which should be a good guide. 

~/QtCreator/latest/share/qtcreator/templates/wizards/files
