### ISSUE TITLE
Cannot extend ROS workspace

### ISSUE THREAD

**Issue by iohanaan** [ros-industrial/ros_qtc_plugin#280]
I want to extend default ROS workspace (/opt/ros/kinetic) with my own workspace. How can I do this with plugin?
For example: I have one workspace with SDK, which located in another directory instead of /opt/ros. And I want to create new workspace with examples, which should load sdk workspace and ros workspace.

Also I use catkin_make and can't migrate to catkin tools

**Comment by Levi-Armstrong** [comment]
You need to prepend the CMAKE_PREFIX_PATH environment variable with the path to your other workspace.  I think you can provide cmake arguments -E env NAME=VALUE but have never tested it.

**Comment by iohanaan** [comment]
I provided next cmake arguments: -DCMAKE_PREFIX_PATH=VALUE
and it's works, thanks
