### ISSUE TITLE
Issue with Indenting in C++

### ISSUE THREAD

**Issue by nprof50** [ros-industrial/ros_qtc_plugin#281]
First off, thank you for all the hard work on this plugin. Qt has been my go-to IDE for ROS development since I discovered this existed.

In regards to the problem, I have two C++ workspaces. The first workspace is completely fine with regards to indentation (single 4-spaced tab indent). However, the second workspace seems to be ignoring the 4-spaces-per-tab indent style I've defined in the settings. It's stuck indenting only 2 spaces. The main difference I'm seeing between the files in workspace 1 & 2 is that workspace 1 gives me no warnings at the top of the file. Workspace 2 seems to have a recurring warning for every file:

"Warning: This file is not part of any project. The code model might have issues to parse this file properly."

The files are all added in the add_directories step in the CMakeLists.txt and I have run catkin_make using Qt's build system. I noticed on the FAQ for this plugin that this warning can be persistent and can be ignored, but it seems to be the only defined difference that would cause the second workspace to indent so weirdly. Is there anything I can do to fix this? I'd be happy to provide more information if needed.

**Comment by Levi-Armstrong** [comment]
Hello,

I am glad you like the IDE plugin. Are you using the latest which is installed using a Qt Installer? Also when creating/importing a new workspace the style is set at the project level. So if you make your workspace active, by right clicking on it and setting it as active. Then click on the project tab on the left then there is a gray text *Code Style* select it and then set the style guide for the project. It by default is set the ROS style guide which is 2 spaces. I hope this helps. 

Also if you have multiple workspace open in a single Qt Creator you must activate it prior to selecting build which may be why the warning is showing up but ignore if you are already aware of this. I just want  to give you as much information as possible to help resolve the issue.

**Comment by nprof50** [comment]
Man you hit the nail on the head! I hadn't had the right code style selected for that project. I thought it wasn't something that was set per-project. Thank you so much for your help!
