### ISSUE TITLE
Install for Arm architecture

### ISSUE THREAD

**Issue by nathangeorge1** [ros-industrial/ros_qtc_plugin#282]
Hello,

Can this plugin be installed on an Arm board, like the Jetson TX1?

I tried to run the .run installer, but got 
`bash: ./qtcreator-ros-xenial-latest-online-installer.run: cannot execute binary file: Exec format error`

Thanks,
Nathan

**Comment by Levi-Armstrong** [comment]
No would need to build from source. I believe the recommend approach is to use the deploy feature when using Qt Creator to develop on an Arm board.

**Comment by nathangeorge1** [comment]
Interesting; I'll look into it; have you done embedded deployment before or know of any good resources?

**Comment by nathangeorge1** [comment]
sorry; should've googled this first: https://www.jetsonhacks.com/2017/01/31/install-qt-creator-nvidia-jetson-tx1/
