### ISSUE TITLE
Qt Creator crashes when creating a new package

### ISSUE THREAD

**Issue by yangshiliang** [ros-industrial/ros_qtc_plugin#284]
Environment:
OS: Ubuntu 16.04
Installer: qtcreator-ros-xenial-latest-offline-installer.run (20180629)
About Qt Creator: Qt Creator 4.5.1 Based on Qt 5.10.0 (GCC 4.9.3, 64 bit)

Reproduce steps:
1. Start Qt Creator from command line: qtcreator-ros
2. With NO ROS workspace opened, click File > New File or Project...
3. Click ROS > Package > Choose
4. Qt Creator crashes.
The crash message is as follows:
[1]    3330 segmentation fault (core dumped)  qtcreator-ros

However, this issue does not occur for the installer "qtcreator-ros-trusty-441-offline-installer.run".

Workaround:
1. Open a ROS workspace.
2. New a package. Everything is fine.

**Comment by Levi-Armstrong** [comment]
Thank you for the feedback. I need to add a check that make sure the user has a workspace loaded before allowing them to add a new package.

**Comment by harryman1** [comment]
I have the same issue, could you please indicate when a pacth will be released for this problem, please

**Comment by Levi-Armstrong** [comment]
This should be addressed by PR #305.
