### ISSUE TITLE
Run configuration for debug

### ISSUE THREAD

**Issue by martinakos** [ros-industrial/ros_qtc_plugin#286]
If I create a run configuration with ROS Launch Step and I press the debug arrow, qtcreator builds the packages in the workspace and shows the dialog below 
![image](https://user-images.githubusercontent.com/2371869/42944908-d7c53496-8b5e-11e8-8d29-944650d6fa0d.png)

If I create the run configuration with ROS Attach to Node and select the package, node and tick Continue on attach, as in the image below:
![image](https://user-images.githubusercontent.com/2371869/42945241-c4984e48-8b5f-11e8-838c-32b1bf1f3b57.png)

then press the debug row, qtcreator builds the workspace but doesn't launch anything. 

How am I meant to use these run configurations to launch a node for debugging?

Notice I can start my node externally and attach the debugger to it successfully.

**Comment by Levi-Armstrong** [comment]
Did you have both the rosrun step and the debug step?

**Comment by cristea** [comment]
I have the same behavior. Maybe I should have asked here first :) 
[](https://answers.ros.org/question/289819/debugging-using-ros-qt-creator-plugin/)

**Comment by nathangeorge1** [comment]
If it matter, trying to [attach to unstarted process](https://ros-industrial.github.io/ros_qtc_plugin/_source/Debugging-Catkin-Workspace.html) gives me:

`poll failed with error Interrupted system call`

**Comment by martinakos** [comment]
I have tried a roslaunch step and then a ros attach to node step as in the figure below

![image](https://user-images.githubusercontent.com/2371869/43156602-85577c4c-8f72-11e8-9da4-5dd4a625d696.png)

It builds and starts the voxblox node. However, it doesn't hit any breakpoints. Then if I "attach to a running application..." it attaches and stops at the break points.

**Comment by Levi-Armstrong** [comment]
You are using it correctly and I have experience this recently myself so I will mark this as bug.

**Comment by Levi-Armstrong** [comment]
Also in the case of attaching to a process you will need to add a sleep at the beginning of the node to allow enough time for the debugger to attach. This is is suppose to do the same thing as manually attaching to a process so it also will require a sleep.

**Comment by atleaa** [comment]
First of all, very nice work on the plugin.
Are there any updates on this issue? I have a similar setup as described by martinakos and debugging does not start automatically (even with sleep). My current workaround is to use Attach to Running/Unstarted Application...

**Comment by Levi-Armstrong** [comment]
Use the standard qt creator Attach to running application or unstated application mention by @atlas for now until the bug is resolved.

**Comment by Levi-Armstrong** [comment]
@mptangtang @atleaa I uploaded a new version that has not been publicly announced. The offline installers have been uploaded [here](https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.3.2) and wanted to see if either of you could test this version out and see if it solves the issue. Once confirmed I will push the online installer so everyone gets notified of a new release.

**Comment by Reinbert** [comment]
I just installed and tried https://github.com/ros-industrial/ros_qtc_plugin/releases/download/0.3.2/qtcreator-ros-xenial-latest-offline-installer.run and it works for me. Thank you.

**Comment by cslxiao** [comment]
the latest release still doesn't work

**Comment by Levi-Armstrong** [comment]
What is not working for you?
