### ISSUE TITLE
Clicking "Help" Crashes Qt Creator

### ISSUE THREAD

**Issue by nathangeorge1** [ros-industrial/ros_qtc_plugin#289]
Clicking the "Help" button in the left sidebar always crashes Qt Creator. I remember there were some other buttons crashing it too. Is this something to ask here or in the Qt bug tracker?

**Comment by Levi-Armstrong** [comment]
Fixed in the latest version. Download the latest installer.

**Comment by OrHirshfeldFFR** [comment]
I already have an older version and have the same problem.

I was wondering if I should remove the old version and install from scratch or I can use the installer to update my current version. 

I changed some settings in Qt-Creator and I prefer to keep them.
