### ISSUE TITLE
Installer download links not working

### ISSUE THREAD

**Issue by inspire1989** [ros-industrial/ros_qtc_plugin#290]
Hi,
the server at https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/installers/xenial/ isn't responding. Could you upload the latest version of the installer somewhere else? Thanks in advance!

**Comment by Levi-Armstrong** [comment]
I will look into this.

**Comment by Levi-Armstrong** [comment]
It is back up and operational.

**Comment by inspire1989** [comment]
thanks! :)
