### ISSUE TITLE
"Run::SettingsDeployment::Files to deploy" is always empty for Catkin project

### ISSUE THREAD

**Issue by jabobian** [ros-industrial/ros_qtc_plugin#294]
Hi. 

It is easy to do local build and debug with the ros_qtc_plugin. But it is more useful to deploy the project to a remote host (e.g. IPC, embedded boards etc) and debug on from a client (e.g. Laptop).

For convenience, when start a project, I choose "New project" rather than open the CMakeLists.txt file, This will generate "ProjectName.workspace" and "ProjectName.workspace.user" for storing project settings. 
By using install() macros in the CMakeLists.txt, I can get the install space updated by build the project, but it is noted that the "Run::SettingsDeployment::Files to deploy" table is always empty, so the followed "Create tarball" "Upload file via SFTP" could do nothing. I tried to find the place to modify the table of "Run Settings :: Deployment :: Files to deploy" but failed.

On the other hand, the QT Creator [website](http://doc.qt.io/qtcreator/creator-deployment-embedded-linux.html) mentioned using .pro file and QTCreatorDeployment.txt, but even I can a generateQTCreatorDeployment.txt, there is no .pro file in my project, and our qtc_Catkin Project won't recognize the file.

Could anyone pls tell me how to let the "Files to deploy" module to include the files listed in the install() macro?

I guess I can create a tarball myself, and upload it, or use scp to upload all the install files.
But there must be some better approach, could you shed some light?
Many thanks!

**Comment by jabobian** [comment]
the QT Creator website (http://doc.qt.io/qtcreator/creator-deployment-embedded-linux.html) said

Qt Creator cannot extract files to be installed from a CMake project, and therefore, only executable targets are automatically added to deployment files. You must specify all other files in the QtCreatorDeployment.txt file that you create and place in either the root directory of the CMake project or the build directory of the active build configuration. Currently, Qt Creator first checks the root directory and only if no QtCreatorDeployment.txt exists it checks the active build directory.

**Comment by christian-rauch** [comment]
Please try again with the newest version and reopen this issue if the problem still exists.
