### ISSUE TITLE
plugin enforces tabsize of 2

### ISSUE THREAD

**Issue by christian-rauch** [ros-industrial/ros_qtc_plugin#295]
I am using the QtCreator + ROS plugin installed via the *.run installer.
It appeasrs to me that chaning the code style in the options has no effect. E.g. the tabsize is set to 2 spaces, even though I set it to 4 in the `Edit Code Style` in a copied `ROS [built-in]` style.
There are no problems setting the style in a regular installation of QtCreator.

Is the C++ style hard coded in the plugin?

**Comment by Levi-Armstrong** [comment]
It is set at the project level. Look under Project>Code Style.

**Comment by christian-rauch** [comment]
Have project level settings precedence over global settings? It is confusing that there is no hint in the settings dialog and that the settings have no effect.
