### ISSUE TITLE
"This file is not part of any project" Qt C++ project help

### ISSUE THREAD

**Issue by DrSocha** [ros-industrial/ros_qtc_plugin#299]
Hi,

I'm new here. I created this account because I'm desperate. I installed Qt Project  5.11.2 - MSVC 2017 64-bit and Qt Creator 4.x CDB Debugger Support tool only for my school C++ projects.

No matter what I do when I create a new project(New project -> Non-Qt Project -> Plain C++ Application) I get this message and can't do anything with my work. I can't build and run the application whats the main thing to do here. It says "This file is not part of any project. The code model might have issues to parse this file properly." . I'm sure I have to configure it somehow or add some kits but I'm clueless. I also added a picture.
I would kindy ask someone for the help, even step by step what do I have to do since I don't know what I'm doing. This whole programming scene is new for me and I can't even work and learn. For any help I'm very grateful. 

Picture: https://prnt.sc/l6hb1o

(I'm sorry if I chose wrong thread)

Regards,
DrSocha

**Comment by gavanderhoorn** [comment]
Two questions:

 1. are you actually using the ROS Qt Creator plugin or just Qt Creator itself?
 1. I see this:

      >  I installed Qt Project 5.11.2 - MSVC 2017 64-bit

     are you running Windows?

If you'd answer "no; yes", then I don't believe this is the correct tracker.

This project is a *plugin* for Qt Creator. It's not a support channel for Qt Creator itself.

**Comment by Levi-Armstrong** [comment]
No response.
