### ISSUE TITLE
wrong linking of header files

### ISSUE THREAD

**Issue by rhaschke** [ros-industrial/ros_qtc_plugin#30]
When clicking on header files, QTC opens headers from the underlay (e.g. /opt/ros).
Probably include directories are not setup correctly.

**Comment by Levi-Armstrong** [comment]
Is this a newly created workspace or did you open an existing workspace?

**Comment by Levi-Armstrong** [comment]
I assume you are doing development on a package that is installed in the /opt/ros, please take a look in the .workspace file and let me know if there is duplicate include paths for the package.

**Comment by rhaschke** [comment]
Indeed, `/opt/ros/indigo/include` was listed as the very first include directory, overriding the local ones in the workspace. Manually moving the system directories to the end, solved that issue. Probably you need to rework the ordering of directories.

**Comment by Levi-Armstrong** [comment]
OK, Glade to hear. I will work on a fix.

**Comment by Levi-Armstrong** [comment]
@rhaschke, Would you mind testing pull request #31 which should address this issue.

**Comment by rhaschke** [comment]
>@rhaschke <https://github.com/rhaschke>, Would you mind testing pull 
request #31 <https://github.com/ros-industrial/ros_qtc_plugin/pull/31> 
which should address this issue.

I will do that as soon as I have some spare time. Probably not before 
next week.

**Comment by Levi-Armstrong** [comment]
@rhaschke, The change was merged, when you have time let me know if this resolves the issue.

**Comment by rhaschke** [comment]
This seems to work now. Include directories are sorted.
