### ISSUE TITLE
Not Compiling Node .cpp files

### ISSUE THREAD

**Issue by TDurham123** [ros-industrial/ros_qtc_plugin#300]
Ubuntu 16.04 64bit
QtCreator 5.7.1

Installed plugin as per https://ros-industrial.github.io/ros_qtc_plugin/_source/How-to-Install-Users.html
Able to start a new project, add a package and build without issue. The problem is when I add a node and rebuild, the node.cpp file is not compiled. I can fix the issue by manually adding the following lines to my CMakeLists.txt file;

add_executable(my_node my_node.cpp)
target_link_libraries(my_node ${catkin_LIBRARIES})

then everything builds corectly. Seems like there's something very simple I am missing. Any thoughts?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn is correct, currently the onus is on the developer to edit the CMakeLists.txt.

**Comment by TDurham123** [comment]
It would know what to add the same way I did, from the project file. I was under the impression that the purpose of the plugin was to create packages and the nodes they contain. Please excuse my ignorance, I am a long time Qt application developer, but new to ROS.

**Comment by gavanderhoorn** [comment]
> It would know what to add the same way I did, from the project file.

that would need quite some awareness of what is in the project file (which should be already there) and what is in the `CMakeLists.txt`.

As `CMakeLists.txt` are typically written by humans (at least in typical ROS pkgs) and can be quite intricate (and often times order of statements matters), that would probably make inserting statements into one while keeping track of everything in there and making sure not to break what's already there rather complicated and error prone.

If the plugin was in complete control of everything it would probably be less difficult: there would be no humans that could create arbitrary `CMakeList.txt` and any changes that would be lost would be "the fault" of the human.

But as most ROS packages are typically imported from somewhere external, the plugin is not in control, so it cannot make any assumptions, leading to what I described earlier.

I could be wrong and this could be easily solvable in the Qt world, with which I, admittedly, have little experience.

If you do see an easy way to do this while keeping the rest in mind, please suggest one.
