### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by kargarisaac** [ros-industrial/ros_qtc_plugin#301]
Hello,
I'm new in qtcreator. I want to work with ros. I installed qtcreator-ros using the tutorial but when I want to run it in terminal using qtcreator-ros command it gives me the following error:
Segmentation fault (core dumped). 
I don't understand I installed it correctly or not. Should I first install qtcreator and then add ros to it or I have to remove qtcreator completely? first I removed it and installed again using the tutorial but got the same error.

**Comment by Levi-Armstrong** [comment]
It installs everything into a self contained directory so it should have what it needs. What version of Ubuntu are you working with?

**Comment by Levi-Armstrong** [comment]
Where you able to resolve the issue?

**Comment by Levi-Armstrong** [comment]
No response!
