### ISSUE TITLE
Warning: Failed to source workspace because this file does not exist:  "/home/shen/test"

### ISSUE THREAD

**Issue by Zhangpeishen** [ros-industrial/ros_qtc_plugin#308]
Hello, I am using ubuntu 18.04 and melodic and just start.
When I follow the instruction and try to new a project, there is no CMakeList file under my /src. There are only three files like `test/test.workspace` and `test/src`.
Also the terminal will warn that 
`Warning: Failed to source workspace because this file does not exist:  "/mydir/test"`
I am not sure did I create a project correctly or not.
If I ignore it and go on, I meet another problem that is all my header files would be underlined with yellow, it seems to be a common issue, I also read the FAQ `Warning: This file is not part of any project.?` part, but I cannot find some solutions to figure it out. Please some body explain more in detail?

**Comment by Levi-Armstrong** [comment]
The warning has "/mydir/test" but your issue title has "/home/shen/test" mentioned. Did you change the warning message when adding it to the comment?

Also is `/home/shen/test` a ros workspace?

This `Warning: This file is not part of any project.?` warning will exist until the workspace has successfully built within Qt Creator. Have you built the workspace?

**Comment by Zhangpeishen** [comment]
> The warning has "/mydir/test" but your issue title has "/home/shen/test" mentioned. Did you change the warning message when adding it to the comment?
> 
> Also is `/home/shen/test` a ros workspace?
> 
> This `Warning: This file is not part of any project.?` warning will exist until the workspace has successfully built within Qt Creator. Have you built the workspace?

Thank you for the reply.
I just want to hide my path by a fake one, however, it seems stupid now...
/home/shen/test is the real path.
Actually, at first, I tried to create the workspace within Qt Createor in an exist ROS workspace, it showed the same fail warning. So I create a totally new workspace within Qt Creator just like what has the tutorial video done(Click browse and create a new file within Qt Creator and select Melodic, and Catkin Tools and set name as "test" then click next till done). Then I got into this situation what I posted...

**Comment by Levi-Armstrong** [comment]
So I looked into the warning message and found that the message is incorrect see #310. The warning message is just a warning and is common when creating a new workspace because there is no devel directory and the setup.bash for the workspace does not exist. Once a package is included in the workspace and built you should not receive this message again unless the workspace has been cleaned. In your newly created workspace add a package to the src directory and built the workspace and warning should go away.

**Comment by Zhangpeishen** [comment]
> So I looked into the warning message and found that the message is incorrect see #310. The warning message is just a warning and is common when creating a new workspace because there is no devel directory and the setup.bash for the workspace does not exist. Once a package is included in the workspace and built you should not receive this message again unless the workspace has been cleaned. In your newly created workspace add a package to the src directory and built the workspace and warning should go away.

Thank you! I will try it now

**Comment by Zhangpeishen** [comment]
> So I looked into the warning message and found that the message is incorrect see #310. The warning message is just a warning and is common when creating a new workspace because there is no devel directory and the setup.bash for the workspace does not exist. Once a package is included in the workspace and built you should not receive this message again unless the workspace has been cleaned. In your newly created workspace add a package to the src directory and built the workspace and warning should go away.

Hello Levi, another problem is my header files are underlined by yellow, and when I build, the terminal will notice me no flags.make. I would to attach the screen shot:
![image](https://user-images.githubusercontent.com/32186472/49202883-46ccca80-f3fa-11e8-9b25-e50969b5c3bf.png)

![image](https://user-images.githubusercontent.com/32186472/49202895-4df3d880-f3fa-11e8-9e83-04eb667a2351.png)

What shoud I do? Did I miss something from the tutorial? Sorry for asking such silly questions...

**Comment by Levi-Armstrong** [comment]
So the cmake flags warning is common because not every package will have one generated but I would need to take a look at the CMakeLists file. Is this package somewhere I can clone it down?

Also which version are you using 4.5 or 4.8?

**Comment by Zhangpeishen** [comment]
> So the cmake flags warning is common because not every package will have one generated but I would need to take a look at the CMakeLists file. Is this package somewhere I can clone it down?
> 
> Also which version are you using 4.5 or 4.8?

Please check this address.
https://github.com/Zhangpeishen/ROS_Qt 

My version is 4.5
Thank you very much!

**Comment by Levi-Armstrong** [comment]
I was able to get it to build on my machine by make a few changes.

In move.cpp:
comment out these line:
``` cpp
#include <QWidget>
#include "move.ui"
```

In CMakeLists.txt
Commnet out this line:
``` bash
  INCLUDE_DIRS include
```

Change this:
``` bash
 add_executable(move src/zetch_move.cpp)
```
to:
``` bash
 add_executable(move src/move.cpp)
```
