### ISSUE TITLE
Installation Video Server not reachable

### ISSUE THREAD

**Issue by nathangeorge1** [ros-industrial/ros_qtc_plugin#313]
clicking the link to the installation video gives an error

https://aeswiki.datasys.swri.edu/qtcreator_ros/downloads/tutorials/videos/introduction/

**Comment by Levi-Armstrong** [comment]
The videos have also moved and it looks like a missed a hyperlink. Where was this located?

**Comment by nathangeorge1** [comment]
as far as I know, you stored them at the aeswiki link, linked above

**Comment by nathangeorge1** [comment]
cool; I'll make a PR at some point

**Comment by nathangeorge1** [comment]
Definitely should've done this earlier; but now it'll be a priority.

I just noticed that the link you sent is only the first video. Is there a link to the other videos?

**Comment by nathangeorge1** [comment]
@Levi-Armstrong any update on this?

**Comment by Levi-Armstrong** [comment]
Paste the link in the browser and remove the filename and it should take you to the folder with all videos.

**Comment by nathangeorge1** [comment]
see #331

**Comment by nathangeorge1** [comment]
thanks
