### ISSUE TITLE
Automatically generate setup run file

### ISSUE THREAD

**Issue by AustinDeric** [ros-industrial/ros_qtc_plugin#315]
Issue:

Currently, the qt setup script is manually generated and located here:
https://ros-qtc-plugin.readthedocs.io/en/latest/_source/How-to-Install-Users.html

This process should be automated and the file should served from guthub.

Proposed Solution:

The travis pipeline can be made to automatically generate the .run file.

**Comment by Levi-Armstrong** [comment]
Currently discussing this in #364

**Comment by christian-rauch** [comment]
The recommended "installer" is now the snap package.
