### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by lucascoelhof** [ros-industrial/ros_qtc_plugin#317]
Hi all,

First of all, thanks for making this available! It's been very helpful.

I had some installation issues. I'm running Ubuntu 14.04 on a virutal machine (legacy software running ROS Indigo, working right now to migrate to Melodic). First of all, the Installation Guide link on the readme is broken and leads to a 404 error:
![image](https://user-images.githubusercontent.com/6393076/51032468-42fa9f00-1587-11e9-8071-4b1bfd5373a5.png)
However, I was able to find a installation guide [here
](https://ros-qtc-plugin.readthedocs.io/en/latest/)

Then, I followed the guide and tried to install the Online installer, as recommended. But I got this error:
![image](https://user-images.githubusercontent.com/6393076/51032646-f2d00c80-1587-11e9-898b-b63cb7004dd7.png)

Then I used the offline installer and it worked fine. Not sure if this happened because I'm using 14.04...

**Comment by Levi-Armstrong** [comment]
Oh, so the latest updates were only for 16.04 and 18.04 because the latest version of Qt Creator will not build on 14.04. I need to take down the online installer.

**Comment by lucascoelhof** [comment]
Installed worked fine for me on 18.04, just so you know.
