### ISSUE TITLE
QtCreator 4.8.0 rc1 global search doesn't work

### ISSUE THREAD

**Issue by DLuensch** [ros-industrial/ros_qtc_plugin#319]
In the latest version for bionic and xenial (QtCreator 4.8.0), the global search (Ctrl+Shift+F) doesn't work. When you try to find something, no results can be found. it doesn't matter where you search: catkin_ws, Open Documents, etc. The search function for the current file works. When I use "qtcreator-ros-xenial-441-offline-installer.run" the problem doesn't exists. I have Kubuntu 18.04 and tested it with the online and offline installer for the bionic release.

**Comment by jbvo** [comment]
I've had the same issue and found also that the locator doesn't work anymore. I'm running Ubuntu 18.04 and using ROS Melodic with catkin-tools.

**Comment by DLuensch** [comment]
A workaround was to use the old xenial version which works fine on ubuntu 18.04. You can download them here: Offline Installer (https://qtcreator-ros.datasys.swri.edu/downloads/installers/xenial/archived/qtcreator-ros-xenial-441-offline-installer.run), Online Installer (https://qtcreator-ros.datasys.swri.edu/downloads/installers/xenial/archived/qtcreator-ros-xenial-441-online-installer.run)

**Comment by Levi-Armstrong** [comment]
Could you start Qt Creator from the terminal, load project, build project, then perform search and post the output in the terminal?

**Comment by jbvo** [comment]
This is what I get, I've cut of a repetitive part at the end:
```
"Unable to locate package costmap_queue build file: /mnt/data/git/github/robot_navigation_ws/build/costmap_queue/costmap_queue.cbp"
"Unable to locate package dlux_global_planner build file: /mnt/data/git/github/robot_navigation_ws/build/dlux_global_planner/dlux_global_planner.cbp"
"Unable to locate package dlux_plugins build file: /mnt/data/git/github/robot_navigation_ws/build/dlux_plugins/dlux_plugins.cbp"   
"Unable to locate package dwb_critics build file: /mnt/data/git/github/robot_navigation_ws/build/dwb_critics/dwb_critics.cbp" 
"Unable to locate package dwb_local_planner build file: /mnt/data/git/github/robot_navigation_ws/build/dwb_local_planner/dwb_local_planner.cbp"
"Unable to locate package dwb_msgs build file: /mnt/data/git/github/robot_navigation_ws/build/dwb_msgs/dwb_msgs.cbp"        
"Unable to locate package dwb_plugins build file: /mnt/data/git/github/robot_navigation_ws/build/dwb_plugins/dwb_plugins.cbp"
"Unable to locate package global_planner_tests build file: /mnt/data/git/github/robot_navigation_ws/build/global_planner_tests/global_planner_tests.cbp"
"Unable to locate package locomotor build file: /mnt/data/git/github/robot_navigation_ws/build/locomotor/locomotor.cbp"
"Unable to locate package locomotor_msgs build file: /mnt/data/git/github/robot_navigation_ws/build/locomotor_msgs/locomotor_msgs.cbp"
"Unable to locate package locomove_base build file: /mnt/data/git/github/robot_navigation_ws/build/locomove_base/locomove_base.cbp"
"Unable to locate package nav_2d_msgs build file: /mnt/data/git/github/robot_navigation_ws/build/nav_2d_msgs/nav_2d_msgs.cbp"
"Unable to locate package nav_2d_utils build file: /mnt/data/git/github/robot_navigation_ws/build/nav_2d_utils/nav_2d_utils.cbp"
"Unable to locate package nav_core2 build file: /mnt/data/git/github/robot_navigation_ws/build/nav_core2/nav_core2.cbp"
"Unable to locate package nav_core_adapter build file: /mnt/data/git/github/robot_navigation_ws/build/nav_core_adapter/nav_core_adapter.cbp"
"Unable to locate package nav_grid build file: /mnt/data/git/github/robot_navigation_ws/build/nav_grid/nav_grid.cbp"
"Unable to locate package nav_grid_iterators build file: /mnt/data/git/github/robot_navigation_ws/build/nav_grid_iterators/nav_grid_iterators.cbp"
"Unable to locate package nav_grid_pub_sub build file: /mnt/data/git/github/robot_navigation_ws/build/nav_grid_pub_sub/nav_grid_pub_sub.cbp"
"Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/costmap_queue/CMakeFiles/gmock_main.dir/flags.make"
"Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/costmap_queue/CMakeFiles/gmock.dir/flags.make"
"Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dlux_global_planner/CMakeFiles/gmock_main.dir/flags.make"
"Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dlux_global_planner/CMakeFiles/gmock.dir/flags.make"
"Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dlux_plugins/CMakeFiles/gmock_main.dir/flags.make"
"Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dlux_plugins/CMakeFiles/gmock.dir/flags.make"
[...]
```

**Comment by DLuensch** [comment]
@jbvo and @Levi-Armstrong  I have the same list in the terminal for all of my packages in my catkin_ws which do not contain c++ code. After I do a global search, nothing is printed in the terminal.

@Levi-Armstrong: What do you mean with: locate the file you are having an issues with?

You can find the screen shots of the global search

![gloabl_search_search](https://user-images.githubusercontent.com/6607057/51597658-08d0bc00-1efc-11e9-8349-8306560b6921.jpg)
![gloabl_search_result](https://user-images.githubusercontent.com/6607057/51597668-0ec69d00-1efc-11e9-894d-689972d86f42.jpg)

**Comment by Levi-Armstrong** [comment]
Ok, I was able to recreate the issue. Switch Scope to "Files in File System" fixed it on my end. I will mark this as a bug and will need to see why when Scope is set to project it does not work.

**Comment by jbvo** [comment]
Sorry for not providing more info, I didn't and won't have much time to spend on this, but I wanted to add one more piece of info: the second time I open the project qtcreator does not print the `Unable to locate package global_planner_tests build file [...]` warnings, but still search does not work. The other warnings regarding gmock are still there.

I was aware that the `Files in File System` scope works fine. I've tried to use the `Project 'abc'` scope in other non-ROS projects, both cmake and qmake projects work fine, so I'm thinking something is wrong with the listing of files that are part of the project, maybe the interface on qtcreator for this functionality has changed?

**Comment by Levi-Armstrong** [comment]
Yea it had changed in qtcreator and I missed it in my testing since I always use "Files in File System". I almost have it fixed.

**Comment by Levi-Armstrong** [comment]
@DLuensch I have release a new version but I have not made it available to everyone yet. I have uploaded the offline installer to the [release](https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.3.1). Would you have time to test it out?

**Comment by DLuensch** [comment]
> @DLuensch I have release a new version but I have not made it available to everyone yet. I have uploaded the offline installer to the [release](https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.3.1). Would you have time to test it out?

Thanks for your efforts @Levi-Armstrong. I hope I can test it today.

**Comment by jbvo** [comment]
Thanks!

I have just tried it and fixed both the problem of the search and the locator!

**Comment by DLuensch** [comment]
@Levi-Armstrong Thanks allot, for me the fix works also. The Source/Header switch bug (https://github.com/ros-industrial/ros_qtc_plugin/issues/318) is also fixed.

**Comment by jbvo** [comment]
In release 4.8.1 for Bionic this issue seems fixed, so as far as I can see this issue can be closed.
