### ISSUE TITLE
In Qt run settings tab, ROS Step for each run configuration cannot be disabled

### ISSUE THREAD

**Issue by GarethZhang** [ros-industrial/ros_qtc_plugin#32]
The disable tab for ROS Step was not functioning. To simply put, if I have 3 ROS Steps in a specific run configuration, disable tab does not allow me to disable the ROS Step. ROS still launches all the nodes included in the run configuration. 

Does this only happen to me or is there anyone sharing the same issue?

Thanks!

**Comment by Levi-Armstrong** [comment]
@GarethZhang I will take a look and see what I can find.

**Comment by Levi-Armstrong** [comment]
This should be fixed, pull the latest and test it out and let me know if it has been resolved.

**Comment by GarethZhang** [comment]
fixed
