### ISSUE TITLE
QtCreator 4.8.0 rc1: cannot get code formatters/formatting to work

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_qtc_plugin#320]
Not sure whether this is me not understanding something, or perhaps I'm not configuring things correctly, but I cannot get QtCreator to apply standard ROS code formatting rules to my projects.

I've currently configured the `ROS [built-in]` style in:

 1. project settings (Project Settings -> Code Style -> C++)
 1. C++ Code Style in options (Tools -> Options -> C++ -> Code Style)
 1. the ROS options in options (Tools -> Options -> ROS: Default Code Styles)

But Qt Creator seems to ignore all of that and still indents C++ sources and headers with 4 spaces.

I've not touched the "Text Editor -> Behavior" or the "Project Settings -> Editor" settings (Tabs and Indentation) as I was under the impression that configuring the code style should sort those out for me / override those.

---

I'm using Qt Creator 4.8.0 on Ubuntu Xenial (`amd64`) with ROS Kinetic.

**Comment by gavanderhoorn** [comment]
Related / possible duplicates (?): #123 (although I'd like to actually get to a situation where it only indents with 2 spaces per level), #64 and #244.

**Comment by Levi-Armstrong** [comment]
I downloaded Qt Creators Released version and it has the same issue. Most likely something in there code so I created an issue on [Qt Creator Bug Tracker](https://bugreports.qt.io/browse/QTCREATORBUG-21877).

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Ok I have did some more testing and it looks like changing the code style only affects new code written and does not change existing code for me. I believe this is expected behavior. Can you confirm?

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong wrote:
>  it looks like changing the code style only affects new code written and does not change existing code for me. I believe this is expected behavior. Can you confirm?

I've just tested this by creating a new file in an existing project (using the `Add New...` menu option and choosing a C++ header), but after creating a class the editor still indents with 4 spaces for me, while the ROS code formatting is configured.

**Comment by christian-rauch** [comment]
Is this still an issue with the newest Qt Creator release (5.0)?

**Comment by christian-rauch** [comment]
Qt Creator 6 supports clang-format natively. I think this issue is resolved. Please reopen, if you still have issues with code formatting.
