### ISSUE TITLE
zero as null pointer constant

### ISSUE THREAD

**Issue by wumin199** [ros-industrial/ros_qtc_plugin#321]
platform: ubuntu 16.04 

when I installed rqt_plugin and typed:

`ROS_INFO("Hello World")`

it gave me an warning(but works well)

`zero as null pointer constant `

but when I used printf instead, it works well and no warning.

**Comment by gavanderhoorn** [comment]
That is not an issue with `ros_qtc_creator`, it's just a warning from Clang (in C++11 and up mode) that the macro `ROS_INFO(..)` uses `0` instead of `nullptr`.

This is a problem with ROS, not the plugin.

**Comment by gavanderhoorn** [comment]
Even if it's not a problem with the plugin, the warning is pretty annoying ;)

**Comment by gavanderhoorn** [comment]
ROS Answers question: [Compiler warning (c++11): Zero as null pointer constant](https://answers.ros.org/question/324627).
