### ISSUE TITLE
Parsing Files fails when starting QT Creator

### ISSUE THREAD

**Issue by DavidMerzJr** [ros-industrial/ros_qtc_plugin#326]
QT Creator 4.8.1
ROS Plugin 4.8.1
Ubuntu 16.04

When opening QT Creator (after restarting computer or just closing and re-opening), the "parsing files" step shows the green bar indicating success.  However, the files are not 'discovered' properly.  Anything defined in another file is marked as an undeclared identifier.  This occurs even when the project has been built before.  If I build, everything is linked properly.  If I build, close, and re-open, the problem re-appears.

The steps that are shown in the bottom right corner, in the order of appearance:

On Build: Build -> Parsing Build Files for Project "name" -> Parsing C/C++ Files -> Scanning for Tests

On Startup: Parsing Build Files for Project "name" -> Reading Project "name"

**Comment by jbvo** [comment]
I have the same problem using release 0.3.2 (QtCreator / ROS Plugin version 4.8.1) on Ubuntu 18.04.

When I open a project (e.g. https://github.com/locusrobotics/robot_navigation), cloned into a workspace that I have build before and opened with QtCreator before, I see the following warnings in the `General Messages` view:
```
[ROS Warning] Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/costmap_queue/CMakeFiles/gmock_main.dir/flags.make.
[ROS Warning] Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/costmap_queue/CMakeFiles/gmock.dir/flags.make.
[ROS Warning] Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dlux_global_planner/CMakeFiles/gmock_main.dir/flags.make.
[ROS Warning] Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dlux_global_planner/CMakeFiles/gmock.dir/flags.make.
[ROS Warning] Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dlux_plugins/CMakeFiles/gmock_main.dir/flags.make.
[ROS Warning] Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dlux_plugins/CMakeFiles/gmock.dir/flags.make.
[ROS Warning] Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dwb_critics/CMakeFiles/gmock_main.dir/flags.make.
[ROS Warning] Flags file does not exist: /mnt/data/git/github/robot_navigation_ws/build/dwb_critics/CMakeFiles/gmock.dir/flags.make.
[... repeats for all packages ... ]
```

And for each source file I open there's a warning in the top of the editor that says `This file is not part of any project. The code model might have issues to parse this file properly.`

The only output on the commandline that I see is the following:
```
QFileSystemWatcher::removePaths: list is empty
```

When checking the `C++ Code Model Inspector` from the `Tools -> C++` menu, the `Project Parts` tab is empty, even though I have some source files open. After building, this list is filled with a few packages and build configurations and in the bottom there are project files etc.
![QtCreator screenshot 2019-03-12 10-34-26](https://user-images.githubusercontent.com/24601408/54189653-894e7a80-44b2-11e9-9bc0-7fbdeff09c41.png)

It seems that the project setup is only registered within QtCreator after building is finished and not while loading an existing (prebuilt) workspace.

Let me know if there's anything I can check.

**Comment by jbvo** [comment]
While running it some more from the command line I now saw the following output:
```
SOFT ASSERT: "candidates.size() == 1" in file /tmp/abcdefghijklmn/qt-creator/src/plugins/projectexplorer/runconfiguration.cpp, line 957
```

**Comment by mbuijs** [comment]
This problem seems to be solved in build 0.3.4 / QtCreator 4.8.2 used on Ubuntu bionic.

**Comment by beetleskin** [comment]
I still have this issue with the  0.3.4 release on bionic

**Comment by Levi-Armstrong** [comment]
@beetleskin Is this solved in 0.3.5?

**Comment by mbuijs** [comment]
I've opened 2 different workspaces were I had this problem before and with 0.3.5 not anymore. Looks good!

**Comment by beetleskin** [comment]
Same here, looking good, thanks :)

**Comment by DavidMerzJr** [comment]
I haven't been having any more trouble with it.
