### ISSUE TITLE
lexical or preprocessor issue ros.h not found

### ISSUE THREAD

**Issue by DaxiongAI** [ros-industrial/ros_qtc_plugin#328]
hey! lexical or preprocessor issue ros.h not found ,i'm use ubuntu 16.04 and qtcreator-ros-xenial-latest-offline-installer ,what wrong?

**Comment by Levi-Armstrong** [comment]
Did you build at least once within Qt Creator?

**Comment by DaxiongAI** [comment]
yes,my ws build ok

**Comment by DaxiongAI** [comment]
Base path: /home/daxiong/my_ws
Source space: /home/daxiong/my_ws/src
Build space: /home/daxiong/my_ws/build
Devel space: /home/daxiong/my_ws/devel
Install space: /home/daxiong/my_ws/install
####
#### Running command: "cmake /home/daxiong/my_ws/src -DCATKIN_DEVEL_PREFIX=/home/daxiong/my_ws/devel -DCMAKE_INSTALL_PREFIX=/home/daxiong/my_ws/install -G Unix Makefiles" in "/home/daxiong/my_ws/build"
####
####
#### Running command: "make -j12 -l12" in "/home/daxiong/my_ws/build"
####
10:22:58: 进程"/opt/ros/kinetic/bin/catkin_make"正常退出。
10:22:59: Elapsed time: 00:33.

**Comment by Levi-Armstrong** [comment]
Can you provide a screen shot of the message you seeing?

**Comment by grafoteka** [comment]
I'm having the same error.

I can build my project but the ros libraries are not found by QtCreator.

**Comment by Levi-Armstrong** [comment]
Do you have a sample workspace so I may recreate the issue?

**Comment by DaxiongAI** [comment]
here is my ws    [https://github.com/DaxiongAI/test_qtc_plugin.git]

**Comment by DaxiongAI** [comment]
here is my test_ws (https://github.com/DaxiongAI/test_qtc_plugin.git)

**Comment by grafoteka** [comment]
Hi @Levi-Armstrong, 
I don't know how, but first time I run my ROS nodes, automatically QT recognized the libraries. 
So now, is working perfectly.

Thank you!

**Comment by Slahuddin-Ch** [comment]
hey??? how did you solved this issue?

**Comment by grafoteka** [comment]
Hi Slahuddin, finally I move to VSCode with the ROS plugin. I works great, you inly need to install it and everything is working. 

https://code.visualstudio.com/ <https://code.visualstudio.com/>

https://marketplace.visualstudio.com/items?itemName=ms-iot.vscode-ros <https://marketplace.visualstudio.com/items?itemName=ms-iot.vscode-ros> 

https://github.com/ms-iot/vscode-ros <https://github.com/ms-iot/vscode-ros>

Jorge
