### ISSUE TITLE
Purpose of update button?

### ISSUE THREAD

**Issue by rhaschke** [ros-industrial/ros_qtc_plugin#33]
What's the purpose of the Update button in build settings?

![image](https://cloud.githubusercontent.com/assets/5376030/17301058/75741830-5815-11e6-9a19-6995bc1be1c7.png)

I tried to update my project tree to re-generate the list of include directories. But didn't work.
The `ROS distribution` button resets to `Groovy` after restart. By the way, what about newer ROS releases?

**Comment by Levi-Armstrong** [comment]
The source workspace update the environment for the active build configuration (source /devel/setup.bash) . To update the includes right-click on the project folder and there should be a "Reload Project Include Directories...". 

I am currently working an improvement that will handle this internally so you don't have to manually update the includes when changes are made to the cmakelist files, but it is not full implemented.

**Comment by rhaschke** [comment]
Maybe you could add a tooltip to the update button to clarify, that this will only update (build) environment variables.
