### ISSUE TITLE
can't attatch a roslaunch node

### ISSUE THREAD

**Issue by dfcknj** [ros-industrial/ros_qtc_plugin#330]
Hello，
I got an problem can't debug attatch a roslaunch node.(ros melodic and ubuntu 18.04)
My cmake is set(CMAKE_BUILD_TYPE=debug),and in qtcreator-ros Run config Custom Executable is below:
![image](https://user-images.githubusercontent.com/3350310/55490769-e29b6b00-5666-11e9-9d3a-550069693f68.png)

First I roslaunch the node(in terminal) ,then attatch to process it but  qtcreator-ros no in debug mode! 

And this is the log screenshot:
![image](https://user-images.githubusercontent.com/3350310/55491092-7836fa80-5667-11e9-83ad-4a62b8fe28f4.png)

I’m not sure where the configure is wrong,or I have forgot something?

**Comment by Levi-Armstrong** [comment]
It should be fixed, but it has not been released. I recommend using the utilities under debug menu item for now. Also you can try the custom executable run step.

**Comment by oxoocoffee** [comment]
@dfcknj 
I think you got it reversed :)
1. Debug - > Start Debugging -> Attach to Started Application. Select node you want to debug
2. From terminal run roslaunch

In some cases you might have to add sleep(3) first thing in your main() to make sure debugger can catch it.

**Comment by dfcknj** [comment]
thank you,@oxoocoffee,but I checked it can't work too.
I found vscode did it a easier way,just attach to roslaunch node

**Comment by Levi-Armstrong** [comment]
I will have to test this. Thank you for the update.
