### ISSUE TITLE
how  to using this plugin to debug cartographer project？

### ISSUE THREAD

**Issue by minghuizhou123** [ros-industrial/ros_qtc_plugin#336]
Hi, dear Authors:
    when I want to debug some cartographer package code using “Attach to a unstarted process”， but run my project. Ctrl + R， i found some error in “source /home/zmh/work/catkin_ws_isolated/devel/setup.bash”， this should source /home/zmh/work/catkin_ws_isolated/install_isolated/setup.bash。 
![Screenshot from 2019-04-28 14-04-13](https://user-images.githubusercontent.com/49223640/56859563-5b1fee00-69bf-11e9-8e2e-7bdcd129733b.png)
Projects build and run settings：
![Screenshot from 2019-04-28 14-02-50](https://user-images.githubusercontent.com/49223640/56859621-2d877480-69c0-11e9-9cff-bd944c408c7f.png)
![Screenshot from 2019-04-28 14-03-06](https://user-images.githubusercontent.com/49223640/56859624-32e4bf00-69c0-11e9-82e8-9fc66ed888ce.png)

Compiling Cartographer ROS：https://google-cartographer-ros.readthedocs.io/en/latest/compilation.html
cartographer ros build and install：
catkin_make_isolated --install --use-ninja
run：
source install_isolated/setup.bash
roslaunch cartographer_ros demo_revo_lds_rplidar.launch

Could you tell be how to deal with it? Thanks in advance!

**Comment by minghuizhou123** [comment]
when catkin_make_isolated build project，Ctrl + R,it should "source install_isolated/setup.bash"

**Comment by Levi-Armstrong** [comment]
Custom process as the primary build step is currently not supported as the primary build step. You must use either the catkin_make or catkin tools build step. Are you able to use either of the supported build steps?

**Comment by minghuizhou123** [comment]
no, i choose CatkinMake build step,but source devel/setup.bash
![Screenshot from 2019-05-05 10-04-40](https://user-images.githubusercontent.com/49223640/57187130-31b21580-6f1d-11e9-8b25-79259b77b947.png)

**Comment by Levi-Armstrong** [comment]
You have selected CatkinMake as the build system but you added a "Custom Process Step". You need to remove this build step and add either catkin_make or catkin_tools build step.

**Comment by Levi-Armstrong** [comment]
The "Custom Process Step" is meant to follow on of the provided build step. I will update the plugin so this is not possible in the future. I see you are also using catkin_make_isolated so I will work on adding it as an available build step.

**Comment by minghuizhou123** [comment]
thank you! Looking forward to updating the plug-in
![1](https://user-images.githubusercontent.com/49223640/57204026-435fef80-6fe7-11e9-8f0b-b0dc61ba08fb.jpg)

**Comment by Levi-Armstrong** [comment]
Opened issue to add catkin_make_isolated. #365
