### ISSUE TITLE
Is support for Ubuntu 16.04 dropped in latest release?

### ISSUE THREAD

**Issue by NiclasEvestedt** [ros-industrial/ros_qtc_plugin#337]
Hi,
I saw that the latest release only has an installer for bionic and not xenial. Is support for 16.04 dropped from this release?
https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.3.3

Thanks for a great plugin!

**Comment by erik-embarktrucks** [comment]
I have the same problem

**Comment by swefire1** [comment]
I have the same problem, the latest version crashes often on 16.04, it would be great to get the latest fixes.

**Comment by NiclasEvestedt** [comment]
@Levi-Armstrong would be really thankful with just a yes or no for xenial support or not? Thanks!

**Comment by Levi-Armstrong** [comment]
Yes

**Comment by gavanderhoorn** [comment]
That's unfortunate.

What is the biggest bottleneck / problem with supporting Xenial @Levi-Armstrong? Perhaps something can be done about that.

**Comment by NiclasEvestedt** [comment]
@gavanderhoorn he answered yes as yes there is support for xenial. As of a few days there is this tag that has a xenial installer https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.3.5. Works great for me and a lot of the problems I had with the older version seems to be gone! Thanks a lot @Levi-Armstrong !

**Comment by Levi-Armstrong** [comment]
Sorry for not being clearer. I do plan to support xenial as long as    Qt Creator will build.
