### ISSUE TITLE
Blocking process "bash -i"

### ISSUE THREAD

**Issue by christian-rauch** [ros-industrial/ros_qtc_plugin#338]
Since recently, when opening a workspace or creating a new workspace from scratch, the plugin blocks the Qt Creator process for a long time and the whole desktop becomes very sluggish and unusable.
This somehow seems to be related to a child process `bash -i` that is created by `qtcreator-ros` and takes a whole CPU (13% here because 1 of 8 CPUs is used):
![qtc_ros_block](https://user-images.githubusercontent.com/8226248/57015705-2786d300-6c0e-11e9-8708-8ee392f8e181.png)

Eventually, after a very long time, the plugin manages to open the workspace.
When forcefully killing `bash -i`, the desktop behaves normally again.

Edit: This seems to only happen when launched via the desktop launcher / icon. It does hot happen when launched via `QtCreatorROS/latest/bin/qtcreator-ros` from a shell.

**Comment by christian-rauch** [comment]
This might be a long shot, but this issue: https://github.com/enkore/j4-dmenu-desktop/issues/45 shows similar symptoms with `bash -i` (100% CPU, not able to open other programs). They solved it by dropping the `-i`.
Which command is executed in the `bash -i` process that is spawned by the Qt Creator plugin? Would it also work without the `-i`?

**Comment by christian-rauch** [comment]
When launched via `QtCreatorROS/latest/bin/qtcreator-ros` from a shell, the process moves to the background automatically when I select a workspace in the sessions overview. I.e. I get `[1]+  Stopped                 ./QtCreatorROS/latest/bin/qtcreator` after selecting a workspace and repeatedly need to type `fg` (about 8 times) in the shell to bring the QtCreator process to the foreground over and over again. After the session is opened, the process stays in the foreground I can use it as usual.

**Comment by Levi-Armstrong** [comment]
So I added switch from using `bash -c` to `bash -i -c` because when using the `-i` it loads the `.bashrc` which has additional environment variables, like the python path. Do you know of another way to make bash load the `.bashrc` file?

**Comment by christian-rauch** [comment]
No, sorry.
I had this issue once before with PyCharm, where `Exec=bash -i -c "<path_to>/pycharm.sh" %f` used to work for a while but then the process `bash -i` blocked (with high CPU) and PyCharm wouldn't start anymore.
At least when started from the command line, the blocking is caused by the `qtcreator` process going to the background when a session is loaded.

**Comment by Levi-Armstrong** [comment]
When it loads i run the process that parses the workspace in a separate process, which does have a call to bash.

**Comment by Levi-Armstrong** [comment]
@christian-rauch I have just created a pull request removing the -i command to the bash. See PR #347 explanation and see if you agree with the proposal to add environment variable to the users .profile over the .bashrc so application get these environment variables.

**Comment by Levi-Armstrong** [comment]
I removed the use of -i.
