### ISSUE TITLE
Symlinked package folders not considered

### ISSUE THREAD

**Issue by rhaschke** [ros-industrial/ros_qtc_plugin#34]
A symlinked package folder is not correctly searched for source files. Only some top-level files are shown (package.xml, etc). But all C++ sources are missing.

**Comment by Levi-Armstrong** [comment]
@rhaschke I just submitted a PR to address the issue and it should be merged shortly. Thank you for all of your feedback.

**Comment by Levi-Armstrong** [comment]
@rhaschke, I merged the pull request that should fix the issue.

**Comment by Levi-Armstrong** [comment]
@rhaschke Did the latest changes solve the issue?

**Comment by rhaschke** [comment]
Thanks for fixing this.
