### ISSUE TITLE
Manually setting Ninja generator

### ISSUE THREAD

**Issue by bewagner** [ros-industrial/ros_qtc_plugin#340]
Hi, 

I would like to use the Ninja Generator with a Catkin generated ROS Project. If I add '--use-ninja' to the catkinmake Arguments of my build step, I run into the Problem that qtcreator automatically adds a Generator via -G 'CodeBlocks - Unix Makefiles' (The Generator from my Kit Settings). 

I also tried changing the Generator in the kit settings, however this does not have any effect on the command that is run to build my project. That is, qtcreator still executes: 
`catkin_make -G 'CodeBlocks - Unix Makefiles'` even though I set Ninja as the kit Generator.

Is there any way to ignore the kit Generator and use '--use-ninja' manually in the build settings?

**Comment by Levi-Armstrong** [comment]
The `-G 'CodeBlocks - Unix Makefiles'` is required to build the projects files used to build the cpp code model in qt creator for this plugin. It it is not passed then features like follow under cursor, code completion would not work. Is there a specific reason for the need to use this generator?

**Comment by bewagner** [comment]
Thanks for your answer! 

I wanted to try out whether ninja would give me a speedup during build. But if that doesn't work, it's also fine. 

Thanks for your time!
