### ISSUE TITLE
Error when including message header

### ISSUE THREAD

**Issue by mbuijs** [ros-industrial/ros_qtc_plugin#341]
When using release 0.3.4 / QtCreator 4.8.2 on Ubuntu bionic, I get errors when on `#include` statements for messages that are defined anywhere else than `/opt/ros/melodic/include`.
As far as I can see the message headers are generated inside a directory inside the devel space or install space, but this directory is not in the list of include dirs.

For the record: I'm using catkin-tools to build my workspace.

**Comment by Levi-Armstrong** [comment]
Thank you. I am trying to figure out how to solve tthe issue with it sometimes going to headers in the install/devel directory. I solved it by removing these directories from the code model but not it causes the issue you have found. I have reached out to developers of Qt Creator for guidance on how to address this. I hope have feedback soon.

**Comment by Levi-Armstrong** [comment]
This should be fixed in the latest release. Please reopen if not solved.
