### ISSUE TITLE
how to go to defination?

### ISSUE THREAD

**Issue by minghuizhou123** [ros-industrial/ros_qtc_plugin#343]
hi, when i select the call function, shift+F2, not go to defination

**Comment by Levi-Armstrong** [comment]
If does not go to definition then this mean the code model has not been constructed. The code model gets constructed after a successful build within Qt Creator. Have you successfully built your workspace within Qt Creator?

**Comment by minghuizhou123** [comment]
yes，built is ok. when i select the red rectangle, not go to defination
![1](https://user-images.githubusercontent.com/49223640/58392954-fb287000-806e-11e9-821f-6d81754607f9.jpg)

**Comment by Levi-Armstrong** [comment]
Can you try follow under cursor and see if this works?

**Comment by Levi-Armstrong** [comment]
@minghuizhou123 are you still having issues?

**Comment by christian-rauch** [comment]
At least  in newer Qt Creator versions, you can follow symbols by Ctrl + left click on symbols. This requires clang installed and that the workspace was scanned/indexed. This works for me with the newest Qt Creator release (5.0).

In any case, I think this is not related to the ROS plugin. If you continue to have this issue, I recommend reporting this issue to Qt Creator.
