### ISSUE TITLE
Issue with MySql driver - for Qt Creator with online ROS plugin

### ISSUE THREAD

**Issue by RosCstr** [ros-industrial/ros_qtc_plugin#349]
First I will describe my working setup then the problem which I encountered.
Setup: 
- windows 10 machine running a virtual machine with Ubuntu 16.04. Inside the VM I have installed: [ROS Kinetic Kame](http://wiki.ros.org/kinetic/Installation/Ubuntu), [XAMPP 7.3.5 / PHP 7.3.5](https://www.apachefriends.org/ro/download.html) (which installed: mysql  Ver 15.1 Distrib 10.1.39-MariaDB, for Linux (x86_64) using readline 5.1), then installed [Qt Creator with ROS plugin](https://ros-qtc-plugin.readthedocs.io/en/latest/_source/How-to-Install-Users.html#qt-installer-procedure) - using the procedures described in the link. I have created a database with tables using localhost/phpmyadmin and from Qt I have a user UI that tries to connect to the database using MYSQL.

Problem:
- I can not make the UI connect to the databasse because at runtime it stipulates: 
"QSqlDatabase: QMYSQL driver not loaded
QSqlDatabase: available drivers: QSQLITE
Failed to connect to database."
- I tried everything that is on forums but I could not make the QT (using the above described installation) add the MYSQL driver. I tried installing the c++ connector (does not work), installed mysql-server and client (all versions, but one at a time for ubuntu 16.04 -  does not work), and all the other stuff described on the forums. I also entered the sqldrivers folder from QT folder and from terminal ran the following command: ldd libqsqlmysql.so (from Qt standard path used in the above installer: home/QtCreator/latest/lib/Qt/plugins/sqldrivers/), which has the following output:
linux-vdso.so.1 =>  (0x00007fff77102000)
libQt5Sql.so.5 => /home/brain2016/QtCreator/latest/lib/Qt/plugins/sqldrivers/./../../lib/libQt5Sql.so.5 (0x00007f7772538000)
libQt5Core.so.5 => /home/brain2016/QtCreator/latest/lib/Qt/plugins/sqldrivers/./../../lib/libQt5Core.so.5 (0x00007f7771dde000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7771bc1000)
libmysqlclient.so.18 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18 (0x00007f7771605000)
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7771283000)
libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7770f7a000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7770d64000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f777099a000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f7770780000)
libicui18n.so.56 => /home/brain2016/QtCreator/latest/lib/Qt/plugins/sqldrivers/./../../lib/libicui18n.so.56 (0x00007f77702e7000)
libicuuc.so.56 => /home/brain2016/QtCreator/latest/lib/Qt/plugins/sqldrivers/./../../lib/libicuuc.so.56 (0x00007f776ff2f000)
libicudata.so.56 => /home/brain2016/QtCreator/latest/lib/Qt/plugins/sqldrivers/./../../lib/libicudata.so.56 (0x00007f776e54c000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f776e348000)
libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007f776e146000)
libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f776de35000)
/lib64/ld-linux-x86-64.so.2 (0x00007f7772993000)
libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f776dbc5000)

So I have all the libraries installed ok, as far as I can tell.

I can connect to the database using terminal but I can not make it work with Qt. Can anyone help me solve the above issue or at least point me in the right direction in order to put this question on another forum that might help me out? If more information is required in order to solve my problem I can give it. Thanks in advance

**Comment by Levi-Armstrong** [comment]
@DavidMerzJr and @jrgnicho Have you ran into this issue using Qt Application and connecting to a database?

**Comment by DavidMerzJr** [comment]
@Levi-Armstrong - I have not run into this. I think we have been using Python (mysql-connector-python) to interact with the MySQL database, rather than interfacing directly from QT.

**Comment by RosCstr** [comment]
In Ubuntu 14.04 and ROS Indigo I was able to make the connection possible directly from Qt with MySQL. I needed to switch to the next Ubuntu version because of some incompatibility between Rviz Qt version from Indigo distribution and what I want to accomplish using Qt Creator. So the only possibility is to use Python? .....

**Comment by DavidMerzJr** [comment]
@RosCstr - I do not know whether it is the only possibility, but I know that it works for our purposes.  We have been using the mysql-connector-python module in a Python ROS node, while interacting with it from a C++ QT-application/ROS-node.  As far as I can tell, I have no special drivers installed. (See below.)

Extracts of `$ apt list --installed`:
```
mysql-apt-config/unknown,unknown,now 0.8.13-1 all [installed]
mysql-client/unknown,now 8.0.16-2ubuntu16.04 amd64 [installed,automatic]
mysql-common/unknown,now 8.0.16-2ubuntu16.04 amd64 [installed,automatic]
mysql-community-client/unknown,now 8.0.16-2ubuntu16.04 amd64 [installed,automatic]
mysql-community-client-core/unknown,now 8.0.16-2ubuntu16.04 amd64 [installed,automatic]
mysql-community-server/unknown,now 8.0.16-2ubuntu16.04 amd64 [installed,automatic]
mysql-community-server-core/unknown,now 8.0.16-2ubuntu16.04 amd64 [installed,automatic]
mysql-server/unknown,now 8.0.16-2ubuntu16.04 amd64 [installed]
...
qt-at-spi/xenial,now 0.4.0-3 amd64 [installed]
qt4-designer/xenial,now 4:4.8.7+dfsg-5ubuntu2 amd64 [installed,automatic]
qt4-dev-tools/xenial,now 4:4.8.7+dfsg-5ubuntu2 amd64 [installed,automatic]
qt4-doc/xenial,xenial,now 4:4.8.7+dfsg-5ubuntu2 all [installed,automatic]
qt4-linguist-tools/xenial,now 4:4.8.7+dfsg-5ubuntu2 amd64 [installed,automatic]
qt4-qmake/xenial,now 4:4.8.7+dfsg-5ubuntu2 amd64 [installed,automatic]
qt5-qmake/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed,automatic]
qtbase5-dev/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed,automatic]
qtbase5-dev-tools/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed,automatic]
qtbase5-private-dev/xenial-updates,now 5.5.1+dfsg-16ubuntu7.5 amd64 [installed,automatic]
qtchooser/xenial,now 52-gae5eeef-2build1~gcc5.2 amd64 [installed]
qtcore4-l10n/xenial,xenial,now 4:4.8.7+dfsg-5ubuntu2 all [installed]
qtcreator/xenial,now 3.5.1+dfsg-2ubuntu2 amd64 [installed]
qtcreator-data/xenial,xenial,now 3.5.1+dfsg-2ubuntu2 all [installed,automatic]
qtcreator-doc/xenial,xenial,now 3.5.1+dfsg-2ubuntu2 all [installed,automatic]
qtdeclarative5-accounts-plugin/xenial,now 0.6+16.04.20151106-0ubuntu1 amd64 [installed]
qtdeclarative5-dev/xenial,now 5.5.1-2ubuntu6 amd64 [installed,automatic]
qtdeclarative5-dev-tools/xenial,now 5.5.1-2ubuntu6 amd64 [installed]
qtdeclarative5-private-dev/xenial,now 5.5.1-2ubuntu6 amd64 [installed,automatic]
qtdeclarative5-qtquick2-plugin/xenial,now 5.5.1-2ubuntu6 amd64 [installed]
qtdeclarative5-test-plugin/xenial,now 5.5.1-2ubuntu6 amd64 [installed]
qtdeclarative5-ubuntu-ui-toolkit-plugin/xenial,now 1.3.1918+16.04.20160404-0ubuntu1 amd64 [installed]
qtdeclarative5-unity-action-plugin/xenial,now 1.1.0+14.04.20140304-0ubuntu2~gcc5.1 amd64 [installed]
qtmultimedia5-dev/xenial,now 5.5.1-4ubuntu2 amd64 [installed,automatic]
qtscript5-dev/xenial,now 5.5.1+dfsg-2build1 amd64 [installed,automatic]
qtscript5-private-dev/xenial,now 5.5.1+dfsg-2build1 amd64 [installed,automatic]
qttools5-dev/xenial-updates,now 5.5.1-3ubuntu0.1 amd64 [installed,automatic]
qttools5-dev-tools/xenial-updates,now 5.5.1-3ubuntu0.1 amd64 [installed,automatic]
qttools5-private-dev/xenial-updates,now 5.5.1-3ubuntu0.1 amd64 [installed,automatic]
qttranslations5-l10n/xenial,xenial,now 5.5.1-2build1 all [installed]
qtxmlpatterns5-dev-tools/xenial,now 5.5.1-2build1 amd64 [installed,automatic]
```

**Comment by RosCstr** [comment]
Ok, thank you. I will consider this closed then.
