### ISSUE TITLE
Support for ROS2 and colcon

### ISSUE THREAD

**Issue by schornakj** [ros-industrial/ros_qtc_plugin#351]
Specifically, what changes are required to allow the code model to parse ROS2 projects and enable code completion?

**Comment by schornakj** [comment]
As an update, I've started working on a PR to support ROS2 (thanks to lots of help and guidance from @Levi-Armstrong). Code completion works as expected -- good stuff!

There are some ongoing issues related to adding the correct directories to the path environment variables and also general user-friendliness (for example, running many instances of setup.bash takes an obnoxiously long time in ROS2).

**Comment by Levi-Armstrong** [comment]
Add in #342

**Comment by ahcorde** [comment]
is there any guideline of how to use it?

I installed the plugin but I'm only able to see catkin_make and catkinTools. Nothing related to colcon.

**Comment by Levi-Armstrong** [comment]
We are working out a few things we plan to fix before updating the installer repository, but you can get the latest from release [tags](https://github.com/ros-industrial/ros_qtc_plugin/releases) which will have the colcon integration. We are working on fixing the progress bar updating.
