### ISSUE TITLE
perfparser not included

### ISSUE THREAD

**Issue by veimox** [ros-industrial/ros_qtc_plugin#356]
Hi! I was interested in using the performance analyzer provided with Qt but when I run it, a message is shown saying that *perfparser* cannot be found and that has to be exported in an env variable.

If I checked in where this executables are supposed to be (*<path_to_qt_creator>/libexec/qtcreator/*) and the executable is not there. I have installed qt creator from the official repos and it actually installs the binary called *perfparser*. If I copy paste it to the Qt Creator with the ROS plugin, and I run the performance analysis, it actually works.

I have tried to find out how or where the relased QtCreator in this project gets actually compiled but i couldn't find it so I cannot research further. So my question is, why not all the tools that are delivered with the Open Source QtCreator are not delivered with the ROS enabled version and, specifically, perfparser.

Thanks in advance!

**Comment by Levi-Armstrong** [comment]
I noticed when I cloned Qt Creator it asked to a username and password for perparser and would not clone. I did not look any further but is perparser publicly available?

**Comment by veimox** [comment]
The original repo is here and it is GPLv3

https://code.qt.io/cgit/qt-creator/perfparser.git

I got to know this thanks to this GUI (https://github.com/KDAB/hotspot) and
internally uses perf and perfparser.

**Comment by Levi-Armstrong** [comment]
I will look into why it is asking for a username and password.

**Comment by veimox** [comment]
Thanks! I also came across with [this](https://github.com/KDAB/perfparser) fork of hotspot. I am unaware of the differences or if it would work, is just for your information

**Comment by Levi-Armstrong** [comment]
@veimox OK, I figured out the issue and it should be fixed in this [release](https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.3.8)

**Comment by veimox** [comment]
Thanks for the effort! I have just installed that release and I cannot find the executable, can you check in your installation in the path i put in the issue?

**Comment by veimox** [comment]
Taking a fast look at the code of [qt creator](https://github.com/qt-creator/qt-creator/search?q=perfparser&unscoped_q=perfparser), `perfparser` is defined as a submodule and if it exists, it will compile it. Checking the `setup.sh` and supposing that you are using that script for building the release,  I would say that the [submodules are not being cloned](https://github.com/ros-industrial/ros_qtc_plugin/blob/4.9/setup.sh#L213).

**Comment by Levi-Armstrong** [comment]
Sorry I am not using the setup.sh. I am using the code in the master branch with contains the code for creating the installers. The reason it was not included before was that the qt-creator repository was using relative paths for submodules and I was cloning from GitHub and there code is hosted by them. I switched to cloning from https://code.qt.io/qt-creator/qt-creator.git. I appears to clone down and the Perf plugin is being build. Should there be an executable or are they using the library directly?

**Comment by Levi-Armstrong** [comment]
So it appears that the library is being build deployed but it is not deploying the executable. I will look into it further.

**Comment by veimox** [comment]
I see, thanks for the effort!

Btw1: my impresion is that perfparser is not very known within the ROS
community, exposing this feature (e.g. in the wiki) might help to boost the
popularity of this IDE and Plugin.

Btw2: there is no CI in this repo, is there any reason for it? I could help
setting up Travis or Circle CI

**Comment by Levi-Armstrong** [comment]
>Btw1: my impresion is that perfparser is not very known within the ROS community, exposing this feature (e.g. in the wiki) might help to boost the popularity of this IDE and Plugin.

I think this would be great, would you be interested in creating a wiki on how to use it with ros? If so I can add it to the World ROS-I Day on July 2.

> Btw2: there is no CI in this repo, is there any reason for it? I could help setting up Travis or Circle CI

No reason other than I have not had time to set it up. It would be great if you could help set it up. The master branch has the dockers scripts and the installer scripts that build everything and create the installers which could then be CI artifacts. I will push the latest installer data and if you have any question about the scripts let me know and there is a readme in the installer folder.

**Comment by Levi-Armstrong** [comment]
@veimox I just update the release with new installers which does have the perfparser executable. The issue was it checking for a dependency and does not build if it does not exist. Let me know if it does not work.

**Comment by Levi-Armstrong** [comment]
Also just uploaded a new installers that include the docs.

**Comment by veimox** [comment]
The latest binary is working perfectly!

> I think this would be great, would you be interested in creating a wiki on how to use it with ros? If so I can add it to the World ROS-I Day on July 2.

I have created an example package and added a REAMDE with some gifs. You are totally free to take it and put it whenever you want.

https://github.com/veimox/performance_analysis_example

I have also added a tutorial on how to use the native test tool of QtCreator.

> No reason other than I have not had time to set it up. It would be great if you could help set it up. The...

I have taken a look at the master branch and should be straight forward with the current scripts. I have to say that I don't like much having a deployment branch but is fine :smile:. I have also checked that the installer is actually setting the remote repositories to [here](https://qtcreator-ros.datasys.swri.edu/downloads/installers/) and by checking the repo structure I would say that everything is correct but is just not updated. Is there any reason for not updating the repo? Do you have write access to that repo such we could give the CI permissions to publish the artifacts there? I think it would be useful to give partial updates to the users.

**Comment by Levi-Armstrong** [comment]
>I have taken a look at the master branch and should be straight forward with the current scripts. I have to say that I don't like much having a deployment branch but is fine

I assume you are suggesting to put the installer folder in the main branch? I don't have an issues with merging into the main branches.

> I have also checked that the installer is actually setting the remote repositories to here and by checking the repo structure I would say that everything is correct but is just not updated. Is there any reason for not updating the repo? Do you have write access to that repo such we could give the CI permissions to publish the artifacts there? I think it would be useful to give partial updates to the users.

I did not want to update the main repository until I had sufficient testing with the new version to prevent getting slammed with issues and comments. I believe it is ready to push to the main repo which I should be able to do on Monday. I do have write access, but I will need to check with IT if it is possible to push changes based on where they are being stored. 

>  I think it would be useful to give partial updates to the users.
I agree, just need a way to let the users know that it is an pre release. Maybe two repo one that stays updated with the latest and one that only contains stable releases?

**Comment by Levi-Armstrong** [comment]
@veimox I merged your wiki contribution and it is [live](https://ros-qtc-plugin.readthedocs.io/en/latest/_source/Performance-Analysis.html). Thank you.

**Comment by Levi-Armstrong** [comment]
@Jmeyer1292 They have integrated Perf into Qt Creator!

**Comment by veimox** [comment]
I guess we can close this issue!

**Comment by nmoreaud** [comment]
Workaround on Ubuntu:
```
sudo apt install libdw-dev
mkdir -p /tmp/perfparser; cd /tmp/perfparser
git clone --depth 1 --branch v4.8.2 https://github.com/qt-creator/perfparser .
qmake
make
export PERFPROFILER_PARSER_FILEPATH="/tmp/perfparser/bin/perfparser"
qtcreator &
```
