### ISSUE TITLE
ROS Qt Creator support for Windows 10

### ISSUE THREAD

**Issue by Chianugoogidi** [ros-industrial/ros_qtc_plugin#357]
Hello,

I am working with Qt Creator 4.9.1 and running ROS on Windows 10. Are there plans to integrate the ROS Qt plugin into ROS on Windows? 

Thanks!

**Comment by Levi-Armstrong** [comment]
I do but not sure when I will be able to start on it.

**Comment by christian-rauch** [comment]
The latest release (https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.5.0) has Windows support. Just download and extract the released plugin archive into your Qt Creator installation.

**Comment by kidxhac** [comment]
> The latest release (https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.5.0) has Windows support. Just download and extract the released plugin archive into your Qt Creator installation.

Hello,

Is there any instruction about  this plugin on Windows? Could I edit UI factors and build them fullly on Qt6 for ROS directly?

Thank you!

**Comment by kidxhac** [comment]
> The latest release (https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.5.0) has Windows support. Just download and extract the released plugin archive into your Qt Creator installation.

Hello,

Is there any instruction about  this plugin on Windows? Could I edit UI factors and build them fullly on Qt6 for ROS directly?

Thank you!

**Comment by christian-rauch** [comment]
> Is there any instruction about this plugin on Windows?

You just have to extract the plugin archive into your Qt Creator installation. It will have the same folder hierarchy as the Linux installation, just the installation path of the "Qt Creator" folder will be different.

> Could I edit UI factors and build them fullly on Qt6 for ROS directly?

What do you mean by "UI factors"? The Qt 6 is just the runtime for Qt Creator, it cannot be used to build your own programs. For this, you have to install Qt 6 additionally to Qt Creator.

**Comment by kidxhac** [comment]
> > Is there any instruction about this plugin on Windows?
> 
> You just have to extract the plugin archive into your Qt Creator installation. It will have the same folder hierarchy as the Linux installation, just the installation path of the "Qt Creator" folder will be different.
> 
> > Could I edit UI factors and build them fullly on Qt6 for ROS directly?
> 
> What do you mean by "UI factors"? The Qt 6 is just the runtime for Qt Creator, it cannot be used to build your own programs. For this, you have to install Qt 6 additionally to Qt Creator.

Thank you for replying and I'm sorry I didn't make myself clear.
I have installed this plugin and copied them into Qt Creator's folder(win10+Qt Creator 6.0.2+MSVC 2019). I also ran the example of sending mesage on ros node, it worked well.
Next, I started  working on the example: https://qtcreator-ros.datasys.swri.edu/downloads/tutorials/videos/introduction/(Part%202)%20ROS%20QT%20Intro%20-%20Import,%20Build,%20and%20Run%20Settings.mp4

Here with 2 bugs:

1. "Adding new"--"ROS"--"Package" fail
In "Package Details", "Path" of pkg couldn't be set, it showed: The path "C:\catkin_qt\src" is not in the workspace.
Then I used dos and command "catkin_create_pkg" to solve it. 

2.While buiding my project, it came with errors

23:55:51: Running steps for project catkin_qt...
23:55:51: Could not start process "catkin_make"  --cmake-args -G "CodeBlocks - Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug .
Error while building/deploying project catkin_qt (kit: Desktop Qt 6.1.3 MSVC2019 64bit)
When executing step "CatkinMake Step"
23:55:51: Elapsed time: 00:00.

I also tried to open an existing Ros workspace and build the project, nothing changed in the project.
Till here, I'm comfused that whether I can edit and build Ros project directly on Qt Creator(ros commands worked). Or , maybe there are some mistakes about my settings. Please give me some instructions or examples on windows platform.

Thank you!

**Comment by christian-rauch** [comment]
I have never used ROS on Windows. So I can not properly test the plugin. I only tested that the plugin loads and that I could create a workspace. If there is a bug with the plugin that cannot be reproduced on Ubuntu/Linux, I will just rely on someone else to fix it and send a PR. Sorry.

If there is an issue with creating workspaces or packages via the UI, then I recommend doing this on the command line and just loading the workspace and packages via the plugin.

**Comment by kidxhac** [comment]
Thank you very much, I'll try and maybe update some results.

**Comment by e71828** [comment]
Hi, I have the same need, thanks very much. please tell me how to run `C:\opt\ros\noetic\x64\setup.bat` for qt to find the ros-disro.

if any, please help me how to build and run a test.

**Comment by christian-rauch** [comment]
The plugin for Qt Creator should load, but I haven't really tested it with ROS. I am not using ROS on Windows or macOS, so I cannot support these. The Windows and macOS support relies on the community. But I will review and merge PRs if they fix Windows or macOS issues with the plugin.

General ROS issues should be discussed at https://answers.ros.org.
