### ISSUE TITLE
Add CI and CD to the repo

### ISSUE THREAD

**Issue by veimox** [ros-industrial/ros_qtc_plugin#364]
I need to think it though a bit more. Ideas so far:
* Use jinja2 for templates -> clear out the building script
* Use a Makefile instead of plain bash script -> follow de facto scripting mechanisims
* User dockers that already have Qt and QtInstaller frameworks at the desired versions -> Simplify and accelerate workflow. We need to do json scripts for headless installation.
* Enable deployment for (1) github releases and (2) the current repo -> automatic deployment
* Run, at least, a build for every combination -> we have a builds/not-builds warning

The git flow I imagine is:
* For every push, compile (and tests if any)
* When there is a repo tag (e.g. 0.3.2), build and deploy

Question:
* Do we need to support all QtVersions? Right now there is a branch per version

**Comment by Levi-Armstrong** [comment]
> Use jinja2 for templates -> clear out the building script

Works for me, I have never used it but it looks nice. Do you have any examples where you have used this. A little off topic, we have been looking for a way to document examples where we could use a python script to strip out text from the cpp and create a rst for a wiki. Would jinja2 work for something like this.

> Use a Makefile instead of plain bash script -> follow de facto scripting mechanisims

I am not opposed to a Makefile, but what about using python? This is what Qt Creator [uses](https://github.com/qt-creator/qt-creator/blob/master/scripts/deployqt.py) then somehow you are able to call `make deployqt`.

> User dockers that already have Qt and QtInstaller frameworks at the desired versions -> Simplify and accelerate workflow. We need to do json scripts for headless installation.

This works for me. Should they be hosted [here](https://github.com/ros-industrial/docker)?

> The git flow I imagine is:

Sounds good to me.

> Do we need to support all QtVersions? Right now there is a branch per version.

I mainly been just following Qt Creator branching. Not all version are support on every distro due to Qt Creator drops support for later distros. We would just need to keep the latest for each distro.

**Comment by veimox** [comment]
> Python + jinja2

Let'd do it!
> Docker

If possible, would be perfect! We can create the docker file outside and then move it there.
> Git flow + Qt Creator versions

Roger

I will have some time by the end of the week, lets use this issue and the coming PR to discuss the progress :smile:

**Comment by Levi-Armstrong** [comment]
Sounds good.

**Comment by Levi-Armstrong** [comment]
@veimox Would you be interested in featuring a blog on ROS-Industrial on the perf tool and how ROS developers can leverage this tool?

**Comment by veimox** [comment]
Sure! I have checked the website and there is [already a post](https://rosindustrial.org/news/2019/7/3/new-release-ros-qt-creator-491-with-ros2-support), I imagine you are thinking in something different. If so, it would be nice to know: (1) target people, (2) where would be posted -to know the format-, (3) length of the post.

**Comment by veimox** [comment]
Updates for the CI/CD. 

I thought that the best is to have two or three different docker containers. 
1. Ubuntu/Xenial with the desired Qt libraries compiled
2. Using the previous one, compile QtCreator and any other tool we want so the compilation of the plugin is the fastest
3. Using the previous one, compile the plugin and, if desired, pack it and deploy it.

I am creating different repos and I am building in docker hub (is faster than travis). For the Qt one, here is the [repo](https://github.com/veimox/docker-qt) and here is the [docker](https://hub.docker.com/). For the QTC one, here is the [repo](https://github.com/veimox/docker-qtc) and here is the [docker](https://cloud.docker.com/u/veimox/repository/docker/veimox/qtc).

As you can see the QTC one fails. The issue is in the `make deployqt` where it updates the `rpath` of clang. Specifically:

```bash
new rpath '$ORIGIN/../lib:$ORIGIN/../../../../lib/Qt/lib' too large; maximum length 14
Traceback (most recent call last):
  File "/tmp/abcdefghijklmnopqrstuvwxyz/qt-creator/scripts/deployqt.py", line 351, in <module>
    main()
  File "/tmp/abcdefghijklmnopqrstuvwxyz/qt-creator/scripts/deployqt.py", line 341, in main
    common.fix_rpaths(install_dir, os.path.join(qt_deploy_prefix, 'lib'), qt_install_info, chrpath_bin)
  File "/tmp/abcdefghijklmnopqrstuvwxyz/qt-creator/scripts/common.py", line 164, in fix_rpaths
    fix_rpaths_helper(filepath)
  File "/tmp/abcdefghijklmnopqrstuvwxyz/qt-creator/scripts/common.py", line 146, in fix_rpaths_helper
    subprocess.check_call([chrpath, '-r', ':'.join(new_rpath), filepath])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/chrpath', '-r', '$ORIGIN/../lib:$ORIGIN/../../../../lib/Qt/lib', '/tmp/abcdefghijklmnopqrstuvwxyz/libclang/bin/llvm-mt']' returned non-zero exit status 7
Makefile:515: recipe for target 'deployqt' failed
```

In this step in [takes all binaries](https://github.com/qt-creator/qt-creator/blob/master/scripts/deployqt.py#L258) within the clang folder and updates the rpath. The issue is that these have an `rpath` that is very small because they are expressed as relative folders (`$ORIGIN/../lib`) and the relative path to our folder is longer (`$ORIGIN/../../../../lib/Qt/lib`).

I haven't got much time to look at it, but is a consistent error. What I wonder is how then it can compile for anyone else (including you :smile:) because I think I am following the same steps that are defined in the `master` branch and in the QTC repo.

PD: I am also using the repo from Qt, not the one from Github, because the `.submodules` are defined as relative paths and `perparser` is not forked in github, thus it fails in the cloning step.

**Comment by Levi-Armstrong** [comment]
> Sure! I have checked the website and there is already a post, I imagine you are thinking in something different. If so, it would be nice to know: (1) target people, (2) where would be posted -to know the format-, (3) length of the post.

I was thinking of a blog post that is focused on Perf and how ROS developers may leverage it for ROS development. I would say one to two pages should be good and if it is written in markdown I can easily upload to our ROS-Industrial website with little changes.

**Comment by Levi-Armstrong** [comment]
> I haven't got much time to look at it, but is a consistent error. What I wonder is how then it can compile for anyone else (including you smile) because I think I am following the same steps that are defined in the master branch and in the QTC repo.

I ran into the same issue, I believe I fixed it by putting Qt Creator source, ROS QTC source and Qt libraries under the same folder and then when mapping it to the docker, I mapped it as close to home as possible to keep both absolute and relative paths as short as possible.

**Comment by veimox** [comment]
@Levi-Armstrong Hi! I got some time free and I retook this issue. 

**Highlights:**
* We can have now CI. It takes around 2-5 minutes (depending on the service) to compile and pack. Pretty neat!
* I am using CircleCI for the pipeline because it supports "natively" run in an specified docker image (unlike travis). It also supports uploading and hosting artifacts meaning that we can have a binary (online/offline) per commit for local testing. 
* Example [here](https://circleci.com/gh/veimox/ros_qtc_plugin/19).

**Lowlights:**
* Compiling QtCreator in the pipeline is impossible. I have tried different free providers (travis, circleci, bitbucket pipelines) and all of them reach the maximum allowed limit before compiling. This means that we need to build the docker image is hosted infrastructure (it can be a laptop) and push to docker hub manually.
* I am compiling YamlCPP and Termwidget in the QtCreator compilation to speed up the CI process but that makes the docker image very tight to this plugin. I think this might be a problem in the future but is fine for now.
* I finally decided to got for bash scripting because the scripts are actually not that difficult to read and creates less dependencies.
* The scripts, templates and other resources are placed within the .circleci folder. This could change to support "local developer builds" but as of now there is not a clear guide on how another person can easily create a development environment. Besides the scripts rely on assumptions that are only true in the upstream docker image (e.g. exported environmental variables). Let me know what you think.

**Issues left:**
* Parametrize most of the variables (e.g. release date, release version from tag... etc).
* Port services to somewhere else more "official" than my accounts.
* Add deployment steps.
* Add secrets in such accounts so they can automatically push artifacts. Here I imagine we would have Github (for people that downloads from "releases" page) and the Qt Installer Online repo (for OTA updates).
* Documentation

**Workflow:**
There are two docker containers we build on top of:
1. Ubuntu/Xenial with the desired Qt libraries compiled: [repo](https://github.com/veimox/docker-qt) and [docker](https://cloud.docker.com/u/veimox/repository/docker/veimox/qt). Right now I am compiling bionic and xenial with 5.12.4.
2. QtCreator compiled [repo](https://github.com/veimox/docker-qtc) and [docker](https://cloud.docker.com/u/veimox/repository/docker/veimox/qtc). Right now I am compiling v4.9.2 for xenial and bionic.

This allows to test out the plugin with different combinations of Qt and QtCreator which is basically the main point of this effort :smile: 

**Next steps:**
1. Let me know what you think
2. I will be working in the rest of the issues in the coming days and prepare a PR.

**Comment by gavanderhoorn** [comment]
@Levi-Armstrong: do these scripts / `Dockerfile`s remind you of something? ;)

**Comment by Levi-Armstrong** [comment]
> @Levi-Armstrong: do these scripts / Dockerfiles remind you of something? ;)

Yep :)

**Comment by Levi-Armstrong** [comment]
@veimox This is great! I don't see any immediate issues, but I have a few questions.

1. Does it still package both Qt Creator and ROS Plugin?
2. Will the docker files remain in another repository or will they eventually be located in the .circleci folder?

Do to the current location of the repository for the online installer, we would need to package everything into a archive file and then we would be able to nightly check for this file and unpack it on our end into the correct location. Do you see any issues?

**Comment by veimox** [comment]
> Does it still package both Qt Creator and ROS Plugin?

It packs the exact same things as of today. You can try to download the [offline version](https://19-194495287-gh.circle-artifacts.com/0/tmp/abcdefghijklmnopqrstuvwxyz/installer/xenial/latest/qtcreator-ros-xenial-latest-offline-installer.run) from [here](https://circleci.com/gh/veimox/ros_qtc_plugin/19#artifacts/containers/0) and install it local it to check it out.

> Will the docker files remain in another repository or will they eventually be located in the .circleci folder?

Good question... As of now I had them in different because then I could use the push events to trigger a build. I prefer have different repos because we can tag them separately and know that [this](https://github.com/veimox/docker-qt/tree/5.12.4) tag is exactly the Qt 5.12.4 and we can deterministic and independently build that image at any point. It adds some overhead, but is only when we want to try out in a new QtCreator/Qt version combination.

**Comment by Levi-Armstrong** [comment]
Awesome! Sounds good to me.

**Comment by christian-rauch** [comment]
I recently added a GitHub workflow (https://github.com/ros-industrial/ros_qtc_plugin/blob/devel/.github/workflows/main.yml) to build a binary plugin archive that can be installed on top of a standard Qt Creator installation. Those archives are added to the GitHub release page which makes this very convenient. I thought we could maybe also create the installers in this workflow and add those to the release page too. The workflow already downloads the official binary distributions of Qt and Qt Creator. This is controlled by the versions defined in `versions.yaml`. So updating the workflow only requires updating the version in that file.

Alternatively, we could create a flatpak/snap package that gathers the official Qt Creator binaries and the release binary plugin archive without the need to compile those again.
