### ISSUE TITLE
perfparser not found?

### ISSUE THREAD

**Issue by facontidavide** [ros-industrial/ros_qtc_plugin#366]
I am very excited about the addition of perf to the project.

I followed the instructions [here](https://ros-qtc-plugin.readthedocs.io/en/latest/_source/Performance-Analysis.html), but I got this error

![image](https://user-images.githubusercontent.com/2822888/60421163-8bffe780-9be9-11e9-9bfd-73e9235a76f3.png)

**Comment by veimox** [comment]
@facontidavide This sounds like you dont have the latest version. Download the latest from the [release page](https://github.com/ros-industrial/ros_qtc_plugin/releases) and install. If you have a version already installed, you have to remove it (e.g. for the default installation path `rm -rf ~/QtCreator`)

**Comment by facontidavide** [comment]
I just removed the old one and installed the latest (0.3.8)

the components.xml file confirms it:

```XML
<Packages>
    <ApplicationName>Qt Creator with ROS Plug-in</ApplicationName>
    <ApplicationVersion>1.0.0</ApplicationVersion>
    <Package>
        <Name>org.rosindustrial.qtros</Name>
        <Title>Qt Creator for ROS</Title>
        <Description>Install Qt Creator for ROS Development</Description>
        <Version>1.0.11</Version>
        <LastUpdateDate></LastUpdateDate>
        <InstallDate>2019-07-03</InstallDate>
        <Size>0</Size>
    </Package>
    <Package>
        <Name>org.rosindustrial.qtros.latest</Name>
        <Title>Qt Creator (4.9.1)</Title>
        <Description>Installs the Qt Creator IDE</Description>
        <Version>4.9.1.0</Version>
        <LastUpdateDate></LastUpdateDate>
        <InstallDate>2019-07-03</InstallDate>
        <Size>565825407</Size>
        <Dependencies>org.rosindustrial.qtros</Dependencies>
        <Checkable>true</Checkable>
    </Package>
    <Package>
        <Name>org.rosindustrial.qtros.latest.rqtc</Name>
        <Title>ROS Plug-in (0.3.8)</Title>
        <Description>Installs the ROS Qt Creator Plug-in</Description>
        <Version>0.3.8.0</Version>
        <LastUpdateDate></LastUpdateDate>
        <InstallDate>2019-07-03</InstallDate>
        <Size>3122878</Size>
        <Dependencies>org.rosindustrial.qtros.latest</Dependencies>
    </Package>
</Packages>

```

**Comment by veimox** [comment]
The `perfparser` tool should be in `<install path>/latest/libexec/qtcreator/`, can you check is actually there?

**Comment by facontidavide** [comment]
Nope:

```
 df  ⋯  libexec  qtcreator  ls -l
total 43180
-rwxr-xr-x 1 df df    27688 Jun 30 03:16 buildoutputparser
drwxr-xr-x 4 df df     4096 Jul  3 15:28 clang
-rwxr-xr-x 1 df df   705736 Jun 30 03:16 clangbackend
-rwxr-xr-x 1 df df 20305904 Jun 30 03:16 clangpchmanagerbackend
-rwxr-xr-x 1 df df 21874928 Jun 30 03:16 clangrefactoringbackend
-rwxr-xr-x 1 df df   110536 Jun 30 03:16 cpaster
-rwxr-xr-x 1 df df     1384 Jun 30 02:37 dmgbuild
-rwxr-xr-x 1 df df    44216 Jun 30 03:16 qbs_processlauncher
-rwxr-xr-x 1 df df   686328 Jun 30 03:16 qml2puppet
-rwxr-xr-x 1 df df    14904 Jun 30 03:16 qtc-askpass
-rw-r--r-- 1 df df      103 Jun 30 03:16 qt.conf
-rwxr-xr-x 1 df df    14856 Jun 30 03:16 qtcreator_process_stub
-rwxr-xr-x 1 df df    48288 Jun 30 03:16 qtpromaker
-rwxr-xr-x 1 df df   352672 Jun 30 03:16 sdktool
```

**Comment by veimox** [comment]
Then undoutbly, the error is correct :smile: 

I have downloaded and installed latest versions of both `xenial` and `bionic` and I confirm that `perfparser` is ONLY deployed in `bionic`.

@Levi-Armstrong Is it possible that the `xenial` version has to be redeployed with `perfparser`?

**Comment by Levi-Armstrong** [comment]
Ok I will get it fixed.

**Comment by Levi-Armstrong** [comment]
I found what went wrong. I am rebuilding things and have fixed the install script. I let you know when it is available.

**Comment by facontidavide** [comment]
awesome

**Comment by Levi-Armstrong** [comment]
I uploaded new offline installers for xenial and bionic to release 0.3.8 which have also been update to 4.9.2. Tomorrow I will update the repo for the online installer. Let me know if you have any issues.

**Comment by facontidavide** [comment]
fixed, thanks!

**Comment by Levi-Armstrong** [comment]
The online repository has been updated so you can perform an update if using the online installer.
