### ISSUE TITLE
StartupWMClass: Desktop Shortcut not Working Properly on Ubuntu 18.04

### ISSUE THREAD

**Issue by beetleskin** [ros-industrial/ros_qtc_plugin#367]
On Ubuntu, the [installer](https://github.com/ros-industrial/ros_qtc_plugin/releases) creates a .desktop file at `~/.local/share/applications/QtProject-qtcreator-ros-latest.desktop`. When one puts this into the dock and uses it, new instances are created instead of opening the existing one:

![Screenshot from 2019-07-02 09-43-02](https://user-images.githubusercontent.com/3697554/60493895-114cd000-9cae-11e9-9341-fc0c3edae301.png)

The reason is the changed _StartupWMClass_ which this distribution changes to _qtcreator-ros_ (from _qtcreator_?). To fix this, I always add `StartupWMClass=qtcreator-ros` to the generated/cloned .desktop file.

**Comment by Levi-Armstrong** [comment]
So the desktop file should like the following?
```
[Desktop Entry]
Type=Application
Exec=/home/QtCreator/latest/bin/qtcreator-ros
Path=/home/QtCreator/latest
Name=Qt Creator (4.9.1)
GenericName=The IDE of choice for Qt development.
GenericName[de]=Die IDE der Wahl zur Qt Entwicklung
Icon=QtProject-qtcreator
Terminal=false
StartupWMClass=qtcreator-ros
Categories=Development;IDE;Qt;
MimeType=text/x-c++src;text/x-c++hdr;text/x-xsrc;application/x-designer;application/vnd.qt.qmakeprofile;application/vnd.qt.xml.resource;text/x-qml;text/x-qt.qml;text/x-qt.qbs;
```

**Comment by Levi-Armstrong** [comment]
I added `StartupWMClass=qtcreator-ros` to the .desktop file. I will update online installers tomorrow.

**Comment by Levi-Armstrong** [comment]
I just install the latest and it appears to work now. I will wait to close until you provide confirmation that it is working.

**Comment by Levi-Armstrong** [comment]
The online installer repository has been updated, check for updates and let me know if the issue still exists.

**Comment by beetleskin** [comment]
Looking good, and I'd love to verify, but when hitting the update-button, the MaintainanceTool freezes. Right after clicking "Next":

![Screenshot from 2019-07-05 21-05-53](https://user-images.githubusercontent.com/3697554/60741166-b72b6380-9f68-11e9-91c6-a48748664460.png)

Not sure if this is related to the last update.

**Comment by beetleskin** [comment]
.. Seems to be solved (just tried it again after restart ^^).

Wörks! Thanks!
