### ISSUE TITLE
Control + Click functionality very slow

### ISSUE THREAD

**Issue by RohanBampal** [ros-industrial/ros_qtc_plugin#369]
I just installed version 0.3.8 from an older version (don't remember the version, it was 1 year back).
First thing I noticed was after building the project, the Control+Click functionality was very slow(takes 1-2 minutes to work) and would only work fast 1-2 minutes after building is completed.
I am using Ubuntu 16.04
I am running QtCreator by `qtcreator-ros.sh` since the plain `qtcreator-ros` has conflicts

**Comment by Levi-Armstrong** [comment]
Qt Creator has switch to using Clang Code Model and it can be slow. I would recommend change some of the settings for the clang code model.

**Comment by RohanBampal** [comment]
Ok. Thanks!
