### ISSUE TITLE
Help with setup.

### ISSUE THREAD

**Issue by RickBlacker** [ros-industrial/ros_qtc_plugin#37]
Hi Levi.

I'm not sure where else I'm supposed to send you this, I looked for an email address but didn't see one. I apologize if this is the incorrect location to to be asking these questions.

I'm pretty new to Linux, QT and ROS. So, I'm sorry if the questions I'm about to ask are very basic... 

I'm trying to get your ROS QT plugin setup properly but having some issues. I'm sure it's all user error from not undertanding all this properly.

In your WIKI, you said download the latest version of QT. I already have QT installed sure it's up to date. 

In step 1.1, you mention to configure QT Chooser to look at :
/home/<username>/Qt/<version>/gcc_64/bin
/home/<username>/Qt/<version>/gcc_64/lib

I'm curious why I'd need to tell QT Chooser to look here when QT is already setup just fine with my pre existing install of QT.

In step 1.2 I'm going on the assumption that this is an either-or.  Either setup for users or setup for developers. Yes? For now I just want to setup for users. I saved the bash script and executed it. As you probably know, this created the qtc_plugins folder. I also noticed that it downloaded what looks to be a full install of QT via the qt-creator directory.  I'm curious to know what this is for. 

in setup 1.3, you mention launch QT creator via the command prompt $qtcreator. When I run this I get an error stating "The program qtcreator is currently not installed .......

However, QT launches just fine if I click the icon from app launcher. When I launch from the app launcher, I go into new project, import project, I don't see any type of ROS workspace.

Was hoping you might be able to shed some light on my issues.

Thanks!

**Comment by Levi-Armstrong** [comment]
The current version of the plugin is built for Qt Creator 4.0 which has a dependency requirement for Qt 5.5.0 or later. Now there is another option if you don't want to build from source you can follow the process described in this issue #17 it provide a Debian for both Indigo and Kinetic but you have to install Qt from a ppa.

What version of Ubuntu are you using?

**Comment by RickBlacker** [comment]
Hey Levi, thanks for the quick response.
I'm using Ubuntu 16.04 on this particular machine

**Comment by Levi-Armstrong** [comment]
So the wiki was written with 14.04 in mind along with the setup script. If you don't mind I can walk you through how to get it installed on 16.04 with the current version Qt which should be good on 16.04. 

Can you check and make sure that ros_qtc_plugin was full cloned into the qtc_plugins directory?

**Comment by RickBlacker** [comment]
I don't mind at all. :)
I have at my "Home" directory folder structure that looks like this...
Home/DEVELOPMENT_APPS/QT

From there I downloaded the setup.sh script, after running that script, I ended up with
Home/DEVELOPMENT_APPS/qtc_plugins/

Inside the plugins folder I have this.

Home/DEVELOPMENT_APPS/qtc_plugins/qt-creator
Home/DEVELOPMENT_APPS/qtc_plugins/qt-creator-build
Home/DEVELOPMENT_APPS/qtc_plugins/ros_qtc_plugin
Home/DEVELOPMENT_APPS/qtc_plugins/ros_qtc_plugin_build

It DOES look like /qtc_plugins/ros_qtc_plugin was fully cloned.

**Comment by Levi-Armstrong** [comment]
Ok let me look into it a little more and I will get back to you soon. I may be able to get a deb that will work to solve the problem.

**Comment by RickBlacker** [comment]
Awesome. My goal is to be able to do ROS development in QT. I come from a Microsoft world so I'm used to Visual Studio and it's environment.  Ramping up in the Linux world is a bit complex in comparison.  :)

**Comment by RickBlacker** [comment]
Hi Levi... Was hoping to find out how things are coming along with this?  :)

**Comment by Levi-Armstrong** [comment]
It looks like it will take a little longer than expected. If would like to start using it know we do have debian for 16.04 but it will require you to use qt57 from a third party ppa. The install process is below and once I finish the native debian you will be able to remove everything and install the new version.

Build of 1d247be1 for Xenial (and on top of `ppa:beineri/opt-qt57-xenial`): [qt57creator-ros-plugin_0.1.0-git-1d247be1_amd64_xenial.deb.zip](https://github.com/ros-industrial/ros_qtc_plugin/files/366418/qt57creator-ros-plugin_0.1.0-git-1d247be1_amd64_xenial.deb.zip)

Setup for Xenial:

```shell
sudo add-apt-repository ppa:beineri/opt-qt57-xenial
sudo apt-get update
sudo apt-get install qt57creator qt57-meta-minimal
```

Now download the above `.deb.zip` somewhere, rename to just `.deb`. Then:
```shell
sudo dpkg -i /path/to/wherever/you/saved/qt57creator-ros-plugin_0.1.0-git-1d247be1_amd64_xenial.deb
```

There should be an icon for `Qt 5.7 Creator` in the Dash. If there isn't, start `/opt/qt57/bin/qtcreator-wrapper`. That should start the right version of Qt Creator, with the plugin.

**Comment by RickBlacker** [comment]
Does this mean I need to uninstall the existing QT Creator that I have installed?
And if so, what is the proper way to do this in Ubuntu?  Sorry, I know lame question, but I've been in the Microsoft world all my adult life. ;)

**Comment by Levi-Armstrong** [comment]
You should not have to. If you have issues after installing it let me know.

**Comment by RickBlacker** [comment]
Do I NEED to keep the existing version of QT Creator?  Seems like I don't.  Also, I don't have any existing projects that rely on this version of QT creator.

**Comment by gavanderhoorn** [comment]
On 10-8-2016 18:35, Rick wrote:
> Do I NEED to keep the existing version of QT Creator?  Seems like I don't.  Also, I don't have any existing projects that rely on this version of QT creator.

No, there is no need to keep your current version.

The instructions Levi copied will install a stand-alone version 4 Qt 
Creator and the corresponding Qt version (5.7) from the PPA. The plugin 
deb will install the plugin into the correct location.

Note that it only works for x64 installations, Ubuntu Xenial and that 
specific PPA.

**Comment by Levi-Armstrong** [comment]
@RickBlacker, I was able to get a Debian release on Launchpad.net; see the latest comment [here](https://github.com/ros-industrial/ros_qtc_plugin/issues/17). Would you mind following the wiki and let me know if everything works on Xenial?
