### ISSUE TITLE
Very slow typing when adding new Colcon arguments to build step

### ISSUE THREAD

**Issue by schornakj** [ros-industrial/ros_qtc_plugin#375]
When I add Colcon arguments to my build step (for example, `--packages-up-to my_package`), there is a very long pause in between when I type each character and when the characters are actually entered in the field.

I think this is because the whole workspace is being (unnecessarily?) re-sourced repeatedly whenever this text entry field is updated.

**Comment by Levi-Armstrong** [comment]
> I think this is because the whole workspace is being (unnecessarily?) re-sourced repeatedly whenever this text entry field is updated.

I have noticed the slow typing. Have you confirmed that it is constantly sourcing?

**Comment by Levi-Armstrong** [comment]
You are correct it is sourcing every time it should be using the current environment instead of sourcing and pulling it every time. 

https://github.com/ros-industrial/ros_qtc_plugin/blob/4.9/src/project_manager/ros_catkin_tools_step.cpp#L377-L381

**Comment by Levi-Armstrong** [comment]
Addressed by #377
