### ISSUE TITLE
ros_qtc_plugin0.3.10 didn't work properly on Ubuntu 18.04

### ISSUE THREAD

**Issue by mptangtang** [ros-industrial/ros_qtc_plugin#381]
I am using Ubunt 18.04 LTS and downloaded the ros_qtc_plugin 0.3.10 from the website
https://github.com/ros-industrial/ros_qtc_plugin/releases/download/0.3.10/qtcreator-ros-bionic-latest-offline-installer.run

However, there are some problems when I use it. 

After I creare a new ros package, the tree view doesn't refresh unless I restart  the QtCreator.

```
When I try to build the simplest node using the plugin, there are errors as follows:
[ROS Warning] Unable to locate build directory for package: myfetch_gazebo.
[ROS Warning] Failed to source workspace because this file does not exist: /home/user/qtros_ws/myfetch_ws/devel/setup.bash.
[ROS Warning] Failed to source workspace because this file does not exist: /home/user/qtros_ws/myfetch_ws/devel/setup.bash.
```

Another question is that what's the principle of ros_qtc_plugin?

**Comment by Levi-Armstrong** [comment]
I recommend recommending using the installer links from the wiki preferably the online installer so you get notified of updates. If you use the offline installer it is on you to check for updates manually.

The print out you provided are labeled as warning and can occur if the project has not successfully been built from within qt creator.

>After I create a new ros package, the tree view doesn't refresh unless I restart the QtCreator.

This is a known bug #350 

>Another question is that what's the principle of ros_qtc_plugin?

It adds the functionality to Qt Creator on how to build and run ROS workspaces. It manages the Code model so you use all of the normal functionality of Qt Creator (Syntax Highlighting, Code Completion, etc. ) There is much more but I recommend reading the wiki and watching the tutorials for more information. 

If after the workspace builds successfully from withing qt creator and code completion and syntax highlighting is working then it is functioning as expected. Now if after a successful build and those things do not work then there may be either an issues with your cmake or the plugin. If this is a case please provided a basic example workspace to replicate the issue you are experiencing.

**Comment by mptangtang** [comment]
Thank you very much.

The ros_qtc_plugin0.3.10 works well for me except it won't refresh the new
ros packages. I have to reopen the project to reload the project. However,
it is still tolerable.

Thanks a lot for your help



Levi Armstrong <notifications@github.com> 于2019年8月6日周二 上午9:13写道：
