### ISSUE TITLE
Leading dot inserted on every file save

### ISSUE THREAD

**Issue by pavloblindnology** [ros-industrial/ros_qtc_plugin#383]
Hi.
After installing the latest version 4.9.2.2 + 0.3.10, I have period "." inserted at the very beginning of file on each file save (after any editing). Tried to turn off automatic whitespace cleaning, indentation, tabulation options - no help.
Very annoying.

**Comment by Levi-Armstrong** [comment]
Please post a screen shot.

**Comment by pavloblindnology** [comment]
After further investigation I found that it's not period symbol, it's U+FEFF symbol which defines bytes order.

**Comment by pavloblindnology** [comment]
Aha. Just need to set Tools->Options->Text Editor->File Encodings->UTF-8 BOM to Always delete.
