### ISSUE TITLE
Plugin won't detect ROS distribution

### ISSUE THREAD

**Issue by ybabs** [ros-industrial/ros_qtc_plugin#385]
I'm having issues getting the Plugin to detect the detect my ros version. Nothing gets populated in the distribution section. 

![image](https://user-images.githubusercontent.com/29642663/63519017-1bd75900-c4ea-11e9-8188-195f7aa18abf.png)

I create the workspace and try to create a package and I run into other issues as well.
![image](https://user-images.githubusercontent.com/29642663/63519193-6a84f300-c4ea-11e9-8e5d-b610c40f888f.png)
The package folder isn't created in my workspace and doesn't show in QT. When I navigate to the folder, nothing is created there as well. 

Any tips?

**Comment by Levi-Armstrong** [comment]
Where is ros installed? It looks in /opt/ros but if it is in a different location go to Tools>Options>ROS and change the location it looks for ros.

![image](https://user-images.githubusercontent.com/9803128/63523629-16651900-c4c0-11e9-90f3-9b90c044e15a.png)

**Comment by ybabs** [comment]
Ah, I just checked, and it was pointing to opt/ros/kinetic. i changed that and I seem to get a distro now
![image](https://user-images.githubusercontent.com/29642663/63524020-1df1e580-c4f3-11e9-81e8-5b7bd720b662.png)

However, when I still create a package within the workspace. Nothing seems to be created. There are no CMake files present in the toplevel directory and the package directory isn't created as well

![image](https://user-images.githubusercontent.com/29642663/63524116-55f92880-c4f3-11e9-89a5-3df3e84cdaf0.png)

**Comment by Levi-Armstrong** [comment]
>However, when I still create a package within the workspace. Nothing seems to be created. There are no CMake files present in the toplevel directory and the package directory isn't created as well

I believe this is related to an existing issue. If you close the project and open it again does it show up?

**Comment by ybabs** [comment]
Not at all. I've tried building with catkin make as well but it's the same issue. I can currently edit the files and add the files manually in another IDE e.g. vscode and I can build them from QT.  I just can't seem to view them for some reason. Interestingly enough, I'm running into similar issues when just trying to build my workspace using normal Qt without the plugin. I'm going to test this on another system and see if I run into the same issues.

**Comment by Levi-Armstrong** [comment]
@InterestingWalrus Did you run into the same issue on the other machine?

**Comment by ybabs** [comment]
Hi, unfortunately yes I did. I tried installing on a fresh install of 18.04 and melodic and I ran into the same issues. I eventually decided to  use vscode for now

**Comment by ybabs** [comment]
Hi, revisiting this issue, I was wondering if you had any pointers. I'm able to create the workspace but I notice the Cmakelist file isn't created by the plugin and the src folder doesn't  exist in workspace even though it's shown in qt

**Comment by ybabs** [comment]
Decided to setup Qt cmake with vscode instead.
