### ISSUE TITLE
My Qt plugin can't recognize ros, can't jump to ros.h

### ISSUE THREAD

**Issue by ghost** [ros-industrial/ros_qtc_plugin#388]
I got following warning in General Messages:

[ROS Warning] Unable to locate package add_bootup build file: /home/user/workspace/build/add_bootup/add_bootup.cbp.

This is weird, it works fine on the other computer

**Comment by Levi-Armstrong** [comment]
This is normal if the package does not contain c++ code. If it does include c++ code then this is an issue. The plugin uses the code block file to generate the internal code model.
