### ISSUE TITLE
Ros distribution not recognized?

### ISSUE THREAD

**Issue by Anne0112** [ros-industrial/ros_qtc_plugin#389]
Hello,

I installed the Qt ROS plugin. I am running it on Ubuntu 18.04 and use ROS melodic. I can create a new Ros project. However, when I try to create a new Ros project I can't select any distribution as there is nothing in the dropdown menu in the pop up.

When I then build my workspace I get the following issue: The source directory "home/anne/catkin_ws/src" does not exist.

I am able to catkin make my workspace from shell and don't understand why I can't select the Ros distribution. Any idea what the problem can be?

**Comment by turinglife** [comment]
please refer to "https://github.com/ros-industrial/ros_qtc_plugin/issues/385".

there is another method that reinstall the ros melodic according to the official guideline. For example, http://wiki.ros.org/melodic/Installation/Ubuntu.
