### ISSUE TITLE
PCL auto-complete not working

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/ros_qtc_plugin#39]
I'm not sure if this is an issue or not.  I've been working with a node that uses PCL, but the auto-complete is not working.  I had to add (manually) the following to the workspace file:
`
        <Directory>/usr/include/pcl-1.7</Directory>
`
Is this a known issue or user error?  Should QT automatically add this based on the `CMakeLists.txt`?

**Comment by gavanderhoorn** [comment]
> Should QT automatically add this based on the `CMakeLists.txt`?

afaict, yes.

Are the correct set of include dirs exported by the package you are working on?

**Comment by Levi-Armstrong** [comment]
You should not not have to add it manually, but anytime a new library is added to the cmakelists.txt or a new package is added you will need to Reload Project Include Directories.... The Reload should of solved the issue if you run into this issue again please let me know.  If you right click on the root node of the project tree you should see the Reload option.

I am currently working on an improvement to manage this internally so the user does not have to manually update the code model, but it is not ready yet.

**Comment by shaun-edwards** [comment]
@Levi-Armstrong, thanks for the quick reply.  I'll try the `Reload` next time.

**Comment by Levi-Armstrong** [comment]
@shaun-edwards, if you get a chance run it and let me know if it disappears? If it does, then I will mark it as a bug.
