### ISSUE TITLE
Qt ROS crosscompilation

### ISSUE THREAD

**Issue by ftheirs** [ros-industrial/ros_qtc_plugin#393]
Hi levi!
I'm working with ROS and a jetson TX2 and I have configured my QtCreator to compile my applications for Desktop and my embedded platform.
Now, I want to work in the same way with my ROS project but I have some problems.
I cannot set ROS paths to /opt/ros/kinetic (in jetson tx2), QtCreator takes automatically /opt/ros/melodic (desktop configuration). I am sure that my crosscompile kit is working fine since I can compile the ROS project but when I run some nodes work fine and others want to link against my desktop ROS distribution.
Is there any tutorial to configure Qt ROS plugin to crosscompile? I really want to try this out to save an enormous amount of time.

Desktop
Kubuntu 18.04
ROS: melodic
Qt Creator 4.9.2 Based on Qt 5.12.4 (GCC 7.4.0, 64 bit)

JetsonTx2
Ubuntu 16.04
ROS: kinetic
Qt 5.10.1

Thanks!

**Comment by loulansuiye** [comment]
I hope know this answer too,thx

**Comment by Levi-Armstrong** [comment]
In the latest version you should be able to select the path to the ros distribution when importing it into qt creator.  Your .workspace file should look like what is below

```
<?xml version="1.0"?>
<Workspace>
    <Distribution path="/opt/ros/melodic"/>
    <DefaultBuildSystem value="1"/>
    <WatchDirectories>
        <Directory>src</Directory>
    </WatchDirectories>
</Workspace>
```
