### ISSUE TITLE
how can compile out this ros_qtc_plugin  plugin with src with qt creator

### ISSUE THREAD

**Issue by loulansuiye** [ros-industrial/ros_qtc_plugin#394]
every time when I  try  to compile the ros_qtc_plugin src in qt creator .The ide always reminds me ,there are lots of header files and libraries have been included ,especially  some explore etc

**Comment by Levi-Armstrong** [comment]
I am not following. I assume you are building the plug-in from source. If you are having issues you may take a look at the currently PR which has a lot of detail on how to build the plug-in.

**Comment by christian-rauch** [comment]
The build instructions changed significantly and do not require to compile Qt Creator from source on supported architectures. Try the new instructions and open a new issue if those do not work for you. I am going to close this since the old instructions are not supported anymore.
