### ISSUE TITLE
variable value marked as "optimized out"

### ISSUE THREAD

**Issue by SeanGuoXuan** [ros-industrial/ros_qtc_plugin#397]
I have been experienced with variable value marked as "optimized out" during debugging. Can someone give hints how to resolve this?

OS: ubuntu 18.04
qt: Qt Creator 4.9.2
ros: melodic

**Comment by Levi-Armstrong** [comment]
If it is optimized out, the library was built with optimization turned on. If it is a package within your workspace then make sure in the build configuration it is using debug. If it is at the system level you will need to see if the library provides debug symbols or build it from source within your workspace.

**Comment by SeanGuoXuan** [comment]
it is due to dependent package camkelist file configuration issue. Problem solved.
