### ISSUE TITLE
integrate the ROS Qt plugin into ROS2 on Windows and Ubuntu18.04?

### ISSUE THREAD

**Issue by gleke** [ros-industrial/ros_qtc_plugin#399]
Hello,

I am working with Qt Creator 4.11.0 and running ROS2 on Windows 10 and Ubuntu18.04. Are there plans to integrate the ROS Qt plugin into ROS2 on Windows and Ubuntu18.04?

Thanks!

**Comment by Levi-Armstrong** [comment]
There is but not sure when it will happen, but PR are welcome.

**Comment by christian-rauch** [comment]
The plugin needs [`qtermwidget`](https://github.com/lxqt/qtermwidget), which is currently not supported on Windows. If someone manages to build qtermwidget on Windows and get the patches merged upstream, we can enable the CI configuration (https://github.com/ros-industrial/ros_qtc_plugin/blob/devel/.github/workflows/main.yml) to test this.

Until then, I think there is nothing that we can do in this repo. I am going to close this, but feel free to reopen this once Windows support was added to qtermwidget.
