### ISSUE TITLE
Compilation errors with QTC 4.1

### ISSUE THREAD

**Issue by rhaschke** [ros-industrial/ros_qtc_plugin#40]
The plugin is bound to QTC 4.0. Compilation against latest branch 4.1 fails with lot of errors.

**Comment by Levi-Armstrong** [comment]
It is currently only been tested against QTC 4.0. Is there a particular need from 4.1? The reason I ask is I have a few items that I am working and it may be a while until I upgrade it to 4.1.

**Comment by Levi-Armstrong** [comment]
@rhaschke, I have updated the package and it now compiles against qtcreator version 4.1.

**Comment by rhaschke** [comment]
Cool, thanks!
