### ISSUE TITLE
support for Jetson TX2 with a system of ubuntu18.04? Which is arm64 arhitecture.

### ISSUE THREAD

**Issue by ShieldQiQi** [ros-industrial/ros_qtc_plugin#400]
I can't run the "online install .run" file because a “invaild encoding” error, which I guess result from the arm64 arhitecture.
Then I tried to install it in a "developer mode", but there is no for 18.04 bionic.
Thank you.

**Comment by liangChengGit** [comment]
me too, the resanon is arm64 arhitecture , so we can build srouce to install .
==  Missing        : libqtermwidget57-0-dev
==  Missing        : python-catkin-tools

**Comment by ShieldQiQi** [comment]
> me too, the resanon is arm64 arhitecture , so we can build srouce to install .
> ==  Missing        : libqtermwidget57-0-dev
> ==  Missing        : python-catkin-tools
> 

haha, It has been a long time.
I didn't use this plugin in my TX2 finally. I tried to insert my workspace into the Qt creator by modify the CMakelist.txt, just as the ros wiki tutorial said. And if I need a Qt GUI, I will import another ros-qt ros-package in my workspace.

**Comment by Levi-Armstrong** [comment]
I have some time freeing up in December where I will be switching to leveraging snapcraft for deployment which should make this possible with little effort.

**Comment by BernardinD** [comment]
Any news on this?

**Comment by christian-rauch** [comment]
> Any news on this?

You should be able to build the plugin from source on any architecture. Do you get any compilation errors?

**Comment by BernardinD** [comment]
@christian-rauch sorry for the late response, my focus changed for a while. But I can't seem for find the source installation for the plugin. I'm looking at the wiki but I don't see any source instructions

**Comment by Jiac-W** [comment]
Hello, @ShieldQiQi,  how can I import the workspace into Qt Creator by modifying the CMakeLists.txt file on TX2?

**Comment by ShieldQiQi** [comment]
> Hello, @ShieldQiQi, how can I import the workspace into Qt Creator by modifying the CMakeLists.txt file on TX2?

https://www.cnblogs.com/QiQi-Robotics/p/13569508.html
this blog may help, you can refer to the ROS wiki "ROS IDE" part also. 

The fact is by modifying the CMakeList file to let the Qt Creator know this project is a CMake project

you can find my Qt-ROS Proj CMAKELIST file here: https://github.com/ShieldQiQi/TX2_StereoSLAM/blob/master/src/CMakeLists.txt
