### ISSUE TITLE
Code model failing to parse includes when a non related package exists

### ISSUE THREAD

**Issue by williamhaarhoff** [ros-industrial/ros_qtc_plugin#401]
I've been using the ros_qtc_plugin for a couple of years now with no issues until now. 

I have two packages:
- weeding_abstract
- weeding_examples

The abstract package defining an api, and a companion package with examples showing usage. Since splitting the code between these two packages my syntax highlighting has stopped working in the abstract package. The abstract package still builds shared libraries which should be used by the example package. 

Here is my directory layout:

```
├── weeding_abstract
│   ├── CMakeLists.txt
│   ├── include
│   │   └── weeding_abstract
│   │       └── abstract_arm_ros_interface.h
│   ├── package.xml
│   └── src
│       └── abstract_arm_ros_interface.cpp
└── weeding_examples
    ├── CMakeLists.txt
    ├── include
    │   └── weeding_examples
    ├── package.xml
    └── src
```

The really weird behaviour occurs when I delete the weeding_examples package and rebuild weeding_abstract, the code model is able to parse the abstract_arm_ros_interface.h in the weeding_abstract package. Once I restore the weeding_examples package and rebuild abstract_arm_ros_interface.h is not parsed by the code model and syntax highlighting breaks. 

Both weeding_abstract and weeding_examples are valid catkin packages, both can be built without errors. 

To continue determining the nature of this issue, I completely removed all code from the weeding_examples package and broke all dependencies between weeding_examples and weeding_abstract. It seems just the mere presence of a package named weeding_examples in the workspace seems to be causing these issues. 

I can supply a minimal reproducible example if this would help. 
Many thanks

**Comment by Levi-Armstrong** [comment]
A minimal example would help so I can inspect the code model and code block files cmake generates which are used to generate the code model.

**Comment by williamhaarhoff** [comment]
Thanks for your quick response. I've made a [minimal example](https://github.com/williamhaarhoff/rosqtc_reproducible_bug).

Building both weeding_abstract and weeding_examples packages and it fails parse properly. 
Removing weeding_examples and rebuilding causes parsing to work on my machine. 

I am using Qt 4.9.2(4.9.0)

Thanks

**Comment by williamhaarhoff** [comment]
Hi Levi, 

Any luck with that minimal example repo?

**Comment by nicolasfrick** [comment]
Hi Levi,

I have the same issue with indexing but only if I build with ```catkin_make```. If I use ```catkin build``` the imports can be resolved by qt creator, afterwards I can use ```catkin_make```. I want to use ```catkin_make``` for this project and have to run ```catkin_build``` in advance every time I started qt creator. If I restart and don't build with ```catkin build``` first, it's not working.
Do you have any suggestions what causes this behaviour?

Thank you very much.

**Comment by gavanderhoorn** [comment]
> I want to use `catkin_make` for this project [..]

somewhat off-topic, but genuinely curious: what's the reason you'd like to use `catkin_make`?

**Comment by Levi-Armstrong** [comment]
Ah, that explains it. I only use `catkin build` and `catkin_make` has not been tested thoroughly. It will take some time to track down the bug and create a fix. As @gavanderhoorn stated, is there a reason  why you are using `catkin_make`?

**Comment by nicolasfrick** [comment]
The reason was because the ```<project name>_SOURCE_DIR``` variable is used in my CMakeLists.txt to reference another package. As it's not set by ```catkin build``` I switched to ```catkin_make```. I guess I'd have been better searched for substituting the variable instead of digging hours in the wrong direction.. I also read a bit about both build tools now and apparently ```catkin build``` is the one to prefer :) Thank's for your answers!
@Levi-Armstrong  please notice that I wasn't the one who started this issue, probably it doesn't solve @williamhaarhoff 's problem. I hope it was ok to join in here.

**Comment by gavanderhoorn** [comment]
> The reason was because the `<project name>_SOURCE_DIR` variable is used in my CMakeLists.txt to reference another package. As it's not set by `catkin build` I switched to `catkin_make`

Two comments here:

 - `<project_name>_SOURCE_DIR` is a standard CMake variable ([docs](https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_SOURCE_DIR.html)). It's not set by either `catkin_tools` or `catkin_make`, but by CMake when the `project(..)` statement is encountered.
 - using relative locations between packages is -- if I understand correctly what you're doing -- a rather big code smell. Definitely not something you should be doing, regardless of which build tool you use, or whether it works or not.

**Comment by Levi-Armstrong** [comment]
@williamhaarhoff Are you using `catkin build` or `catking_make`?

**Comment by Levi-Armstrong** [comment]
@williamhaarhoff I tracked down the issue. For some reason it does not work if you set the package xml version to 2.0. If you change this to 1.0 everything works. When set to 2.0 it fails to parse the package.xml files in the workspace causing issues.

**Comment by Levi-Armstrong** [comment]
@williamhaarhoff Is there a 2.0 version of xml?

**Comment by gavanderhoorn** [comment]
Afaik only `1.0` and `1.1` are valid values.

Could it be there is/was some confusion about "ROS package format 2" and "XML version 2"?

**Comment by williamhaarhoff** [comment]
Thanks, changing the package xml version fixes my issue. Yes I must have accidentally set the xml version when I intended to only set the ROS package format. 

For reference I use catkin build.

**Comment by nicolasfrick** [comment]
> > The reason was because the `<project name>_SOURCE_DIR` variable is used in my CMakeLists.txt to reference another package. As it's not set by `catkin build` I switched to `catkin_make`
> 
> Two comments here:
> 
>     * `<project_name>_SOURCE_DIR` is a standard CMake variable ([docs](https://cmake.org/cmake/help/latest/variable/PROJECT-NAME_SOURCE_DIR.html)). It's not set by either `catkin_tools` or `catkin_make`, but by CMake when the `project(..)` statement is encountered.
> 
>     * using relative locations between packages is -- if I understand correctly what you're doing -- a rather big code smell. Definitely not something you should be doing, regardless of which build tool you use, or whether it works or not.

Thanks @gavanderhoorn, indeed it was dirty. I've changed the project and have a clean build file now. Also, I can use ```catkin build``` again.
