### ISSUE TITLE
forget to run source devel/setup.bash before run

### ISSUE THREAD

**Issue by wegatron** [ros-industrial/ros_qtc_plugin#403]
when use debug configuration It failed to run the launch file, the release configuration works fine. it seems forget to run `source devel/setup.bash`. The plugin I use is [lastest version](https://github.com/ros-industrial/ros_qtc_plugin/releases/download/0.3.10/qtcreator-ros-bionic-latest-offline-installer.run)
the output in ROS Terminals:
![image](https://user-images.githubusercontent.com/6188292/79715769-4262c380-8307-11ea-9b86-80813a3a340d.png)

The program can start if I run the `source devel/setup.bash` and then run the launch command manually. The Release configuration works fine too.

**Comment by christian-rauch** [comment]
There has been a new release that can be installed on top of a standard Qt Creator installation. I am using this for a while now without issues. I am going to close this for now, but please reopen this if your issue still persists with the newest 0.4 release.
