### ISSUE TITLE
Release for Qt Creator 4.14

### ISSUE THREAD

**Issue by christian-rauch** [ros-industrial/ros_qtc_plugin#406]
Are there plans to release an installer for the newer Qt Creator 4.13?

The last release is nearly a year ago and newer Qt Creator versions deal better with HiDPI screens.

**Comment by Levi-Armstrong** [comment]
I do. I have time coming up where I plan to upgrade and fix some issues with it. I also plan to release it as a snap package and update CI so these are automatically generated to simplify the release process.

**Comment by christian-rauch** [comment]
That's awesome! Thanks. I very much prefer an auto-updated snap package over the manual installer.

You need a sponsor button for this project :-)

**Comment by v4hn** [comment]
[Cross referencing another discussion on newer versions of QtCreator](https://github.com/ros-industrial/ros_qtc_plugin/pull/387#issuecomment-640793670).

Personally, I run neither Ubuntu nor a snap ecosystem. I believe the biggest issue is not setting up better deployment, but actually patching for the API of newer qtc versions. It looks like the long term plan has been (for quite a long time) to get the plugin updated and submit it for inclusion in the qtcreator-developer tree, so that further API changes will be adjusted by the upstream maintainers.

At the moment I run with a slightly patched version of qt-creator 4.10 (with llvm 10 support), but I experience quite a lot of random lag in window redraw that might be one of the unaddressed issues even with 4.10. I tried to migrate to 4.12 before, but eventually gave up because I don't even *know* about all the functionality that needs to be tested with such a migration and there have been many API changes.

@Levi-Armstrong I know you are doing lots of great work at all fronts and there's only so much one can do per day.
You've been talking in terms of future tense [for over half a year now](https://github.com/ros-industrial/ros_qtc_plugin/pull/387#issuecomment-541433976) w.r.t. this issue. Is there any way to support you in getting this working with current qtc and submit it? It would be really nice to see it fully functional with current (and future) versions.

**Comment by vincent-hui** [comment]
Qt Creator 4.13 RC released.
Qt Creator 4.13 should be released this month.
Are there plans to release an installer for the newer Qt Creator 4.13?

**Comment by vincent-hui** [comment]
Qt Creator 4.13 released
https://www.qt.io/blog/qt-creator-4.13-released

**Comment by christian-rauch** [comment]
@Levi-Armstrong As an intermediate step to get the entire plugin functionality upstreamed, would it be possible to split the whole functionality into a catkin/colcon plugin and a ROS1/2 plugin? I imagine that upstreaming a catkin/colcon-only plugin first would reduce the maintenance costs as you would only need to adapt the ROS-specific parts, and from my perspective the catkin/colcon support provides the main functionality of the plugin as you can build and debug ROS nodes without the templates.

**Comment by vincent-hui** [comment]
[Qt Creator 4.14 Beta released](https://www.qt.io/blog/qt-creator-4.14-beta-released)

**Comment by vincent-hui** [comment]
Qt Creator 4.14 should be released next month.
Are there plans to release an installer for the newer Qt Creator 4.14?

Thanks

**Comment by vincent-hui** [comment]
[Qt Creator 4.14 RC released](https://www.qt.io/blog/qt-creator-4.14-rc-released)

Are there plans to release an installer for Qt Creator 4.14?

Thanks

**Comment by jfrascon** [comment]
Is the current qt-creator-ros plugin hosted in this repo still using Qt 4.9.2?

**Comment by christian-rauch** [comment]
> Is the current qt-creator-ros plugin hosted in this repo still using Qt 4.9.2?

Do you mean `Qt Creator` instead of `Qt`?
The [latest release](https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.3.10) will install Qt Creator 4.9.2, which is compiled with Qt 5.12.4.

**Comment by vincent-hui** [comment]
Qt Creator 4.14 released
https://www.qt.io/blog/qt-creator-4.14-released

**Comment by christian-rauch** [comment]
@vincent-hui see https://github.com/ros-industrial/ros_qtc_plugin/pull/417

For the impatient, you can use pre-built binaries (without the templates) for Ubuntu 20.04 / Qt Creator 4.14:
1. download [libROSProjectManager.so.txt](https://github.com/ros-industrial/ros_qtc_plugin/files/5838646/libROSProjectManager.so.txt)
2. remove the `.txt` (`mv libROSProjectManager.so.txt libROSProjectManager.so`)
3. copy `libROSProjectManager.so` to your Qt Creator plugin path, e.g. `~/Qt/Tools/QtCreator/lib/qtcreator/plugins/`

Or all in one step:
```
wget https://github.com/ros-industrial/ros_qtc_plugin/files/5838646/libROSProjectManager.so.txt -O ~/Qt/Tools/QtCreator/lib/qtcreator/plugins/libROSProjectManager.so
```

**Comment by christian-rauch** [comment]
Support has been merge by https://github.com/ros-industrial/ros_qtc_plugin/pull/417. Please create a new issue if something is not working as it used to with version 4.9.2.

**Comment by vincent-hui** [comment]
Hi @christian-rauch

Thank you very much for your porting.

Sorry , currently I have no time to test it.

Is there any plan to upstream the repo of ros_qtc_plugin to the repo of Qt Creator?

I think upstreaming ros_qtc_plugin can greatly benefit to both of ROS community of Qt community.

**Comment by christian-rauch** [comment]
I also think that upstreaming this into the Qt Creator repo would reduce the API maintenance burden. But I have no idea how this is done and what the implications would be. Would they adapt the API for you, or do you have to keep maintainer anyway with the same duties that you would have now (i.e. keeping track of API changes)?

Maybe @Levi-Armstrong knows more about the upstreaming work?

**Comment by Levi-Armstrong** [comment]
They should keep things up to date with API changes. The only thing that we would need to do is update the style to match the Qt Creator style and create PR.

**Comment by christian-rauch** [comment]
> The only thing that we would need to do is update the style to match the Qt Creator style and create PR.

This should be relatively easy using a clang-format style file.

If upstreaming the plugin (or parts of it) is a viable option, maybe we should go this route instead of putting the efforts into creating a snap version of Qt Creator.
@Levi-Armstrong Do you know the procedure how to get this upstream? Do you need help with this?

**Comment by Levi-Armstrong** [comment]
Any help with getting the style update would be great. I will work on getting the contributor agreement signed so I can submit the PR. Then it would be working through any request they may have.

**Comment by vincent-hui** [comment]
https://lists.qt-project.org/pipermail/qt-creator/2021-February/008783.html
Should we create a new issue to discuss the ros_qtc_plugin release for Qt Creator 4.15?
Thanks

**Comment by christian-rauch** [comment]
The release of 4.15 is still months away [(~ Apr 20 2021)](https://wiki.qt.io/Qt_Creator_Releases). I would stick with https://github.com/ros-industrial/ros_qtc_plugin/issues/325 to track the integration into the upstream repo.

**Comment by vincent-hui** [comment]
I propose the first task of ros_qtc_plugin release for Qt Creator 4.15 is upstreaming ros_qtc_plugin.

**Comment by vincent-hui** [comment]
Qt Creator 4.15 has been branched out.
https://github.com/qt-creator/qt-creator/tree/4.15

**Comment by vincent-hui** [comment]
[Qt Creator 4.15 Beta2 released.](https://www.qt.io/blog/qt-creator-4.15-beta2-released)

**Comment by vincent-hui** [comment]
[Qt Creator 4.15 released](https://www.qt.io/blog/qt-creator-4.15-released)

**Comment by christian-rauch** [comment]
> [Qt Creator 4.15 released](https://www.qt.io/blog/qt-creator-4.15-released)

Qt Creator 4.15 ROS plugin released :-)
https://github.com/ros-industrial/ros_qtc_plugin/tree/4.15

plugin: [libROSProjectManager.zip](https://github.com/ros-industrial/ros_qtc_plugin/files/6430475/libROSProjectManager.zip)

**Comment by vincent-hui** [comment]
@christian-rauch thank a lot.
