### ISSUE TITLE
Ubuntu20.04 qt-ros plugin

### ISSUE THREAD

**Issue by 54onePiece** [ros-industrial/ros_qtc_plugin#407]
Is there a qt-ros plugin supported on ubuntu20.04? I want to develop a software for sending messages from qt to ros2 Foxy in Ubuntu20.04.

**Comment by 54onePiece** [comment]
I installed qt-ros of ubuntu18.04 under ubuntu20.04. When creating a new project, there is no option to import ROS Workspace in the import Project

**Comment by wilcobonestroo** [comment]
I am also working in Ubuntu 20. Did you manage to get it running @54onePiece ?

**Comment by 54onePiece** [comment]
> I am also working in Ubuntu 20. Did you manage to get it running @54onePiece ?

Sorry, my focus has been changed to ubuntu18.04

**Comment by wilcobonestroo** [comment]
> I installed qt-ros of ubuntu18.04 under ubuntu20.04. When creating a new project, there is no option to import ROS Workspace in the import Project

@54onePiece I tried the qt-ros plugin under Ubuntu 20.04 and it works fine for me. You can find the option to import a ROS Workspace under **Other Project**.

![Screenshot from 2020-09-20 16-50-22](https://user-images.githubusercontent.com/1830620/93714261-c1cc1b80-fb61-11ea-8196-ba53730a61a4.png)

**Comment by fkreh** [comment]
I tried the qt-ros online installer for ubuntu 18.40under ubuntu 20.40. After the installation it worked fine. But after restarting the machine it lost the ros-plugin.

When trying to open a ros workspace i get the following message:
![Bildschirmfoto von 2020-09-24 10-45-54](https://user-images.githubusercontent.com/39989278/94122827-5204ac00-fe53-11ea-9330-3eeaff64c912.png)

**Comment by Levi-Armstrong** [comment]
Try running `qtcreator-ros` in a terminal and see if the issue persists. The desktop launcher could be the issues where it is finding the system one.

**Comment by christian-rauch** [comment]
The newest release at https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.4.0 supports Qt Creator 5.0. I am using this on Ubuntu 20.04. You can directly extract the archive to your Qt Creator installation.
