### ISSUE TITLE
Add the sql library in Qt. Just like QT +=sql in the .pro file in Qt

### ISSUE THREAD

**Issue by 54onePiece** [ros-industrial/ros_qtc_plugin#408]
I added in Cmakelists
find_package(Qt5 REQUIRED Core Widgets Sql)
set(QT_LIBRARIES Qt5::Widgets Qt5::Sql)
Then add #include <QtSql/QSqlDatabase> and other corresponding header files in the program without error. But the main program still reports an error /home/sl/OMS/src/oms/src/main_window.cpp:62: error: undefined reference to `QSqlDatabase::drivers()'. How should this be resolved?

**Comment by christian-rauch** [comment]
This issue does not seem specific to the ROS plugin. I am going to close this. Please reopen with more information about the issue with the ROS plugin.
