### ISSUE TITLE
Best way to install Qt Creator in Ubuntu 20

### ISSUE THREAD

**Issue by wilcobonestroo** [ros-industrial/ros_qtc_plugin#409]
There are no installation instructions for Ubuntu 20 in the [docs](https://ros-qtc-plugin.readthedocs.io/en/latest/_source/How-to-Install-Users.html) yet. What is the best way to use ROS Industrial QT Creator plugin in Ubuntu 20? Is building from source for now the best option?

**Comment by Levi-Armstrong** [comment]
Some have had good luck with just using the on for 18.04.

**Comment by wilcobonestroo** [comment]
I tried it in Ubuntu 20 and it works fine.
