### ISSUE TITLE
Installation Support using PPA

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#41]

**Comment by henriqueribeiro** [comment]
@Levi-Armstrong 
Sorry to re-write this again but I wrote on the other issue and since it's now closed...

> I just made a clean installation of ubuntu 14.04 and ROS and after following step 1.1 qtcreator was unable to find the plugin. There is no "Import ROS Workspace" option available.

**Comment by Levi-Armstrong** [comment]
Sorry, It looks like it failed to upload for trusty so I am pushing an new version. I notify you when it has been published.

**Comment by Levi-Armstrong** [comment]
@henriqueribeiro, a new version is available. I would perform the commands below just make sure everything install cleanly for the first time.
```
sudo apt-get remove qt57creator-plugin-ros
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros
```

**Comment by Levi-Armstrong** [comment]
@RickBlacker, were you able to get it to install?

**Comment by RickBlacker** [comment]
@Levi-Armstrong 
Hey Levi, yes, I think things are working.  Have not had a chance to play yet. I'm digging into some other code at the moment.  

Thanks a million!!!!

**Comment by henriqueribeiro** [comment]
@Levi-Armstrong It's working like a charm now! Thanks a lot

**Comment by Levi-Armstrong** [comment]
Great! Happy to here everything is working now.
