### ISSUE TITLE
How to change catkin config ?

### ISSUE THREAD

**Issue by doisyg** [ros-industrial/ros_qtc_plugin#414]
Hello,
Thanks for this amazing plugin which is used everyday by our team!
I recently wanted to build my workspace with catkin tools and with a `linked` develspace  : https://catkin-tools.readthedocs.io/en/latest/advanced/linked_develspace.html
It is supposed to be the default catkin tools config.
But I realized that upon workspace opening, Qtcreator is executing a config step which is setting the workspace in `merged`.
How to change this to default to `linked` ?

**Comment by Levi-Armstrong** [comment]
Sorry not near my computer, but I believe where you can add catkin and cmake arguments there should be an a button to edit the catkin config file. I will look when I get to a computer and post how to edit the default file so you do not have to edit it ever time you create a new workspace.

**Comment by doisyg** [comment]
Found it, thanks!
![image](https://user-images.githubusercontent.com/15727892/100394156-62482b80-303c-11eb-9adb-943e942968ee.png)
