### ISSUE TITLE
unable to locate build directory for package in qt creator

### ISSUE THREAD

**Issue by theinthankhaing** [ros-industrial/ros_qtc_plugin#415]
Hi 

I am new to ROS. I am now using ROS melodic. I have created package using catkin make but in the qt creator when i create the workspace. I got the error "unable to locate build directory for package".

Can anyone help me?

**Comment by Levi-Armstrong** [comment]
Does your workspace currently follow this structure?
```
workspace_folder/         -- WORKSPACE
  src/                    -- SOURCE SPACE
    package_1/
      CMakeLists.txt
      package.xml
      ...
    package_n/
      CMakeLists.txt
      package.xml
```

**Comment by theinthankhaing** [comment]
Hi

Thanks for replying me. yes it folllows. i have reinstalled qtcreator and restarted ubuntu. it works now.

**Comment by Levi-Armstrong** [comment]
Great.
