### ISSUE TITLE
suggestion: simplify install instructions

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_qtc_plugin#42]
I'd like to suggest the following to make the installation instructions clearer:

 1. more clearly define what *users* of the plugin are, and what *developers* are
 1. split the current *Setup ROS Qt Creator Plug in* wiki page into two separate pages, one for users (just the PPAs and `apt-get` line), the other for developers (using `setup.sh`)
 1. clearly mark both pages as *separate* procedures, so as to avoid users assuming that they have to follow both (the page currently starts the *developer* section with: "This section explains how to setup your system for development", which can be really confusing (development of what?))
 1. condense the 'user install' to just three lines (for Trusty, but similar for Xenial):

  ```
   sudo add-apt-repository ppa:beineri/opt-qt57-trusty
   sudo add-apt-repository ppa:levi-armstrong/ppa
   sudo apt-get update && sudo apt-get install qt57creator-plugin-ros
  ```

    Dependencies will be automatically installed by `apt-get`, no need to do everything separately.
 1. clearly mark the PPA instructions as *Ubuntu only*, and possibly include steps for non-Ubuntu users?

**Comment by Levi-Armstrong** [comment]
Sound good! I will work on it over the next few days.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn, Take a look at the updated wiki and let me know what you think.

**Comment by gavanderhoorn** [comment]
Nice, this is already much clearer.

Should the 'Home' page provide a bit of text clarifying what a *user* is and what a *developer*? That explanation could then also already directly link to the relevant pages.

**Comment by gavanderhoorn** [comment]
And (but not sure): perhaps add that developers would not need to / should not install the PPA debs.

**Comment by Levi-Armstrong** [comment]
> Should the 'Home' page provide a bit of text clarifying what a user is and what a developer? That explanation could then also already directly link to the relevant pages.

I have updated the home page to providing a definition for _Users_ and _Developers_.

> And (but not sure): perhaps add that developers would not need to / should not install the PPA debs.

I need to overhaul the developer setup since it know built using qt57, there is no need to download Qt from there website.  I also updated the wiki to show that both user and developers need to follow the install instruction.

**Comment by gavanderhoorn** [comment]
Looks good.

> I also updated the wiki to show that both user and developers need to follow the install instruction.

This is just me trying to understand, but what do you mean with this exactly?

**Comment by Levi-Armstrong** [comment]
Before, the process for developers required them to download the latest Qt libraries from Qt, but since the Debian is being build against qt57 ppa it is probably better that the developers use the qt57 libraries. Also they will need the libqtermwidget57-0 library and the dev version which I need to add to the developer wiki. The reason this was not required before I include the libqtermwidget github as a submodule just to simplify the process using the setup script. I will be submitting a PR to reflect this change soon after I update the setup script.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn: I have separated the user and developer instructions and updated it to work for the latest. Are you good with closing the issue?

**Comment by gavanderhoorn** [comment]
Yep. Great improvement.

I've changed the [Home page](/ros-industrial/ros_qtc_plugin/wiki) a bit ([diff](https://github.com/ros-industrial/ros_qtc_plugin/wiki/Home/_compare/a195b218ee9ff951876700ea7f9ce945c18e9a01...648b33294d0f111557c77eca9311df4ddde6bc30)), to make things extra clear (I got some questions here locally).

Please revert the changes if you don't agree with them.

**Comment by gavanderhoorn** [comment]
Thanks for addressing this.

:+1:

**Comment by Levi-Armstrong** [comment]
Looks Great!

**Comment by durovsky** [comment]
I have gone through the installation procedure today and it took me a while to figure our prerequisities. I had only basic qtcreator installed and when I tried to install qt ros plugin it resulted in various dependency problems. So in my opinion it would be nice to have a "Prerequisities" section just before installation steps that would clarify that full version of QT needs to be installed, where to get it from and maybe how to install it directly. It might save a lot of time to many people not so familiar with QT.

**Comment by gavanderhoorn** [comment]
I'm curious what you would define as the "full version" of Qt? After adding the PPAs, `apt` should be able to figure out the dependencies of `qt57creator-plugin-ros`, and install both Qt 5.7 as well as Qt Creator 5.7 built against that. After that, it should install the plugin itself.

What is it that you had to install in addition to that that you'd like to see added to the documentation?

**Comment by durovsky** [comment]
To get plugin installed successfully I had to sudo apt-get remove qtcreator, download QT installer from origin [website](https://www.qt.io/download-open-source/) a let it download and install QT5.7 and then procede to the installation steps with ppa. Without full QT installed, sudo apt-get update && sudo apt-get install qt57creator-plugin-ros resulted in error about missing files from /opt/qt57 folder. This is my experience, if basic 3steps installation from the documentation works fine for most of the users let it as it is.

**Comment by Levi-Armstrong** [comment]
What error did you received that required you to remove qtcreator? If it is a package discrepancy that should be removed, I can ask the maintainer of qt57 to add it as a conflict remove to the qt57creator Debian. The maintainer recently added one for qtcreator-data which was causing install issues like you have mentioned.

Do you have a list of missing files from the /opt/qt57?

**Comment by gavanderhoorn** [comment]
@durovsky: you should not need to go out and install Qt by yourself, especially not using the installer from the `qt.io` web site. The `apt-get install ..` line should have taken care of all of that.

If not, that would be something to fix.

**Comment by durovsky** [comment]
I ve managed to repeat the problem on fresh ubuntu 14.04 LTS. So if I `sudo apt-get install qtcreator` first and then try to follow plugin instllation steps, the installation step -  `sudo apt-get update && sudo apt-get install qt57creator-plugin-ros` results in following error:

```
...
Fetched 5 829 kB in 11s (504 kB/s)                                             
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qt57creator-plugin-ros : Depends: qt57creator (>= 4.1.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The solution is to remove existing version of qtcreator -` sudo apt-get remove qtcreator` and then repeat installation steps as described in "How to install" section. I confirm that installing QT from the installer is not required as @gavanderhoorn mentioned.

**Comment by Levi-Armstrong** [comment]
Based on the output message it does find qt57creator but it is not going to install it.  If you try to install qt57creator it should print out a message saying it has a conflict with qtcreator. There reason for this is the maintainer of qt57 has added the line to the Debian controls file. This prevents the qt57creator from being installed until the conflicting packages are removed. I am not sure if there is a way around this, but I can add a not to the install that it must be removed if already installed.

`Conflicts: qtcreator, qt51creator, qt52creator, qt53creator, qt54creator, qt55creator, qt56creator`
