### ISSUE TITLE
provide a standalone plugin archieve

### ISSUE THREAD

**Issue by christian-rauch** [ros-industrial/ros_qtc_plugin#422]
Qt Creator supports installing plugins from an archive:
![qtc_plugin_archive](https://user-images.githubusercontent.com/8226248/105527825-17653000-5cdc-11eb-9812-66dcc3610c15.png)

I couldn't find documentation on how this archive is structured, but I think it is simply a zipped version of all the files that get installed after the build step.

Would it be possible to provide this as a build artefact on GitHub? This would allow using the binary distribution of Qt Creator (https://www.qt.io/offline-installers).

**Comment by Levi-Armstrong** [comment]
This would be nice. You may just be able to zip the install directory when just building the plugin.

**Comment by Levi-Armstrong** [comment]
Maybe we could use [this](https://github.com/fpoussin/qtcreator-doxygen/blob/master/.github/workflows/build_qmake.yml) pipeline?

**Comment by christian-rauch** [comment]
It looks as if it creates archives like "Linux-x64.zip" but their release page https://github.com/fpoussin/qtcreator-doxygen/releases/tag/v0.4.8 only shows ".so" files.

Is the CI file supposed to upload artefacts directly to the GitHub release page?

It's quite complex but it also builds for Windows and macOS which would be nice for users on those platforms. We could create a branch and give it a try.

**Comment by Levi-Armstrong** [comment]
> It's quite complex but it also builds for Windows and macOS which would be nice for users on those platforms. We could create a branch and give it a try.

sounds good to me
