### ISSUE TITLE
No cmakelist in src file.Is there anything wrong?

### ISSUE THREAD

**Issue by wuyanze0226** [ros-industrial/ros_qtc_plugin#424]
I think i have installed the plugin successfully.but there is no cmakelist in src file.
![image](https://user-images.githubusercontent.com/78069913/105954745-1b17fe80-60b0-11eb-8eaf-50de707d7e75.png)

**Comment by christian-rauch** [comment]
Does your workspace have packages? Only packages have a `CMakeLists.txt`. There is none for the workspace itself when using CatkinTools, i.e. it is expected that there is no `CMakeLists.txt` in `test`.

Which version are you using and how did you install it?

**Comment by wuyanze0226** [comment]
> Does your workspace have packages? Only packages have a `CMakeLists.txt`. There is none for the workspace itself when using CatkinTools, i.e. it is expected that there is no `CMakeLists.txt` in `test`.
> 
> Which version are you using and how did you install it?

Hi, thank you for your reply.I using Ubuntu 18.04,and installed the plugin follow the tutorial in website. there is no error and warming.But I can't new a ROS package in src file, (when i new a package, there is nothing in src) and i find there is no CMakeLists.txt in src.

**Comment by christian-rauch** [comment]
By default, the plugin uses CatkinTools, which will not create a `CMakeLists.txt` in the workspace or the `src` folder. This was only the case with the older CatkinMake.

If your workspace is empty, i.e. there are no packages in `src`, you have to git clone a package in there or create a new one:
- GUI: Ctrl+N, then ROS → Package
- CLI: `catkin create pkg your_new_package_name`

In all these regards, the plugin behaves the same way as calling `catkin build`.
