### ISSUE TITLE
"Reading Project" nonstop during Build

### ISSUE THREAD

**Issue by v4hn** [ros-industrial/ros_qtc_plugin#425]
@christian-rauch

Here's another potential issue I see with 4.14 (not sure with which version it started or whether it was always like that):

When building/cleaning/rebuilding a workspace, qt-creator seems to "re-read" the project files/structure/? more than once a second the whole time.

Here's the note I see on the bottom right:
![reading-project](https://user-images.githubusercontent.com/680358/106262822-d2815200-6223-11eb-9b92-2ac5bd57fe85.png)

That's probably not the way it is intended to work in qt-creator and I'm unsure how much overhead it incurs.

**Comment by christian-rauch** [comment]
I don't see this issue with a small workspace using colcon or catkin tools.

Are you experiencing this on a particular large workspace? Which build system are you using?

**Comment by v4hn** [comment]
> Are you experiencing this on a particular large workspace? Which build system are you using?

I use catkin tools.

"large" is a fuzzy term. It's one of my "smaller" workspaces with ~6 minutes build time from scratch on an i5-6300 Laptop.
I don't think it's related to the size of the workspace though.

Briefly looking at the code it looks like either `ROSProject::refresh` or `ROSProject::fileSystemChanged` keeps getting called way more often than it should.

**Comment by christian-rauch** [comment]
Yes, so I suspect that once a package has been built and installed, the directory tree updates and the plugging refreshes the known project files. I think it is supposed to be this way so that when message header files etc. are generated on the fly, the IDE can know about them. If you have many (>50) smaller packages (that's what I mean with large workspace), then this will result in frequent project file updates.

@Levi-Armstrong should the IDE reparse the project when a package has been built?

**Comment by v4hn** [comment]
> Yes, so I suspect that once a package has been built and installed, the directory tree updates and the plugging refreshes the known project files. I think it is supposed to be this way so that when message header files etc. are generated on the fly, the IDE can know about them. If you have many (>50) smaller packages (that's what I mean with large workspace), then this will result in frequent project file updates.

I don't think that's it. The mentioned namespace only has 10 packages, though various compile units for each one.

**Comment by v4hn** [comment]
I had a few minutes to look at this and it turns out `fileSystemChanged(path)` is called on my system almost continuously during build/clean for many paths in the build, devel, and log folders.

Can you replicate this @christian-rauch, @Levi-Armstrong  ?

Does it make sense to ignore these subfolders in the method or is there some earlier hook to tell qtcreator the plugin does not care about it during build?

**Comment by v4hn** [comment]
> Can you replicate this ?

Most likely you can't. I just tracked it down after the kids went to bed...
It seems my .workspace file was broken and missed a `watchDirectories` entry.
In this case, the [default behavior in the plugin is to watch the whole project folder](https://github.com/ros-industrial/ros_qtc_plugin/blob/devel/src/project_manager/ros_utils.cpp#L424).

At the moment, I don't see why this `watchDirectories` field exists in the first place.
The only folder ever to be watched is the source path of the workspace and this can be easily queried at runtime.
So why have all the overhead of this watchDirectories structure @Levi-Armstrong ?

The only reason why `src` is not altogether the hardcoded value for the source space is because apparently catkin tools supports other names for it (wow). But even in this context [there is already a comment saying adding `.` can result  crashes](https://github.com/ros-industrial/ros_qtc_plugin/blob/devel/src/project_manager/ros_utils.cpp#L1197).

At the place where the top-level folder might be added to watchDirectories, we can't really query for the source folder.
How about changing the hard-coded constant here to `src` (or maybe check if that folder exists and use it if it does)?

**Comment by Levi-Armstrong** [comment]
>At the moment, I don't see why this watchDirectories field exists in the first place.
The only folder ever to be watched is the source path of the workspace and this can be easily queried at runtime.
So why have all the overhead of this watchDirectories structure @Levi-Armstrong ?

I believe this was to know when packages and files are added outsided of Qt Creator. Also as you noted that catkin supports different names. Does Qt Creator know have better support for knowing with workspace has changed to keep the project updated?

> At the place where the top-level folder might be added to watchDirectories, we can't really query for the source folder.
How about changing the hard-coded constant here to src (or maybe check if that folder exists and use it if it does)?

I good with changing the it to default to src directory if it exists.

Do you all know what is the purpose or advantage to having the Project Tree in Qt Creator versus just using the File System view? All it looks like is a filtered view of the folder and curious if it required to have.

**Comment by christian-rauch** [comment]
> Do you all know what is the purpose or advantage to having the Project Tree in Qt Creator versus just using the File System view? All it looks like is a filtered view of the folder and curious if it required to have.

At least for the CMake plugin, this makes a difference. There, the "file-tree" is sorted "CMake sub-project folder" → "CMake project" → "source files". While one of your CMake projects could be buried deep in your file hierarchy `a/b/c/d/proj/CMakeLists.txt` the project view would show this as `proj`.

In Pangolin, this looks like:
filesystem:
![pangolin_filesys](https://user-images.githubusercontent.com/8226248/106586881-dae9cd80-6540-11eb-9cf6-8fddee490527.png)

project:
![pangolin_proj](https://user-images.githubusercontent.com/8226248/106586923-e63cf900-6540-11eb-8f33-1046b3a37d4c.png)

Granted, here the `CMakeLists.txt`s are laid out like the filesystem, so the views have a similar structure.

If you want to adopt this in the ROS plugin, you could imagine that the first level would be the catkin/colcon package name and the second level could be the libraries or ROS node executables. I.e. this would be flat showing the catkin packages, instead of showing their hierarchy in the filesystem.

**Comment by v4hn** [comment]
> I good with changing the it to default to src directory if it exists.

I will prepare a patch.



> > At the moment, I don't see why this watchDirectories field exists in the first place.
> > The only folder ever to be watched is the source path of the workspace and this can be easily queried at runtime.
> > So why have all the overhead of this watchDirectories structure @Levi-Armstrong ?
>
> I believe this was to know when packages and files are added outsided of Qt Creator. Also as you noted that catkin supports different names. Does Qt Creator know have better support for knowing with workspace has changed to keep the project updated?

I believe we *do need* the watchDirectories logic in general, but I was talking about [the data field in the workspace file](https://github.com/ros-industrial/ros_qtc_plugin/blob/devel/src/project_manager/ros_utils.cpp#L416). Sorry for being imprecise before. The field [is written by the wizard and contains only the source path of the workspace](https://github.com/ros-industrial/ros_qtc_plugin/blob/devel/src/project_manager/ros_project_wizard.cpp#L267).
I don't see a reason for this field to exist in the first place because the source path could probably just as easily be queried in the logic that sets up the file watcher on startup.
I was just wondering if there was any other reason this field exists.

**Comment by christian-rauch** [comment]
> > I good with changing the it to default to src directory if it exists.
> 
> I will prepare a patch.

I would like to keep the source directory configurable. This could be done in the project wizard with a new field for "source directory" which is `src` by default.

**Comment by v4hn** [comment]
> I would like to keep the source directory configurable.

To clarify:

- The only way to have a different name for the source folder is via catkin tools, so a non-src folder is quite a restricted scenario. Personally I would not advertise this as a feature.

- If everything works as expected the default I linked to is never relevant - it's only triggered if the workspace file is corrupted.

If the file is corrupted there is no guarantee any other entries in there are correct, so I would propose to either
- get rid of the whole field in the file to begin with,
- throw a fatal error if it's not found,
- or add a saner default than just "watch everything" (which results in strange behavior and apparently can also crash).

If you are not happy with my simple 3-line patch using the third option, what would you prefer?

**Comment by christian-rauch** [comment]
> - The only way to have a different name for the source folder is via catkin tools, so a non-src folder is quite a restricted scenario. Personally I would not advertise this as a feature.

Right, you have to store this folder in the configuration and pass it to catkin/colcon. So it is definitely more work to implement and I actually don't think that many people use source folders other than `src`.

To make things easier, I would just hard-code the `src` folder in the plugin and remove the entire `WatchDirectories` option (option 1).

Everything else will just create a discrepancy between where catkin/colcon thinks where the source is and where Qt Creator thinks it should watch for source files. A user can still change this value manually, which will break the catkin/colcon ↔ Qt Creator sync. 

So better remove the `WatchDirectories` completely and just document that the workspace has to have the source in `src`.
