### ISSUE TITLE
How to copy text on ros terminals

### ISSUE THREAD

**Issue by yes89929** [ros-industrial/ros_qtc_plugin#426]
I wnat to copy text printed on the ros terminal.

but [ctrl+c], [ctrl+shift+c], [r click] etc. diden't work.

![image](https://user-images.githubusercontent.com/33365390/106569351-bd842600-6577-11eb-8a91-a473c4697d06.png)

**Comment by christian-rauch** [comment]
I think this is currently not supported. You have to use an external terminal for this.


The ROS Terminal is using the `QTermWidget` from https://github.com/lxqt/qtermwidget. The copy&paste functionality has to be implemented there.
