### ISSUE TITLE
trying to overwrite '/usr/share/mime/packages/Nokia-QtCreator.xml'

### ISSUE THREAD

**Issue by Petrox** [ros-industrial/ros_qtc_plugin#43]
After following
https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users-&-Developers)#section1.2
on ubuntu16.04 with qtcreator already installed, I got:

```
Unpacking qt57creator (4.0.2-1basyskom1) ...
dpkg: error processing archive /var/cache/apt/archives/qt57creator_4.0.2-1basyskom1_amd64.deb (--unpack):
 trying to overwrite '/usr/share/mime/packages/Nokia-QtCreator.xml', which is also in package qtcreator-data 3.5.1+dfsg-2ubuntu2
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
```

of course
    dpkg --remove qtcreator-data ; apt-get -f install 
solved the problem, but you might want to conflict (remove) with qtcreator-data not just qtcreator itself.

**Comment by Levi-Armstrong** [comment]
@Petrox, Thanks for the feedback. I will report it to the owner of the qt57 ppa, but there is no guarantee that this will get resolved.

**Comment by Levi-Armstrong** [comment]
I just sent the owner a email. I will provide an update if I receive a response.

**Comment by Petrox** [comment]
Sorry, that I did not check who's the ppa owner. :) I was just following
the installguide, and not peeking behind the scenes. :)

Thank you for the plugin development, it makes qtcreator usage simpler.

**Comment by Levi-Armstrong** [comment]
> Thank you for the plugin development, it makes qtcreator usage simpler.

Thank you, I will keep this open until I have time to update the wiki.

**Comment by Levi-Armstrong** [comment]
Wiki has been update
