### ISSUE TITLE
How to install ros_qtc_plugin on Jetson Xavier belonging to the aarch64 architecture? Or is there a plug-in source code suitable for aarch64 Ubuntu 18.04？

### ISSUE THREAD

**Issue by Jiac-W** [ros-industrial/ros_qtc_plugin#431]
I can't run the "online install .run" file because a “invaild encoding” error, which I guess result from the arm64 arhitecture.
Then I tried to install it in a "developer mode", but there is no for 18.04 bionic.
Thank you

**Comment by christian-rauch** [comment]
There is no binary distribution for the ROS plugin on arm64. You will have to compile it and Qt Creator from source.

**Comment by Jiac-W** [comment]
Hi! Christian! Do you know where to get the source code of the ROS plugin on arm64? Ths~

**Comment by christian-rauch** [comment]
The source code is in this very repository you created the issue in. There is no source code for specific CPU architectures, you have to compile the source code into a binary library specifically for the arm64 architecture.

**Comment by Jiac-W** [comment]
If you don't mind, please give me a concise guide to find the source code of this plug-in in this repository ? I have tried several times and still cannot find the directory of the plug-in source code. And how can I recompile the source code on arm64? Thank you so much!

**Comment by christian-rauch** [comment]
@Anthony-DC I am a bit confused why you cannot see the source code. The source code is in this git repo: https://github.com/ros-industrial/ros_qtc_plugin.

To compile Qt Creator just follow the official instructions at https://wiki.qt.io/Building_Qt_Creator_from_Git. The newest Qt Creator requires a newer Qt version than that available on stock Ubuntu 20.04. In this case, you have to get a binary Qt distribution from somewhere else, compile Qt from source or just upgrade your Ubuntu.

To compile the plugin, clone the plugin git repo in the same directory where you cloned the folder `qt-creator` into and run `qmake` and then `make -j`.
