### ISSUE TITLE
Installer for 4.15 release

### ISSUE THREAD

**Issue by kamilsaigol** [ros-industrial/ros_qtc_plugin#432]
The latest release doesn't include installers https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.3.11

Is there a new way to install? I see there is a plugin archive linked in https://github.com/ros-industrial/ros_qtc_plugin/issues/406 which seems to be for QtCreator 4.15 but that (closed) issue is the only place this shows up.

**Comment by christian-rauch** [comment]
You have to compile the plugin from source, unfortunately.

I added the library (.so) to the issue to make it easier to use the plugin. You can copy that library to your Qt Creator plugin folder. This will not include any templates etc. and it will break once you update to Qt Creator 4.16 and later.
