### ISSUE TITLE
Why can't I use subscribe to subscribe to messages from other nodes in makewindow? I've added ROS header files

### ISSUE THREAD

**Issue by lianbashou123** [ros-industrial/ros_qtc_plugin#442]
![2a2c2210f1b84e82](https://user-images.githubusercontent.com/88788972/133538283-976556bc-c082-4f0d-93f5-f5c787a5c03e.jpg)
![20210916_100841](https://user-images.githubusercontent.com/88788972/133538302-c309ca30-3604-49f9-99ee-064560117224.jpg)

**Comment by v4hn** [comment]
Read your error messages. `subscribe` expects at least three arguments (the missing one being the callback).
Don't post such generic issues here. They have nothing to do with the qt-creator plugin.

**Comment by christian-rauch** [comment]
@lianbashou123 I agree with @v4hn. Please post such generic ROS questions on https://answers.ros.org. You are much more likely to get a relevant answer there. We want to keep this issue tracker for tracking issues related to the Qt Creator plugin. If in doubt, then first try to compile your workspace on the command line (using the same build tool) without Qt Creator. Any generic ROS issue will also show up there. The command line will also give you much more verbose output by default.

In future, please paste the raw syntax-highlighted code and error messages separately. This makes it possible to use full-text search in the issues. The "Compile Output" pane (accessible via mouse or Alt+3 keys) will also show you much more verbose information about the compiler error. This is the same as compiling on the command line in a terminal.
