### ISSUE TITLE
buildstep configurations are not accessible

### ISSUE THREAD

**Issue by v4hn** [ros-industrial/ros_qtc_plugin#444]
I just wanted to set the number of build jobs in my qt-creator build configuration and found no way to do that.
The build step configurations for the ROS build steps have been empty for as long as I've used the plugin.
This is what I see in the build config screen over here:

![buildstep-config](https://user-images.githubusercontent.com/680358/133615974-6abe3171-295d-48fc-a4d5-bf531ee24ce8.png)

Notice the various options available in the IncrediBuild step (I just added that for illustration).

Looking at the plugin code though, it looks like there is quite a bit of code dedicated to UI options for these steps including jobs and various others! [See here for catkin_tools](
https://github.com/ros-industrial/ros_qtc_plugin/blob/6f763a699151b3a2d47424c8b589c4a4e27fc3f8/src/project_manager/ros_catkin_tools_step.cpp#L681).
But there does not seem to be anything even instantiating [the class](https://github.com/ros-industrial/ros_qtc_plugin/blob/6f763a699151b3a2d47424c8b589c4a4e27fc3f8/src/project_manager/ros_catkin_tools_step.cpp#L681).

Is this yet another API that got deprecated and removed in qt-creator at some point?
I have no idea whether it's one line missing or requires an entire rewrite, but it would be great to see these configurations available!

@christian-rauch @Levi-Armstrong ?

**Comment by Levi-Armstrong** [comment]
In the older version under the catkin, tools step you could select the `Edit...` button which would bring this widget up for editing catkin tools profiles.

![image](https://user-images.githubusercontent.com/9803128/133618462-b16b8dcf-e063-4ffc-b88d-512b4a394cd8.png)

![image](https://user-images.githubusercontent.com/9803128/133618685-8e96f9a6-2992-4986-8fb9-e9c34efabfab.png)

**Comment by christian-rauch** [comment]
It's totally possible that this got removed accidentally by me during one of the many API transitions. I never noticed that, since I am not using that functionality. Do you know with which version this functionality disappeared?

Edit: I tested the old 4.9.2 installer and I see the options there. So this definitely broke with one of the API transitions. But there were 7 of them (4.{10...15}, 5.0), so it will take some time to figure out which update broke this functionality.

**Comment by Levi-Armstrong** [comment]
I am currently on 4.9.2 which has this functionality.

**Comment by christian-rauch** [comment]
I assume that this broke with 59ac8cd81323c56b94e49ab88d0aa698a3d8d4ea. It should work with 4.13 and not with 4.14.

**Comment by christian-rauch** [comment]
@v4hn Can you check if https://github.com/ros-industrial/ros_qtc_plugin/pull/447 solves this issue for you? It should add the configuration widgets again and undo some of the changes from 59ac8cd81323c56b94e49ab88d0aa698a3d8d4ea. You can download the plugin archive from the build artefacts at: https://github.com/ros-industrial/ros_qtc_plugin/actions/runs/1261301357.

Edit: plugin archive from CI: [ROSProjectManager-0.4.0-Linux-x86_64.zip](https://github.com/ros-industrial/ros_qtc_plugin/files/7209750/ROSProjectManager-0.4.0-Linux-x86_64.zip)
