### ISSUE TITLE
Losing parts of function

### ISSUE THREAD

**Issue by gaolingminhhh** [ros-industrial/ros_qtc_plugin#457]
I installed the plugin successfully,but when I saw the video,I found something wrong.
I am using 
Ubuntu18.04,aarch64.
 Qt Creator 5.0.3   
Qt 5.15.2
And source code version is 0.4
There is no version for arm64,so I compile from source code by myself.
![2021-11-13 09-14-00屏幕截图](https://user-images.githubusercontent.com/24429670/141601358-df04f7e4-d331-4e60-9b96-60e30419f6cf.png)

**Comment by christian-rauch** [comment]
> I installed the plugin successfully,but when I saw the video,I found something wrong.

Can you explain what is missing?

My "New File or Project ..." (Ctrl+N) dialog looks like:
![ros_plugin](https://user-images.githubusercontent.com/8226248/141780991-f08dafc5-1a5c-4a77-961e-f449e28aaf09.png)
So my best guess is that the templates are missing?

> There is no version for arm64,so I compile from source code by myself.

There are no official Qt Creator binaries for arm64 on Linux, so the CI and the `setup.py` script will only be able to download the x64 binaries and create an archive with the x64 plugin.

How did you install the plugin? Did you create the plugin archive and extracted it to the Qt Creator root folder?
