### ISSUE TITLE
Installation error: Depends: qt57creator (>= 4.0.2) but it is not installable

### ISSUE THREAD

**Issue by masterhui** [ros-industrial/ros_qtc_plugin#46]
Hi,
I just tried to install qt57creator-plugin-ros follwoing the installation instructions for "Users". Adding the ppa's worked fine. But when I try to install the plugin, I get:

```
ros@base:~$ sudo apt-get update && sudo apt-get install qt57creator-plugin-ros
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [94,5 kB]
Hit:2 http://de.archive.ubuntu.com/ubuntu xenial InRelease                                           
Hit:3 http://ppa.launchpad.net/beineri/opt-qt57-xenial/ubuntu xenial InRelease                                                  
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                                                                    
Hit:5 http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu xenial InRelease                                 
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                                                
Hit:7 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease      
Hit:8 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:10 http://packages.ros.org/ros/ubuntu xenial InRelease
Fetched 94,5 kB in 5s (16,5 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qt57creator-plugin-ros : Depends: qt57creator (>= 4.0.2) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

My setup:
- Ubuntu 16.04
- ROS Kinetic
- Qt Creator 4.1.0

Regards

**Comment by Levi-Armstrong** [comment]
It depends on qt57creator. I am not sure why it did not prompt you to install the dependencies during the install of qt57creator-plugin-ros. I would uninstall Qt Creator 4.1.0 and install qt57creator. Then follow the install procedure again.

**Comment by masterhui** [comment]
If I try to install qt57creator separately via apt-get I get the same "not installable" error. Any ideas how to find out what the problem might be?Cheers


		_____________________________

**Comment by Levi-Armstrong** [comment]
Can you provide the terminal output from `sudo apt-get install qt57creator`?

**Comment by masterhui** [comment]
My last reply was from my mobile, so I could't include the console output. When I got back in this morning an re-ran the same command, the install procedure complete without error. Maybe the reboot over night helped. Thank you for your support anyway!

**Comment by jacknlliu** [comment]
I met the same problem in Ros Indigo, Ubuntu 14.04. And I followed the instruction add the repository, but I can't find the package qt57creator.

**Comment by Levi-Armstrong** [comment]
Check and make sure that the ppa information is located in /etc/apt/sources.list.d/beineri-opt-qt57-trusty.list? The filename may not match exactly but it should be something close.

**Comment by jacknlliu** [comment]
I'm sure that  file `/etc/apt/sources.list.d/beineri-opt-qt57-trusty.list` exist.

**Comment by Levi-Armstrong** [comment]
Inside the file does it have the lines below?

```
deb http://ppa.launchpad.net/beineri/opt-qt57-trusty/ubuntu trusty main 
deb-src http://ppa.launchpad.net/beineri/opt-qt57-trusty/ubuntu trusty main 
```

**Comment by jacknlliu** [comment]
The content of the list file is:
```
deb http://ppa.launchpad.net/beineri/opt-qt57-trusty/ubuntu trusty main
# deb-src http://ppa.launchpad.net/beineri/opt-qt57-trusty/ubuntu trusty main
```

**Comment by Levi-Armstrong** [comment]
I would try `sudo apt-get update` again, then proceed with the install of the plugin.

**Comment by duonglacbk** [comment]
Sorry for late reply, I have been reinstall Ubuntu and Qt ros
1. I completed installing Ros plug in for Qt59 as this instruction:

sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial
sudo add-apt-repository ppa:levi-armstrong/ppa
sudo apt update && sudo apt install qt59creator
sudo apt install qt57creator-plugin-ros

2. I create a new ROS package:
![1](https://user-images.githubusercontent.com/15654372/33241227-f3a0ccaa-d305-11e7-9481-5f7d1dfd508a.png)

I only write ros as the name of my package

![2](https://user-images.githubusercontent.com/15654372/33241236-1380a3ec-d306-11e7-9807-b44426ac539d.png)

Then Next

![3](https://user-images.githubusercontent.com/15654372/33241242-1e13df40-d306-11e7-81f1-9045f6bc85ed.png)

After that I push Finish, the Qt59 auto close. And the errors as following:

![5](https://user-images.githubusercontent.com/15654372/33241318-02f26d02-d307-11e7-8b40-c5adc14e27bc.png)

![6](https://user-images.githubusercontent.com/15654372/33241323-14a68bbe-d307-11e7-97f4-95c7bb23e2d9.png)

Please help me!
If you need further information please let me know!
