### ISSUE TITLE
cannot be loaded in windows 

### ISSUE THREAD

**Issue by zk8514** [ros-industrial/ros_qtc_plugin#461]
![Screenshot 2022-03-01 161224](https://user-images.githubusercontent.com/45388062/156130455-60001b81-67f0-42be-9454-4fae08aefd5a.png)

**Comment by christian-rauch** [comment]
It is hard to fix this without details. Which version of the plugin is this? Which version of Qt Creator are you using? Do you have all the dependencies installed?

**Comment by zk8514** [comment]
> It is hard to fix this without details. Which version of the plugin is this? Which version of Qt Creator are you using? Do you have all the dependencies installed?

 plugin 0.5.0   qt6.0.2
and about dependencies, github only shows what is needed in ubuntu, these packages i can't find via chocolatey
![image](https://user-images.githubusercontent.com/45388062/156279230-055bb8b0-040c-4973-ba4e-af277a15e88b.png)

**Comment by christian-rauch** [comment]
Please, don't paste screenshots of text. Paste the text instead directly.

These are build dependencies. They are only required if you want to build the plugin from source. I assume you are trying to use the binary Windows builds (*.dll).

> plugin 0.5.0 qt6.0.2

The Qt version is not important. The Qt Creator version has to match the plugin version because of API differences. That is why I was asking for the Qt Creator version.

From where did you download Qt Creator?

**Comment by christian-rauch** [comment]
I downloaded [Qt Creator 6.0.2 for Windows 64-bit](https://download.qt.io/official_releases/qtcreator/6.0/6.0.2/qt-creator-opensource-windows-x86_64-6.0.2.exe) and [ROSProjectManager-0.5.0-Windows-AMD64.zip](https://github.com/ros-industrial/ros_qtc_plugin/releases/download/0.5.0/ROSProjectManager-0.5.0-Windows-AMD64.zip).

After extracting the plugin zip file to `C:\Qt\qtcreator-6.0.2`, I can start Qt Creator and see the ROS plugin in the list of plugins:
![ros_qtc_windows](https://user-images.githubusercontent.com/8226248/156354054-0c59b422-b63f-4750-be5a-1933f51e4f0b.png)

**Comment by zk8514** [comment]
> I downloaded [Qt Creator 6.0.2 for Windows 64-bit](https://download.qt.io/official_releases/qtcreator/6.0/6.0.2/qt-creator-opensource-windows-x86_64-6.0.2.exe) and [ROSProjectManager-0.5.0-Windows-AMD64.zip](https://github.com/ros-industrial/ros_qtc_plugin/releases/download/0.5.0/ROSProjectManager-0.5.0-Windows-AMD64.zip).
> 
> After extracting the plugin zip file to `C:\Qt\qtcreator-6.0.2`, I can start Qt Creator and see the ROS plugin in the list of plugins: ![ros_qtc_windows](https://user-images.githubusercontent.com/8226248/156354054-0c59b422-b63f-4750-be5a-1933f51e4f0b.png)

thank you   
i installed a new Qt creator in C:\ ,then it loaded the plugin successfullly

**Comment by zk8514** [comment]
I'm sorry, but I have met another trouble:
![QQ截图20220303110621](https://user-images.githubusercontent.com/45388062/156490898-3ac90012-6410-4fe3-9bc9-2004792a9a69.png)
it can't detect the  ROS distribution although I set the ROS Distros. I tried many paths ,such as` C:\opt\ros\melodic\x64`, `C:\opt\ros\melodic\x64\bin`, but it also didn't work
I installed the ros by wiki:https://wiki.ros.org/Installation/Windows

**Comment by christian-rauch** [comment]
I have no experience with ROS on Windows and can therefore give no answer for this. I recommend that you use Ubuntu.

You probably have to make sure that ROS has been installed correctly and you have to provide the full path of the installation. I would try to run some ROS nodes from the command line before working with the ROS Qt Creator plugin.

If you need more help with generic ROS questions, use https://answers.ros.org and https://robotics.stackexchange.com. This issue tracker is only for the Qt Creator plugin and we also only provide rudimentary support for other operations systems than Ubuntu.
