### ISSUE TITLE
I can not download the installer

### ISSUE THREAD

**Issue by vkaser** [ros-industrial/ros_qtc_plugin#471]
I am trying to access the ros plug-in download homepage

https://qtcreator-ros.datasys.swri.edu/downloads/installers/bionic/qtcreator-ros-bionic-latest-online-installer.run

to install qt-ros-plugin, but I couldn't.

I think the server has a problem.

Could you fix this problem? Thanks

**Comment by christian-rauch** [comment]
The old installer is deprecated and not supported anymore. The [README](https://github.com/ros-industrial/ros_qtc_plugin#readme) in this repo gives you three options to install the plugin:
1. install the snap package that includes Qt Creator and the plugin
2. install the plugin on top of an already existing Qt Creator installation
3. build everything from source :-)

I doubt that the old installer will be reactivated since it installs a very old Qt Creator version.

**Comment by vkaser** [comment]
@christian-rauch Thank you!

**Comment by fayyazpocker** [comment]
Is the installer available somewhere ? I could try to install the snap package but it is quite difficult to install it inside a docker.

**Comment by christian-rauch** [comment]
> Is the installer available somewhere ?

Which installer do you mean? The online Qt Creator installer is available on the Qt homepage. This is mentioned in the [Plugin Installation paragraph](https://github.com/ros-industrial/ros_qtc_plugin#plugin-installation) on the main page. Did you encounter an issue with this? If the instructions do not work, then please open a new issue so we can update the installation instructions.

> I could try to install the snap package but it is quite difficult to install it inside a docker.

Qt Creator and the plugin are meant to be used on a developer desktop or workstation. Running this inside a Docker container is not a "supported" scenario.

**Comment by fayyazpocker** [comment]
I meant the bionic installer(https://qtcreator-ros.datasys.swri.edu/downloads/installers/bionic/qtcreator-ros-bionic-latest-online-installer.run). I could find that the alternate solution to get ros plugin by default is to install sudo snap install qtcreator-ros --classic but unfortunately the snapcraft do not work inside the docker container. Hence either i could get the installer.run setup or will have to build the plugin and add to qtcreator manually.

**Comment by christian-rauch** [comment]
> I meant the bionic installer(https://qtcreator-ros.datasys.swri.edu/downloads/installers/bionic/qtcreator-ros-bionic-latest-online-installer.run).

We already established in the first two posts that [the old installer is not available anymore](https://github.com/ros-industrial/ros_qtc_plugin/issues/471#issue-1439435341) and that [we do not plan to support this](https://github.com/ros-industrial/ros_qtc_plugin/issues/471#issuecomment-1306866602).

> I could find that the alternate solution to get ros plugin by default is to install sudo snap install qtcreator-ros --classic but unfortunately the snapcraft do not work inside the docker container. Hence either i could get the installer.run setup or will have to build the plugin and add to qtcreator manually.

Did you read the [installation instructions](https://github.com/ros-industrial/ros_qtc_plugin#plugin-installation) and tried to install Qt Creator and the plugin as suggested there via the online installer and the plugin archives from the release page?

**Comment by fayyazpocker** [comment]
Yes. I tried but there was an issue with glibc version mismatch which would require me to upgrade glibc version in my host which might cause problem with other programs. I installed using online installer and extracted the ros plugin which i downloaded from the [release page](https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/9.0) and tried both installing the plugin via qtcreator also tried manually copying the .so file to the plugins folder. It caused a mismatch version in glibc and showed that it require 2.32 but my system have 2.31.

**Comment by christian-rauch** [comment]
> Yes. I tried but there was an issue with glibc version mismatch 

But this is a different and [known issue](https://github.com/ros-industrial/ros_qtc_plugin/issues/475). If the solution there does not work, then please comment there.

This very issue is for the old installer and was pinned to inform users that the older installer does not exist anymore and that there are now alternative ways to install Qt Creator and the plugin.

**Comment by christian-rauch** [comment]
@Levi-Armstrong Can you update the [documentation](https://ros-qtc-plugin.readthedocs.io) and remove the outdated links to the installer and maybe just have it point to the main page of this GitHub repo?
