### ISSUE TITLE
Installing the plugin for older Qt Creator version

### ISSUE THREAD

**Issue by hirenpatel1207** [ros-industrial/ros_qtc_plugin#476]
I am using an older Qt Creator version.
Qt Creator = 5.0.2 
Qt = 5.12.2

How can I install the plugin for this version? If, I download the zip from release and then try to install the plugin via Qt Creator->Plugins->Install Plugin then it says could not find Qt Creator.

I tried to build the plugin by downloading the repo and running
``cmake -B build -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="~/Qt5.12.12/Tools/QtCreator;~/Qt5.12.12/5.12.12/gcc_64"
``
But it fails to build with error
  Could not find a package configuration file provided by "QtCreator" with
  any of the following names:

    QtCreatorConfig.cmake
    qtcreator-config.cmake

**Comment by christian-rauch** [comment]
Do you need specifically such an old version? Generally, you should follow the instructions on the main page to install the plugin: https://github.com/ros-industrial/ros_qtc_plugin. There it says that you have to copy the content of the binary plugin archive into the Qt Creator folder. The binary releases are available at https://github.com/ros-industrial/ros_qtc_plugin/releases. For Qt Creator 5, the plugin version 0.4.x should work: https://github.com/ros-industrial/ros_qtc_plugin/releases/tag/0.4.3.

If you do not need a specific version, I would recommend that you simply install the latest version via the Qt installer and follow the instructions on the main page to install the plugin, or simply use the snap package.

**Comment by hirenpatel1207** [comment]
Thanks for the quick reply,

I tired version 0.4.x and works fine. The choice of Qt=5.12.2 is because of the licensing issue with Qt, its available under LGPL, the latest versions are GPL.
Anyways, I will close this issue.
