### ISSUE TITLE
add QDataVisualization

### ISSUE THREAD

**Issue by qll1003** [ros-industrial/ros_qtc_plugin#480]
I want to use the component QDataVisualization in ros-qtc-plugin, but this module does not exist after the installation of the downloaded qtcreator-ros-bionic-latest-offline-installer.run. How should I add this component?

**Comment by Levi-Armstrong** [comment]
I recommend using the snap version. The installer you used is very old.

**Comment by christian-rauch** [comment]
As @Levi-Armstrong said, the `.run` installers are not supported any more.

Apart from this, I am not sure what you are referring to by `QDataVisualization`. Do you mean [Qt Data Visualization](https://doc.qt.io/qt-6/qtdatavisualization-index.html)? This is part of Qt and has nothing to do with Qt Creator or the ROS plugin in this repo. You can / have to install the Qt components yourself (https://doc.qt.io/qt-6/get-and-install-qt.html).

**Comment by qll1003** [comment]
thanks
