### ISSUE TITLE
"Add new..." is not enabled to add new files in the project folder. How can I solve this problem?

### ISSUE THREAD

**Issue by thiagosass** [ros-industrial/ros_qtc_plugin#482]
When I need to add a new window or new files, I have to manually add them to CMAKELists.txt because "Add New..." is disabled. How do I resolve this?

I'm using:

Desktop_Qt_6_5_0_MinGW_64_bit-Debug

![Referência](https://user-images.githubusercontent.com/24324866/233379231-9f8adb7f-fd5d-4c1d-ba8f-adf978032cf2.jpg)

**Comment by christian-rauch** [comment]
Is this the ROS plugin? It doesn't look like it. If you have problems with the generic Qt Creator, please report them to them. This repo is only about the ROS plugin.
