### ISSUE TITLE
Docker Device not present

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#491]
@christian-rauch Any idea why the docker device is not present under device?

**Comment by christian-rauch** [comment]
What "Docker device" do you mean?

**Comment by Levi-Armstrong** [comment]
https://doc.qt.io/qtcreator/creator-adding-docker-devices.html

**Comment by christian-rauch** [comment]
At least in Qt Creator 12 it's an experimental plugin and probably isn't activated by default. But I assume that this is unrelated to the ROS plugin.

**Comment by christian-rauch** [comment]
After I enable "Docker (experimental)" I can see the Docker tab under Devices.

**Comment by Levi-Armstrong** [comment]
Sorry I was looking under devices and did not see a plugin, but it is under utilities. I thought since it was not under devices that the snap must not have been built with the plugin.
