### ISSUE TITLE
Unable able to build with latest update no auto source /opt/ros/../setup.bash

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#500]
It looks like ros is no longer being sourced automatically causing it to fail to build after a clean using catkin tools. I now have to call catkin build in the terminal first then I am able to build again within qt creator

**Comment by Levi-Armstrong** [comment]
It might be good to add back the message which printed out if the sourcing the ros distro failed because it unclear if that is the issue.

**Comment by christian-rauch** [comment]
Does this only happen with catkin or can you reproduce this with colcon too? (You can build ROS 1 workspaces with colcon too.)

**Comment by christian-rauch** [comment]
I assume that the issue is caused by b746e54688c9f630e1862e81b148ee8a32b9ac8b and should affect all build tools. @Levi-Armstrong Can you revert that comment and see if it solves the issue?

**Comment by Levi-Armstrong** [comment]
> Does this only happen with catkin or can you reproduce this with colcon too? (You can build ROS 1 workspaces with colcon too.)

I have not tried colcon but will and post my findings.

**Comment by christian-rauch** [comment]
I could reproduce this right after creating a new "ROS Workspace" project from scratch. I reworked how the environment variables are gathered in the Qt Creator 14 version of the plugin (https://github.com/ros-industrial/ros_qtc_plugin/pull/506). Please try that PR and let me know if it fixes your issue (it does for me) and if this solution of splitting the process and the environment variables is ok for you.
