### ISSUE TITLE
Problems with creating package and creating new files

### ISSUE THREAD

**Issue by Qqww4599** [ros-industrial/ros_qtc_plugin#501]
Hello
I am a ros2 beginner and have some problems
I download ros_qtc_plugin zip file from https://github.com/ros-industrial/ros_qtc_plugin/releases, and install ros_qtc_plugin 13.1 in qt creator 13.0.0. I have tried ros_qtc_plugin 13.0 but unlucky...

I have 2 problems

1. When I have created a workspace and plan to create a package in the src directory, I right-click on the src folder and select Add New. There should be many creation options like this
![未命名5](https://github.com/ros-industrial/ros_qtc_plugin/assets/71856163/6d302f1c-caa5-420f-8d38-6783a1e8ae68)
,but it seems that I only have the option to create a package.
![未命名2](https://github.com/ros-industrial/ros_qtc_plugin/assets/71856163/0e510c6a-b350-441d-8436-3dfe9a220f78)

2. I followed the steps[ in this tutorial ](https://qtcreator-ros.d10.us.swri.org/downloads/tutorials/videos/introduction/(Part%203)%20ROS%20QT%20Intro%20-%20Hello%20World!.mp4)to create a package, but I couldn’t press next in the window to create a ROS package using the same operation.
![未命名3](https://github.com/ros-industrial/ros_qtc_plugin/assets/71856163/f56f8098-e55b-46fd-9bd3-c610e79d7565)

Below is my current environment:
OS: Ubuntu 22.04
Qt Version: 6.6.0
Qt Creator: 13.0.0

Please tell me how to solve these problems, thank you!

**Comment by christian-rauch** [comment]
I personally have never used those widgets to create packages or files in a workspace. But AFAIK, those templates only exist or ROS 1 packages. You cannot use them for ROS 2 packages. Do they work in a ROS 1 workspace as expected?

**Comment by Qqww4599** [comment]
Thank you for your reply and suggestions. Due to the design and architecture of the project, we should not consider ROS1. So this tool doesn’t yet support ROS2?

**Comment by christian-rauch** [comment]
The Qt Creator plugin supports colcon, i.e. works with ROS 2 workspaces. However, it does not contain templates for ROS 2 nodes. See also https://github.com/ros-industrial/ros_qtc_plugin/issues/453.
