### ISSUE TITLE
Source code compilation and installation 

### ISSUE THREAD

**Issue by Mark9999999** [ros-industrial/ros_qtc_plugin#502]
There is no installation package for linux-arm64 in the release. How should I install ros-qtc-plugin through source code

**Comment by christian-rauch** [comment]
This is documented in the README: https://github.com/ros-industrial/ros_qtc_plugin?tab=readme-ov-file#build-the-plugin-archive. There is also a snap package for the arm64 architecture.

Please read the instructions first before creating issues. If the instructions do not work for you, you can create a new issue with details on what does not work.
