### ISSUE TITLE
Performing a clean removes user defined environment variables

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#509]
In the past this was not the case and any user defined environment variables would persist.

**Comment by christian-rauch** [comment]
Could this be related to https://github.com/ros-industrial/ros_qtc_plugin/issues/500? Does the update to Qt Creator 14 (https://github.com/ros-industrial/ros_qtc_plugin/pull/506) fix the issue?

**Comment by christian-rauch** [comment]
I am assuming that #506 fixes the issue since it reworks how the sourcing is done. Simply reopen if this issue persists and give steps to reproduce this.
