### ISSUE TITLE
Incompatible Qt version between Qt Creator 15 (6.7.2) and the ROS plugin (6.8.0)

### ISSUE THREAD

**Issue by doisyg** [ros-industrial/ros_qtc_plugin#521]
With Qt Creator from deb: https://github.com/qt-creator/qt-creator/releases/tag/v15.0.0

![image](https://github.com/user-attachments/assets/fcf3ae58-622d-4d9d-b90a-95e6eb10ad11)

![Screenshot from 2024-12-20 21-51-22](https://github.com/user-attachments/assets/b6ee4950-8026-4588-a4a7-0959ef96e00e)

**Comment by christian-rauch** [comment]
It's a bit hidden and there are not "official" installation instructions for the Debian package from our side yet. We have instructions for building the plugin as [Debian package](https://github.com/ros-industrial/ros_qtc_plugin?tab=readme-ov-file#build-the-plugin-archive) and this also mentions to get the Debian package from https://download.qt.io:
```sh
# install the experimental Qt Creator package
# from the `cpack_experimental` folder under https://download.qt.io/*_releases/qtcreator/
wget $(./packaging/format-deb-url.py) --directory-prefix=/tmp
sudo apt install /tmp/qtcreator-opensource-linux-*-*.deb
```
The Debian package from https://download.qt.io should use the same dependencies, including Qt, that we use to build the plugin on the CI.

I was not aware that the Qt Creator Debian packages from https://download.qt.io and from https://github.com/qt-creator/qt-creator use different Qt versions. Good to know.

I will look into providing better instructions or an installation script for installing the Qt Creator Debian package and the matching plugin.

**Comment by doisyg** [comment]
And I was not aware of the deb versions in https://download.qt.io/ :smile: 
Strange that they are different, but anyway, with installing that version it works now. Thanks!

![image](https://github.com/user-attachments/assets/8d70ada6-2a7c-4ea9-aa16-568d829729db)
