### ISSUE TITLE
Spelling mistake in setup.sh

### ISSUE THREAD

**Issue by asmaloney** [ros-industrial/ros_qtc_plugin#54]
I'm not using this plugin, but I was looking at it as an example.

This spelling mistake jumped out at me:

   https://github.com/ros-industrial/ros_qtc_plugin/blob/master/setup.sh#L79

**Comment by Levi-Armstrong** [comment]
Thank you @asmaloney, I will get it fixed.

**Comment by Levi-Armstrong** [comment]
Addressed by PR #55
