### ISSUE TITLE
When add/importing package, active branch is not shown until project is reopended

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#57]
The active branch is not shown next to the folder name until the project is closed and opened again.

**Comment by oxoocoffee** [comment]
Can you please provide better explanation for this? Or how to recreate this scenario from start?

**Comment by Levi-Armstrong** [comment]
I set it up such that the branch is shown next to the package folder, and it should update if you go to the terminal and checkout a different branch but it currently does not. When I original set it up it was working but in the latest version of Qt Creator it appears to have quit working. [Here](https://github.com/ros-industrial/ros_qtc_plugin/blob/c8c08701f3d3d2d247316f14211fc5ca4b42d20d/src/project_manager/ros_project.cpp#L96) is where I am making the connection which should trigger an update when the branch is change via teminal.

**Comment by oxoocoffee** [comment]
So I try on my latest build and what I see is when I switch between back and forth between branches master and test [branch] next to project name does not auto refresh. When I switch focus to Qt creator then it updates (some refresh call?). Also placing break point in void ROSProject::repositoryChanged(const QString &repository) is never fired. I found void ROSProjectNode::updateVersionControlInfoHelper() and that also is not called.

**Comment by Levi-Armstrong** [comment]
Did you have any luck with why the call backs where not getting fired?

**Comment by Levi-Armstrong** [comment]
Seems to be fixed in the latest release.
