### ISSUE TITLE
No Executable Specified when running code from QtCreator

### ISSUE THREAD

**Issue by superjax** [ros-industrial/ros_qtc_plugin#58]
Hey, I love this plugin, it's fantastic, but I am having an issue.

When I try to run/Debug my node from within QtCreator, i get

```bash
No executable specified
Debugging has finished
```

I have set the Run Step to `rosrun <package> <node>` and I have a roscore running in the background, and I've tried starting qtcreator both from a terminal and from the supplied icon with the same result.

I can run successfully run the node from my terminal with `rosrun <package> <node>` 

I've also read the instructions on your wiki, and if I choose Debug->Start Debugging->Attach to an Unstarted Application and select my Executable then check "Continue on Attach" I get into this crazy loop where the debugger stops responding.

I've simplified my main file as much as I can, and I'm starting with a long `sleep()` command as mentioned in #29 to no avail.

Any ideas?

**Comment by Levi-Armstrong** [comment]
@superjax, This is just a guess, but which run button did you click? Because to debug ROS it currently requires the use of "Attach to an Unstarted Application" you should click the icon without the debug symbol.

**Comment by superjax** [comment]
I actually tried both.  If I run "Attach to an Unstarted Application" then the Play button (without the bug) then I get this response in the application output

'''
Debugging starts
Debugging has finished
'''

With the bug, then I get that weird loop.

**Comment by superjax** [comment]
By the way, here is my main file for reference

```c
#include <ros/ros.h>
#include "kitty_sim/kitty_sim.h"

int main(int argc, char** argv)
{
  sleep(1000);
  ros::init(argc, argv, "kitty_sim_node"); /// <--- breakpoint here
  ros::NodeHandle nh;

  kitty_sim::kittySim Sim;


  ros::spin();

  return 0;
}
```

**Comment by superjax** [comment]
Oh, you know what, I may be having issues with this because of Levi-Armstrong/gdb-7.7.1#2.  Do you think that might be the case?

**Comment by Levi-Armstrong** [comment]
That should not be an issue. That provides a particular feature not currently available but the plug-in does not depend on this feature.

**Comment by Levi-Armstrong** [comment]
@superjax, I will test your code today and see if I get the same behavior.

**Comment by Levi-Armstrong** [comment]
@superjax I have tested your example. The first thing I noticed is that `sleep(1000)` is set to 1000 seconds, usually 2 to 5 seconds works. After changing this to 2 seconds and rebuilding the workspace using the build configuration "Debug" everything attached fine. I was able to recreated the same debugger looping by building the project using build configuration "Release" or "Default" which is what every the project was previously built with which is usually "Release" and then attaching to the node. The debugger looping is a result of the `ros::spin` which the node never ends so the debugger stays attached. If you remove this line the debugger will end but not stop at your break point because the project was not built using the "Debug" build configuration. To change the build configuration go Projects on the left bar with the wrench icon and at the top of the page there is drop down box labeled build configuration, change this to "Debug" and rebuild the project. Then try again.

**Comment by Levi-Armstrong** [comment]
@superjax, were you able to resolve the issue?

**Comment by superjax** [comment]
Not really, I ended up just re-installing the most current version of QtCreator (not the plugin) and working with that.  I'm in the middle of some time-critical work so I don't have time to try the plugin again, but when i have time I'll try it again.  You can go ahead and close this issue, I'll re-open it if I have problems when I try again later.

**Comment by vharron** [comment]
I had this problem because my cmake binary moved off of my path and QtCreator couldn't find cmake anywhere.  YMMV

**Comment by ZuoJiaxing** [comment]
@vharron , I have the same problem with you.  Anyway to fix it ?

**Comment by vharron** [comment]
Change your PATH to include a cmake binary or move a cmake binary into your PATH

**Comment by maxgittelman** [comment]
Under Tools > Options > Build & Run > CMake, the auto-detected System CMake is found at `/usr/bin/cmake` should I be changing this to somewhere else, @vharron ? Everything runs smoothly when playing, it's only the fact that when debugging I get the double message

```
Debugging starts
Debugging has finished
```
@superjax Did you ever resolve the issue?

**Comment by Levi-Armstrong** [comment]
When debugging ros nodes you should use the attach to unstarted method described in the wiki. If it is a single node you can use the custom executable run step instead and then the run debug button will work assuming the project was built in debug.

**Comment by maxgittelman** [comment]
To which wiki are you referring?

**Comment by Levi-Armstrong** [comment]
The github wiki. Sorry for not provide a more detailed response, i am away from my computer at the moment.

**Comment by Levi-Armstrong** [comment]
Here is the [link](https://github.com/ros-industrial/ros_qtc_plugin/wiki/4.-Debugging-Catkin-Workspace).
