### ISSUE TITLE
QT Quick drop down doesn't have a ROS listed

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial/ros_qtc_plugin#59]
Ubuntu: 14.04

The `Qt Quick` drop down list doesn't have a ROS item as described in `3.4` - `#3`

**Comment by Levi-Armstrong** [comment]
I take a look today and see what the issue is.

**Comment by Levi-Armstrong** [comment]
@shaun-edwards: You are correct it is missing. Is it needed for the Qt Quick or should I remove the step from the wiki?

**Comment by shaun-edwards** [comment]
I don't need it, but I don't know what Qt Quick is?

**Comment by Levi-Armstrong** [comment]
I have removed this step from the wiki, based on the description below it does not apply.


>Qt Quick includes a declarative scripting language called QML. Qt Declarative is a runtime interpreter that reads the Qt declarative user interface definition, QML data, and displays the UI that it describes.
