### ISSUE TITLE
More details in debug mode

### ISSUE THREAD

**Issue by samieti02** [ros-industrial/ros_qtc_plugin#63]
Hello friendly people, 

according to issue #60 , i have other questions. 
Let say, this is how looks the structure of the package "catkin_ws" that i'm using and the node is called motive_node. So i have

>    /catkin_ws

> >            |_build
> >                   |_catkin, catkin_generated, CMakeFiles
> >                   |_motive_node, test_results
> >                   |_CATKIN_IGNORE, catkin_make.cahe, camke_install.cmake, .....
> >             |_devel
> >                   |_include, lib, share, setup.bash, ....
> >             |_gdb-7.7.1
> >             |_src
> >                   |_motive_node
> >                                |_config, include, launch, src, CMakeLists.txt, CMakeLists.txt.user, ...
> >                   |_build-motive_node-Desktop-Debug
> >                                |_catkin, catkin_generated, CMakeFiles, devel, src, test_results, CATKIN_IGNORE, ....
> >                   |_CMakeLists.txt
> 

ok , now i open for example 2 terminal, 
First, on one: i source qtcreator and start it, 
 
> open project->catkin_ws/src/motive_node/CMakeLists.txt (according that i have already run the command 'catkin_make'  a few days before).

qtcreator creates a new directory "build-motive_node-Desktop-Debug" with the new files, almost the same as the first directory build in  'catkin_ws/build'

on the 2nd terminal: i launch the node with roslaunch

And then i follow the instructions on issue #60 , 

1) Lets assume, you work with mocap in a company or at home and you have to connect ros to mocap using the command 'roslaunch', to get informations about motion (x,y,z) of the markers, that means the debugging can only work when this connection has been established, otherwise it cant work ?
Because when the software is in another place, and you are at home and only have the package 'motive_node' with you, you can not start to debug for example the cpp data contained in 'motive_node/src/motive_data.cpp' , because you are not able to connect to the mocap software, because roslaunch will not work ?
I ask, because it is not clear for me the meaning of attach to running application, unstarted application and start and debug external application? i thought that it would be possible to debugg the cpp data without to run 'roslaunch' , using unstarted application. Because like i said, when i'm in another place i can not run roslaunch and i want to make some modifications in the cpp data.

2) when  i follow the instructions on issue #60  , i also get 
QIODevice::read (QFile, "/proc/9701/stat"): device not open
QIODevice::read (QFile, "/proc/9702/stat"): device not open
QIODevice::read (QFile, "/proc/9708/stat"): device not open
QIODevice::read (QFile, "/proc/9711/stat"): device not open
... 

but i am still able to debug. Is it bad to have device not open on the console?

3) After that i have try 

> open project->catkin_ws/src/motive_node/CMakeLists.txt (according that i have already run the command 'catkin_make'  a few days before).

then i tried 

> open project->catkin_ws/src/CMakeLists.txt (according that i have already run the command 'catkin_make'  a few days before).

And then

> Projects->build->Edit build configuration: Debug

A new project and new directory were created 'catkin_wsbuild-src-Debug' under catkin_ws/catkin_wsbuild-src-Debug, containing also the information,

what do you think is the preferred version between the 2 variants? Or is it better to directly import the workspace using import ros project?

4) Let say , i have a code which looks like this 

`#include "motive_node/motive_data.h"`
`#include "motive_node/motive_config.h"`
`#include <ros/ros.h>`
`#include <tf/transform_datatypes.h>`
`#include <string>`

`int main( int argc, char* argv[] )`
`{ `
`  // Initialize`
`  ros::init(argc, argv, "mo_node");`
`  ros::NodeHandle n("~");`

` string infos = "My first stream"`
` ROS_DEBUG_STREAM("Info" << infos)`
`  }`

I can not stream the info on the console. Also ROS_DEBUG doesnt work?

Does anyone can help?

Thank you so much!
Sami

**Comment by Levi-Armstrong** [comment]
Hello Sami, It appears you are not using the ros project manager plugin. If you open using the CMakeLists.txt it will use the built-in cmake project manager. I recommend using the ros project manager because it is built specifically for ROS,  please refer to the this [tutorial](https://www.youtube.com/watch?v=GqBzI7O9h8A). 

But to try and address the issue, if it is not printing out ROS_DEBUG in the Qt Creator application output, I would recommend adding a "\n" to the end of your string and see if this works. If so, there may be an issue with Qt Creator application output window.

**Comment by Levi-Armstrong** [comment]
>Is it bad to have device not open on the console?

This is an artifact of the terminal window I am using, it is not an issue. In the next release this should be resolved.

**Comment by Levi-Armstrong** [comment]
@samieti02 Where you able to resolve the issue?

**Comment by samieti02** [comment]
@Levi-Armstrong  Thanks a lot for the reply. 
I was able to debug. I could see the values in the right side, but sometimes when i save differents values (using a for loop), in a variable created with a defined class, i  can see only the 1st change (for i=0), but not the other changes (for i>0), when i loop.
   
Sometimes, when i debug, the arrow on the left side jumps directly into the while(ros::ok()) and doesnt stop on ros::init(argc, argv, "mo_node"); ros::NodeHandle n("~"), although i have set some breakpoints on the code line ros::init(argc, argv, "mo_node"); . This happens when i import the complete package using the function of the plugin, but when i open the project by locating or using the path workspace/src/CMakelist.txt, and then debug, it stops on ros::init(argc, argv, "mo_node");  I dont know why?????

ROS_DEBUG still dont work. The debug console remains blank.

**Comment by Levi-Armstrong** [comment]
>I was able to debug. I could see the values in the right side, but sometimes when i save differents values (using a for loop), in a variable created with a defined class, i can see only the 1st change (for i=0), but not the other changes (for i>0), when i loop.

@samieti02 This would be a good question for Qt Creator Developers. See the [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/5.-Where-to-find-Qt-Creator-Plug-in-Support) for information on where to get help.

>Sometimes, when i debug, the arrow on the left side jumps directly into the while(ros::ok()) and doesnt stop on ros::init(argc, argv, "mo_node"); ros::NodeHandle n("~"), although i have set some breakpoints on the code line ros::init(argc, argv, "mo_node"); . This happens when i import the complete package using the function of the plugin, but when i open the project by locating or using the path workspace/src/CMakelist.txt, and then debug, it stops on ros::init(argc, argv, "mo_node"); I dont know why?????

How are you attaching the debugger?

> ROS_DEBUG still dont work. The debug console remains blank.

Did you try adding the new line character to the end of the string being printed out?

**Comment by samieti02** [comment]
Thks for the feedback and sorry for the late answer., i was not there.

How are you attaching the debugger?
Under Debug, i select attach to an unstarted programm, i choose the node where it is located in devel/lib. ANd then ctrl+r to start, then the program stop first at the line code ros::NodeHandle n, even without breakpoints. Here i have to start the node in the terminal using the roslaunch command, and then it goes ahead.

Did you try adding the new line character to the end of the string being printed out?
yes i added at the end \n ,but it still dont work

**Comment by Levi-Armstrong** [comment]
When using the method attach to unstarted program some node can launch faster than the debugger can attach. In this case I add a sleep(5) at the top to allow time for the debugger to attach. I don't know of anyway around this at the moment.

>but when i open the project by locating or using the path workspace/src/CMakelist.txt, and then debug, it stops on ros::init(argc, argv, "mo_node"); I dont know why?????

I assume when using the CMakeProject manager you are launching the executable directly which is different than attaching to an unstarted program. You can achieve the same behavior within the ros plugin by using the custom process run step.

**Comment by Levi-Armstrong** [comment]
@samieti02 Wanted to follow up and see if you are still having issues.

**Comment by samieti02** [comment]
@Levi-Armstrong , thks for the reply. No new one. I use now, most of the time the process run step.
