### ISSUE TITLE
Can't change code style (formatting)

### ISSUE THREAD

**Issue by facontidavide** [ros-industrial/ros_qtc_plugin#64]
I noticed that when the plugin is active I can not modify the formatting in Preferences->C++->Code Style.

To be precise, I change them, but my settings are ignored

**Comment by Levi-Armstrong** [comment]
Sorry this should probably be in the wiki somewhere, but the ros plug-in sets the code style at the project level which is convenient when working on different projects with different code styles. This will eventually make its way into a settings option but I just have not gotten around to creating the widget yet. If you select the projects tab on the left you will see a few option at the top like Build & Run | Editor | Code Style | Dependencies | etc. Under the Code Style tab is where you set the project level code style.
