### ISSUE TITLE
Can't see the ros option in the import project drop list after installation.

### ISSUE THREAD

**Issue by lightofaugust** [ros-industrial/ros_qtc_plugin#65]
Hi Levi,

My installation process went kind of smooth I guess, but the plug-in was not added in qt creator. 
1. I can't see the ros workspace option in the import drop list;
2. There was no ros related plug-in the plug-in list either.
any suggestions?
![qt plugin](https://cloud.githubusercontent.com/assets/16217997/21131938/69f35b06-c14c-11e6-9a2b-4f3b089b22dd.png)

thanks.

**Comment by gavanderhoorn** [comment]
Can you make sure you're starting the correct `qtcreator` binary?

**Comment by lightofaugust** [comment]
I think so, I'm not quite sure what you mean by 'correct'. 
![screenshot from 2016-12-13 16 17 26](https://cloud.githubusercontent.com/assets/16217997/21132583/b59b845e-c14f-11e6-9195-b684d31f4215.png)

**Comment by gavanderhoorn** [comment]
Do you have another version of Qt Creator on your system?

What is the output of `which qtcreator`?

**Comment by Levi-Armstrong** [comment]
Can you try the instructions below and let us know if it works using this method?
```
source /opt/qt57/bin/qt57-env.sh
./opt/qt57/bin/qtcreator-wrapper
```

**Comment by Levi-Armstrong** [comment]
Also based on the image you provide, the version 4.0.0 suggest you must have the default version of qtcreator also installed. The version that comes with qt57creator is 4.1.0, so I recommend doing a purge removal of qt57creator and qtcreator, then reinstall qt57creator.

**Comment by lightofaugust** [comment]
Sorry for the late response, I didn't have access to my laptop recently.
@gavanderhoorn ,hi gavanderhoorn, i'm using ubuntu14 lts. And I don't get anything from 'which qtcreator' in the terminal.
@Levi-Armstrong , hi Levi, the instruction you provided gives 'no such file or directory'. I will try reinstall qt57 first and let you know the result. 

Many thanks!

**Comment by lightofaugust** [comment]
Hi Levi, 
I initially installed qt4 creator from the ubuntu14 software center, before I installed qt5.7, I unistalled qt4 creator also from the software center. You see the qt creator version is 4.0.2 because that's the defaut version that comes with qt5.7.0. 
So now I unistalled qt5.7, to this point I suppose that I have removed both versions of qt creator. I installed version 4.2.0 creator seperately(without installing qt5.7.*). Still I don't get the ros plugin. 

![screenshot from 2016-12-23 11 43 09](https://cloud.githubusercontent.com/assets/16217997/21446738/0acc1fb2-c905-11e6-8a3e-43ee9c8781b6.png)

any suggestion?
Thanks!

**Comment by Levi-Armstrong** [comment]
Sorry you are still having issues. The current plug-in requires qt57creator and qt57creator 4.1.0. [Here](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt57-trusty) is a link to qt57creator showing to be version 4.1.0 so I think you have qtcreator installed from a different source. Try installing qt57creator again and try the command below in a terminal. My previous request was incorrect shown below, I was going off memory and did not test it.

Correct: (Tested)
`/opt/qt57/bin/qtcreator-wrapper `

Incorrect:
```
source /opt/qt57/bin/qt57-env.sh
./opt/qt57/bin/qtcreator-wrapper
```

**Comment by Levi-Armstrong** [comment]
Here is what you should see:
![screenshot from 2016-12-23 00 54 58](https://cloud.githubusercontent.com/assets/9803128/21448625/7e567b86-c8aa-11e6-9e16-f8a91e9499dc.png)

![screenshot from 2016-12-23 00 56 44](https://cloud.githubusercontent.com/assets/9803128/21448654/bbec2040-c8aa-11e6-8643-3dc50e0a23bf.png)

**Comment by Levi-Armstrong** [comment]
Also qt57creator should create a desktop icon. If it does not then create a file on your desktop called qt57creator.desktop and place the content below in the file.
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Exec=/opt/qt57/bin/qtcreator-wrapper %F
Icon=QtProject-qtcreator
Type=Application
Terminal=false
Name=Qt 5.7 Creator
GenericName=Integrated Development Environment
MimeType=text/x-c++src;text/x-c++hdr;text/x-xsrc;application/x-designer;application/vnd.nokia.qt.qmakeprofile;application/vnd.nokia.xml.qt.resource;
Categories=Qt;Development;IDE;
InitialPreference=9
```

**Comment by lightofaugust** [comment]
Thanks Levi,
It works! 
another minor problem though: when I run '/opt/qt57/bin/qtcreator-wrapper' in the terminal, I got the following warning, which I don't know if it matters. 
`~$ /opt/qt57/bin/qtcreator-wrapper
Cannot update Qt version information: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake cannot be run.
`
Thanks!

**Comment by Levi-Armstrong** [comment]
I will look into it and see if I get the same message launching from the terminal.
