### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by won13y** [ros-industrial/ros_qtc_plugin#69]
I have met following problem related to unmet dependencies.

wkyoun@wkyoun-XPS-13-9343:~/catkin_ws/src$ sudo apt-get install qt57creator-plugin-ros

    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:

    The following packages have unmet dependencies:
     qt57creator-plugin-ros : Depends: qt57creator (>= 4.1.0) but it is not going to be installed
    E: Unable to correct problems, you have held broken packages.

**Comment by Levi-Armstrong** [comment]
Did you add both ppa's shown in the [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)#11-installation-procedure-for-ubuntu-1404)?

**Comment by Levi-Armstrong** [comment]
@won13y I wanted to follow up and see if were able to get the issue resolved?
