### ISSUE TITLE
The setup.sh script is cloning the wrong ros_qtc_plugin repository.

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#7]

**Comment by Levi-Armstrong** [comment]
This has been addressed by PR #5.

Developers and user, to fix the issue you must delete both folders (ros_qtc_plugins and ros_qtc_plugins-build) then go through the setup process again.

Note: There is no need to delete the folders (qt-creator and qt-creator-build) as long the setup process is executed in the same location as the first time it was ran.

**Comment by Levi-Armstrong** [comment]
FYI, @VictorLamoine and @raultron

**Comment by VictorLamoine** [comment]
I did not try the plug-in yet but thanks for the info :)

**Comment by raultron** [comment]
Thanks :)
