### ISSUE TITLE
Symlink does not execute

### ISSUE THREAD

**Issue by huoxiaoyao** [ros-industrial/ros_qtc_plugin#76]
executing direclty or sourcing wirks fine, but symlinking the wrapper does not open qtcreator any more. Seems like an easy fix, just open qtcreator directly without testing for names etc (here is the debug output):

+ QT_BASE_DIR=/opt/qt57
+ export QTDIR=/opt/qt57
+ QTDIR=/opt/qt57
+ export PATH=/opt/qt57/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ PATH=/opt/qt57/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
++ uname -m
+ [[ x86_64 == \x\8\6\_\6\4 ]]
+ export LD_LIBRARY_PATH=/opt/qt57/lib/x86_64-linux-gnu:/opt/qt57/lib:
+ LD_LIBRARY_PATH=/opt/qt57/lib/x86_64-linux-gnu:/opt/qt57/lib:
+ export PKG_CONFIG_PATH=/opt/qt57/lib/pkgconfig:
+ PKG_CONFIG_PATH=/opt/qt57/lib/pkgconfig:
++ echo qtcreator
++ grep wrapper
+ TEST=
+ '[' '' '!=' '' ']'

vs, when executing directly:

+ QT_BASE_DIR=/opt/qt57
+ export QTDIR=/opt/qt57
+ QTDIR=/opt/qt57
+ export PATH=/opt/qt57/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ PATH=/opt/qt57/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
++ uname -m
+ [[ x86_64 == \x\8\6\_\6\4 ]]
+ export LD_LIBRARY_PATH=/opt/qt57/lib/x86_64-linux-gnu:/opt/qt57/lib:
+ LD_LIBRARY_PATH=/opt/qt57/lib/x86_64-linux-gnu:/opt/qt57/lib:
+ export PKG_CONFIG_PATH=/opt/qt57/lib/pkgconfig:
+ PKG_CONFIG_PATH=/opt/qt57/lib/pkgconfig:
++ echo /opt/qt57/bin/qtcreator-wrapper
++ grep wrapper
+ TEST=/opt/qt57/bin/qtcreator-wrapper
+ '[' /opt/qt57/bin/qtcreator-wrapper '!=' '' ']'
++ echo /opt/qt57/bin/qtcreator-wrapper
++ sed s/-wrapper//
+ exec /opt/qt57/bin/qtcreator

, which works fine

**Comment by huoxiaoyao** [comment]
reason being of course that $0 is "qtcreator", not "qtcreator-wrapper" when executed in this way. Just replacing the whole block with exec `qtcreator` $* fixes this

**Comment by Levi-Armstrong** [comment]
@huoxiaoyao Sorry what file is this, is this the qtcreator-wrapper file?

**Comment by huoxiaoyao** [comment]
oh, sorry, yes, this is the qtcreator-wrapper

**Comment by Levi-Armstrong** [comment]
Do you mind posting it [here](https://answers.launchpad.net/~beineri)? I don't have control of the qt library just the ros qt plug-in but the maintainer has been responsive in fixing issues.

**Comment by huoxiaoyao** [comment]
Ah yes, sure. Thanks for letting me know.
