### ISSUE TITLE
beneiri PPA for Qt5.7 no longer exists

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/ros_qtc_plugin#77]
As far as I can tell, it has been renamed to [opt-qt571-trusty](https://launchpad.net/~beineri/+archive/ubuntu/opt-qt571-trusty) (from `opt-qt57-trusty`).

The wiki should probably be updated to reflect this.

**Comment by gavanderhoorn** [comment]
And the plugin rebuild, as various dependencies also no longer exist.

**Comment by Levi-Armstrong** [comment]
You are right it was there last week, but I will work on getting it updated. Also 5.71 uses qtcreator 4.2 so I will create a new version of the plug-in.

**Comment by Levi-Armstrong** [comment]
Everyone, to prevent further issues I have created my own ppa to store the qt libraries. This will prevent unknown update in the beneiri ppa. See the updated [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)) for instructions on removing the beneiri ppa's and adding the my ppa.

**Comment by oxoocoffee** [comment]
I am trying to ad your ppa and getting error. I am running Linux Mint 18.1 x64 (based on Ubuntu 16.04)
My  $ lsb_release -c
Codename:	serena

 $ sudo add-apt-repository ppa:beineri/opt-qt57-xenial
[sudo] password for oxoocoffee: 
'This PPA does not support xenial'

Would it be possible to add serena?

**Comment by oxoocoffee** [comment]
I figured I will go for now with Virtual box. So following your Wiki I got this on Ubuntu Desktop 16.04 .x64

sudo add-apt-repository ppa:beineri/opt-qt57-xenial
sudo add-apt-repository ppa:levi-armstrong/ppa
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros libqtermwidget57-0-dev

Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                                              
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                               
Hit:4 http://ppa.launchpad.net/levi-armstrong/ppa/ubuntu xenial InRelease                                           
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                                       
Fetched 306 kB in 0s (406 kB/s)                                                               
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libqtermwidget57-0-dev : Depends: libqtermwidget57-0 (= 0.6.0-0xenial1) but it is not going to be installed
 qt57creator-plugin-ros : Depends: libqtermwidget57-0 (>= 0.6.0) but it is not going to be installed
                          Depends: qt57base but it is not installable
                          Depends: qt57creator (>= 4.2.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

Did you ever see this?

**Comment by Levi-Armstrong** [comment]
Did you go through this [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)) where the install procedure is as below? I would recommend removing anything installed from the beineri repository and then remove the beineri ppa.

```
sudo add-apt-repository ppa:levi-armstrong/qt-libraries-xenial  
sudo add-apt-repository ppa:levi-armstrong/ppa  
sudo apt-get update && sudo apt-get install qt57creator-plugin-ros
```

**Comment by oxoocoffee** [comment]
Nop I did not but I will. I did go straight to developers. Perhaps for fresh install it would be good to add link to Users first to remove beineri or update Developers?

https://github.com/ros-industrial/ros_qtc_plugin/wiki/2.-Improve-ROS-Qt-Creator-Plugin-(Developers-ONLY)

**Comment by oxoocoffee** [comment]
Ok That worked for me. I had little problem with rendering Qt Creator menus under VirtualBox bot I got this resolved.  For some that might experience this issue I installed "sudo apt-get install gnome-session-fallback" 
and selected software renderer "GNOME Flashback (Meta City) with 3D option turned off in VM settings and this fixed my problem.

**Comment by Levi-Armstrong** [comment]
Oops, I forgot to update the Developers wiki. It has been updated.
