### ISSUE TITLE
For ROS run configuration

### ISSUE THREAD

**Issue by passgall** [ros-industrial/ros_qtc_plugin#80]
Hi,
When I use this new version ros_qtc_plugin. I can build project successfully. But when I want to run the project .In the step ROS run configuration, the ros_qtc_plugin cannot auto detect the package and node. So I should fill this message manually like this"ROS Step: rosrun beginner_tutorials listener". I cannot upload the picture by this . I remember that this can auto detect in the old version. Can you give me a old version？Because this is very confuse for a beginner. Thanks!

**Comment by Levi-Armstrong** [comment]
I will look into it and see if I have the same issue.

**Comment by Levi-Armstrong** [comment]
Are you not able to use the drop down and select the package?

**Comment by passgall** [comment]
yes！I should do this by adding in the argument

**Comment by Levi-Armstrong** [comment]
I am a little confused. Let me know which of the following steps did not work.

1. Add the rosrun step.
2. Select a package.
  - Is the package in the list?
3. Select an executable.
  - Is the executable in the list?
  - If not, in a terminal can you navigate to the devel directory and verify that the executable actual exists?

**Comment by passgall** [comment]
When I added the rod step，the package is not in the list.Also I cannot select the package because the list box is disabled.The node list is the same.
I didn't use the method you mentioned in third.

**Comment by Levi-Armstrong** [comment]
Is this what yours looks like? But your not able to find your package name in the list?

![image](https://cloud.githubusercontent.com/assets/9803128/22361476/b416d172-e41f-11e6-9fc6-700fd7e975c6.png)

If that is the case lets launch Qt Creator from a terminal and see what messages are being printed out. Launch Qt Creator using the command below, then go through the step of adding the ROS Run Step, then selecting the drop down list. Then go to the terminal and past any information that was printed out. This should help narrow down what is going on.

`/opt/qt57/bin/qtcreator-wrapper`

**Comment by passgall** [comment]
I just do this by your suggestion.  I have found that many package showed in the drop down list but the package name of my project is not display in the package list .I do not know why?

**Comment by Levi-Armstrong** [comment]
Did anything print out in the terminal?

Also can you navigate to your workspace, then source it and run the following command and let me know if your package is listed there.

`rospack list | grep "name_of_package`

**Comment by passgall** [comment]
Hi, 
I run qtcreator from terminal and I use this command “rospack list | grep "my package name”in the terminal. I cannot find the package name in the package name list. Also there are no printing out messages in the terminal.

**Comment by Levi-Armstrong** [comment]
It sounds like there maybe an issue with the workspace or package. Did you source the workspace prior to running the rospack command in the terminal?

**Comment by Levi-Armstrong** [comment]
So I did a lot of testing and I was able to recreate the issue. I submitted a fix PR #81 and once merged I will push another binary. Thank you for the feedback.

**Comment by Levi-Armstrong** [comment]
Addressed by PR #81

**Comment by passgall** [comment]
hi,
I have  found another question. When I run node in qtcreator. It shows this message in QT Ros terminals "run talker" where the talker is node name. But the package name "beginner_tutorials" is lost. So there are no other message shown in the QT Ros terminal.
When I used "rosrun  beginner_tutorials talker" in ubuntu terminal. It works very well.So there are some errors in the /ros_qtc_plugin.Can you give me sugesstions?
