### ISSUE TITLE
new Qt Creator 5.7.1 build wont load properly

### ISSUE THREAD

**Issue by iminternet** [ros-industrial/ros_qtc_plugin#82]
I installed your new qt creator 4.2 with qt 5.7.1 build in my new (clean) ubuntu 14.04 virtual machine.
I used your new PPA cause the old benri PPA wasn't available any more.
After installation I can start your qt creator but it is not loading properly.
![qtcreator571](https://cloud.githubusercontent.com/assets/24550050/22395514/7a8f6680-e541-11e6-89c4-0b533315d7a6.JPG)
The "Welcome" page stays black and it is not possible to click any menu button. It doesnt open anything.
You can choose the "Edit" page, but you can not open anything. There is no right click menu or anything working. Most of the time those pressing actions result in a crash of qt creator.

I tried reinstalling the plugin and "apt-get purge" the whole qt creator and installing it again.
Didn't help.
Can you help me solving the problem?

Thanks in advance!

PS: My work installation still works fine (the older Qt Creator 4.1 build with Qt 5.7.0), but I did not add the new PPA yet there so I guess it didn't update.

**Comment by Levi-Armstrong** [comment]
I did an upgraded on my machine after changing the ppa and everything still appeared to work. I will purge my system of qt57 and reinstall to see if I have the same issue.

**Comment by Levi-Armstrong** [comment]
So I uninstalled all of qt57 on my machine and reinstalled it and everything worked. I will create a vm tomorrow and see if I can recreate the issue.

**Comment by iminternet** [comment]
Does Qt Creator need graphical hardware assistance for drawing the application window? Maybe its not working cause there is not 3D hardware acceleration in my virtualbox VM?

**Comment by Levi-Armstrong** [comment]
>Does Qt Creator need graphical hardware assistance for drawing the application window? Maybe its not working cause there is not 3D hardware acceleration in my virtualbox VM?

I am not sure on this.

I did create a new VM and installed everything per the wiki and everything worked for me. I would assume maybe something else is going on. I would check the version of Qt Creator just to make sure it is launching the qt 5.7.1 version.

**Comment by Levi-Armstrong** [comment]
Are you still having issues on the VM?

**Comment by iminternet** [comment]
I turned of the "3D hardware acceleration" for my VM. Now it works fine.
Sorry it wasnt a problem of your Qt Creator build after all.
Thanks anyway for your help :)
