### ISSUE TITLE
Show warning pop-up message with "debug" button is pressed

### ISSUE THREAD

**Issue by Levi-Armstrong** [ros-industrial/ros_qtc_plugin#83]
If the user is trying to debug a **roslaunch** or a **rosrun** configuration and the "debug" button is presses, launch a pop-up message that reminds that the correct process require the manual use of "Attach to unstarted application". 

@facontidavide Thank you for your feedback.

**Comment by passgall** [comment]
I have  an issue like this.When I followed this process
   Compile in debug mode. Note: Make sure the build configuration is set to debug.
   Debug-> Start Debugging->Attach to unstarted application--> and then choose the executable and    start watching
   Then press Ctrl+R (Assuming the run configuration is setup to launch your node, otherwise you run it from any terminal on the machine and it will still attach.)
....
It shows Debugging start. Debugging has finished.  And debug cannot stop at breakpoints. I found some questions that other learners had proposed .But I cannot solve this question.

**Comment by Levi-Armstrong** [comment]
When using the attach methods, sometime your programs can finish before the debugger can full attach. I recommend adding a `sleep(3);` at the top of your program to give the debugger time to attach.

**Comment by passgall** [comment]
I added this sleep(3) or sleep(300) at top of program. But it still does not work.

**Comment by Levi-Armstrong** [comment]
Please verify that the executable has been built in debug, see [here](http://stackoverflow.com/questions/3284112/how-to-check-if-program-was-compiled-with-debug-symbols) for instructions.

**Comment by passgall** [comment]
Sorry, I can not understand your instruction. I had Build System : CatkinMake and BuildType :Debug. Also I have checked the managekit. There are no mistake. Is this not ok?

**Comment by Levi-Armstrong** [comment]
Sorry for not giving more details, but it is possible to define it in the CMakeLists.txt file and it will ignore the flag passed to catkin_make. It would be good to verify that the actual executable in your devel directory is actually built in debug by following the instruction in the link.

**Comment by passgall** [comment]
Sorry,Can you tell me how to modify in the CMakeLists.txt file for detail? I really don't know what to do!

**Comment by Levi-Armstrong** [comment]
Try this:

- Step 1: cd <workspace>/devel/lib/<package name>
- Step 2: objdump --syms <node name> | grep "debug"

If it was built in debug this will print information to the terminal, if not nothing will be printed.

**Comment by passgall** [comment]
When I used the up step, It shows "debug_info, debug_abbrev, debug_line..." I think my program was built in debug mode. But It still can not stop at breakpoints.

**Comment by passgall** [comment]
I followed this comment http://answers.ros.org/question/204263/debugging-with-qtcreator/. It works...
very thanks!

**Comment by Levi-Armstrong** [comment]
Do you mind explaining what you had to do, to get it to work?

**Comment by Levi-Armstrong** [comment]
I you had a CMakeLists.txt.user file this would mean you are not using this plugin but the CMake plugin provided by Qt, because this plug.creates a .workspace and .workspace.user file.

**Comment by passgall** [comment]
I have tested it by another computer. Maybe my setup was suited for this comment http://answers.ros.org/question/34966/debugging-ros-package-with-qtcreator/?answer=34977#post-id-34977.
When I added this ...
sudo apt-get install libcap2-bin 
sudo setcap cap_sys_ptrace=eip /usr/bin/gdb
It works!

**Comment by Levi-Armstrong** [comment]
Ah, did you ever go through this [wiki](https://github.com/ros-industrial/ros_qtc_plugin/wiki/3.-Setup-Qt-Creator-for-ROS)? Section 3.1 setups ptrace but it is different that what you did, if not I will add these step to the wiki, but I am not sure if they are needed.

**Comment by passgall** [comment]
Sorry. I did't go through section 3.1 of the wiki before.

**Comment by Levi-Armstrong** [comment]
OK, usually I would get a pop up message bellow. Did you every receive this message?

```
ptrace: Operation not permitted.

Could not attach to the process. Make sure no other debugger traces this process.
Check the settings of
/proc/sys/kernel/yama/ptrace_scope
For more details, see /etc/sysctl.d/10-ptrace.conf
```

**Comment by nathangeorge1** [comment]
hello @Levi-Armstrong, currently I'm getting this message; how do I fix it so that I can debug? My process is building in debug mode, and following `4.1 Attach to a unstarted process` at https://github.com/ros-industrial/ros_qtc_plugin/wiki/4.-Debugging-Catkin-Workspace

**Comment by nathangeorge1** [comment]
Also my message looks like this:

![image](https://user-images.githubusercontent.com/2744891/30341473-188c76cc-97c4-11e7-8469-cfd2df15a2cb.png)

**Comment by nathangeorge1** [comment]
I fixed it by following `3.1 Setup Ubuntu to allow debugging/ptrace` at https://github.com/ros-industrial/ros_qtc_plugin/wiki/3.-Setup-Qt-Creator-for-ROS

**Comment by Levi-Armstrong** [comment]
@nathangeorge1 Thank you for your feedback. I have updated the wiki with a prerequisite section point the instructions for allowing ptrace.

**Comment by Levi-Armstrong** [comment]
#152 Adds message box when pressing run debug.

**Comment by Levi-Armstrong** [comment]
Update I have integrated a Attach to Unstarted Run Step to simplify debugging ros workspace. Now you can add the run step to start watching for the process press the debug run button. Note: You must either add another run step that actually launches the node or launch it from another terminal.
