### ISSUE TITLE
rosrun doesn't work properly after adding a Run step in Run Settings

### ISSUE THREAD

**Issue by vdivald** [ros-industrial/ros_qtc_plugin#84]
I created an empty workspace, I have built it without a problem, then went to the Projects tab to Add Run Step. It lists the available packages properly, I chose rviz package with rviz target to test, so basically it should run 'rosrun rviz rviz'. But when I hit the Run button, the package just disappears and it tries to run only 'rosrun  rviz' in the console. It happens with any other package as well when I try/create other ones.

I created a screencast video about the problem: https://www.youtube.com/watch?v=7YFolYlOn1E

**Comment by Levi-Armstrong** [comment]
@vdivald, thank you for your feedback. I also noticed that late last week. I hope to have a fix soon.

**Comment by aje0005** [comment]
I seem to be running into the same exact problem. I've tried reinstalling the plugin as per the instructions and by running bash setup.sh and I am still having the same problem. What is the best way I can incorporate the fix into my install?

Thanks

**Comment by Levi-Armstrong** [comment]
Sorry @aje0005, I have not done release with the latest fix. I will try and push a new version tonight.

**Comment by Levi-Armstrong** [comment]
The package has been released. You can perform:
```
sudo apt-get update & sudo apt-get upgrade
```

**Comment by vdivald** [comment]
Thank you Levi, it works well now.

**Comment by aje0005** [comment]
Thanks Levi!
