### ISSUE TITLE
ros/ros.h

### ISSUE THREAD

**Issue by cl13554212322** [ros-industrial/ros_qtc_plugin#87]
ros/ros.h no such file or directory:
I have added the <IncludePaths> aready, but it doesn't work.
`<?xml version="1.0" encoding="UTF-8"?>
<Workspace>
    <Distribution name="indigo"/>
    <WatchDirectories>
        <Directory>src</Directory>
    </WatchDirectories>
    <IncludePaths>
        <Directory>/opt/ros/indigo/include/</Directory>
    </IncludePaths>
</Workspace>`
Thank you!

**Comment by cl13554212322** [comment]
Add: I have installed the new Qt on Ubuntu14.04/indigo, I can import ROS workspace, but I can't find the header file.
1.   sudo add-apt-repository ppa:levi-armstrong/qt-libraries-trusty
2.   sudo add-apt-repository ppa:levi-armstrong/ppa  
3.   sudo apt-get update && sudo apt-get install qt57creator-plugin-ros

**Comment by Levi-Armstrong** [comment]
That is normal when you first import a workspace. They way the IDE works is it requires a Code Block Project file to be generated which provides the necessary information to the IDE, like include paths, source files, etc. If you build the project from within the IDE it will generate these files and parse them, followed by updating the Qt Creator Code model. Then everything should work. The code model gets updated every time the project is built within IDE.

**Comment by cl13554212322** [comment]
Thanks, I have sovled the problem already.
`sudo gedit /usr/lib/x86_64-linux-gnu/qtchooser/default.conf` 
and changed the text
/home/chlong/Qt5.7.0/5.7/gcc_64/bin
/home/chlong/Qt5.7.0/5.7/gcc_64/lib
to
/opt/qt57/bin
/opt/qt57/lib
then,  all will works.
