### ISSUE TITLE
Debugging with boost vectors

### ISSUE THREAD

**Issue by aje0005** [ros-industrial/ros_qtc_plugin#91]
I've been working with this plugin for a couple weeks now, and am loving it. However, one thing that has been frustrating is that when I am debugging my ros node, the values stored in boost vectors do not show up in the workspace panel to the right. All the panel will show me is the size of the vector. This forces me to write cout statements everywhere to see what the values are, which almost defeats the purpose of using an ide. 

The type of boost vector is as follows:

boost::numeric::ublas::vector

Is there anyway I can values stored in these vectors to show up while debugging? Thanks.

**Comment by Levi-Armstrong** [comment]
I have seen this with pointer arrays but it may be the same. See this [link](http://stackoverflow.com/questions/7533833/view-array-contents-in-qt-creator-debugger).

**Comment by Levi-Armstrong** [comment]
Also you may take a look [here](https://svn.boost.org/trac/boost/wiki/DebuggerVisualizers).
