### ISSUE TITLE
Wiki page not showing correctly

### ISSUE THREAD

**Issue by mmoerdijk** [ros-industrial/ros_qtc_plugin#97]
There are some small problems with the wiki page.
[https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)#section1.1](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)#section1.1)

**Comment by gavanderhoorn** [comment]
Fixed ([diff](https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)/_compare/07f5be35e9ea64b1b180ad5612a361953899affc...a06791046dab2bfddee77d82147aec0d8a51ef79)).
