### ISSUE TITLE
Qt is not finding my headers anymore.

### ISSUE THREAD

**Issue by bracco23** [ros-industrial/ros_qtc_plugin#98]
I opened Qt as usual to work on my code and now it cannot find my code anymore.

I have the usual structure:

pkg
|----include
|----|----pkg
|----|----|----*bunch of include files*
|----src
|----|----*bunch of src files*

The package are compiling fine with catkin_make, but Qt doesn't see my headers anymore.

In one of the src i have included my headers, Eigen headers and the headers of my messages and of this three only the messages gets found, for the others Qt tells me it cannot find them. (but it can find, in another executable, gtest headers)

I tried deleting the "project.workspace" files and importing it again, uninstalling and reinstalling the plugin and uninstalling and reinstalling everything, but nothing worked.

EDIT: 

I add some info about my system:

**uname -r -v -m -p -i -o**

4.4.0-67-generic #88~14.04.1-Ubuntu SMP Thu Mar 9 15:30:23 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**qt version**
Qt Creator 4.2.1
Based on Qt 5.7.1 (GCC 4.8.4, 64 bit)

**ros plugin version**

Name: ROSProjectManager
Version: 4.2.1
Compatibilty version: 4.2.0

**Comment by Levi-Armstrong** [comment]
Can you try building with catkin tools? Goto your build settings and change it to catkin tools and add a build and clean step. You do not need to remove the catkin make step they get disabled when you switch the build system to catkin tools. You will also have to perform a clean after adding the new steps to wipe out the catkin make build files.

**Comment by bracco23** [comment]
After building with CatkinTools it worked, now it can see all the headers, but it used to work also with CatkinMake.

**Comment by Levi-Armstrong** [comment]
Have you recently updated your system?

If you don't mind, can you launch qt creator from a terminal and rebuild using catkin make and let me know if anything gets printed to the terminal?

**Comment by bracco23** [comment]
yes, I received updates for ros and the plugin for the 08/03 according to my apt history.

I ran qt from the console and the moment, I opened the project, did a clean and a build with catkin_make and a bunch of messages have been written on the terminal.
To have the messages more clearly divided between clean and build I closed everything and ran again, and the same messages appeared the moment I opened the project.

"Unable to parse build information for package: crazyflie"
"Unable to parse build information for package: crazyflie_controller"
"Unable to parse build information for package: crazyflie_cpp"
"Unable to parse build information for package: crazyflie_driver"
"Unable to parse build information for package: crazyflie_tools"
"Unable to parse build information for package: formation_control"
"Unable to parse build information for package: gazebo_tutorials"
"Unable to locate build information for package: gztutorial_gazebo"
"Unable to locate build information for package: hector_keyboard_teleop"
"Flags file does not exist: /home/bracco23/tesi_catkin_ws/build/mocap_optitrack/CMakeFiles/mocap_optitrack_mocap_node.dir/flags.make"
"Unable to parse build information for package: netft_utils"
"Unable to parse build information for package: ram_crazy"
"Unable to locate build information for package: rrbot_control"
"Unable to locate build information for package: rrbot_description"
"Unable to locate build information for package: rrbot_gazebo"
"Unable to locate build information for package: two_quad_load"

**Comment by Levi-Armstrong** [comment]
>Also, it seems to me that the packages there are in a "Unable to locate..." are all the packages I have under a CATKIN_IGNORE folder, the others are the packages I actually build.

Ah, are the missing headers files in the packages with the CATKIN_IGNORE file? If so, you will need to actually build them from the IDE at least once and after every clean so the necessary project files get generated by cmake. Try removing the CATKIN_IGNORE and after the first successful build adding it back and let me know if it solves the issue. Thank you for the help with trouble shooting this issue.

**Comment by Levi-Armstrong** [comment]
Also I pushed a new release on 3/13/17 which had some bug fixes, so I would also try updating it again.

**Comment by bracco23** [comment]
> Ah, are the missing headers files in the packages with the CATKIN_IGNORE file?

No, they're not, the workspace builds fine (if headers file were missing or ignored there would have been problems with building) but the IDE cannot find and parse them, that is my only problem.

As a last try before posting this issue yesterday I uninstalled everything, added the PPA again, updated and installed following the wiki from scratch, I guess that means I already have the latest version you pushed. I will do an update & upgrade again, to see if anything comes new.

**Comment by Levi-Armstrong** [comment]
>"Unable to parse build information for package: crazyflie"
"Unable to parse build information for package: crazyflie_controller"
"Unable to parse build information for package: crazyflie_cpp"
"Unable to parse build information for package: crazyflie_driver"
"Unable to parse build information for package: crazyflie_tools"
"Unable to parse build information for package: formation_control"
"Unable to parse build information for package: gazebo_tutorials"
"Unable to locate build information for package: gztutorial_gazebo"
"Unable to locate build information for package: hector_keyboard_teleop"
"Flags file does not exist: /home/bracco23/tesi_catkin_ws/build/mocap_optitrack/CMakeFiles/mocap_optitrack_mocap_node.dir/flags.make"
"Unable to parse build information for package: netft_utils"
"Unable to parse build information for package: ram_crazy"
"Unable to locate build information for package: rrbot_control"
"Unable to locate build information for package: rrbot_description"
"Unable to locate build information for package: rrbot_gazebo"
"Unable to locate build information for package: two_quad_load"

Just so I understand correctly all of the packages above have a CATKIN_IGNORE file so they are not being built?

Also, for the missing headers files is related to a single package for is it related to several packages?

**Comment by bracco23** [comment]
crazyflie, crazyflie_controller, crazyflie_cpp, crazyflie_driver, crazyflie_tools, formation_control, ram_crazy, mocap_optitrack are the packages in my workspace that are NOT under a CATKIN_IGNORE directory, they are the one I'm interested in building and editing and stuff.

two_quad_load, netft_utils, and the others are under a CATKIN_IGNORE directory, therefore they are not involved in the building process and I don't care, I leave them there for other reasons but are transparent to catkin.

**Comment by Levi-Armstrong** [comment]
Ok, that explains things. I think I know what may be the issue but I thought I resolved this in the latest release. Can you run the command below and verify that the version is 0.1.5-0xenial5?

```
dpkg-query -l | grep "qt57creator-plugin-ros"
```

**Comment by bracco23** [comment]
mmh, nope, i'm on 14.04, therefore my version is 0.1.5-0trusty5 amd64.

**Comment by Levi-Armstrong** [comment]
Sorry, the version you have is the latest for trusty.

Could you try moving the packages that you you need out of the CATKIN_IGNORE folder and into the workspace src directory and rebuilding?

**Comment by bracco23** [comment]
The packages I need are all out of the CATKIN_IGNORE, I could literally just take that folder out of the workspace and nothing would change. 

The build itself is working fine, catkin finds all the headers it needs exactly where I tell it they are, the only issue is with the IDE not finding some of these headers.

**Comment by Levi-Armstrong** [comment]
Ok, Can you take a look in <workspace>/build/crazyflie directory and see if there is a file with the extension  *.cbp* and if so what is the name of the file?

**Comment by bracco23** [comment]
Ok, I moved to my build folder and executed
**find . -name "*.cbp"**
to see all the CodeBlocks file available:

*./mocap_optitrack/mocap_optitrack.cbp
./catkin_workspace.cbp
./crazyflie_ros/crazyflie/crazyflie.cbp
./crazyflie_ros/crazyflie_demo/crazyflie_demo.cbp
./crazyflie_ros/crazyflie_controller/crazyflie_controller.cbp
./crazyflie_ros/crazyflie_description/crazyflie_description.cbp
./crazyflie_ros/crazyflie_driver/crazyflie_driver.cbp
./crazyflie_ros/crazyflie_cpp/crazyflie_cpp.cbp
./crazyflie_ros/crazyflie_tools/crazyflie_tools.cbp
./formation_control/formation_control.cbp
./ram_crazy/ram_crazy.cbp*

As you can see each package has it's own cbp file in their directory (the structure is the same of the src folder) with the right name, I guess.

**Comment by Levi-Armstrong** [comment]
Ok, thank you for the help. I know how to test this and see if I can replicate the issue. I had this issue before when packages are in a subfolder but I thought I solved this issue. I will do some testing and see what I can find.

**Comment by Levi-Armstrong** [comment]
I was able to recreate the issue. With the new release of Catkin Tools integrations it was not easy to make the project file backwards compatible. In my test case all I had to do was delete the two file with the following extension (.workspace & .workspace.user) and re-import the project and then everything worked. Let me know if this resolves the issue, if not I am working on a changes to add more debug information to the project build file parsing.

**Comment by suarez-ramon** [comment]
Hello,

I am also having the same issue with the headers in my project. On some packages it's unable to link them.

**Comment by bracco23** [comment]
As i said i already tried to delete and reload. I also tried to uninstall and reinstall the whole thing, delete and reload but it did not work. I don't have the chance to try again right now but i will do, even if i don't think it will succeed.

**Comment by Levi-Armstrong** [comment]
OK, Uninstalling and reinstall the plug-in would not have remove your project file (.workspace and .workspace.user) in your workspace. Did you try in the past removing these or did you just reopen the project from the recent list after reinstalling?

**Comment by Levi-Armstrong** [comment]
I just pushed a new version providing more debug information during the parsing of the project. I will let you know when it is officially released (~30min) and if you could run qt creator from the terminal and post the output from the terminal after the package is opened and you have tried building it? It will help me track down the issue.

**Comment by Levi-Armstrong** [comment]
A new version has been release perform an update/upgrade and let me know what gets output to the terminal. Thank you for your help.

**Comment by bracco23** [comment]
Ok i did this:

**cd catkin_ws**
**find -name "*.workspace*" -delete**
**rm -rf build/ devel/** 
**sudo apt-get remove qt57creator** *it removes also the plugin automatically*
**sudo apt-get upgrade**
**sudo apt-get install qt57creator-plugin-ros**

At this point I check for the version and it still says 0.1.5-0trusty5, which I found strange, but I went on.

**/opt/qt57/bin/qtcreator**

And did a new project, import workspace, and after that I did a build with CatkinMake from the GUI.

The output, before and after the build is:

*"Unable to locate build information for package: crazyflie"
"Unable to locate build information for package: crazyflie_controller"
"Unable to locate build information for package: crazyflie_cpp"
"Unable to locate build information for package: crazyflie_demo"
"Unable to locate build information for package: crazyflie_description"
"Unable to locate build information for package: crazyflie_driver"
"Unable to locate build information for package: crazyflie_tools"
"Unable to locate build information for package: formation_control"
"Unable to locate build information for package: gazebo_tutorials"
"Unable to locate build information for package: gztutorial_gazebo"
"Unable to locate build information for package: hector_keyboard_teleop"
"Unable to locate build information for package: mocap_optitrack"
"Unable to locate build information for package: netft_utils"
"Unable to locate build information for package: ram_crazy"
"Unable to locate build information for package: rrbot_control"
"Unable to locate build information for package: rrbot_description"
"Unable to locate build information for package: rrbot_gazebo"
"Unable to locate build information for package: two_quad_load"
"Unable to parse build information for package: crazyflie"
"Unable to parse build information for package: crazyflie_controller"
"Unable to parse build information for package: crazyflie_cpp"
"Unable to parse build information for package: crazyflie_driver"
"Unable to parse build information for package: crazyflie_tools"
"Unable to parse build information for package: formation_control"
"Unable to parse build information for package: gazebo_tutorials"
"Unable to locate build information for package: gztutorial_gazebo"
"Unable to locate build information for package: hector_keyboard_teleop"
"Flags file does not exist: /home/bracco23/tesi_catkin_ws/build/mocap_optitrack/CMakeFiles/mocap_optitrack_mocap_node.dir/flags.make"
"Unable to parse build information for package: netft_utils"
"Unable to parse build information for package: ram_crazy"
"Unable to locate build information for package: rrbot_control"
"Unable to locate build information for package: rrbot_description"
"Unable to locate build information for package: rrbot_gazebo"
"Unable to locate build information for package: two_quad_load"*

Closed the GUI (accidentally by pressing Ctrl-c), opening again, reopening the project, this gets written:

*"Unable to parse build information for package: crazyflie"
"Unable to parse build information for package: crazyflie_controller"
"Unable to parse build information for package: crazyflie_cpp"
"Unable to parse build information for package: crazyflie_driver"
"Unable to parse build information for package: crazyflie_tools"
"Unable to parse build information for package: formation_control"
"Unable to parse build information for package: gazebo_tutorials"
"Unable to locate build information for package: gztutorial_gazebo"
"Unable to locate build information for package: hector_keyboard_teleop"
"Flags file does not exist: /home/bracco23/tesi_catkin_ws/build/mocap_optitrack/CMakeFiles/mocap_optitrack_mocap_node.dir/flags.make"
"Unable to parse build information for package: netft_utils"
"Unable to parse build information for package: ram_crazy"
"Unable to locate build information for package: rrbot_control"
"Unable to locate build information for package: rrbot_description"
"Unable to locate build information for package: rrbot_gazebo"
"Unable to locate build information for package: two_quad_load"*

I'm going to try update again to see if a new version comes up, if it does i'll do the same test again (just deleting project stuff and recompiling from scratch, no uninstalling) and i'll let you know.

**Comment by Levi-Armstrong** [comment]
you should runt `sudo apt-get update` prior to upgrade. and you should get  0.1.5-0trusty6.

**Comment by bracco23** [comment]
My brain will never stop being confused between apt-get upgrade and apt-get update.

so, again:

**cd catkin_ws
find -name "\*.workspace\*" -delete
rm -rf build/ devel/
sudo apt-get update
sudo apt-get upgrade
/opt/qt57/bin/qtcreator**

Create new project, import ROS workspace, and this is the output:

*"Unable to locate build directory for package: crazyflie"
"Unable to locate build directory for package: crazyflie_controller"
"Unable to locate build directory for package: crazyflie_cpp"
"Unable to locate build directory for package: crazyflie_demo"
"Unable to locate build directory for package: crazyflie_description"
"Unable to locate build directory for package: crazyflie_driver"
"Unable to locate build directory for package: crazyflie_tools"
"Unable to locate build directory for package: formation_control"
"Unable to locate build directory for package: gazebo_tutorials"
"Unable to locate build directory for package: gztutorial_gazebo"
"Unable to locate build directory for package: hector_keyboard_teleop"
"Unable to locate build directory for package: mocap_optitrack"
"Unable to locate build directory for package: netft_utils"
"Unable to locate build directory for package: ram_crazy"
"Unable to locate build directory for package: rrbot_control"
"Unable to locate build directory for package: rrbot_description"
"Unable to locate build directory for package: rrbot_gazebo"
"Unable to locate build directory for package: two_quad_load"*

At this point i build, since i deleted the files and i need to build again, and after it finishes the build and tried to loads the files, this is the output:

*"Unable to locate package crazyflie build file: /home/bracco23/tesi_catkin_ws/build/catkin_generated/metapackages/crazyflie/crazyflie.cbp"
"Unable to locate package crazyflie_controller build file: /home/bracco23/tesi_catkin_ws/build/CMakeFiles/catkin_workspace_OTHER_FILES.dir/crazyflie_ros/crazyflie_controller/crazyflie_controller.cbp"
"Unable to locate package crazyflie_cpp build file: /home/bracco23/tesi_catkin_ws/build/CMakeFiles/catkin_workspace_OTHER_FILES.dir/crazyflie_ros/crazyflie_cpp/crazyflie_cpp.cbp"
"Unable to locate package crazyflie_driver build file: /home/bracco23/tesi_catkin_ws/build/CMakeFiles/catkin_workspace_OTHER_FILES.dir/crazyflie_ros/crazyflie_driver/crazyflie_driver.cbp"
"Unable to locate package crazyflie_tools build file: /home/bracco23/tesi_catkin_ws/build/CMakeFiles/catkin_workspace_OTHER_FILES.dir/crazyflie_ros/crazyflie_tools/crazyflie_tools.cbp"
"Unable to locate package formation_control build file: /home/bracco23/tesi_catkin_ws/build/CMakeFiles/catkin_workspace_OTHER_FILES.dir/formation_control/formation_control.cbp"
"Unable to locate package gazebo_tutorials build file: /home/bracco23/tesi_catkin_ws/build/CMakeFiles/catkin_workspace_OTHER_FILES.dir/old/demos/gazebo_ros_demos/custom_plugin_tutorial/gazebo_tutorials.cbp"
"Unable to locate build directory for package: gztutorial_gazebo"
"Unable to locate build directory for package: hector_keyboard_teleop"
"Flags file does not exist: /home/bracco23/tesi_catkin_ws/build/mocap_optitrack/CMakeFiles/mocap_optitrack_mocap_node.dir/flags.make"
"Unable to locate package netft_utils build file: /home/bracco23/tesi_catkin_ws/build/CMakeFiles/catkin_workspace_OTHER_FILES.dir/old/netft_utils/netft_utils.cbp"
"Unable to locate package ram_crazy build file: /home/bracco23/tesi_catkin_ws/build/CMakeFiles/catkin_workspace_OTHER_FILES.dir/ram_crazy/ram_crazy.cbp"
"Unable to locate build directory for package: rrbot_control"
"Unable to locate build directory for package: rrbot_description"
"Unable to locate build directory for package: rrbot_gazebo"
"Unable to locate build directory for package: two_quad_load"*

I'll quote here one of my comments  of a few days ago. I executed the command again in the build folder and the output is the same

> Ok, I moved to my build folder and executed
> find . -name "*.cbp"
> to see all the CodeBlocks file available:
> 
> ./mocap_optitrack/mocap_optitrack.cbp
> ./catkin_workspace.cbp
> ./crazyflie_ros/crazyflie/crazyflie.cbp
> ./crazyflie_ros/crazyflie_demo/crazyflie_demo.cbp
> ./crazyflie_ros/crazyflie_controller/crazyflie_controller.cbp
> ./crazyflie_ros/crazyflie_description/crazyflie_description.cbp
> ./crazyflie_ros/crazyflie_driver/crazyflie_driver.cbp
> ./crazyflie_ros/crazyflie_cpp/crazyflie_cpp.cbp
> ./crazyflie_ros/crazyflie_tools/crazyflie_tools.cbp
> ./formation_control/formation_control.cbp
> ./ram_crazy/ram_crazy.cbp

**Comment by Levi-Armstrong** [comment]
OK, It is a bug in how I am determining the build directory for a package. I work on a resolution and a fix shortly. Thank you for helping track things down.

**Comment by Levi-Armstrong** [comment]
I just pushed a new release it should get published in about 30 minutes. Then you can perform an update & upgrade to get the latest. Let me know if this fixes the issue.

**Comment by bracco23** [comment]
Sorry for late reply, I just checked and it solved the problem for me, I didn't even need to reimport the project, I opened the old one and it was working fine.

**Comment by Levi-Armstrong** [comment]
@bracco23, Glad to hear. Thank you for the help tracking down the bug.

@suarez-ramon, Have you tested the latest to see if it solves it for you?

**Comment by suarez-ramon** [comment]
I did a software upgrade with the GUI and it works fine for me now. I don't know if it had anything to do but I also deleted the old .workspace file and now it's perfect. Thanks!!

**Comment by Levi-Armstrong** [comment]
@suarez-ramon Great! There was an intermittent bug in how I was locating the build directory for a package.
